import Foundation

enum AppLocalizable {
    static func string(_ key: String, language: AppLanguage) -> String {
        switch language {
        case .french:
            return french[key] ?? english[key] ?? key
        case .english:
            return english[key] ?? key
        case .portuguese:
            return portuguese[key] ?? english[key] ?? key
        }
    }

    // MARK: - French

    private static let french: [String: String] = [
        "tab.home": "Home",
        "tab.library": "Biblio",
        "tab.profile": "Profil",

        "library.title": "Bibliothèque",
        "library.tab.courses": "Cours",
        "library.tab.collections": "Collections",
        "library.search.placeholder": "Rechercher un cours...",

        "language.section": "Langue",
        "language.french": "Français",
        "language.english": "English",
        "language.portuguese": "Português",

        "onboarding.intro.title": "Deviens cultivé\nen 10 minutes\npar jour",
        "onboarding.intro.cta": "Commencer",

        "settings.title": "Options",
        "settings.section.progress": "Progression",
        "settings.section.premium": "Premium",
        "settings.section.data": "Données",
        "settings.section.legal": "Légal",
        "settings.section.about": "À propos",
        "settings.section.developer": "Développeur",
        "settings.courses.completed": "%d cours terminés",
        "settings.courses.available": "sur %d disponibles",
        "settings.streak.title": "%d jours de suite",
        "settings.streak.subtitle": "Continue comme ça !",
        "settings.premium.title": "Passer à Premium",
        "settings.premium.subtitle": "Cours et quiz illimités",
        "settings.reset.title": "Réinitialiser la progression",
        "settings.terms.title": "Conditions générales",
        "settings.privacy.title": "Politique de confidentialité",
        "settings.restore.title": "Restaurer les achats",
        "settings.about.version": "Version",
        "settings.about.courses": "Cours disponibles",
        "settings.debug.resetOnboarding": "Refaire l'onboarding",
        "settings.debug.resetDaily": "Reset cours du jour",
        "settings.debug.daily.done": "Fait aujourd'hui",
        "settings.debug.daily.pending": "Pas encore fait",
        "settings.footer": "Made with ♥ — Sophia",
        "settings.reset.alert.title": "Réinitialiser ?",
        "settings.reset.alert.cancel": "Annuler",
        "settings.reset.alert.confirm": "Réinitialiser",
        "settings.reset.alert.message": "Toute ta progression sera effacée. Cette action est irréversible.",
        "settings.onboarding.alert.title": "Refaire l'onboarding ?",
        "settings.onboarding.alert.confirm": "Relancer",
        "settings.onboarding.alert.message": "L'onboarding sera relancé depuis le début (DEBUG uniquement).",

        "legal.terms.title": "Conditions",
        "legal.privacy.title": "Confidentialité",

        "subject.histoire": "Histoire",
        "subject.sciences": "Sciences",
        "subject.litterature": "Littérature",
        "subject.art": "Art",
        "subject.mythologie": "Mythologie",
        "subject.comprendreLeMonde": "Comprendre le monde actuel",
        "subject.histoire.short": "Histoire",
        "subject.sciences.short": "Sciences",
        "subject.litterature.short": "Littérature",
        "subject.art.short": "Art",
        "subject.mythologie.short": "Mythologie",
        "subject.comprendreLeMonde.short": "Monde actuel",

        "rarity.commune": "Commune",
        "rarity.rare": "Rare",
        "rarity.epique": "Épique",
        "rarity.legendaire": "Légendaire",

        "home.skip": "Passer",
        "home.bravo": "Bravo !",
        "home.allCompleted": "Tu as terminé tous les cours disponibles.",
        "home.locked": "Verrouillé",
        "home.start": "Commencer",

        "library.empty.title": "Aucun résultat",
        "library.empty.subtitle": "Essaie un autre mot-clé.",
        "library.seeMore": "Voir plus",
        "library.unlock": "Débloquer",
        "library.lockedBadge": "VERROUILLÉ",

        "collections.title": "COLLECTIONS",
        "collections.subtitle": "Des parcours guidés pour relier les idées entre elles.",
        "collections.complete": "Collection terminée",
        "collections.progress": "%d / %d cours terminés",
        "collections.badge.complete": "TERMINÉE",
        "collections.badge.path": "PARCOURS",
        "collections.xpAtEnd": "+%d XP à la fin",
        "collections.pathComplete": "Parcours complet",

        "subject.courses.count": "%d cours",
        "subject.completed.singular": "%d terminé",
        "subject.completed.plural": "%d terminés",

        "cards.collect.title": "CARTES À COLLECTER",
        "cards.seeAll": "Voir tout →",
        "cards.unit": "cartes",
        "cards.empty": "Termine un cours pour débloquer tes premières cartes.",
        "cards.quizStats.title": "QUIZZ RÉUSSIS",
        "cards.correctAnswers": "bonnes réponses",
        "cards.successRate": "réussite",
        "cards.myCards": "Mes cartes",
        "cards.unlocked": "débloquées",
        "cards.unlocked.title": "Carte débloquée !",
        "cards.tapToReveal": "Tape pour révéler",
        "cards.globalXP": "+%d XP globaux",

        "course.keyTakeaway": "À RETENIR",

        "common.continue": "Continuer",

        "celebration.collectionAdvanced": "Collection avancée !",
        "celebration.coursesCompleted": "cours terminés",
        "celebration.collectionComplete": "Collection terminée !",

        "common.next": "Suivant",
        "common.letsGo": "C'est parti !",
        "common.letsGoShort": "C'est parti",
        "common.close": "Fermer",
        "common.processing": "Traitement…",
        "common.startLearning": "Commencer à apprendre",
        "common.backHome": "Retour à l'accueil",
        "common.retryQuiz": "Refaire le quiz",
        "common.seeMoreArrow": "Voir plus →",
        "common.streak.day": "JOUR",
        "common.streak.days": "JOURS",
        "common.levelShort": "NIV. %d",
        "common.increaseGoal": "Augmenter l'objectif",
        "common.decreaseGoal": "Réduire l'objectif",
        "common.miniQuiz": "Mini Quiz",
        "common.xpEarned": "+%d XP gagnés",
        "common.xpBeforeNext": "· %d avant niv. %d",

        "onboarding.welcome.title": "Sophia est ton partenaire pour maîtriser",
        "onboarding.welcome.rotating.histoire": "l'histoire",
        "onboarding.welcome.rotating.sciences": "les sciences",
        "onboarding.welcome.rotating.litterature": "la littérature",
        "onboarding.welcome.rotating.art": "l'art",
        "onboarding.welcome.rotating.mythologie": "la mythologie",
        "onboarding.welcome.rotating.comprendreLeMonde": "le monde actuel",

        "onboarding.phone.title": "Combien de temps\nsur ton téléphone ?",
        "onboarding.phone.subtitle": "Chaque jour, en moyenne.",
        "onboarding.phone.lessThan1h": "Moins de 1h",
        "onboarding.phone.1to2h": "1h à 2h",
        "onboarding.phone.2to4h": "2h à 4h",
        "onboarding.phone.moreThan4h": "Plus de 4h",
        "onboarding.phone.hours.1": "1 heure",
        "onboarding.phone.hours.2": "2 heures",
        "onboarding.phone.hours.3": "3 heures",
        "onboarding.phone.hours.5": "5 heures",

        "onboarding.wasted.intro": "%@ par jour sur ton téléphone, c'est",
        "onboarding.wasted.hoursLost": "heures perdues par an.",
        "onboarding.wasted.daysComplete": "Soit %@ complets.",
        "onboarding.wasted.transform": "Avec Sophia, transforme ce temps en culture.",
        "onboarding.wasted.days.7": "7 jours",
        "onboarding.wasted.days.23": "23 jours",
        "onboarding.wasted.days.45": "45 jours",
        "onboarding.wasted.days.91": "91 jours",

        "onboarding.objectives.title": "Ton objectif\navec Sophia ?",
        "onboarding.objectives.subtitle": "Sélectionne un ou plusieurs objectifs.",
        "onboarding.objective.curious": "Être plus curieux",
        "onboarding.objective.learnNew": "Apprendre de nouvelles choses",
        "onboarding.objective.impress": "Impressionner tes proches",
        "onboarding.objective.social": "Renforcer ton aisance en société",
        "onboarding.objective.reduceScroll": "Réduire ton temps à scroller",

        "onboarding.interests.title": "Quels sujets\nt'intéressent ?",
        "onboarding.interests.subtitle": "Sélectionne au moins un sujet.",

        "onboarding.dailyGoal.title": "Chaque jour, tu veux apprendre...",
        "onboarding.dailyGoal.subtitle": "Tu pourras modifier ton objectif plus tard.",
        "onboarding.dailyGoal.perDay": "%@ par jour !",
        "onboarding.dailyGoal.singular": "apprentissage",
        "onboarding.dailyGoal.plural": "apprentissages",

        "onboarding.loading.title": "On prépare ton parcours",
        "onboarding.loading.subtitle": "Quelques secondes, promis.",
        "onboarding.loading.step1": "Analyse de tes réponses",
        "onboarding.loading.step2": "Sélection de tes 3 matières",
        "onboarding.loading.step3": "Préparation de ton parcours",

        "onboarding.projection.line1": "Petite habitude,",
        "onboarding.projection.line2": "résultats incroyables.",
        "onboarding.projection.its": "C'est",
        "onboarding.projection.newThings": "nouvelles choses que tu sauras",
        "onboarding.projection.inOneYear": "d'ici un an.",

        "onboarding.social.badge": "Avis vérifiés",
        "onboarding.social.stat": "des utilisateurs se sentent\nplus intéressants et à l'aise\nen société grâce à Sophia.",
        "onboarding.social.review1.name": "Lucas M.",
        "onboarding.social.review1.text": "Je me sentais nul en culture G, maintenant j'ai toujours un truc intéressant à raconter.",
        "onboarding.social.review2.name": "Camille R.",
        "onboarding.social.review2.text": "10 min par jour et j'ai l'impression d'apprendre plus qu'en cours.",
        "onboarding.social.review3.name": "Thomas D.",
        "onboarding.social.review3.text": "J'adore le format. C'est clair, rapide et on retient vraiment.",

        "onboarding.graph.title": "Ta progression\nculturelle",
        "onboarding.graph.subtitle": "Avec et sans Sophia",
        "onboarding.graph.culture": "CULTURE",
        "onboarding.graph.withSophia": "Avec Sophia",
        "onboarding.graph.withoutSophia": "Sans Sophia",
        "onboarding.graph.today": "Aujourd'hui",
        "onboarding.graph.oneYear": "1 an",
        "onboarding.graph.tagline": "Sophia accélère ta culture\nde manière exponentielle.",

        "onboarding.final.title": "Profil prêt !",
        "onboarding.final.subtitle": "Bienvenue dans Sophia.\nCommence à apprendre dès maintenant.",
        "onboarding.final.subjects": "TES MATIÈRES",

        "onboarding.trial.badge": "Offre de bienvenue",
        "onboarding.trial.title": "Vos 3 premiers jours\nsont offerts",
        "onboarding.trial.unlimitedCourses": "Cours illimités",
        "onboarding.trial.allQuizzes": "Tous les quiz",
        "onboarding.trial.noSurprise": "Pas de surprise",
        "onboarding.trial.notifyTitle": "Nous vous notifierons\n1 jour avant la fin\nde votre essai gratuit",
        "onboarding.trial.cancelAnytime": "Annulez à tout moment, sans frais.",
        "onboarding.trial.day1": "JOUR 1",
        "onboarding.trial.day2": "JOUR 2",
        "onboarding.trial.day3": "JOUR 3",
        "onboarding.trial.fullAccess": "Accès complet",
        "onboarding.trial.notificationSent": "Notification envoyée",
        "onboarding.trial.trialEnds": "Fin de l'essai",

        "paywall.cancelAnytime": "Annule à tout moment, sans frais.",
        "paywall.header": "Deviens la personne\nla plus intéressante\nde la pièce.",
        "paywall.freeSubjects": "Tes 3 matières gratuites",
        "paywall.lockedSubjects": "3 matières à débloquer",
        "paywall.teaserTitle": "Un aperçu de ce qui t'attend",
        "paywall.teaserSubtitle": "Des centaines de cours premium à débloquer",
        "paywall.featureColumn": "Fonctionnalité",
        "paywall.freeColumn": "Gratuit",
        "paywall.premiumColumn": "Premium",
        "paywall.feature.3subjects": "3 matières",
        "paywall.feature.allSubjects": "Toutes les matières",
        "paywall.feature.unlimitedCourses": "Cours illimités",
        "paywall.feature.miniQuiz": "Mini Quiz",
        "paywall.feature.fullLibrary": "Bibliothèque complète",
        "paywall.plan.yearly": "Annuel",
        "paywall.plan.monthly": "Mensuel",
        "paywall.plan.yearlySubtitle": "Facturé annuellement",
        "paywall.plan.monthlySubtitle": "Sans engagement",
        "paywall.plan.perYear": "/ an",
        "paywall.plan.perMonth": "/ mois",
        "paywall.plan.discount": "-58%",
        "paywall.plan.fallback.yearlyPrice": "39,99 €",
        "paywall.plan.fallback.monthlyPrice": "9,99 €",
        "paywall.plan.fallback.yearlyMonthly": "3,33 € / mois",
        "paywall.trialBadge": "Essai gratuit 3 jours",
        "paywall.restoreRow": "Restaurer · Conditions · Confidentialité",
        "paywall.trialSheet.title": "Commence ton essai\ngratuit de 3 jours",
        "paywall.trialSheet.start": "Commencer l'essai gratuit",
        "paywall.trial.today": "Aujourd'hui",
        "paywall.trial.noPayment": "Aucun paiement",
        "paywall.trial.todayDetail": "Accès à toutes les fonctionnalités Premium.",
        "paywall.trial.in2days": "Dans 2 jours",
        "paywall.trial.reminder": "On te prévient",
        "paywall.trial.reminderDetail": "Notification 1 jour avant la fin de l'essai.",
        "paywall.trial.in3days": "Dans 3 jours",
        "paywall.trial.starts": "Ton abonnement démarre",
        "paywall.trial.startsDetail": "Annule avant si tu ne veux pas continuer.",
        "paywall.review1.quote": "Parfait dans les transports. J'apprends chaque jour sans effort.",
        "paywall.review1.author": "Marie, 28 ans",
        "paywall.review2.quote": "Enfin une app qui me fait passer du scroll à la culture.",
        "paywall.review2.author": "Thomas, 34 ans",
        "paywall.review3.quote": "Les cours sont courts, drôles, et je retiens vraiment.",
        "paywall.review3.author": "Inès, 22 ans",
        "paywall.review4.quote": "Mes amis me demandent d'où je sors toutes ces anecdotes.",
        "paywall.review4.author": "Lucas, 31 ans",
        "paywall.review5.quote": "L'onboarding personnalisé m'a convaincu dès la première minute.",
        "paywall.review5.author": "Sarah, 26 ans",

        "offer.unique": "Votre offre unique",
        "offer.discount": "-70% POUR TOUJOURS",
        "offer.perMonth": "/mois",
        "offer.billed": "facturé",
        "offer.expiresIn": "Expire dans",
        "offer.unlock": "Débloquer mon accès -70%",
        "offer.restore": "Restaurer les achats",
        "offer.feature1": "240 cours de culture générale",
        "offer.feature2": "Quiz interactifs illimités",
        "offer.feature3": "Nouveau contenu chaque semaine",

        "profile.title": "Profil",
        "profile.streak.start": "Lis un cours pour démarrer !",
        "profile.streak.beginning": "Tu as commencé, continue !",
        "profile.streak.good": "Belle régularité 👏",
        "profile.streak.great": "Tu es en feu 🔥",
        "profile.favorites": "Mes favoris",
        "profile.favorites.count": "%d cours sauvegardés",
        "profile.quiz.recent": "MES QUIZ RÉCENTS",
        "profile.quiz.locked": "Quiz verrouillés",
        "profile.quiz.lockedSubtitle": "Disponibles avec l'essai gratuit — 3 jours offerts",
        "profile.quiz.unlock": "Débloquer mes quiz",
        "profile.quiz.emptyTitle": "Pas encore de quiz",
        "profile.quiz.emptySubtitle": "Termine un cours pour passer ton premier quiz.",
        "profile.progress.bySubject": "PROGRESSION PAR THÈME",
        "profile.unlock.trial": "Débloque avec l'essai gratuit",
        "profile.quiz.retry": "Refaire",
        "profile.quiz.all": "Tous mes quiz",
        "profile.quiz.none": "Aucun quiz pour le moment.",
        "profile.progress.max": "%d XP · niveau max",
        "profile.progress.toNext": "%d XP · %d avant niv. %d",

        "quiz.feedback.correct": "Bonne réponse !",
        "quiz.feedback.excellent": "Excellent !",
        "quiz.feedback.amazing": "Incroyable !",
        "quiz.feedback.wrong": "Pas tout à fait...",
        "quiz.completed": "Bravo, quiz terminé !",
        "quiz.correctAnswers": "bonnes réponses",
        "quiz.xpProgress": "Progression XP",
        "quiz.levelUp": "Niveau supérieur !",
        "quiz.breakdown.correct": "Bonnes réponses",
        "quiz.breakdown.completed": "Quiz terminé",
        "quiz.xpProgress.max": "%d XP · niveau max",
        "quiz.xpProgress.toNext": "%d XP avant niv. %d",

        "course.completed": "Apprentissage terminé !",
        "course.dailyFreeDone": "Tu as terminé ton cours gratuit du jour",
        "course.streak.day": "Jour de suite",
        "course.streak.days": "Jours de suite",
        "course.streak.message": "Tu deviens vraiment cultivé, tu deviens incollable en %@ !",
        "course.streak.onTrack": "En route pour ta série !",

        "prepaywall.quiz.title": "Débloquez gratuitement\nles quiz",
        "prepaywall.quiz.subtitle": "Testez vos connaissances et\nprogressez chaque jour",
        "prepaywall.course.subtitle": "Continuez à apprendre et\ndécouvrez de nouveaux sujets",
        "prepaywall.course.access": "Accéder au cours",

        "levelUp.title": "Niveau supérieur !",

        "globalRank.curieux": "Curieux",
        "globalRank.erudit": "Érudit",
        "globalRank.savant": "Savant",
        "globalRank.maitre": "Maître",
        "globalRank.legende": "Légende",
        "globalRank.title": "Rang global",
        "globalRank.badge": "RANG GLOBAL",
        "globalRank.maxLevel": "Niveau max",
        "globalRank.xpBefore": "%d XP avant %@",
        "globalRank.newRank": "Nouveau rang !",
        "globalRank.reachedLevel": "Tu viens d'atteindre le niveau %d",

        "paywall.unavailable.title": "Offre indisponible",
        "paywall.unavailable.message": "Impossible de charger cette offre pour le moment.",
    ]

    // MARK: - English

    private static let english: [String: String] = [
        "tab.home": "Home",
        "tab.library": "Library",
        "tab.profile": "Profile",

        "library.title": "Library",
        "library.tab.courses": "Courses",
        "library.tab.collections": "Collections",
        "library.search.placeholder": "Search for a course...",

        "language.section": "Language",
        "language.french": "Français",
        "language.english": "English",
        "language.portuguese": "Português",

        "onboarding.intro.title": "Become cultured\nin 10 minutes\na day",
        "onboarding.intro.cta": "Get started",

        "settings.title": "Settings",
        "settings.section.progress": "Progress",
        "settings.section.premium": "Premium",
        "settings.section.data": "Data",
        "settings.section.legal": "Legal",
        "settings.section.about": "About",
        "settings.section.developer": "Developer",
        "settings.courses.completed": "%d courses completed",
        "settings.courses.available": "out of %d available",
        "settings.streak.title": "%d-day streak",
        "settings.streak.subtitle": "Keep it up!",
        "settings.premium.title": "Upgrade to Premium",
        "settings.premium.subtitle": "Unlimited courses and quizzes",
        "settings.reset.title": "Reset progress",
        "settings.terms.title": "Terms of Service",
        "settings.privacy.title": "Privacy Policy",
        "settings.restore.title": "Restore purchases",
        "settings.about.version": "Version",
        "settings.about.courses": "Available courses",
        "settings.debug.resetOnboarding": "Restart onboarding",
        "settings.debug.resetDaily": "Reset daily course",
        "settings.debug.daily.done": "Done today",
        "settings.debug.daily.pending": "Not yet done",
        "settings.footer": "Made with ♥ — Sophia",
        "settings.reset.alert.title": "Reset?",
        "settings.reset.alert.cancel": "Cancel",
        "settings.reset.alert.confirm": "Reset",
        "settings.reset.alert.message": "All your progress will be erased. This cannot be undone.",
        "settings.onboarding.alert.title": "Restart onboarding?",
        "settings.onboarding.alert.confirm": "Restart",
        "settings.onboarding.alert.message": "Onboarding will start over from the beginning (DEBUG only).",

        "legal.terms.title": "Terms",
        "legal.privacy.title": "Privacy",

        "subject.histoire": "History",
        "subject.sciences": "Science",
        "subject.litterature": "Literature",
        "subject.art": "Art",
        "subject.mythologie": "Mythology",
        "subject.comprendreLeMonde": "Understanding today's world",
        "subject.histoire.short": "History",
        "subject.sciences.short": "Science",
        "subject.litterature.short": "Literature",
        "subject.art.short": "Art",
        "subject.mythologie.short": "Mythology",
        "subject.comprendreLeMonde.short": "Current affairs",

        "rarity.commune": "Common",
        "rarity.rare": "Rare",
        "rarity.epique": "Epic",
        "rarity.legendaire": "Legendary",

        "home.skip": "Skip",
        "home.bravo": "Bravo!",
        "home.allCompleted": "You've completed all available courses.",
        "home.locked": "Locked",
        "home.start": "Start",

        "library.empty.title": "No results",
        "library.empty.subtitle": "Try another keyword.",
        "library.seeMore": "See more",
        "library.unlock": "Unlock",
        "library.lockedBadge": "LOCKED",

        "collections.title": "COLLECTIONS",
        "collections.subtitle": "Guided journeys to connect ideas.",
        "collections.complete": "Collection complete",
        "collections.progress": "%d / %d courses completed",
        "collections.badge.complete": "COMPLETE",
        "collections.badge.path": "JOURNEY",
        "collections.xpAtEnd": "+%d XP at the end",
        "collections.pathComplete": "Journey complete",

        "subject.courses.count": "%d courses",
        "subject.completed.singular": "%d completed",
        "subject.completed.plural": "%d completed",

        "cards.collect.title": "CARDS TO COLLECT",
        "cards.seeAll": "See all →",
        "cards.unit": "cards",
        "cards.empty": "Complete a course to unlock your first cards.",
        "cards.quizStats.title": "QUIZZES PASSED",
        "cards.correctAnswers": "correct answers",
        "cards.successRate": "success rate",
        "cards.myCards": "My cards",
        "cards.unlocked": "unlocked",
        "cards.unlocked.title": "Card unlocked!",
        "cards.tapToReveal": "Tap to reveal",
        "cards.globalXP": "+%d global XP",

        "course.keyTakeaway": "KEY TAKEAWAY",

        "common.continue": "Continue",

        "celebration.collectionAdvanced": "Collection progressed!",
        "celebration.coursesCompleted": "courses completed",
        "celebration.collectionComplete": "Collection complete!",

        "common.next": "Next",
        "common.letsGo": "Let's go!",
        "common.letsGoShort": "Let's go",
        "common.close": "Close",
        "common.processing": "Processing…",
        "common.startLearning": "Start learning",
        "common.backHome": "Back to home",
        "common.retryQuiz": "Retry quiz",
        "common.seeMoreArrow": "See more →",
        "common.streak.day": "DAY",
        "common.streak.days": "DAYS",
        "common.levelShort": "LVL. %d",
        "common.increaseGoal": "Increase goal",
        "common.decreaseGoal": "Decrease goal",
        "common.miniQuiz": "Mini Quiz",
        "common.xpEarned": "+%d XP earned",
        "common.xpBeforeNext": "· %d to lvl. %d",

        "onboarding.welcome.title": "Sophia is your partner to master",
        "onboarding.welcome.rotating.histoire": "history",
        "onboarding.welcome.rotating.sciences": "science",
        "onboarding.welcome.rotating.litterature": "literature",
        "onboarding.welcome.rotating.art": "art",
        "onboarding.welcome.rotating.mythologie": "mythology",
        "onboarding.welcome.rotating.comprendreLeMonde": "current affairs",

        "onboarding.phone.title": "How much time\ndo you spend on your phone?",
        "onboarding.phone.subtitle": "Each day, on average.",
        "onboarding.phone.lessThan1h": "Less than 1h",
        "onboarding.phone.1to2h": "1h to 2h",
        "onboarding.phone.2to4h": "2h to 4h",
        "onboarding.phone.moreThan4h": "More than 4h",
        "onboarding.phone.hours.1": "1 hour",
        "onboarding.phone.hours.2": "2 hours",
        "onboarding.phone.hours.3": "3 hours",
        "onboarding.phone.hours.5": "5 hours",

        "onboarding.wasted.intro": "%@ per day on your phone, that's",
        "onboarding.wasted.hoursLost": "hours lost per year.",
        "onboarding.wasted.daysComplete": "That's %@ full days.",
        "onboarding.wasted.transform": "With Sophia, turn that time into culture.",
        "onboarding.wasted.days.7": "7 days",
        "onboarding.wasted.days.23": "23 days",
        "onboarding.wasted.days.45": "45 days",
        "onboarding.wasted.days.91": "91 days",

        "onboarding.objectives.title": "Your goal\nwith Sophia?",
        "onboarding.objectives.subtitle": "Select one or more goals.",
        "onboarding.objective.curious": "Be more curious",
        "onboarding.objective.learnNew": "Learn new things",
        "onboarding.objective.impress": "Impress the people around you",
        "onboarding.objective.social": "Feel more at ease socially",
        "onboarding.objective.reduceScroll": "Cut down on scrolling time",

        "onboarding.interests.title": "What topics\ninterest you?",
        "onboarding.interests.subtitle": "Select at least one topic.",

        "onboarding.dailyGoal.title": "Each day, you want to learn...",
        "onboarding.dailyGoal.subtitle": "You can change your goal later.",
        "onboarding.dailyGoal.perDay": "%@ per day!",
        "onboarding.dailyGoal.singular": "lesson",
        "onboarding.dailyGoal.plural": "lessons",

        "onboarding.loading.title": "We're preparing your journey",
        "onboarding.loading.subtitle": "Just a few seconds, promise.",
        "onboarding.loading.step1": "Analyzing your answers",
        "onboarding.loading.step2": "Selecting your 3 subjects",
        "onboarding.loading.step3": "Preparing your journey",

        "onboarding.projection.line1": "Small habit,",
        "onboarding.projection.line2": "incredible results.",
        "onboarding.projection.its": "That's",
        "onboarding.projection.newThings": "new things you'll know",
        "onboarding.projection.inOneYear": "within a year.",

        "onboarding.social.badge": "Verified reviews",
        "onboarding.social.stat": "of users feel\nmore interesting and at ease\nin social settings thanks to Sophia.",
        "onboarding.social.review1.name": "Lucas M.",
        "onboarding.social.review1.text": "I felt clueless about culture, now I always have something interesting to share.",
        "onboarding.social.review2.name": "Camille R.",
        "onboarding.social.review2.text": "10 minutes a day and I feel like I learn more than in class.",
        "onboarding.social.review3.name": "Thomas D.",
        "onboarding.social.review3.text": "I love the format. It's clear, fast, and I actually remember things.",

        "onboarding.graph.title": "Your cultural\nprogress",
        "onboarding.graph.subtitle": "With and without Sophia",
        "onboarding.graph.culture": "CULTURE",
        "onboarding.graph.withSophia": "With Sophia",
        "onboarding.graph.withoutSophia": "Without Sophia",
        "onboarding.graph.today": "Today",
        "onboarding.graph.oneYear": "1 year",
        "onboarding.graph.tagline": "Sophia accelerates your culture\nexponentially.",

        "onboarding.final.title": "Profile ready!",
        "onboarding.final.subtitle": "Welcome to Sophia.\nStart learning right now.",
        "onboarding.final.subjects": "YOUR SUBJECTS",

        "onboarding.trial.badge": "Welcome offer",
        "onboarding.trial.title": "Your first 3 days\nare free",
        "onboarding.trial.unlimitedCourses": "Unlimited courses",
        "onboarding.trial.allQuizzes": "All quizzes",
        "onboarding.trial.noSurprise": "No surprises",
        "onboarding.trial.notifyTitle": "We'll notify you\n1 day before the end\nof your free trial",
        "onboarding.trial.cancelAnytime": "Cancel anytime, free of charge.",
        "onboarding.trial.day1": "DAY 1",
        "onboarding.trial.day2": "DAY 2",
        "onboarding.trial.day3": "DAY 3",
        "onboarding.trial.fullAccess": "Full access",
        "onboarding.trial.notificationSent": "Notification sent",
        "onboarding.trial.trialEnds": "Trial ends",

        "paywall.cancelAnytime": "Cancel anytime, free of charge.",
        "paywall.header": "Become the most\ninteresting person\nin the room.",
        "paywall.freeSubjects": "Your 3 free subjects",
        "paywall.lockedSubjects": "3 subjects to unlock",
        "paywall.teaserTitle": "A preview of what's ahead",
        "paywall.teaserSubtitle": "Hundreds of premium courses to unlock",
        "paywall.featureColumn": "Feature",
        "paywall.freeColumn": "Free",
        "paywall.premiumColumn": "Premium",
        "paywall.feature.3subjects": "3 subjects",
        "paywall.feature.allSubjects": "All subjects",
        "paywall.feature.unlimitedCourses": "Unlimited courses",
        "paywall.feature.miniQuiz": "Mini Quiz",
        "paywall.feature.fullLibrary": "Full library",
        "paywall.plan.yearly": "Yearly",
        "paywall.plan.monthly": "Monthly",
        "paywall.plan.yearlySubtitle": "Billed annually",
        "paywall.plan.monthlySubtitle": "No commitment",
        "paywall.plan.perYear": "/ year",
        "paywall.plan.perMonth": "/ month",
        "paywall.plan.discount": "-58%",
        "paywall.plan.fallback.yearlyPrice": "€39.99",
        "paywall.plan.fallback.monthlyPrice": "€9.99",
        "paywall.plan.fallback.yearlyMonthly": "€3.33 / month",
        "paywall.trialBadge": "3-day free trial",
        "paywall.restoreRow": "Restore · Terms · Privacy",
        "paywall.trialSheet.title": "Start your\n3-day free trial",
        "paywall.trialSheet.start": "Start free trial",
        "paywall.trial.today": "Today",
        "paywall.trial.noPayment": "No payment",
        "paywall.trial.todayDetail": "Access to all Premium features.",
        "paywall.trial.in2days": "In 2 days",
        "paywall.trial.reminder": "We'll remind you",
        "paywall.trial.reminderDetail": "Notification 1 day before the trial ends.",
        "paywall.trial.in3days": "In 3 days",
        "paywall.trial.starts": "Your subscription starts",
        "paywall.trial.startsDetail": "Cancel before if you don't want to continue.",
        "paywall.review1.quote": "Perfect on my commute. I learn every day effortlessly.",
        "paywall.review1.author": "Marie, 28",
        "paywall.review2.quote": "Finally an app that turns scrolling into culture.",
        "paywall.review2.author": "Thomas, 34",
        "paywall.review3.quote": "The courses are short, fun, and I actually remember them.",
        "paywall.review3.author": "Inès, 22",
        "paywall.review4.quote": "My friends ask where I get all these anecdotes.",
        "paywall.review4.author": "Lucas, 31",
        "paywall.review5.quote": "The personalized onboarding convinced me in the first minute.",
        "paywall.review5.author": "Sarah, 26",

        "offer.unique": "Your one-time offer",
        "offer.discount": "-70% FOREVER",
        "offer.perMonth": "/month",
        "offer.billed": "billed",
        "offer.expiresIn": "Expires in",
        "offer.unlock": "Unlock my -70% access",
        "offer.restore": "Restore purchases",
        "offer.feature1": "240 general knowledge courses",
        "offer.feature2": "Unlimited interactive quizzes",
        "offer.feature3": "New content every week",

        "profile.title": "Profile",
        "profile.streak.start": "Read a course to get started!",
        "profile.streak.beginning": "You've started, keep going!",
        "profile.streak.good": "Great consistency 👏",
        "profile.streak.great": "You're on fire 🔥",
        "profile.favorites": "My favorites",
        "profile.favorites.count": "%d saved courses",
        "profile.quiz.recent": "RECENT QUIZZES",
        "profile.quiz.locked": "Quizzes locked",
        "profile.quiz.lockedSubtitle": "Available with the free trial — 3 days free",
        "profile.quiz.unlock": "Unlock my quizzes",
        "profile.quiz.emptyTitle": "No quizzes yet",
        "profile.quiz.emptySubtitle": "Complete a course to take your first quiz.",
        "profile.progress.bySubject": "PROGRESS BY TOPIC",
        "profile.unlock.trial": "Unlock with free trial",
        "profile.quiz.retry": "Retry",
        "profile.quiz.all": "All my quizzes",
        "profile.quiz.none": "No quizzes yet.",
        "profile.progress.max": "%d XP · max level",
        "profile.progress.toNext": "%d XP · %d to lvl. %d",

        "quiz.feedback.correct": "Correct!",
        "quiz.feedback.excellent": "Excellent!",
        "quiz.feedback.amazing": "Amazing!",
        "quiz.feedback.wrong": "Not quite...",
        "quiz.completed": "Well done, quiz complete!",
        "quiz.correctAnswers": "correct answers",
        "quiz.xpProgress": "XP progress",
        "quiz.levelUp": "Level up!",
        "quiz.breakdown.correct": "Correct answers",
        "quiz.breakdown.completed": "Quiz completed",
        "quiz.xpProgress.max": "%d XP · max level",
        "quiz.xpProgress.toNext": "%d XP to lvl. %d",

        "course.completed": "Lesson complete!",
        "course.dailyFreeDone": "You've completed your free course for today",
        "course.streak.day": "Day streak",
        "course.streak.days": "Day streak",
        "course.streak.message": "You're becoming truly cultured — unstoppable in %@!",
        "course.streak.onTrack": "On your way to a streak!",

        "prepaywall.quiz.title": "Unlock quizzes\nfor free",
        "prepaywall.quiz.subtitle": "Test your knowledge and\nprogress every day",
        "prepaywall.course.subtitle": "Keep learning and\ndiscover new topics",
        "prepaywall.course.access": "Access the course",

        "levelUp.title": "Level up!",

        "globalRank.curieux": "Curious",
        "globalRank.erudit": "Scholar",
        "globalRank.savant": "Sage",
        "globalRank.maitre": "Master",
        "globalRank.legende": "Legend",
        "globalRank.title": "Global rank",
        "globalRank.badge": "GLOBAL RANK",
        "globalRank.maxLevel": "Max level",
        "globalRank.xpBefore": "%d XP to %@",
        "globalRank.newRank": "New rank!",
        "globalRank.reachedLevel": "You just reached level %d",

        "paywall.unavailable.title": "Offer unavailable",
        "paywall.unavailable.message": "Unable to load this offer right now.",
    ]

    // MARK: - Portuguese

    private static let portuguese: [String: String] = [
        "tab.home": "Início",
        "tab.library": "Biblioteca",
        "tab.profile": "Perfil",

        "library.title": "Biblioteca",
        "library.tab.courses": "Cursos",
        "library.tab.collections": "Coleções",
        "library.search.placeholder": "Pesquisar um curso...",

        "language.section": "Idioma",
        "language.french": "Français",
        "language.english": "English",
        "language.portuguese": "Português",

        "onboarding.intro.title": "Cultiva-te\nem 10 minutos\npor dia",
        "onboarding.intro.cta": "Começar",

        "settings.title": "Definições",
        "settings.section.progress": "Progresso",
        "settings.section.premium": "Premium",
        "settings.section.data": "Dados",
        "settings.section.legal": "Jurídico",
        "settings.section.about": "Sobre",
        "settings.section.developer": "Programador",
        "settings.courses.completed": "%d cursos concluídos",
        "settings.courses.available": "de %d disponíveis",
        "settings.streak.title": "%d dias seguidos",
        "settings.streak.subtitle": "Continua assim!",
        "settings.premium.title": "Torna-te Premium",
        "settings.premium.subtitle": "Cursos e quizzes ilimitados",
        "settings.reset.title": "Repor progresso",
        "settings.terms.title": "Termos de Serviço",
        "settings.privacy.title": "Política de Privacidade",
        "settings.restore.title": "Restaurar compras",
        "settings.about.version": "Versão",
        "settings.about.courses": "Cursos disponíveis",
        "settings.debug.resetOnboarding": "Reiniciar onboarding",
        "settings.debug.resetDaily": "Repor curso diário",
        "settings.debug.daily.done": "Concluído hoje",
        "settings.debug.daily.pending": "Ainda por concluir",
        "settings.footer": "Feito com ♥ — Sophia",
        "settings.reset.alert.title": "Repor?",
        "settings.reset.alert.cancel": "Cancelar",
        "settings.reset.alert.confirm": "Repor",
        "settings.reset.alert.message": "Todo o teu progresso será apagado. Esta ação não pode ser anulada.",
        "settings.onboarding.alert.title": "Reiniciar onboarding?",
        "settings.onboarding.alert.confirm": "Reiniciar",
        "settings.onboarding.alert.message": "O onboarding vai recomeçar desde o início (apenas DEBUG).",

        "legal.terms.title": "Termos",
        "legal.privacy.title": "Privacidade",

        "subject.histoire": "História",
        "subject.sciences": "Ciências",
        "subject.litterature": "Literatura",
        "subject.art": "Arte",
        "subject.mythologie": "Mitologia",
        "subject.comprendreLeMonde": "Compreender o mundo atual",
        "subject.histoire.short": "História",
        "subject.sciences.short": "Ciências",
        "subject.litterature.short": "Literatura",
        "subject.art.short": "Arte",
        "subject.mythologie.short": "Mitologia",
        "subject.comprendreLeMonde.short": "Mundo atual",

        "rarity.commune": "Comum",
        "rarity.rare": "Rara",
        "rarity.epique": "Épica",
        "rarity.legendaire": "Lendária",

        "home.skip": "Ignorar",
        "home.bravo": "Boa!",
        "home.allCompleted": "Concluíste todos os cursos disponíveis.",
        "home.locked": "Bloqueado",
        "home.start": "Começar",

        "library.empty.title": "Sem resultados",
        "library.empty.subtitle": "Experimenta outra palavra-chave.",
        "library.seeMore": "Ver mais",
        "library.unlock": "Desbloquear",
        "library.lockedBadge": "BLOQUEADO",

        "collections.title": "COLEÇÕES",
        "collections.subtitle": "Percursos guiados para ligar ideias entre si.",
        "collections.complete": "Coleção concluída",
        "collections.progress": "%d / %d cursos concluídos",
        "collections.badge.complete": "CONCLUÍDA",
        "collections.badge.path": "PERCURSO",
        "collections.xpAtEnd": "+%d XP no final",
        "collections.pathComplete": "Percurso concluído",

        "subject.courses.count": "%d cursos",
        "subject.completed.singular": "%d concluído",
        "subject.completed.plural": "%d concluídos",

        "cards.collect.title": "CARTAS A COLECIONAR",
        "cards.seeAll": "Ver tudo →",
        "cards.unit": "cartas",
        "cards.empty": "Conclui um curso para desbloqueares as tuas primeiras cartas.",
        "cards.quizStats.title": "QUIZZES CONCLUÍDOS",
        "cards.correctAnswers": "respostas certas",
        "cards.successRate": "taxa de sucesso",
        "cards.myCards": "As minhas cartas",
        "cards.unlocked": "desbloqueadas",
        "cards.unlocked.title": "Carta desbloqueada!",
        "cards.tapToReveal": "Toca para revelar",
        "cards.globalXP": "+%d XP globais",

        "course.keyTakeaway": "A RETER",

        "common.continue": "Continuar",

        "celebration.collectionAdvanced": "Coleção avançada!",
        "celebration.coursesCompleted": "cursos concluídos",
        "celebration.collectionComplete": "Coleção concluída!",

        "common.next": "Seguinte",
        "common.letsGo": "Vamos!",
        "common.letsGoShort": "Vamos",
        "common.close": "Fechar",
        "common.processing": "A processar…",
        "common.startLearning": "Começar a aprender",
        "common.backHome": "Voltar ao início",
        "common.retryQuiz": "Repetir quiz",
        "common.seeMoreArrow": "Ver mais →",
        "common.streak.day": "DIA",
        "common.streak.days": "DIAS",
        "common.levelShort": "NÍV. %d",
        "common.increaseGoal": "Aumentar objetivo",
        "common.decreaseGoal": "Diminuir objetivo",
        "common.miniQuiz": "Miniquiz",
        "common.xpEarned": "+%d XP ganhos",
        "common.xpBeforeNext": "· %d até ao nív. %d",

        "onboarding.welcome.title": "Sophia é a tua parceira para dominares",
        "onboarding.welcome.rotating.histoire": "a história",
        "onboarding.welcome.rotating.sciences": "as ciências",
        "onboarding.welcome.rotating.litterature": "a literatura",
        "onboarding.welcome.rotating.art": "a arte",
        "onboarding.welcome.rotating.mythologie": "a mitologia",
        "onboarding.welcome.rotating.comprendreLeMonde": "a atualidade",

        "onboarding.phone.title": "Quanto tempo\npassas ao telemóvel?",
        "onboarding.phone.subtitle": "Em média, por dia.",
        "onboarding.phone.lessThan1h": "Menos de 1h",
        "onboarding.phone.1to2h": "1h a 2h",
        "onboarding.phone.2to4h": "2h a 4h",
        "onboarding.phone.moreThan4h": "Mais de 4h",
        "onboarding.phone.hours.1": "1 hora",
        "onboarding.phone.hours.2": "2 horas",
        "onboarding.phone.hours.3": "3 horas",
        "onboarding.phone.hours.5": "5 horas",

        "onboarding.wasted.intro": "%@ por dia ao telemóvel, isso são",
        "onboarding.wasted.hoursLost": "horas perdidas por ano.",
        "onboarding.wasted.daysComplete": "Isto dá %@ completos.",
        "onboarding.wasted.transform": "Com a Sophia, transforma esse tempo em cultura.",
        "onboarding.wasted.days.7": "7 dias",
        "onboarding.wasted.days.23": "23 dias",
        "onboarding.wasted.days.45": "45 dias",
        "onboarding.wasted.days.91": "91 dias",

        "onboarding.objectives.title": "Qual é o teu objetivo\ncom a Sophia?",
        "onboarding.objectives.subtitle": "Seleciona um ou mais objetivos.",
        "onboarding.objective.curious": "Ser mais curioso",
        "onboarding.objective.learnNew": "Aprender coisas novas",
        "onboarding.objective.impress": "Impressionar quem te rodeia",
        "onboarding.objective.social": "Sentir-te mais à vontade socialmente",
        "onboarding.objective.reduceScroll": "Reduzir o tempo que passas a fazer scroll",

        "onboarding.interests.title": "Que temas\nte interessam?",
        "onboarding.interests.subtitle": "Seleciona pelo menos um tema.",

        "onboarding.dailyGoal.title": "Todos os dias, queres aprender...",
        "onboarding.dailyGoal.subtitle": "Poderás alterar o teu objetivo mais tarde.",
        "onboarding.dailyGoal.perDay": "%@ por dia!",
        "onboarding.dailyGoal.singular": "lição",
        "onboarding.dailyGoal.plural": "lições",

        "onboarding.loading.title": "Estamos a preparar o teu percurso",
        "onboarding.loading.subtitle": "Só alguns segundos, prometemos.",
        "onboarding.loading.step1": "A analisar as tuas respostas",
        "onboarding.loading.step2": "A selecionar as tuas 3 matérias",
        "onboarding.loading.step3": "A preparar o teu percurso",

        "onboarding.projection.line1": "Pequeno hábito,",
        "onboarding.projection.line2": "resultados incríveis.",
        "onboarding.projection.its": "São",
        "onboarding.projection.newThings": "novas coisas que vais saber",
        "onboarding.projection.inOneYear": "dentro de um ano.",

        "onboarding.social.badge": "Avaliações verificadas",
        "onboarding.social.stat": "dos utilizadores sentem-se\nmais interessantes e mais à vontade\nem contextos sociais graças à Sophia.",
        "onboarding.social.review1.name": "Lucas M.",
        "onboarding.social.review1.text": "Antes sentia-me sem cultura geral; agora tenho sempre algo interessante para contar.",
        "onboarding.social.review2.name": "Camille R.",
        "onboarding.social.review2.text": "10 minutos por dia e sinto que aprendo mais do que nas aulas.",
        "onboarding.social.review3.name": "Thomas D.",
        "onboarding.social.review3.text": "Adoro o formato. É claro, rápido e retenho mesmo o que aprendo.",

        "onboarding.graph.title": "A tua progressão\ncultural",
        "onboarding.graph.subtitle": "Com e sem Sophia",
        "onboarding.graph.culture": "CULTURA",
        "onboarding.graph.withSophia": "Com Sophia",
        "onboarding.graph.withoutSophia": "Sem Sophia",
        "onboarding.graph.today": "Hoje",
        "onboarding.graph.oneYear": "1 ano",
        "onboarding.graph.tagline": "A Sophia acelera a tua cultura\nde forma exponencial.",

        "onboarding.final.title": "Perfil pronto!",
        "onboarding.final.subtitle": "Boas-vindas à Sophia.\nComeça já a aprender.",
        "onboarding.final.subjects": "AS TUAS MATÉRIAS",

        "onboarding.trial.badge": "Oferta de boas-vindas",
        "onboarding.trial.title": "Os teus primeiros 3 dias\nsão grátis",
        "onboarding.trial.unlimitedCourses": "Cursos ilimitados",
        "onboarding.trial.allQuizzes": "Todos os quizzes",
        "onboarding.trial.noSurprise": "Sem surpresas",
        "onboarding.trial.notifyTitle": "Vamos avisar-te\n1 dia antes do fim\ndo teu teste gratuito",
        "onboarding.trial.cancelAnytime": "Cancela a qualquer momento, sem custos.",
        "onboarding.trial.day1": "DIA 1",
        "onboarding.trial.day2": "DIA 2",
        "onboarding.trial.day3": "DIA 3",
        "onboarding.trial.fullAccess": "Acesso total",
        "onboarding.trial.notificationSent": "Notificação enviada",
        "onboarding.trial.trialEnds": "Fim do teste",

        "paywall.cancelAnytime": "Cancela a qualquer momento, sem custos.",
        "paywall.header": "Torna-te a pessoa\nmais interessante\nda sala.",
        "paywall.freeSubjects": "As tuas 3 matérias gratuitas",
        "paywall.lockedSubjects": "3 matérias por desbloquear",
        "paywall.teaserTitle": "Uma amostra do que te espera",
        "paywall.teaserSubtitle": "Centenas de cursos premium por desbloquear",
        "paywall.featureColumn": "Funcionalidade",
        "paywall.freeColumn": "Grátis",
        "paywall.premiumColumn": "Premium",
        "paywall.feature.3subjects": "3 matérias",
        "paywall.feature.allSubjects": "Todas as matérias",
        "paywall.feature.unlimitedCourses": "Cursos ilimitados",
        "paywall.feature.miniQuiz": "Miniquiz",
        "paywall.feature.fullLibrary": "Biblioteca completa",
        "paywall.plan.yearly": "Anual",
        "paywall.plan.monthly": "Mensal",
        "paywall.plan.yearlySubtitle": "Cobrado anualmente",
        "paywall.plan.monthlySubtitle": "Sem fidelização",
        "paywall.plan.perYear": "/ ano",
        "paywall.plan.perMonth": "/ mês",
        "paywall.plan.discount": "-58%",
        "paywall.plan.fallback.yearlyPrice": "39,99 €",
        "paywall.plan.fallback.monthlyPrice": "9,99 €",
        "paywall.plan.fallback.yearlyMonthly": "3,33 € / mês",
        "paywall.trialBadge": "Teste gratuito de 3 dias",
        "paywall.restoreRow": "Restaurar · Termos · Privacidade",
        "paywall.trialSheet.title": "Começa o teu\nteste gratuito de 3 dias",
        "paywall.trialSheet.start": "Começar teste gratuito",
        "paywall.trial.today": "Hoje",
        "paywall.trial.noPayment": "Sem pagamento",
        "paywall.trial.todayDetail": "Acesso a todas as funcionalidades Premium.",
        "paywall.trial.in2days": "Daqui a 2 dias",
        "paywall.trial.reminder": "Avisamos-te",
        "paywall.trial.reminderDetail": "Notificação 1 dia antes do fim do teste.",
        "paywall.trial.in3days": "Daqui a 3 dias",
        "paywall.trial.starts": "A tua subscrição começa",
        "paywall.trial.startsDetail": "Cancela antes se não quiseres continuar.",
        "paywall.review1.quote": "Perfeito para as deslocações. Aprendo todos os dias sem esforço.",
        "paywall.review1.author": "Marie, 28",
        "paywall.review2.quote": "Finalmente uma app que transforma scroll em cultura.",
        "paywall.review2.author": "Thomas, 34",
        "paywall.review3.quote": "Os cursos são curtos, divertidos e eu retenho mesmo.",
        "paywall.review3.author": "Inès, 22",
        "paywall.review4.quote": "Os meus amigos perguntam-me de onde tiro estas histórias todas.",
        "paywall.review4.author": "Lucas, 31",
        "paywall.review5.quote": "O onboarding personalizado convenceu-me logo no primeiro minuto.",
        "paywall.review5.author": "Sarah, 26",

        "offer.unique": "A tua oferta única",
        "offer.discount": "-70% PARA SEMPRE",
        "offer.perMonth": "/mês",
        "offer.billed": "cobrado",
        "offer.expiresIn": "Expira em",
        "offer.unlock": "Desbloquear o meu acesso -70%",
        "offer.restore": "Restaurar compras",
        "offer.feature1": "240 cursos de cultura geral",
        "offer.feature2": "Quizzes interativos ilimitados",
        "offer.feature3": "Novo conteúdo todas as semanas",

        "profile.title": "Perfil",
        "profile.streak.start": "Lê um curso para começares!",
        "profile.streak.beginning": "Já começaste, continua!",
        "profile.streak.good": "Boa consistência 👏",
        "profile.streak.great": "Estás imparável 🔥",
        "profile.favorites": "Os meus favoritos",
        "profile.favorites.count": "%d cursos guardados",
        "profile.quiz.recent": "QUIZZES RECENTES",
        "profile.quiz.locked": "Quizzes bloqueados",
        "profile.quiz.lockedSubtitle": "Disponíveis com o teste gratuito — 3 dias grátis",
        "profile.quiz.unlock": "Desbloquear os meus quizzes",
        "profile.quiz.emptyTitle": "Ainda não há quizzes",
        "profile.quiz.emptySubtitle": "Conclui um curso para fazeres o teu primeiro quiz.",
        "profile.progress.bySubject": "PROGRESSO POR MATÉRIA",
        "profile.unlock.trial": "Desbloqueia com o teste gratuito",
        "profile.quiz.retry": "Repetir",
        "profile.quiz.all": "Todos os meus quizzes",
        "profile.quiz.none": "Ainda não há quizzes.",
        "profile.progress.max": "%d XP · nível máximo",
        "profile.progress.toNext": "%d XP · %d até ao nív. %d",

        "quiz.feedback.correct": "Correto!",
        "quiz.feedback.excellent": "Excelente!",
        "quiz.feedback.amazing": "Incrível!",
        "quiz.feedback.wrong": "Quase...",
        "quiz.completed": "Boa, quiz concluído!",
        "quiz.correctAnswers": "respostas certas",
        "quiz.xpProgress": "Progresso de XP",
        "quiz.levelUp": "Subiste de nível!",
        "quiz.breakdown.correct": "Respostas certas",
        "quiz.breakdown.completed": "Quiz concluído",
        "quiz.xpProgress.max": "%d XP · nível máximo",
        "quiz.xpProgress.toNext": "%d XP até ao nív. %d",

        "course.completed": "Curso concluído!",
        "course.dailyFreeDone": "Concluíste o teu curso gratuito de hoje",
        "course.streak.day": "Dia seguido",
        "course.streak.days": "Dias seguidos",
        "course.streak.message": "Estás mesmo a tornar-te culto — vais ficar imbatível em %@!",
        "course.streak.onTrack": "No bom caminho para a tua sequência!",

        "prepaywall.quiz.title": "Desbloqueia gratuitamente\nos quizzes",
        "prepaywall.quiz.subtitle": "Testa os teus conhecimentos e\nprogride todos os dias",
        "prepaywall.course.subtitle": "Continua a aprender e\ndescobre novos temas",
        "prepaywall.course.access": "Aceder ao curso",

        "levelUp.title": "Subiste de nível!",

        "globalRank.curieux": "Curioso",
        "globalRank.erudit": "Erudito",
        "globalRank.savant": "Sábio",
        "globalRank.maitre": "Mestre",
        "globalRank.legende": "Lenda",
        "globalRank.title": "Classificação global",
        "globalRank.badge": "CLASSIFICAÇÃO GLOBAL",
        "globalRank.maxLevel": "Nível máximo",
        "globalRank.xpBefore": "%d XP até %@",
        "globalRank.newRank": "Novo estatuto!",
        "globalRank.reachedLevel": "Acabaste de alcançar o nível %d",

        "paywall.unavailable.title": "Oferta indisponível",
        "paywall.unavailable.message": "Não foi possível carregar esta oferta neste momento.",

    ]
}