import Foundation

enum AppLocalizable {
    static func string(_ key: String, language: AppLanguage) -> String {
        switch language {
        case .french:
            return french[key] ?? english[key] ?? key
        case .english:
            return english[key] ?? key
        case .german:
            return german[key] ?? english[key] ?? key
        }
    }

    // MARK: - French

    private static let french: [String: String] = [
        "tab.home": "Home",
        "tab.library": "Biblio",
        "tab.profile": "Profil",

        "library.title": "Bibliothèque",
        "library.tab.courses": "Cours",
        "library.tab.collections": "Collections",
        "library.search.placeholder": "Rechercher un cours...",

        "language.section": "Langue",
        "language.french": "Français",
        "language.english": "English",
        "language.german": "Deutsch",

        "onboarding.intro.title": "Deviens cultivé\nen 10 minutes\npar jour",
        "onboarding.intro.cta": "Commencer",

        "settings.title": "Options",
        "settings.section.progress": "Progression",
        "settings.section.premium": "Premium",
        "settings.section.data": "Données",
        "settings.section.legal": "Légal",
        "settings.section.about": "À propos",
        "settings.section.developer": "Développeur",
        "settings.courses.completed": "%d cours terminés",
        "settings.courses.available": "sur %d disponibles",
        "settings.streak.title": "%d jours de suite",
        "settings.streak.subtitle": "Continue comme ça !",
        "settings.premium.title": "Passer à Premium",
        "settings.premium.subtitle": "Cours et quiz illimités",
        "settings.reset.title": "Réinitialiser la progression",
        "settings.terms.title": "Conditions générales",
        "settings.privacy.title": "Politique de confidentialité",
        "settings.restore.title": "Restaurer les achats",
        "settings.about.version": "Version",
        "settings.about.courses": "Cours disponibles",
        "settings.debug.resetOnboarding": "Refaire l'onboarding",
        "settings.debug.resetDaily": "Reset cours du jour",
        "settings.debug.daily.done": "Fait aujourd'hui",
        "settings.debug.daily.pending": "Pas encore fait",
        "settings.footer": "Made with ♥ — Sophia",
        "settings.reset.alert.title": "Réinitialiser ?",
        "settings.reset.alert.cancel": "Annuler",
        "settings.reset.alert.confirm": "Réinitialiser",
        "settings.reset.alert.message": "Toute ta progression sera effacée. Cette action est irréversible.",
        "settings.onboarding.alert.title": "Refaire l'onboarding ?",
        "settings.onboarding.alert.confirm": "Relancer",
        "settings.onboarding.alert.message": "L'onboarding sera relancé depuis le début (DEBUG uniquement).",

        "legal.terms.title": "Conditions",
        "legal.privacy.title": "Confidentialité",

        "subject.histoire": "Histoire",
        "subject.sciences": "Sciences",
        "subject.litterature": "Littérature",
        "subject.art": "Art",
        "subject.mythologie": "Mythologie",
        "subject.comprendreLeMonde": "Comprendre le monde actuel",
        "subject.histoire.short": "Histoire",
        "subject.sciences.short": "Sciences",
        "subject.litterature.short": "Littérature",
        "subject.art.short": "Art",
        "subject.mythologie.short": "Mythologie",
        "subject.comprendreLeMonde.short": "Monde actuel",

        "rarity.commune": "Commune",
        "rarity.rare": "Rare",
        "rarity.epique": "Épique",
        "rarity.legendaire": "Légendaire",

        "home.skip": "Passer",
        "home.bravo": "Bravo !",
        "home.allCompleted": "Tu as terminé tous les cours disponibles.",
        "home.locked": "Verrouillé",
        "home.start": "Commencer",

        "library.empty.title": "Aucun résultat",
        "library.empty.subtitle": "Essaie un autre mot-clé.",
        "library.seeMore": "Voir plus",
        "library.unlock": "Débloquer",
        "library.lockedBadge": "VERROUILLÉ",

        "collections.title": "COLLECTIONS",
        "collections.subtitle": "Des parcours guidés pour relier les idées entre elles.",
        "collections.complete": "Collection terminée",
        "collections.progress": "%d / %d cours terminés",
        "collections.badge.complete": "TERMINÉE",
        "collections.badge.path": "PARCOURS",
        "collections.xpAtEnd": "+%d XP à la fin",
        "collections.pathComplete": "Parcours complet",

        "subject.courses.count": "%d cours",
        "subject.completed.singular": "%d terminé",
        "subject.completed.plural": "%d terminés",

        "cards.collect.title": "CARTES À COLLECTER",
        "cards.seeAll": "Voir tout →",
        "cards.unit": "cartes",
        "cards.empty": "Termine un cours pour débloquer tes premières cartes.",
        "cards.quizStats.title": "QUIZZ RÉUSSIS",
        "cards.correctAnswers": "bonnes réponses",
        "cards.successRate": "réussite",
        "cards.myCards": "Mes cartes",
        "cards.unlocked": "débloquées",
        "cards.unlocked.title": "Carte débloquée !",
        "cards.tapToReveal": "Tape pour révéler",
        "cards.globalXP": "+%d XP globaux",

        "course.keyTakeaway": "À RETENIR",

        "common.continue": "Continuer",

        "celebration.collectionAdvanced": "Collection avancée !",
        "celebration.coursesCompleted": "cours terminés",
        "celebration.collectionComplete": "Collection terminée !",

        "common.next": "Suivant",
        "common.letsGo": "C'est parti !",
        "common.letsGoShort": "C'est parti",
        "common.close": "Fermer",
        "common.processing": "Traitement…",
        "common.startLearning": "Commencer à apprendre",
        "common.backHome": "Retour à l'accueil",
        "common.retryQuiz": "Refaire le quiz",
        "common.seeMoreArrow": "Voir plus →",
        "common.streak.day": "JOUR",
        "common.streak.days": "JOURS",
        "common.levelShort": "NIV. %d",
        "common.increaseGoal": "Augmenter l'objectif",
        "common.decreaseGoal": "Réduire l'objectif",
        "common.miniQuiz": "Mini Quiz",
        "common.xpEarned": "+%d XP gagnés",
        "common.xpBeforeNext": "· %d avant niv. %d",

        "onboarding.welcome.title": "Sophia est ton partenaire pour maîtriser",
        "onboarding.welcome.rotating.histoire": "l'histoire",
        "onboarding.welcome.rotating.sciences": "les sciences",
        "onboarding.welcome.rotating.litterature": "la littérature",
        "onboarding.welcome.rotating.art": "l'art",
        "onboarding.welcome.rotating.mythologie": "la mythologie",
        "onboarding.welcome.rotating.comprendreLeMonde": "le monde actuel",

        "onboarding.phone.title": "Combien de temps\nsur ton téléphone ?",
        "onboarding.phone.subtitle": "Chaque jour, en moyenne.",
        "onboarding.phone.lessThan1h": "Moins de 1h",
        "onboarding.phone.1to2h": "1h à 2h",
        "onboarding.phone.2to4h": "2h à 4h",
        "onboarding.phone.moreThan4h": "Plus de 4h",
        "onboarding.phone.hours.1": "1 heure",
        "onboarding.phone.hours.2": "2 heures",
        "onboarding.phone.hours.3": "3 heures",
        "onboarding.phone.hours.5": "5 heures",

        "onboarding.wasted.intro": "%@ par jour sur ton téléphone, c'est",
        "onboarding.wasted.hoursLost": "heures perdues par an.",
        "onboarding.wasted.daysComplete": "Soit %@ complets.",
        "onboarding.wasted.transform": "Avec Sophia, transforme ce temps en culture.",
        "onboarding.wasted.days.7": "7 jours",
        "onboarding.wasted.days.23": "23 jours",
        "onboarding.wasted.days.45": "45 jours",
        "onboarding.wasted.days.91": "91 jours",

        "onboarding.objectives.title": "Ton objectif\navec Sophia ?",
        "onboarding.objectives.subtitle": "Sélectionne un ou plusieurs objectifs.",
        "onboarding.objective.curious": "Être plus curieux",
        "onboarding.objective.learnNew": "Apprendre de nouvelles choses",
        "onboarding.objective.impress": "Impressionner tes proches",
        "onboarding.objective.social": "Renforcer ton aisance en société",
        "onboarding.objective.reduceScroll": "Réduire ton temps à scroller",

        "onboarding.interests.title": "Quels sujets\nt'intéressent ?",
        "onboarding.interests.subtitle": "Sélectionne au moins un sujet.",

        "onboarding.dailyGoal.title": "Chaque jour, tu veux apprendre...",
        "onboarding.dailyGoal.subtitle": "Tu pourras modifier ton objectif plus tard.",
        "onboarding.dailyGoal.perDay": "%@ par jour !",
        "onboarding.dailyGoal.singular": "apprentissage",
        "onboarding.dailyGoal.plural": "apprentissages",

        "onboarding.loading.title": "On prépare ton parcours",
        "onboarding.loading.subtitle": "Quelques secondes, promis.",
        "onboarding.loading.step1": "Analyse de tes réponses",
        "onboarding.loading.step2": "Sélection de tes 3 matières",
        "onboarding.loading.step3": "Préparation de ton parcours",

        "onboarding.projection.line1": "Petite habitude,",
        "onboarding.projection.line2": "résultats incroyables.",
        "onboarding.projection.its": "C'est",
        "onboarding.projection.newThings": "nouvelles choses que tu sauras",
        "onboarding.projection.inOneYear": "d'ici un an.",

        "onboarding.social.badge": "Avis vérifiés",
        "onboarding.social.stat": "des utilisateurs se sentent\nplus intéressants et à l'aise\nen société grâce à Sophia.",
        "onboarding.social.review1.name": "Lucas M.",
        "onboarding.social.review1.text": "Je me sentais nul en culture G, maintenant j'ai toujours un truc intéressant à raconter.",
        "onboarding.social.review2.name": "Camille R.",
        "onboarding.social.review2.text": "10 min par jour et j'ai l'impression d'apprendre plus qu'en cours.",
        "onboarding.social.review3.name": "Thomas D.",
        "onboarding.social.review3.text": "J'adore le format. C'est clair, rapide et on retient vraiment.",

        "onboarding.graph.title": "Ta progression\nculturelle",
        "onboarding.graph.subtitle": "Avec et sans Sophia",
        "onboarding.graph.culture": "CULTURE",
        "onboarding.graph.withSophia": "Avec Sophia",
        "onboarding.graph.withoutSophia": "Sans Sophia",
        "onboarding.graph.today": "Aujourd'hui",
        "onboarding.graph.oneYear": "1 an",
        "onboarding.graph.tagline": "Sophia accélère ta culture\nde manière exponentielle.",

        "onboarding.final.title": "Profil prêt !",
        "onboarding.final.subtitle": "Bienvenue dans Sophia.\nCommence à apprendre dès maintenant.",
        "onboarding.final.subjects": "TES MATIÈRES",

        "onboarding.trial.badge": "Offre de bienvenue",
        "onboarding.trial.title": "Vos 3 premiers jours\nsont offerts",
        "onboarding.trial.unlimitedCourses": "Cours illimités",
        "onboarding.trial.allQuizzes": "Tous les quiz",
        "onboarding.trial.noSurprise": "Pas de surprise",
        "onboarding.trial.notifyTitle": "Nous vous notifierons\n1 jour avant la fin\nde votre essai gratuit",
        "onboarding.trial.cancelAnytime": "Annulez à tout moment, sans frais.",
        "onboarding.trial.day1": "JOUR 1",
        "onboarding.trial.day2": "JOUR 2",
        "onboarding.trial.day3": "JOUR 3",
        "onboarding.trial.fullAccess": "Accès complet",
        "onboarding.trial.notificationSent": "Notification envoyée",
        "onboarding.trial.trialEnds": "Fin de l'essai",

        "paywall.cancelAnytime": "Annule à tout moment, sans frais.",
        "paywall.header": "Deviens la personne\nla plus intéressante\nde la pièce.",
        "paywall.freeSubjects": "Tes 3 matières gratuites",
        "paywall.lockedSubjects": "3 matières à débloquer",
        "paywall.teaserTitle": "Un aperçu de ce qui t'attend",
        "paywall.teaserSubtitle": "Des centaines de cours premium à débloquer",
        "paywall.featureColumn": "Fonctionnalité",
        "paywall.freeColumn": "Gratuit",
        "paywall.premiumColumn": "Premium",
        "paywall.feature.3subjects": "3 matières",
        "paywall.feature.allSubjects": "Toutes les matières",
        "paywall.feature.unlimitedCourses": "Cours illimités",
        "paywall.feature.miniQuiz": "Mini Quiz",
        "paywall.feature.fullLibrary": "Bibliothèque complète",
        "paywall.plan.yearly": "Annuel",
        "paywall.plan.monthly": "Mensuel",
        "paywall.plan.yearlySubtitle": "Facturé annuellement",
        "paywall.plan.monthlySubtitle": "Sans engagement",
        "paywall.plan.perYear": "/ an",
        "paywall.plan.perMonth": "/ mois",
        "paywall.plan.discount": "-58%",
        "paywall.plan.fallback.yearlyPrice": "39,99 €",
        "paywall.plan.fallback.monthlyPrice": "9,99 €",
        "paywall.plan.fallback.yearlyMonthly": "3,33 € / mois",
        "paywall.trialBadge": "Essai gratuit 3 jours",
        "paywall.restoreRow": "Restaurer · Conditions · Confidentialité",
        "paywall.trialSheet.title": "Commence ton essai\ngratuit de 3 jours",
        "paywall.trialSheet.start": "Commencer l'essai gratuit",
        "paywall.trial.today": "Aujourd'hui",
        "paywall.trial.noPayment": "Aucun paiement",
        "paywall.trial.todayDetail": "Accès à toutes les fonctionnalités Premium.",
        "paywall.trial.in2days": "Dans 2 jours",
        "paywall.trial.reminder": "On te prévient",
        "paywall.trial.reminderDetail": "Notification 1 jour avant la fin de l'essai.",
        "paywall.trial.in3days": "Dans 3 jours",
        "paywall.trial.starts": "Ton abonnement démarre",
        "paywall.trial.startsDetail": "Annule avant si tu ne veux pas continuer.",
        "paywall.review1.quote": "Parfait dans les transports. J'apprends chaque jour sans effort.",
        "paywall.review1.author": "Marie, 28 ans",
        "paywall.review2.quote": "Enfin une app qui me fait passer du scroll à la culture.",
        "paywall.review2.author": "Thomas, 34 ans",
        "paywall.review3.quote": "Les cours sont courts, drôles, et je retiens vraiment.",
        "paywall.review3.author": "Inès, 22 ans",
        "paywall.review4.quote": "Mes amis me demandent d'où je sors toutes ces anecdotes.",
        "paywall.review4.author": "Lucas, 31 ans",
        "paywall.review5.quote": "L'onboarding personnalisé m'a convaincu dès la première minute.",
        "paywall.review5.author": "Sarah, 26 ans",

        "offer.unique": "Votre offre unique",
        "offer.discount": "-70% POUR TOUJOURS",
        "offer.perMonth": "/mois",
        "offer.billed": "facturé",
        "offer.expiresIn": "Expire dans",
        "offer.unlock": "Débloquer mon accès -70%",
        "offer.restore": "Restaurer les achats",
        "offer.feature1": "240 cours de culture générale",
        "offer.feature2": "Quiz interactifs illimités",
        "offer.feature3": "Nouveau contenu chaque semaine",

        "profile.title": "Profil",
        "profile.streak.start": "Lis un cours pour démarrer !",
        "profile.streak.beginning": "Tu as commencé, continue !",
        "profile.streak.good": "Belle régularité 👏",
        "profile.streak.great": "Tu es en feu 🔥",
        "profile.favorites": "Mes favoris",
        "profile.favorites.count": "%d cours sauvegardés",
        "profile.quiz.recent": "MES QUIZ RÉCENTS",
        "profile.quiz.locked": "Quiz verrouillés",
        "profile.quiz.lockedSubtitle": "Disponibles avec l'essai gratuit — 3 jours offerts",
        "profile.quiz.unlock": "Débloquer mes quiz",
        "profile.quiz.emptyTitle": "Pas encore de quiz",
        "profile.quiz.emptySubtitle": "Termine un cours pour passer ton premier quiz.",
        "profile.progress.bySubject": "PROGRESSION PAR THÈME",
        "profile.unlock.trial": "Débloque avec l'essai gratuit",
        "profile.quiz.retry": "Refaire",
        "profile.quiz.all": "Tous mes quiz",
        "profile.quiz.none": "Aucun quiz pour le moment.",
        "profile.progress.max": "%d XP · niveau max",
        "profile.progress.toNext": "%d XP · %d avant niv. %d",

        "quiz.feedback.correct": "Bonne réponse !",
        "quiz.feedback.excellent": "Excellent !",
        "quiz.feedback.amazing": "Incroyable !",
        "quiz.feedback.wrong": "Pas tout à fait...",
        "quiz.completed": "Bravo, quiz terminé !",
        "quiz.correctAnswers": "bonnes réponses",
        "quiz.xpProgress": "Progression XP",
        "quiz.levelUp": "Niveau supérieur !",
        "quiz.breakdown.correct": "Bonnes réponses",
        "quiz.breakdown.completed": "Quiz terminé",
        "quiz.xpProgress.max": "%d XP · niveau max",
        "quiz.xpProgress.toNext": "%d XP avant niv. %d",

        "course.completed": "Apprentissage terminé !",
        "course.dailyFreeDone": "Tu as terminé ton cours gratuit du jour",
        "course.streak.day": "Jour de suite",
        "course.streak.days": "Jours de suite",
        "course.streak.message": "Tu deviens vraiment cultivé, tu deviens incollable en %@ !",
        "course.streak.onTrack": "En route pour ta série !",

        "prepaywall.quiz.title": "Débloquez gratuitement\nles quiz",
        "prepaywall.quiz.subtitle": "Testez vos connaissances et\nprogressez chaque jour",
        "prepaywall.course.subtitle": "Continuez à apprendre et\ndécouvrez de nouveaux sujets",
        "prepaywall.course.access": "Accéder au cours",

        "levelUp.title": "Niveau supérieur !",

        "globalRank.curieux": "Curieux",
        "globalRank.erudit": "Érudit",
        "globalRank.savant": "Savant",
        "globalRank.maitre": "Maître",
        "globalRank.legende": "Légende",
        "globalRank.title": "Rang global",
        "globalRank.badge": "RANG GLOBAL",
        "globalRank.maxLevel": "Niveau max",
        "globalRank.xpBefore": "%d XP avant %@",
        "globalRank.newRank": "Nouveau rang !",
        "globalRank.reachedLevel": "Tu viens d'atteindre le niveau %d",

        "paywall.unavailable.title": "Offre indisponible",
        "paywall.unavailable.message": "Impossible de charger cette offre pour le moment.",
    ]

    // MARK: - English

    private static let english: [String: String] = [
        "tab.home": "Home",
        "tab.library": "Library",
        "tab.profile": "Profile",

        "library.title": "Library",
        "library.tab.courses": "Courses",
        "library.tab.collections": "Collections",
        "library.search.placeholder": "Search for a course...",

        "language.section": "Language",
        "language.french": "Français",
        "language.english": "English",
        "language.german": "Deutsch",

        "onboarding.intro.title": "Become cultured\nin 10 minutes\na day",
        "onboarding.intro.cta": "Get started",

        "settings.title": "Settings",
        "settings.section.progress": "Progress",
        "settings.section.premium": "Premium",
        "settings.section.data": "Data",
        "settings.section.legal": "Legal",
        "settings.section.about": "About",
        "settings.section.developer": "Developer",
        "settings.courses.completed": "%d courses completed",
        "settings.courses.available": "out of %d available",
        "settings.streak.title": "%d-day streak",
        "settings.streak.subtitle": "Keep it up!",
        "settings.premium.title": "Upgrade to Premium",
        "settings.premium.subtitle": "Unlimited courses and quizzes",
        "settings.reset.title": "Reset progress",
        "settings.terms.title": "Terms of Service",
        "settings.privacy.title": "Privacy Policy",
        "settings.restore.title": "Restore purchases",
        "settings.about.version": "Version",
        "settings.about.courses": "Available courses",
        "settings.debug.resetOnboarding": "Restart onboarding",
        "settings.debug.resetDaily": "Reset daily course",
        "settings.debug.daily.done": "Done today",
        "settings.debug.daily.pending": "Not yet done",
        "settings.footer": "Made with ♥ — Sophia",
        "settings.reset.alert.title": "Reset?",
        "settings.reset.alert.cancel": "Cancel",
        "settings.reset.alert.confirm": "Reset",
        "settings.reset.alert.message": "All your progress will be erased. This cannot be undone.",
        "settings.onboarding.alert.title": "Restart onboarding?",
        "settings.onboarding.alert.confirm": "Restart",
        "settings.onboarding.alert.message": "Onboarding will start over from the beginning (DEBUG only).",

        "legal.terms.title": "Terms",
        "legal.privacy.title": "Privacy",

        "subject.histoire": "History",
        "subject.sciences": "Science",
        "subject.litterature": "Literature",
        "subject.art": "Art",
        "subject.mythologie": "Mythology",
        "subject.comprendreLeMonde": "Understanding today's world",
        "subject.histoire.short": "History",
        "subject.sciences.short": "Science",
        "subject.litterature.short": "Literature",
        "subject.art.short": "Art",
        "subject.mythologie.short": "Mythology",
        "subject.comprendreLeMonde.short": "Current affairs",

        "rarity.commune": "Common",
        "rarity.rare": "Rare",
        "rarity.epique": "Epic",
        "rarity.legendaire": "Legendary",

        "home.skip": "Skip",
        "home.bravo": "Bravo!",
        "home.allCompleted": "You've completed all available courses.",
        "home.locked": "Locked",
        "home.start": "Start",

        "library.empty.title": "No results",
        "library.empty.subtitle": "Try another keyword.",
        "library.seeMore": "See more",
        "library.unlock": "Unlock",
        "library.lockedBadge": "LOCKED",

        "collections.title": "COLLECTIONS",
        "collections.subtitle": "Guided journeys to connect ideas.",
        "collections.complete": "Collection complete",
        "collections.progress": "%d / %d courses completed",
        "collections.badge.complete": "COMPLETE",
        "collections.badge.path": "JOURNEY",
        "collections.xpAtEnd": "+%d XP at the end",
        "collections.pathComplete": "Journey complete",

        "subject.courses.count": "%d courses",
        "subject.completed.singular": "%d completed",
        "subject.completed.plural": "%d completed",

        "cards.collect.title": "CARDS TO COLLECT",
        "cards.seeAll": "See all →",
        "cards.unit": "cards",
        "cards.empty": "Complete a course to unlock your first cards.",
        "cards.quizStats.title": "QUIZZES PASSED",
        "cards.correctAnswers": "correct answers",
        "cards.successRate": "success rate",
        "cards.myCards": "My cards",
        "cards.unlocked": "unlocked",
        "cards.unlocked.title": "Card unlocked!",
        "cards.tapToReveal": "Tap to reveal",
        "cards.globalXP": "+%d global XP",

        "course.keyTakeaway": "KEY TAKEAWAY",

        "common.continue": "Continue",

        "celebration.collectionAdvanced": "Collection progressed!",
        "celebration.coursesCompleted": "courses completed",
        "celebration.collectionComplete": "Collection complete!",

        "common.next": "Next",
        "common.letsGo": "Let's go!",
        "common.letsGoShort": "Let's go",
        "common.close": "Close",
        "common.processing": "Processing…",
        "common.startLearning": "Start learning",
        "common.backHome": "Back to home",
        "common.retryQuiz": "Retry quiz",
        "common.seeMoreArrow": "See more →",
        "common.streak.day": "DAY",
        "common.streak.days": "DAYS",
        "common.levelShort": "LVL. %d",
        "common.increaseGoal": "Increase goal",
        "common.decreaseGoal": "Decrease goal",
        "common.miniQuiz": "Mini Quiz",
        "common.xpEarned": "+%d XP earned",
        "common.xpBeforeNext": "· %d to lvl. %d",

        "onboarding.welcome.title": "Sophia is your partner to master",
        "onboarding.welcome.rotating.histoire": "history",
        "onboarding.welcome.rotating.sciences": "science",
        "onboarding.welcome.rotating.litterature": "literature",
        "onboarding.welcome.rotating.art": "art",
        "onboarding.welcome.rotating.mythologie": "mythology",
        "onboarding.welcome.rotating.comprendreLeMonde": "current affairs",

        "onboarding.phone.title": "How much time\ndo you spend on your phone?",
        "onboarding.phone.subtitle": "Each day, on average.",
        "onboarding.phone.lessThan1h": "Less than 1h",
        "onboarding.phone.1to2h": "1h to 2h",
        "onboarding.phone.2to4h": "2h to 4h",
        "onboarding.phone.moreThan4h": "More than 4h",
        "onboarding.phone.hours.1": "1 hour",
        "onboarding.phone.hours.2": "2 hours",
        "onboarding.phone.hours.3": "3 hours",
        "onboarding.phone.hours.5": "5 hours",

        "onboarding.wasted.intro": "%@ per day on your phone, that's",
        "onboarding.wasted.hoursLost": "hours lost per year.",
        "onboarding.wasted.daysComplete": "That's %@ full days.",
        "onboarding.wasted.transform": "With Sophia, turn that time into culture.",
        "onboarding.wasted.days.7": "7 days",
        "onboarding.wasted.days.23": "23 days",
        "onboarding.wasted.days.45": "45 days",
        "onboarding.wasted.days.91": "91 days",

        "onboarding.objectives.title": "Your goal\nwith Sophia?",
        "onboarding.objectives.subtitle": "Select one or more goals.",
        "onboarding.objective.curious": "Be more curious",
        "onboarding.objective.learnNew": "Learn new things",
        "onboarding.objective.impress": "Impress the people around you",
        "onboarding.objective.social": "Feel more at ease socially",
        "onboarding.objective.reduceScroll": "Cut down on scrolling time",

        "onboarding.interests.title": "What topics\ninterest you?",
        "onboarding.interests.subtitle": "Select at least one topic.",

        "onboarding.dailyGoal.title": "Each day, you want to learn...",
        "onboarding.dailyGoal.subtitle": "You can change your goal later.",
        "onboarding.dailyGoal.perDay": "%@ per day!",
        "onboarding.dailyGoal.singular": "lesson",
        "onboarding.dailyGoal.plural": "lessons",

        "onboarding.loading.title": "We're preparing your journey",
        "onboarding.loading.subtitle": "Just a few seconds, promise.",
        "onboarding.loading.step1": "Analyzing your answers",
        "onboarding.loading.step2": "Selecting your 3 subjects",
        "onboarding.loading.step3": "Preparing your journey",

        "onboarding.projection.line1": "Small habit,",
        "onboarding.projection.line2": "incredible results.",
        "onboarding.projection.its": "That's",
        "onboarding.projection.newThings": "new things you'll know",
        "onboarding.projection.inOneYear": "within a year.",

        "onboarding.social.badge": "Verified reviews",
        "onboarding.social.stat": "of users feel\nmore interesting and at ease\nin social settings thanks to Sophia.",
        "onboarding.social.review1.name": "Lucas M.",
        "onboarding.social.review1.text": "I felt clueless about culture, now I always have something interesting to share.",
        "onboarding.social.review2.name": "Camille R.",
        "onboarding.social.review2.text": "10 minutes a day and I feel like I learn more than in class.",
        "onboarding.social.review3.name": "Thomas D.",
        "onboarding.social.review3.text": "I love the format. It's clear, fast, and I actually remember things.",

        "onboarding.graph.title": "Your cultural\nprogress",
        "onboarding.graph.subtitle": "With and without Sophia",
        "onboarding.graph.culture": "CULTURE",
        "onboarding.graph.withSophia": "With Sophia",
        "onboarding.graph.withoutSophia": "Without Sophia",
        "onboarding.graph.today": "Today",
        "onboarding.graph.oneYear": "1 year",
        "onboarding.graph.tagline": "Sophia accelerates your culture\nexponentially.",

        "onboarding.final.title": "Profile ready!",
        "onboarding.final.subtitle": "Welcome to Sophia.\nStart learning right now.",
        "onboarding.final.subjects": "YOUR SUBJECTS",

        "onboarding.trial.badge": "Welcome offer",
        "onboarding.trial.title": "Your first 3 days\nare free",
        "onboarding.trial.unlimitedCourses": "Unlimited courses",
        "onboarding.trial.allQuizzes": "All quizzes",
        "onboarding.trial.noSurprise": "No surprises",
        "onboarding.trial.notifyTitle": "We'll notify you\n1 day before the end\nof your free trial",
        "onboarding.trial.cancelAnytime": "Cancel anytime, free of charge.",
        "onboarding.trial.day1": "DAY 1",
        "onboarding.trial.day2": "DAY 2",
        "onboarding.trial.day3": "DAY 3",
        "onboarding.trial.fullAccess": "Full access",
        "onboarding.trial.notificationSent": "Notification sent",
        "onboarding.trial.trialEnds": "Trial ends",

        "paywall.cancelAnytime": "Cancel anytime, free of charge.",
        "paywall.header": "Become the most\ninteresting person\nin the room.",
        "paywall.freeSubjects": "Your 3 free subjects",
        "paywall.lockedSubjects": "3 subjects to unlock",
        "paywall.teaserTitle": "A preview of what's ahead",
        "paywall.teaserSubtitle": "Hundreds of premium courses to unlock",
        "paywall.featureColumn": "Feature",
        "paywall.freeColumn": "Free",
        "paywall.premiumColumn": "Premium",
        "paywall.feature.3subjects": "3 subjects",
        "paywall.feature.allSubjects": "All subjects",
        "paywall.feature.unlimitedCourses": "Unlimited courses",
        "paywall.feature.miniQuiz": "Mini Quiz",
        "paywall.feature.fullLibrary": "Full library",
        "paywall.plan.yearly": "Yearly",
        "paywall.plan.monthly": "Monthly",
        "paywall.plan.yearlySubtitle": "Billed annually",
        "paywall.plan.monthlySubtitle": "No commitment",
        "paywall.plan.perYear": "/ year",
        "paywall.plan.perMonth": "/ month",
        "paywall.plan.discount": "-58%",
        "paywall.plan.fallback.yearlyPrice": "€39.99",
        "paywall.plan.fallback.monthlyPrice": "€9.99",
        "paywall.plan.fallback.yearlyMonthly": "€3.33 / month",
        "paywall.trialBadge": "3-day free trial",
        "paywall.restoreRow": "Restore · Terms · Privacy",
        "paywall.trialSheet.title": "Start your\n3-day free trial",
        "paywall.trialSheet.start": "Start free trial",
        "paywall.trial.today": "Today",
        "paywall.trial.noPayment": "No payment",
        "paywall.trial.todayDetail": "Access to all Premium features.",
        "paywall.trial.in2days": "In 2 days",
        "paywall.trial.reminder": "We'll remind you",
        "paywall.trial.reminderDetail": "Notification 1 day before the trial ends.",
        "paywall.trial.in3days": "In 3 days",
        "paywall.trial.starts": "Your subscription starts",
        "paywall.trial.startsDetail": "Cancel before if you don't want to continue.",
        "paywall.review1.quote": "Perfect on my commute. I learn every day effortlessly.",
        "paywall.review1.author": "Marie, 28",
        "paywall.review2.quote": "Finally an app that turns scrolling into culture.",
        "paywall.review2.author": "Thomas, 34",
        "paywall.review3.quote": "The courses are short, fun, and I actually remember them.",
        "paywall.review3.author": "Inès, 22",
        "paywall.review4.quote": "My friends ask where I get all these anecdotes.",
        "paywall.review4.author": "Lucas, 31",
        "paywall.review5.quote": "The personalized onboarding convinced me in the first minute.",
        "paywall.review5.author": "Sarah, 26",

        "offer.unique": "Your one-time offer",
        "offer.discount": "-70% FOREVER",
        "offer.perMonth": "/month",
        "offer.billed": "billed",
        "offer.expiresIn": "Expires in",
        "offer.unlock": "Unlock my -70% access",
        "offer.restore": "Restore purchases",
        "offer.feature1": "240 general knowledge courses",
        "offer.feature2": "Unlimited interactive quizzes",
        "offer.feature3": "New content every week",

        "profile.title": "Profile",
        "profile.streak.start": "Read a course to get started!",
        "profile.streak.beginning": "You've started, keep going!",
        "profile.streak.good": "Great consistency 👏",
        "profile.streak.great": "You're on fire 🔥",
        "profile.favorites": "My favorites",
        "profile.favorites.count": "%d saved courses",
        "profile.quiz.recent": "RECENT QUIZZES",
        "profile.quiz.locked": "Quizzes locked",
        "profile.quiz.lockedSubtitle": "Available with the free trial — 3 days free",
        "profile.quiz.unlock": "Unlock my quizzes",
        "profile.quiz.emptyTitle": "No quizzes yet",
        "profile.quiz.emptySubtitle": "Complete a course to take your first quiz.",
        "profile.progress.bySubject": "PROGRESS BY TOPIC",
        "profile.unlock.trial": "Unlock with free trial",
        "profile.quiz.retry": "Retry",
        "profile.quiz.all": "All my quizzes",
        "profile.quiz.none": "No quizzes yet.",
        "profile.progress.max": "%d XP · max level",
        "profile.progress.toNext": "%d XP · %d to lvl. %d",

        "quiz.feedback.correct": "Correct!",
        "quiz.feedback.excellent": "Excellent!",
        "quiz.feedback.amazing": "Amazing!",
        "quiz.feedback.wrong": "Not quite...",
        "quiz.completed": "Well done, quiz complete!",
        "quiz.correctAnswers": "correct answers",
        "quiz.xpProgress": "XP progress",
        "quiz.levelUp": "Level up!",
        "quiz.breakdown.correct": "Correct answers",
        "quiz.breakdown.completed": "Quiz completed",
        "quiz.xpProgress.max": "%d XP · max level",
        "quiz.xpProgress.toNext": "%d XP to lvl. %d",

        "course.completed": "Lesson complete!",
        "course.dailyFreeDone": "You've completed your free course for today",
        "course.streak.day": "Day streak",
        "course.streak.days": "Day streak",
        "course.streak.message": "You're becoming truly cultured — unstoppable in %@!",
        "course.streak.onTrack": "On your way to a streak!",

        "prepaywall.quiz.title": "Unlock quizzes\nfor free",
        "prepaywall.quiz.subtitle": "Test your knowledge and\nprogress every day",
        "prepaywall.course.subtitle": "Keep learning and\ndiscover new topics",
        "prepaywall.course.access": "Access the course",

        "levelUp.title": "Level up!",

        "globalRank.curieux": "Curious",
        "globalRank.erudit": "Scholar",
        "globalRank.savant": "Sage",
        "globalRank.maitre": "Master",
        "globalRank.legende": "Legend",
        "globalRank.title": "Global rank",
        "globalRank.badge": "GLOBAL RANK",
        "globalRank.maxLevel": "Max level",
        "globalRank.xpBefore": "%d XP to %@",
        "globalRank.newRank": "New rank!",
        "globalRank.reachedLevel": "You just reached level %d",

        "paywall.unavailable.title": "Offer unavailable",
        "paywall.unavailable.message": "Unable to load this offer right now.",
    ]

    // MARK: - German (shell — phase 1; full UI in phase 2)

    private static let german: [String: String] = [
        "tab.home": "Start",
        "tab.library": "Bibliothek",
        "tab.profile": "Profil",

        "library.title": "Bibliothek",
        "library.tab.courses": "Kurse",
        "library.tab.collections": "Sammlungen",
        "library.search.placeholder": "Kurs suchen...",

        "language.section": "Sprache",
        "language.french": "Français",
        "language.english": "English",
        "language.german": "Deutsch",

        "onboarding.intro.title": "Werde gebildet\nin 10 Minuten\npro Tag",
        "onboarding.intro.cta": "Loslegen",

        "settings.title": "Einstellungen",
        "settings.section.progress": "Fortschritt",
        "settings.section.premium": "Premium",
        "settings.section.data": "Daten",
        "settings.section.legal": "Rechtliches",
        "settings.section.about": "Über",
        "settings.section.developer": "Entwickler",
        "settings.courses.completed": "%d Kurse abgeschlossen",
        "settings.courses.available": "von %d verfügbar",
        "settings.footer": "Made with ♥ — Sophia",

        "legal.terms.title": "AGB",
        "legal.privacy.title": "Datenschutz",

        "subject.histoire": "Geschichte",
        "subject.sciences": "Wissenschaften",
        "subject.litterature": "Literatur",
        "subject.art": "Kunst",
        "subject.mythologie": "Mythologie",
        "subject.comprendreLeMonde": "Die heutige Welt verstehen",
        "subject.histoire.short": "Geschichte",
        "subject.sciences.short": "Wissenschaften",
        "subject.litterature.short": "Literatur",
        "subject.art.short": "Kunst",
        "subject.mythologie.short": "Mythologie",
        "subject.comprendreLeMonde.short": "Gegenwart",
    ]
}
