import Foundation

struct LegalSection: Identifiable {
    let id: String
    let title: String
    let body: String
}

enum LegalDocumentContent {
    static func terms(language: AppLanguage) -> [LegalSection] {
        switch language {
        case .french: termsFrench
        case .english: termsEnglish
        case .spanish: termsSpanish
        case .german: termsGerman
        case .portuguese: termsPortuguese
        case .italian: termsItalian
        }
    }

    static func privacy(language: AppLanguage) -> [LegalSection] {
        switch language {
        case .french: privacyFrench
        case .english: privacyEnglish
        case .spanish: privacySpanish
        case .german: privacyGerman
        case .portuguese: privacyPortuguese
        case .italian: privacyItalian
        }
    }

    // MARK: - Terms (FR)

    private static let termsFrench: [LegalSection] = [
        LegalSection(id: "1", title: "1. Acceptation des conditions", body: "En téléchargeant, installant ou utilisant l'application Sophia (ci-après « l'Application »), vous acceptez d'être lié par les présentes Conditions Générales d'Utilisation (« CGU »). Si vous n'acceptez pas ces conditions, veuillez ne pas utiliser l'Application."),
        LegalSection(id: "2", title: "2. Description du service", body: "Sophia est une application mobile éducative de culture générale proposant des cours, quiz et contenus interactifs. L'Application est disponible sur iOS et peut proposer des contenus gratuits ainsi que des abonnements premium."),
        LegalSection(id: "3", title: "3. Compte et utilisation", body: "La création d'un compte (via Apple ou Google) est proposée pour sauvegarder votre progression et la synchroniser entre vos appareils. Les nouveaux utilisateurs se connectent lors de l'intégration ; les utilisateurs existants peuvent créer un compte à tout moment depuis les réglages. Sans compte, vos données de progression sont stockées localement sur votre appareil et la réinstallation de l'Application peut entraîner leur perte. Vous pouvez supprimer votre compte à tout moment depuis les réglages."),
        LegalSection(id: "4", title: "4. Abonnements et achats", body: "Sophia propose des abonnements premium (mensuel et annuel) via l'App Store d'Apple. Les prix sont affichés dans l'Application et peuvent varier selon votre pays. Le paiement est prélevé sur votre compte Apple ID à la confirmation de l'achat. L'abonnement se renouvelle automatiquement sauf si le renouvellement automatique est désactivé au moins 24 heures avant la fin de la période en cours. Vous pouvez gérer et annuler vos abonnements dans les réglages de votre compte App Store."),
        LegalSection(id: "5", title: "5. Essai gratuit", body: "Un essai gratuit peut être proposé aux nouveaux utilisateurs. À l'expiration de la période d'essai, l'abonnement sera automatiquement converti en abonnement payant sauf annulation préalable. Toute partie non utilisée de la période d'essai gratuit sera perdue lors de l'achat d'un abonnement."),
        LegalSection(id: "6", title: "6. Propriété intellectuelle", body: "L'ensemble des contenus de l'Application (textes, illustrations, design, logo, cours, quiz) sont protégés par le droit d'auteur et restent la propriété exclusive de Sophia. Toute reproduction, distribution ou utilisation non autorisée est strictement interdite."),
        LegalSection(id: "7", title: "7. Limitation de responsabilité", body: "Les contenus proposés dans l'Application sont fournis à titre éducatif et informatif. Sophia ne garantit pas l'exactitude, l'exhaustivité ou l'actualité des informations présentées. L'Application est fournie « en l'état » sans garantie d'aucune sorte."),
        LegalSection(id: "8", title: "8. Modification des conditions", body: "Sophia se réserve le droit de modifier les présentes CGU à tout moment. Les utilisateurs seront informés des modifications significatives. La poursuite de l'utilisation de l'Application après modification vaut acceptation des nouvelles conditions."),
        LegalSection(id: "9", title: "9. Droit applicable", body: "Les présentes CGU sont soumises au droit français. Tout litige relatif à l'interprétation ou à l'exécution des présentes sera soumis aux tribunaux compétents."),
        LegalSection(id: "10", title: "10. Contact", body: "Pour toute question relative aux présentes CGU, vous pouvez nous contacter via l'App Store ou par email à l'adresse indiquée sur notre page App Store."),
    ]

    // MARK: - Terms (EN)

    private static let termsEnglish: [LegalSection] = [
        LegalSection(id: "1", title: "1. Acceptance of terms", body: "By downloading, installing, or using the Sophia app (the \"App\"), you agree to be bound by these Terms of Service (\"Terms\"). If you do not accept these terms, please do not use the App."),
        LegalSection(id: "2", title: "2. Description of the service", body: "Sophia is an educational general-knowledge mobile app offering courses, quizzes, and interactive content. The App is available on iOS and may offer free content as well as premium subscriptions."),
        LegalSection(id: "3", title: "3. Account and use", body: "Creating an account (via Apple or Google) is offered to save your progress and sync it across your devices. New users sign in during onboarding; existing users can create an account at any time from Settings. Without an account, your progress data is stored locally on your device and reinstalling the App may result in its loss. You can delete your account at any time from Settings."),
        LegalSection(id: "4", title: "4. Subscriptions and purchases", body: "Sophia offers premium subscriptions (monthly and annual) through Apple's App Store. Prices are displayed in the App and may vary by country. Payment is charged to your Apple ID account upon purchase confirmation. Subscriptions renew automatically unless auto-renew is turned off at least 24 hours before the end of the current period. You can manage and cancel subscriptions in your App Store account settings."),
        LegalSection(id: "5", title: "5. Free trial", body: "A free trial may be offered to new users. When the trial period ends, the subscription will automatically convert to a paid subscription unless cancelled beforehand. Any unused portion of a free trial is forfeited when purchasing a subscription."),
        LegalSection(id: "6", title: "6. Intellectual property", body: "All App content (text, illustrations, design, logo, courses, quizzes) is protected by copyright and remains the exclusive property of Sophia. Any unauthorized reproduction, distribution, or use is strictly prohibited."),
        LegalSection(id: "7", title: "7. Limitation of liability", body: "Content in the App is provided for educational and informational purposes. Sophia does not guarantee the accuracy, completeness, or timeliness of the information presented. The App is provided \"as is\" without warranty of any kind."),
        LegalSection(id: "8", title: "8. Changes to terms", body: "Sophia reserves the right to modify these Terms at any time. Users will be notified of significant changes. Continued use of the App after changes constitutes acceptance of the new terms."),
        LegalSection(id: "9", title: "9. Governing law", body: "These Terms are governed by French law. Any dispute relating to the interpretation or performance of these Terms shall be submitted to the competent courts."),
        LegalSection(id: "10", title: "10. Contact", body: "For any questions regarding these Terms, you can contact us via the App Store or by email at the address listed on our App Store page."),
    ]

    // MARK: - Privacy (FR)

    private static let privacyFrench: [LegalSection] = [
        LegalSection(id: "1", title: "1. Introduction", body: "La présente Politique de Confidentialité décrit comment Sophia (ci-après « nous », « notre » ou « l'Application ») collecte, utilise et protège vos informations personnelles. Nous nous engageons à protéger votre vie privée et à traiter vos données de manière transparente."),
        LegalSection(id: "2", title: "2. Données collectées", body: "Sophia est conçue selon le principe de minimisation des données. L'Application stocke sur votre appareil :\n\n- Votre progression dans les cours et quiz\n- Vos préférences (centres d'intérêt, objectifs)\n- Votre streak (jours consécutifs d'utilisation)\n- Vos cours favoris\n\nCes données locales ne sont pas transmises à nos serveurs.\n\nL'Application envoie également des événements d'usage anonymes à Mixpanel (région UE) pour comprendre comment l'app est utilisée et l'améliorer. Ces événements ne contiennent pas votre nom, email ou contenu personnel.\n\nSi vous nous envoyez un retour via le formulaire des réglages, votre message et, si vous le renseignez, votre adresse email sont transmis à Formspree pour nous permettre de vous répondre. Des informations techniques (version de l'app, langue, appareil) sont jointes automatiquement."),
        LegalSection(id: "3", title: "3. Données d'abonnement", body: "Si vous souscrivez à un abonnement premium, la transaction est gérée entièrement par Apple via l'App Store. Nous n'avons pas accès à vos informations de paiement (numéro de carte, adresse de facturation). Nous recevons uniquement la confirmation de votre statut d'abonnement via RevenueCat, notre partenaire de gestion des abonnements."),
        LegalSection(id: "4", title: "4. RevenueCat", body: "Nous utilisons RevenueCat pour gérer les abonnements in-app. RevenueCat peut collecter un identifiant anonyme d'appareil pour vérifier votre statut d'abonnement. Aucune donnée personnelle identifiable n'est partagée. Pour plus d'informations, consultez la politique de confidentialité de RevenueCat sur leur site web."),
        LegalSection(id: "5", title: "5. Données analytiques (Mixpanel)", body: "Nous utilisons Mixpanel, hébergé dans l'Union européenne, pour mesurer l'utilisation de l'Application (écrans visités, cours ouverts, interactions avec le paywall, etc.). Mixpanel reçoit un identifiant anonyme généré par l'appareil, la version de l'app, la langue et des événements d'usage agrégés. Aucune donnée nominative n'est collectée. Vous pouvez nous contacter pour demander la suppression de ces données analytiques."),
        LegalSection(id: "6", title: "6. Données Apple Analytics", body: "L'Application peut également bénéficier des statistiques anonymes fournies par Apple (App Analytics). Ces données sont agrégées et ne permettent pas de vous identifier personnellement. Vous pouvez désactiver le partage d'analytics dans les réglages de votre iPhone (Réglages > Confidentialité > Analyses et améliorations)."),
        LegalSection(id: "7", title: "7. Stockage des données", body: "Vos données de progression sont stockées localement sur votre appareil (UserDefaults). Si vous créez un compte (Apple ou Google), elles sont également sauvegardées de façon sécurisée sur nos serveurs Supabase (hébergés dans l'Union européenne) afin de permettre la synchronisation entre vos appareils. La désinstallation de l'Application supprime les données locales ; la suppression de votre compte efface définitivement les données associées sur le serveur."),
        LegalSection(id: "8", title: "8. Partage de données", body: "Nous ne vendons, ne louons et ne partageons aucune donnée personnelle avec des tiers à des fins commerciales ou publicitaires. Les données transmises sont limitées à : Apple et RevenueCat (abonnements), Mixpanel (analytics anonymes, UE), Formspree (retours utilisateurs envoyés volontairement depuis les réglages)."),
        LegalSection(id: "9", title: "9. Droits des utilisateurs", body: "Conformément au Règlement Général sur la Protection des Données (RGPD) et aux lois applicables, vous disposez des droits suivants :\n\n- Droit d'accès à vos données\n- Droit de rectification\n- Droit à l'effacement (réinitialisation dans les paramètres)\n- Droit à la portabilité\n- Droit d'opposition\n\nPour exercer ces droits, contactez-nous via l'adresse indiquée sur notre page App Store."),
        LegalSection(id: "10", title: "10. Protection des mineurs", body: "Sophia est une application éducative accessible à tous les âges. Nous ne collectons sciemment aucune donnée personnelle de mineurs de moins de 16 ans. L'Application ne contient aucun contenu inapproprié."),
        LegalSection(id: "11", title: "11. Modifications", body: "Nous nous réservons le droit de modifier cette politique à tout moment. Toute modification sera communiquée via une mise à jour de l'Application.\n\nDernière mise à jour : Juillet 2026"),
    ]

    // MARK: - Privacy (EN)

    private static let privacyEnglish: [LegalSection] = [
        LegalSection(id: "1", title: "1. Introduction", body: "This Privacy Policy describes how Sophia (\"we\", \"our\", or the \"App\") collects, uses, and protects your personal information. We are committed to protecting your privacy and handling your data transparently."),
        LegalSection(id: "2", title: "2. Data collected", body: "Sophia is designed with data minimization in mind. The App stores on your device:\n\n- Your progress in courses and quizzes\n- Your preferences (interests, goals)\n- Your streak (consecutive days of use)\n- Your favorite courses\n\nThis local data is not transmitted to our servers.\n\nThe App also sends anonymous usage events to Mixpanel (EU region) to understand how the app is used and improve it. These events do not include your name, email, or personal content.\n\nIf you send feedback via the in-app form in Settings, your message and, if provided, your email address are transmitted to Formspree so we can respond. Technical information (app version, language, device) is attached automatically."),
        LegalSection(id: "3", title: "3. Subscription data", body: "If you subscribe to a premium plan, the transaction is handled entirely by Apple via the App Store. We do not have access to your payment information (card number, billing address). We only receive confirmation of your subscription status via RevenueCat, our subscription management partner."),
        LegalSection(id: "4", title: "4. RevenueCat", body: "We use RevenueCat to manage in-app subscriptions. RevenueCat may collect an anonymous device identifier to verify your subscription status. No personally identifiable information is shared. For more information, see RevenueCat's privacy policy on their website."),
        LegalSection(id: "5", title: "5. Analytics data (Mixpanel)", body: "We use Mixpanel, hosted in the European Union, to measure App usage (screens visited, courses opened, paywall interactions, etc.). Mixpanel receives an anonymous device identifier, app version, language, and aggregated usage events. No personally identifiable information is collected. You may contact us to request deletion of this analytics data."),
        LegalSection(id: "6", title: "6. Apple Analytics", body: "The App may also benefit from anonymous statistics provided by Apple (App Analytics). This data is aggregated and cannot be used to identify you personally. You can disable analytics sharing in your iPhone settings (Settings > Privacy > Analytics & Improvements)."),
        LegalSection(id: "7", title: "7. Data storage", body: "Your progress data is stored locally on your device (UserDefaults). If you create an account (Apple or Google), it is also securely backed up to our Supabase servers (hosted in the European Union) to enable syncing across your devices. Uninstalling the App deletes the local data; deleting your account permanently removes the associated data on the server."),
        LegalSection(id: "8", title: "8. Data sharing", body: "We do not sell, rent, or share personal data with third parties for commercial or advertising purposes. Data transmitted is limited to: Apple and RevenueCat (subscriptions), Mixpanel (anonymous analytics, EU), Formspree (user feedback voluntarily sent from Settings)."),
        LegalSection(id: "9", title: "9. User rights", body: "Under the General Data Protection Regulation (GDPR) and applicable laws, you have the following rights:\n\n- Right of access to your data\n- Right to rectification\n- Right to erasure (reset in Settings)\n- Right to data portability\n- Right to object\n\nTo exercise these rights, contact us via the address listed on our App Store page."),
        LegalSection(id: "10", title: "10. Protection of minors", body: "Sophia is an educational app suitable for all ages. We do not knowingly collect personal data from children under 16. The App contains no inappropriate content."),
        LegalSection(id: "11", title: "11. Changes", body: "We reserve the right to modify this policy at any time. Any changes will be communicated through an App update.\n\nLast updated: July 2026"),
    ]

    // MARK: - Terms (ES)

    private static let termsSpanish: [LegalSection] = [
        LegalSection(id: "1", title: "1. Aceptación de las condiciones", body: "Al descargar, instalar o usar la aplicación Sophia (en adelante, «la Aplicación»), aceptas quedar vinculado por estas Condiciones Generales de Uso («Condiciones»). Si no aceptas estas condiciones, no utilices la Aplicación."),
        LegalSection(id: "2", title: "2. Descripción del servicio", body: "Sophia es una aplicación móvil educativa de cultura general que ofrece cursos, cuestionarios y contenidos interactivos. La Aplicación está disponible en iOS y puede ofrecer contenidos gratuitos, así como suscripciones premium."),
        LegalSection(id: "3", title: "3. Cuenta y uso", body: "Se ofrece la creación de una cuenta (mediante Apple o Google) para guardar tu progreso y sincronizarlo entre tus dispositivos. Los nuevos usuarios inician sesión durante la incorporación; los usuarios existentes pueden crear una cuenta en cualquier momento desde los ajustes. Sin cuenta, tus datos de progreso se almacenan localmente en tu dispositivo y reinstalar la Aplicación puede provocar su pérdida. Puedes eliminar tu cuenta en cualquier momento desde los ajustes."),
        LegalSection(id: "4", title: "4. Suscripciones y compras", body: "Sophia ofrece suscripciones premium (mensual y anual) a través de la App Store de Apple. Los precios se muestran en la Aplicación y pueden variar según tu país. El pago se cargará a tu cuenta de Apple ID al confirmar la compra. La suscripción se renueva automáticamente, salvo que la renovación automática se desactive al menos 24 horas antes del final del periodo en curso. Puedes gestionar y cancelar tus suscripciones en los ajustes de tu cuenta de la App Store."),
        LegalSection(id: "5", title: "5. Prueba gratuita", body: "Puede ofrecerse una prueba gratuita a los nuevos usuarios. Al finalizar el periodo de prueba, la suscripción se convertirá automáticamente en una suscripción de pago, salvo cancelación previa. Cualquier parte no utilizada del periodo de prueba gratuita se perderá al comprar una suscripción."),
        LegalSection(id: "6", title: "6. Propiedad intelectual", body: "Todos los contenidos de la Aplicación (textos, ilustraciones, diseño, logotipo, cursos, cuestionarios) están protegidos por derechos de autor y siguen siendo propiedad exclusiva de Sophia. Queda estrictamente prohibida cualquier reproducción, distribución o uso no autorizados."),
        LegalSection(id: "7", title: "7. Limitación de responsabilidad", body: "Los contenidos ofrecidos en la Aplicación se proporcionan con fines educativos e informativos. Sophia no garantiza la exactitud, integridad ni actualidad de la información presentada. La Aplicación se proporciona «tal cual», sin garantía de ningún tipo."),
        LegalSection(id: "8", title: "8. Modificación de las condiciones", body: "Sophia se reserva el derecho de modificar estas Condiciones en cualquier momento. Se informará a los usuarios de los cambios significativos. El uso continuado de la Aplicación tras una modificación implica la aceptación de las nuevas condiciones."),
        LegalSection(id: "9", title: "9. Legislación aplicable", body: "Estas Condiciones se rigen por la legislación francesa. Cualquier litigio relativo a la interpretación o ejecución de las presentes se someterá a los tribunales competentes."),
        LegalSection(id: "10", title: "10. Contacto", body: "Para cualquier consulta relativa a estas Condiciones, puedes contactarnos a través de la App Store o por correo electrónico en la dirección indicada en nuestra página de la App Store."),
    ]

    // MARK: - Terms (DE)

    private static let termsGerman: [LegalSection] = [
        LegalSection(id: "1", title: "1. Annahme der Bedingungen", body: "Indem du die Sophia-App (nachfolgend „die App“) herunterlädst, installierst oder nutzt, erklärst du dich mit diesen Allgemeinen Nutzungsbedingungen („Bedingungen“) einverstanden. Wenn du diese Bedingungen nicht akzeptierst, nutze die App bitte nicht."),
        LegalSection(id: "2", title: "2. Beschreibung des Dienstes", body: "Sophia ist eine mobile Lern-App für Allgemeinbildung mit Kursen, Quizzen und interaktiven Inhalten. Die App ist für iOS verfügbar und kann sowohl kostenlose Inhalte als auch Premium-Abonnements anbieten."),
        LegalSection(id: "3", title: "3. Konto und Nutzung", body: "Die Erstellung eines Kontos (über Apple oder Google) wird angeboten, um deinen Fortschritt zu speichern und zwischen deinen Geräten zu synchronisieren. Neue Nutzer melden sich während des Onboardings an; bestehende Nutzer können jederzeit in den Einstellungen ein Konto erstellen. Ohne Konto werden deine Fortschrittsdaten lokal auf deinem Gerät gespeichert und eine Neuinstallation der App kann zu deren Verlust führen. Du kannst dein Konto jederzeit in den Einstellungen löschen."),
        LegalSection(id: "4", title: "4. Abonnements und Käufe", body: "Sophia bietet Premium-Abonnements (monatlich und jährlich) über den App Store von Apple an. Die Preise werden in der App angezeigt und können je nach Land variieren. Die Zahlung wird bei Bestätigung des Kaufs deinem Apple-ID-Konto belastet. Das Abonnement verlängert sich automatisch, sofern die automatische Verlängerung nicht mindestens 24 Stunden vor Ende des laufenden Zeitraums deaktiviert wird. Du kannst deine Abonnements in den Einstellungen deines App-Store-Kontos verwalten und kündigen."),
        LegalSection(id: "5", title: "5. Kostenlose Testphase", body: "Neuen Nutzern kann eine kostenlose Testphase angeboten werden. Nach Ablauf der Testphase wird das Abonnement automatisch in ein kostenpflichtiges Abonnement umgewandelt, sofern es nicht zuvor gekündigt wird. Ein nicht genutzter Teil der kostenlosen Testphase verfällt beim Kauf eines Abonnements."),
        LegalSection(id: "6", title: "6. Geistiges Eigentum", body: "Alle Inhalte der App (Texte, Illustrationen, Design, Logo, Kurse, Quizze) sind urheberrechtlich geschützt und bleiben das ausschließliche Eigentum von Sophia. Jede unbefugte Vervielfältigung, Verbreitung oder Nutzung ist strengstens untersagt."),
        LegalSection(id: "7", title: "7. Haftungsbeschränkung", body: "Die Inhalte der App werden zu Bildungs- und Informationszwecken bereitgestellt. Sophia übernimmt keine Gewähr für die Richtigkeit, Vollständigkeit oder Aktualität der dargestellten Informationen. Die App wird „wie besehen“ ohne jegliche Gewährleistung bereitgestellt."),
        LegalSection(id: "8", title: "8. Änderung der Bedingungen", body: "Sophia behält sich das Recht vor, diese Bedingungen jederzeit zu ändern. Die Nutzer werden über wesentliche Änderungen informiert. Die fortgesetzte Nutzung der App nach einer Änderung gilt als Annahme der neuen Bedingungen."),
        LegalSection(id: "9", title: "9. Anwendbares Recht", body: "Diese Bedingungen unterliegen französischem Recht. Alle Streitigkeiten über die Auslegung oder Erfüllung dieser Bedingungen werden den zuständigen Gerichten vorgelegt."),
        LegalSection(id: "10", title: "10. Kontakt", body: "Bei Fragen zu diesen Bedingungen kannst du uns über den App Store oder per E-Mail an die auf unserer App-Store-Seite angegebene Adresse kontaktieren."),
    ]

    // MARK: - Terms (PT)

    private static let termsPortuguese: [LegalSection] = [
        LegalSection(id: "1", title: "1. Aceitação dos termos", body: "Ao descarregar, instalar ou utilizar a aplicação Sophia (doravante «a Aplicação»), aceitas ficar vinculado aos presentes Termos de Utilização («Termos»). Se não aceitares estes termos, não utilizes a Aplicação."),
        LegalSection(id: "2", title: "2. Descrição do serviço", body: "A Sophia é uma aplicação móvel educativa de cultura geral que oferece cursos, questionários e conteúdos interativos. A Aplicação está disponível em iOS e pode oferecer conteúdos gratuitos, bem como subscrições premium."),
        LegalSection(id: "3", title: "3. Conta e utilização", body: "A criação de uma conta (através da Apple ou Google) é proposta para guardar o teu progresso e sincronizá-lo entre os teus dispositivos. Os novos utilizadores iniciam sessão durante a integração; os utilizadores existentes podem criar uma conta a qualquer momento nas definições. Sem conta, os teus dados de progresso são armazenados localmente no teu dispositivo e reinstalar a Aplicação pode resultar na sua perda. Podes eliminar a tua conta a qualquer momento nas definições."),
        LegalSection(id: "4", title: "4. Subscrições e compras", body: "A Sophia oferece subscrições premium (mensal e anual) através da App Store da Apple. Os preços são apresentados na Aplicação e podem variar consoante o teu país. O pagamento é cobrado na tua conta Apple ID após a confirmação da compra. A subscrição renova-se automaticamente, exceto se a renovação automática for desativada pelo menos 24 horas antes do fim do período em curso. Podes gerir e cancelar as tuas subscrições nas definições da tua conta da App Store."),
        LegalSection(id: "5", title: "5. Período de teste gratuito", body: "Pode ser oferecido um período de teste gratuito aos novos utilizadores. No fim do período de teste, a subscrição será automaticamente convertida numa subscrição paga, salvo cancelamento prévio. Qualquer parte não utilizada do período de teste gratuito é perdida ao adquirir uma subscrição."),
        LegalSection(id: "6", title: "6. Propriedade intelectual", body: "Todos os conteúdos da Aplicação (textos, ilustrações, design, logótipo, cursos, questionários) estão protegidos por direitos de autor e permanecem propriedade exclusiva da Sophia. Qualquer reprodução, distribuição ou utilização não autorizada é estritamente proibida."),
        LegalSection(id: "7", title: "7. Limitação de responsabilidade", body: "Os conteúdos disponibilizados na Aplicação são fornecidos para fins educativos e informativos. A Sophia não garante a exatidão, integralidade ou atualidade das informações apresentadas. A Aplicação é fornecida «tal como está», sem qualquer garantia."),
        LegalSection(id: "8", title: "8. Alteração dos termos", body: "A Sophia reserva-se o direito de alterar os presentes Termos a qualquer momento. Os utilizadores serão informados de alterações significativas. A continuação da utilização da Aplicação após uma alteração implica a aceitação dos novos termos."),
        LegalSection(id: "9", title: "9. Lei aplicável", body: "Os presentes Termos regem-se pela lei francesa. Qualquer litígio relativo à interpretação ou execução dos presentes será submetido aos tribunais competentes."),
        LegalSection(id: "10", title: "10. Contacto", body: "Para qualquer questão relativa aos presentes Termos, podes contactar-nos através da App Store ou por email para o endereço indicado na nossa página da App Store."),
    ]

    // MARK: - Terms (IT)

    private static let termsItalian: [LegalSection] = [
        LegalSection(id: "1", title: "1. Accettazione delle condizioni", body: "Scaricando, installando o utilizzando l'applicazione Sophia (di seguito «l'Applicazione»), accetti di essere vincolato dalle presenti Condizioni Generali d'Uso («Condizioni»). Se non accetti queste condizioni, non utilizzare l'Applicazione."),
        LegalSection(id: "2", title: "2. Descrizione del servizio", body: "Sophia è un'applicazione mobile educativa di cultura generale che offre corsi, quiz e contenuti interattivi. L'Applicazione è disponibile su iOS e può offrire contenuti gratuiti e abbonamenti premium."),
        LegalSection(id: "3", title: "3. Account e utilizzo", body: "La creazione di un account (tramite Apple o Google) è offerta per salvare i tuoi progressi e sincronizzarli tra i tuoi dispositivi. I nuovi utenti accedono durante l'onboarding; gli utenti esistenti possono creare un account in qualsiasi momento dalle impostazioni. Senza un account, i tuoi dati di avanzamento sono memorizzati localmente sul tuo dispositivo e la reinstallazione dell'Applicazione può comportarne la perdita. Puoi eliminare il tuo account in qualsiasi momento dalle impostazioni."),
        LegalSection(id: "4", title: "4. Abbonamenti e acquisti", body: "Sophia offre abbonamenti premium (mensile e annuale) tramite l'App Store di Apple. I prezzi sono indicati nell'Applicazione e possono variare in base al tuo Paese. Il pagamento viene addebitato sul tuo account Apple ID al momento della conferma dell'acquisto. L'abbonamento si rinnova automaticamente, a meno che il rinnovo automatico non venga disattivato almeno 24 ore prima della fine del periodo in corso. Puoi gestire e annullare i tuoi abbonamenti nelle impostazioni del tuo account App Store."),
        LegalSection(id: "5", title: "5. Prova gratuita", body: "Ai nuovi utenti può essere offerta una prova gratuita. Al termine del periodo di prova, l'abbonamento verrà automaticamente convertito in un abbonamento a pagamento, salvo annullamento anticipato. Qualsiasi parte non utilizzata del periodo di prova gratuita andrà persa al momento dell'acquisto di un abbonamento."),
        LegalSection(id: "6", title: "6. Proprietà intellettuale", body: "Tutti i contenuti dell'Applicazione (testi, illustrazioni, design, logo, corsi, quiz) sono protetti dal diritto d'autore e restano di proprietà esclusiva di Sophia. Qualsiasi riproduzione, distribuzione o utilizzo non autorizzato è severamente vietato."),
        LegalSection(id: "7", title: "7. Limitazione di responsabilità", body: "I contenuti offerti nell'Applicazione sono forniti a scopo educativo e informativo. Sophia non garantisce l'esattezza, la completezza o l'attualità delle informazioni presentate. L'Applicazione è fornita «così com'è», senza garanzie di alcun tipo."),
        LegalSection(id: "8", title: "8. Modifica delle condizioni", body: "Sophia si riserva il diritto di modificare le presenti Condizioni in qualsiasi momento. Gli utenti saranno informati di eventuali modifiche significative. L'uso continuato dell'Applicazione dopo una modifica costituisce accettazione delle nuove condizioni."),
        LegalSection(id: "9", title: "9. Legge applicabile", body: "Le presenti Condizioni sono soggette alla legge francese. Qualsiasi controversia relativa all'interpretazione o all'esecuzione delle presenti sarà sottoposta ai tribunali competenti."),
        LegalSection(id: "10", title: "10. Contatti", body: "Per qualsiasi domanda relativa alle presenti Condizioni, puoi contattarci tramite l'App Store o via email all'indirizzo indicato sulla nostra pagina dell'App Store."),
    ]

    // MARK: - Privacy (ES)

    private static let privacySpanish: [LegalSection] = [
        LegalSection(id: "1", title: "1. Introducción", body: "Esta Política de Privacidad describe cómo Sophia (en adelante «nosotros», «nuestro» o «la Aplicación») recopila, utiliza y protege tu información personal. Nos comprometemos a proteger tu privacidad y a tratar tus datos de forma transparente."),
        LegalSection(id: "2", title: "2. Datos recopilados", body: "Sophia está diseñada según el principio de minimización de datos. La Aplicación almacena en tu dispositivo:\n\n- Tu progreso en los cursos y cuestionarios\n- Tus preferencias (intereses, objetivos)\n- Tu racha (días consecutivos de uso)\n- Tus cursos favoritos\n\nEstos datos locales no se transmiten a nuestros servidores.\n\nLa Aplicación también envía eventos de uso anónimos a Mixpanel (región de la UE) para entender cómo se usa la app y mejorarla. Estos eventos no incluyen tu nombre, correo electrónico ni contenido personal.\n\nSi nos envías comentarios a través del formulario de los ajustes, tu mensaje y, si lo indicas, tu dirección de correo electrónico se transmiten a Formspree para que podamos responderte. La información técnica (versión de la app, idioma, dispositivo) se adjunta automáticamente."),
        LegalSection(id: "3", title: "3. Datos de suscripción", body: "Si contratas una suscripción premium, la transacción es gestionada íntegramente por Apple a través de la App Store. No tenemos acceso a tu información de pago (número de tarjeta, dirección de facturación). Solo recibimos la confirmación de tu estado de suscripción a través de RevenueCat, nuestro socio de gestión de suscripciones."),
        LegalSection(id: "4", title: "4. RevenueCat", body: "Utilizamos RevenueCat para gestionar las suscripciones dentro de la app. RevenueCat puede recopilar un identificador anónimo del dispositivo para verificar tu estado de suscripción. No se comparte ninguna información de identificación personal. Para más información, consulta la política de privacidad de RevenueCat en su sitio web."),
        LegalSection(id: "5", title: "5. Datos analíticos (Mixpanel)", body: "Utilizamos Mixpanel, alojado en la Unión Europea, para medir el uso de la Aplicación (pantallas visitadas, cursos abiertos, interacciones con el paywall, etc.). Mixpanel recibe un identificador anónimo generado por el dispositivo, la versión de la app, el idioma y eventos de uso agregados. No se recopila ningún dato personal. Puedes contactarnos para solicitar la eliminación de estos datos analíticos."),
        LegalSection(id: "6", title: "6. Datos de Apple Analytics", body: "La Aplicación también puede beneficiarse de las estadísticas anónimas proporcionadas por Apple (App Analytics). Estos datos son agregados y no permiten identificarte personalmente. Puedes desactivar el uso compartido de datos analíticos en los ajustes de tu iPhone (Ajustes > Privacidad > Análisis y mejoras)."),
        LegalSection(id: "7", title: "7. Almacenamiento de datos", body: "Todos tus datos de progreso se almacenan localmente en tu dispositivo mediante UserDefaults. No se guardan en la nube. Desinstalar la Aplicación elimina de forma definitiva estos datos."),
        LegalSection(id: "8", title: "8. Compartición de datos", body: "No vendemos, alquilamos ni compartimos ningún dato personal con terceros con fines comerciales o publicitarios. Los datos transmitidos se limitan a: Apple y RevenueCat (suscripciones), Mixpanel (analítica anónima, UE), Formspree (comentarios de usuarios enviados voluntariamente desde los ajustes)."),
        LegalSection(id: "9", title: "9. Derechos de los usuarios", body: "De conformidad con el Reglamento General de Protección de Datos (RGPD) y las leyes aplicables, dispones de los siguientes derechos:\n\n- Derecho de acceso a tus datos\n- Derecho de rectificación\n- Derecho de supresión (restablecer en los ajustes)\n- Derecho a la portabilidad\n- Derecho de oposición\n\nPara ejercer estos derechos, contáctanos a través de la dirección indicada en nuestra página de la App Store."),
        LegalSection(id: "10", title: "10. Protección de los menores", body: "Sophia es una aplicación educativa adecuada para todas las edades. No recopilamos conscientemente ningún dato personal de menores de 16 años. La Aplicación no contiene contenido inapropiado."),
        LegalSection(id: "11", title: "11. Modificaciones", body: "Nos reservamos el derecho de modificar esta política en cualquier momento. Cualquier modificación se comunicará mediante una actualización de la Aplicación.\n\nÚltima actualización: julio de 2026"),
    ]

    // MARK: - Privacy (DE)

    private static let privacyGerman: [LegalSection] = [
        LegalSection(id: "1", title: "1. Einleitung", body: "Diese Datenschutzerklärung beschreibt, wie Sophia (nachfolgend „wir“, „unser“ oder „die App“) deine personenbezogenen Daten erhebt, verwendet und schützt. Wir verpflichten uns, deine Privatsphäre zu schützen und deine Daten transparent zu verarbeiten."),
        LegalSection(id: "2", title: "2. Erhobene Daten", body: "Sophia ist nach dem Grundsatz der Datenminimierung konzipiert. Die App speichert auf deinem Gerät:\n\n- Deinen Fortschritt in Kursen und Quizzen\n- Deine Präferenzen (Interessen, Ziele)\n- Deine Serie (aufeinanderfolgende Nutzungstage)\n- Deine Lieblingskurse\n\nDiese lokalen Daten werden nicht an unsere Server übertragen.\n\nDie App sendet außerdem anonyme Nutzungsereignisse an Mixpanel (EU-Region), um zu verstehen, wie die App genutzt wird, und sie zu verbessern. Diese Ereignisse enthalten weder deinen Namen noch deine E-Mail-Adresse oder persönliche Inhalte.\n\nWenn du uns über das Formular in den Einstellungen Feedback sendest, werden deine Nachricht und – sofern angegeben – deine E-Mail-Adresse an Formspree übermittelt, damit wir dir antworten können. Technische Informationen (App-Version, Sprache, Gerät) werden automatisch beigefügt."),
        LegalSection(id: "3", title: "3. Abonnementdaten", body: "Wenn du ein Premium-Abonnement abschließt, wird die Transaktion vollständig von Apple über den App Store abgewickelt. Wir haben keinen Zugriff auf deine Zahlungsinformationen (Kartennummer, Rechnungsadresse). Wir erhalten lediglich die Bestätigung deines Abonnementstatus über RevenueCat, unseren Partner für die Abonnementverwaltung."),
        LegalSection(id: "4", title: "4. RevenueCat", body: "Wir nutzen RevenueCat zur Verwaltung von In-App-Abonnements. RevenueCat kann eine anonyme Gerätekennung erfassen, um deinen Abonnementstatus zu überprüfen. Es werden keine personenbezogenen Daten weitergegeben. Weitere Informationen findest du in der Datenschutzerklärung von RevenueCat auf deren Website."),
        LegalSection(id: "5", title: "5. Analysedaten (Mixpanel)", body: "Wir verwenden Mixpanel, gehostet in der Europäischen Union, um die Nutzung der App zu messen (besuchte Bildschirme, geöffnete Kurse, Paywall-Interaktionen usw.). Mixpanel erhält eine anonyme, vom Gerät generierte Kennung, die App-Version, die Sprache und aggregierte Nutzungsereignisse. Es werden keine personenbezogenen Daten erhoben. Du kannst uns kontaktieren, um die Löschung dieser Analysedaten zu verlangen."),
        LegalSection(id: "6", title: "6. Apple-Analysedaten", body: "Die App kann außerdem von anonymen Statistiken profitieren, die von Apple bereitgestellt werden (App Analytics). Diese Daten sind aggregiert und lassen keine persönliche Identifizierung zu. Du kannst die Weitergabe von Analysedaten in den Einstellungen deines iPhones deaktivieren (Einstellungen > Datenschutz > Analyse & Verbesserungen)."),
        LegalSection(id: "7", title: "7. Datenspeicherung", body: "Alle deine Fortschrittsdaten werden lokal auf deinem Gerät über UserDefaults gespeichert. Sie werden nicht in der Cloud gesichert. Beim Deinstallieren der App werden diese Daten endgültig gelöscht."),
        LegalSection(id: "8", title: "8. Weitergabe von Daten", body: "Wir verkaufen, vermieten oder teilen keine personenbezogenen Daten mit Dritten zu kommerziellen oder Werbezwecken. Die übermittelten Daten beschränken sich auf: Apple und RevenueCat (Abonnements), Mixpanel (anonyme Analysen, EU), Formspree (freiwillig aus den Einstellungen gesendetes Nutzerfeedback)."),
        LegalSection(id: "9", title: "9. Rechte der Nutzer", body: "Gemäß der Datenschutz-Grundverordnung (DSGVO) und den geltenden Gesetzen stehen dir die folgenden Rechte zu:\n\n- Recht auf Auskunft über deine Daten\n- Recht auf Berichtigung\n- Recht auf Löschung (Zurücksetzen in den Einstellungen)\n- Recht auf Datenübertragbarkeit\n- Widerspruchsrecht\n\nUm diese Rechte auszuüben, kontaktiere uns über die auf unserer App-Store-Seite angegebene Adresse."),
        LegalSection(id: "10", title: "10. Schutz von Minderjährigen", body: "Sophia ist eine Lern-App, die für alle Altersgruppen geeignet ist. Wir erheben wissentlich keine personenbezogenen Daten von Kindern unter 16 Jahren. Die App enthält keine unangemessenen Inhalte."),
        LegalSection(id: "11", title: "11. Änderungen", body: "Wir behalten uns das Recht vor, diese Richtlinie jederzeit zu ändern. Alle Änderungen werden über ein App-Update mitgeteilt.\n\nZuletzt aktualisiert: Juli 2026"),
    ]

    // MARK: - Privacy (PT)

    private static let privacyPortuguese: [LegalSection] = [
        LegalSection(id: "1", title: "1. Introdução", body: "A presente Política de Privacidade descreve como a Sophia (doravante «nós», «nosso» ou «a Aplicação») recolhe, utiliza e protege as tuas informações pessoais. Comprometemo-nos a proteger a tua privacidade e a tratar os teus dados de forma transparente."),
        LegalSection(id: "2", title: "2. Dados recolhidos", body: "A Sophia foi concebida segundo o princípio da minimização de dados. A Aplicação armazena no teu dispositivo:\n\n- O teu progresso nos cursos e questionários\n- As tuas preferências (interesses, objetivos)\n- A tua sequência (dias consecutivos de utilização)\n- Os teus cursos favoritos\n\nEstes dados locais não são transmitidos aos nossos servidores.\n\nA Aplicação também envia eventos de utilização anónimos para o Mixpanel (região da UE) para compreender como a app é utilizada e melhorá-la. Estes eventos não incluem o teu nome, email ou conteúdo pessoal.\n\nSe nos enviares comentários através do formulário nas definições, a tua mensagem e, caso o indiques, o teu endereço de email são transmitidos ao Formspree para que possamos responder-te. As informações técnicas (versão da app, idioma, dispositivo) são anexadas automaticamente."),
        LegalSection(id: "3", title: "3. Dados de subscrição", body: "Se subscreveres um plano premium, a transação é gerida integralmente pela Apple através da App Store. Não temos acesso às tuas informações de pagamento (número do cartão, morada de faturação). Recebemos apenas a confirmação do teu estado de subscrição através do RevenueCat, o nosso parceiro de gestão de subscrições."),
        LegalSection(id: "4", title: "4. RevenueCat", body: "Utilizamos o RevenueCat para gerir as subscrições dentro da app. O RevenueCat pode recolher um identificador anónimo do dispositivo para verificar o teu estado de subscrição. Não é partilhada qualquer informação de identificação pessoal. Para mais informações, consulta a política de privacidade do RevenueCat no respetivo site."),
        LegalSection(id: "5", title: "5. Dados analíticos (Mixpanel)", body: "Utilizamos o Mixpanel, alojado na União Europeia, para medir a utilização da Aplicação (ecrãs visitados, cursos abertos, interações com o paywall, etc.). O Mixpanel recebe um identificador anónimo gerado pelo dispositivo, a versão da app, o idioma e eventos de utilização agregados. Não é recolhido qualquer dado pessoal. Podes contactar-nos para solicitar a eliminação destes dados analíticos."),
        LegalSection(id: "6", title: "6. Dados do Apple Analytics", body: "A Aplicação pode também beneficiar de estatísticas anónimas fornecidas pela Apple (App Analytics). Estes dados são agregados e não permitem identificar-te pessoalmente. Podes desativar a partilha de dados analíticos nas definições do teu iPhone (Definições > Privacidade > Análise e melhorias)."),
        LegalSection(id: "7", title: "7. Armazenamento de dados", body: "Todos os teus dados de progresso são armazenados localmente no teu dispositivo através do UserDefaults. Não são guardados na cloud. Desinstalar a Aplicação elimina definitivamente estes dados."),
        LegalSection(id: "8", title: "8. Partilha de dados", body: "Não vendemos, alugamos nem partilhamos quaisquer dados pessoais com terceiros para fins comerciais ou publicitários. Os dados transmitidos limitam-se a: Apple e RevenueCat (subscrições), Mixpanel (análise anónima, UE), Formspree (comentários de utilizadores enviados voluntariamente a partir das definições)."),
        LegalSection(id: "9", title: "9. Direitos dos utilizadores", body: "Nos termos do Regulamento Geral sobre a Proteção de Dados (RGPD) e das leis aplicáveis, dispões dos seguintes direitos:\n\n- Direito de acesso aos teus dados\n- Direito de retificação\n- Direito ao apagamento (repor nas definições)\n- Direito à portabilidade\n- Direito de oposição\n\nPara exercer estes direitos, contacta-nos através da morada indicada na nossa página da App Store."),
        LegalSection(id: "10", title: "10. Proteção de menores", body: "A Sophia é uma aplicação educativa adequada a todas as idades. Não recolhemos conscientemente dados pessoais de menores de 16 anos. A Aplicação não contém conteúdos inadequados."),
        LegalSection(id: "11", title: "11. Alterações", body: "Reservamo-nos o direito de alterar esta política a qualquer momento. Quaisquer alterações serão comunicadas através de uma atualização da Aplicação.\n\nÚltima atualização: julho de 2026"),
    ]

    // MARK: - Privacy (IT)

    private static let privacyItalian: [LegalSection] = [
        LegalSection(id: "1", title: "1. Introduzione", body: "La presente Informativa sulla privacy descrive come Sophia (di seguito «noi», «nostro» o «l'Applicazione») raccoglie, utilizza e protegge le tue informazioni personali. Ci impegniamo a proteggere la tua privacy e a trattare i tuoi dati in modo trasparente."),
        LegalSection(id: "2", title: "2. Dati raccolti", body: "Sophia è progettata secondo il principio della minimizzazione dei dati. L'Applicazione memorizza sul tuo dispositivo:\n\n- I tuoi progressi nei corsi e nei quiz\n- Le tue preferenze (interessi, obiettivi)\n- La tua serie (giorni consecutivi di utilizzo)\n- I tuoi corsi preferiti\n\nQuesti dati locali non vengono trasmessi ai nostri server.\n\nL'Applicazione invia inoltre eventi di utilizzo anonimi a Mixpanel (regione UE) per capire come viene utilizzata l'app e migliorarla. Questi eventi non contengono il tuo nome, la tua email o contenuti personali.\n\nSe ci invii un feedback tramite il modulo nelle impostazioni, il tuo messaggio e, se fornito, il tuo indirizzo email vengono trasmessi a Formspree per consentirci di risponderti. Le informazioni tecniche (versione dell'app, lingua, dispositivo) vengono allegate automaticamente."),
        LegalSection(id: "3", title: "3. Dati di abbonamento", body: "Se sottoscrivi un abbonamento premium, la transazione è gestita interamente da Apple tramite l'App Store. Non abbiamo accesso alle tue informazioni di pagamento (numero della carta, indirizzo di fatturazione). Riceviamo solo la conferma del tuo stato di abbonamento tramite RevenueCat, il nostro partner per la gestione degli abbonamenti."),
        LegalSection(id: "4", title: "4. RevenueCat", body: "Utilizziamo RevenueCat per gestire gli abbonamenti in-app. RevenueCat può raccogliere un identificatore anonimo del dispositivo per verificare il tuo stato di abbonamento. Non viene condivisa alcuna informazione personale identificabile. Per maggiori informazioni, consulta l'informativa sulla privacy di RevenueCat sul loro sito web."),
        LegalSection(id: "5", title: "5. Dati analitici (Mixpanel)", body: "Utilizziamo Mixpanel, ospitato nell'Unione europea, per misurare l'utilizzo dell'Applicazione (schermate visitate, corsi aperti, interazioni con il paywall, ecc.). Mixpanel riceve un identificatore anonimo generato dal dispositivo, la versione dell'app, la lingua ed eventi di utilizzo aggregati. Non viene raccolto alcun dato personale. Puoi contattarci per richiedere la cancellazione di questi dati analitici."),
        LegalSection(id: "6", title: "6. Dati di Apple Analytics", body: "L'Applicazione può inoltre beneficiare delle statistiche anonime fornite da Apple (App Analytics). Questi dati sono aggregati e non consentono di identificarti personalmente. Puoi disattivare la condivisione dei dati analitici nelle impostazioni del tuo iPhone (Impostazioni > Privacy > Analisi e miglioramenti)."),
        LegalSection(id: "7", title: "7. Conservazione dei dati", body: "Tutti i tuoi dati di avanzamento sono memorizzati localmente sul tuo dispositivo tramite UserDefaults. Non vengono salvati nel cloud. La disinstallazione dell'Applicazione comporta l'eliminazione definitiva di questi dati."),
        LegalSection(id: "8", title: "8. Condivisione dei dati", body: "Non vendiamo, noleggiamo né condividiamo alcun dato personale con terzi per finalità commerciali o pubblicitarie. I dati trasmessi si limitano a: Apple e RevenueCat (abbonamenti), Mixpanel (analisi anonime, UE), Formspree (feedback degli utenti inviati volontariamente dalle impostazioni)."),
        LegalSection(id: "9", title: "9. Diritti degli utenti", body: "Ai sensi del Regolamento generale sulla protezione dei dati (GDPR) e delle leggi applicabili, disponi dei seguenti diritti:\n\n- Diritto di accesso ai tuoi dati\n- Diritto di rettifica\n- Diritto alla cancellazione (ripristino nelle impostazioni)\n- Diritto alla portabilità\n- Diritto di opposizione\n\nPer esercitare questi diritti, contattaci all'indirizzo indicato sulla nostra pagina dell'App Store."),
        LegalSection(id: "10", title: "10. Protezione dei minori", body: "Sophia è un'applicazione educativa adatta a tutte le età. Non raccogliamo consapevolmente alcun dato personale di minori di 16 anni. L'Applicazione non contiene contenuti inappropriati."),
        LegalSection(id: "11", title: "11. Modifiche", body: "Ci riserviamo il diritto di modificare la presente informativa in qualsiasi momento. Qualsiasi modifica sarà comunicata tramite un aggiornamento dell'Applicazione.\n\nUltimo aggiornamento: luglio 2026"),
    ]
}
