#!/usr/bin/env python3
"""Generate the self-contained course ranking queries.

The ranking returns a courseId, and Supabase holds neither the title nor how
many lessons a course has -- both ship inside the app. They have to travel with
the query, so they go in as a `values` CTE. A temporary table does not work
here: the Supabase SQL editor opens a new connection per run, so anything made
with `create temporary table` is gone by the next statement.

Writes two files:
    top_courses_with_titles.sql   the ten most-read
    all_courses_with_titles.sql   every course, including the ones nobody opened

Usage:
    python scripts/build_course_titles_sql.py
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
COURSES_V2 = ROOT / "ios" / "Sophia" / "Resources" / "CoursesV2"
CATALOGUE = ROOT / "ios" / "Sophia" / "Resources" / "Locales" / "courses.fr.json"
OUT_DIR = ROOT / "supabase" / "queries"

PREAMBLE = """\
-- {what}
--
-- Generated by scripts/build_course_titles_sql.py -- re-run it when the
-- catalogue changes. Self-contained: paste and run, nothing to set up first.
-- The titles and lesson counts are inlined because Supabase has none of its
-- own, and because the SQL editor opens a new connection per run, which a
-- temporary table does not survive.
--
-- Reading the columns:
--   readers            users who advanced at least one lesson in the course.
--                      ProgressManager only writes an entry when "continue" is
--                      tapped, so a course opened and closed on its first page
--                      does not count here.
--   finishers          users who reached the end (isCompleted).
--   avg_lessons_read   average furthest lesson reached, counting from 1. The
--                      stored value is a 0-based high-water mark, so this is
--                      lastLessonIndex + 1: 5 on a five-lesson course means the
--                      average reader got to the last page.
--   avg_progress_pct   the same thing against this course's own length, which
--                      is what lets two courses be compared.
--   saves              users with the course in their favourites right now.
--
-- Limits, the same as top_courses.sql: signed-in users only, distinct users
-- rather than volume, and a snapshot with no history behind it.

with catalogue (course_id, title, lesson_count) as (
  values
{rows}
),
read as (
  select key as course_id,
         count(*) as readers,
         count(*) filter (where (value ->> 'isCompleted')::boolean) as finishers,
         avg((value ->> 'lastLessonIndex')::int) as avg_index
  from user_progress up
  cross join lateral jsonb_each(up.progress::jsonb -> 'courseProgress')
  group by key
),
saved as (
  select course_id, count(*) as saves
  from user_progress up
  cross join lateral jsonb_array_elements_text(
    coalesce(up.progress::jsonb -> 'favoriteCourseIds', '[]'::jsonb)
  ) as course_id
  group by course_id
)
"""

TOP = """\
select
  coalesce(c.title, r.course_id) as course,
  r.readers,
  r.finishers,
  round(100.0 * r.finishers / nullif(r.readers, 0), 1) as completion_pct,
  round((r.avg_index + 1)::numeric, 2)                as avg_lessons_read,
  round(100.0 * (r.avg_index + 1) / nullif(c.lesson_count, 0), 1) as avg_progress_pct,
  coalesce(s.saves, 0) as saves
from read r
left join saved s on s.course_id = r.course_id
left join catalogue c on c.course_id = r.course_id
order by r.readers desc, r.finishers desc
limit 10;
"""

ALL = """\
select
  c.title                                        as course,
  c.course_id,
  c.lesson_count,
  coalesce(r.readers, 0)                         as readers,
  coalesce(r.finishers, 0)                       as finishers,
  round(100.0 * r.finishers / nullif(r.readers, 0), 1) as completion_pct,
  round((r.avg_index + 1)::numeric, 2)           as avg_lessons_read,
  round(100.0 * (r.avg_index + 1) / nullif(c.lesson_count, 0), 1) as avg_progress_pct,
  coalesce(s.saves, 0)                           as saves
from catalogue c
left join read r on r.course_id = c.course_id
left join saved s on s.course_id = c.course_id
order by coalesce(r.readers, 0) desc, coalesce(s.saves, 0) desc, c.title;
"""


def catalogue_rows() -> list[str]:
    lessons = {
        course["id"]: len(course.get("lessons") or [])
        for course in json.loads(CATALOGUE.read_text(encoding="utf-8"))
    } if CATALOGUE.is_file() else {}
    rows = []
    for path in sorted(COURSES_V2.glob("*.fr.json")):
        course_id = path.name[: -len(".fr.json")]
        content = json.loads(path.read_text(encoding="utf-8"))
        title = (content.get("title") or "").strip()
        count = lessons.get(course_id) or len(content.get("sections") or [])
        if title and count:
            rows.append(
                f"    ('{course_id}', '{title.replace(chr(39), chr(39) * 2)}', {count})"
            )
    return rows


def main() -> int:
    rows = ",\n".join(catalogue_rows())
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for name, what, tail in (
        ("top_courses_with_titles.sql", "The ten most-read courses, with their titles.", TOP),
        ("all_courses_with_titles.sql",
         "Every course, most-read first, including the ones nobody has opened.", ALL),
    ):
        (OUT_DIR / name).write_text(
            PREAMBLE.format(what=what, rows=rows) + tail, encoding="utf-8"
        )
        print(f"  {name}")
    print(f"{len(catalogue_rows())} course(s) inlined")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
