#!/usr/bin/env python3
"""Generate supabase/queries/course_titles.sql from the French course files.

The ranking queries return a courseId, which is readable but ugly in a report.
Supabase holds no titles -- they ship inside the app -- so the lookup is built
here and pasted into the SQL editor alongside the query.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
COURSES_V2 = ROOT / "ios" / "Sophia" / "Resources" / "CoursesV2"
OUT = ROOT / "supabase" / "queries" / "course_titles.sql"


def main() -> int:
    rows = []
    for path in sorted(COURSES_V2.glob("*.fr.json")):
        course_id = path.name[: -len(".fr.json")]
        title = (json.loads(path.read_text(encoding="utf-8")).get("title") or "").strip()
        if title:
            rows.append(f"  ('{course_id}', '{title.replace(chr(39), chr(39) * 2)}')")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "-- courseId -> French title, generated by scripts/build_course_titles_sql.py.\n"
        "-- Paste this before top_courses.sql when you want titles instead of ids.\n"
        "create temporary table if not exists course_titles "
        "(course_id text primary key, title text);\n"
        "truncate course_titles;\n"
        "insert into course_titles (course_id, title) values\n"
        + ",\n".join(rows)
        + ";\n",
        encoding="utf-8",
    )
    print(f"{len(rows)} title(s) -> {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
