#!/usr/bin/env python3
"""Generate the self-contained course analytics queries for Supabase.

Supabase holds none of the catalogue: not the title, not the subject, not how
many lessons a course has. All of that ships inside the app, so it has to travel
with the query as a `values` CTE. A temporary table does not work here -- the
Supabase SQL editor opens a new connection per run, so anything made with
`create temporary table` is gone by the next statement.

Writes, all self-contained and all exportable as CSV from the editor:

    all_courses.sql        one row per course, every dimension and metric. The
                           master export -- pivot it in a spreadsheet.
    top_courses.sql        the ten most-read.
    by_subject.sql         aggregated per subject.
    by_subcategory.sql     aggregated per subcategory.

Usage:
    python scripts/build_course_titles_sql.py
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
COURSES_V2 = ROOT / "ios" / "Sophia" / "Resources" / "CoursesV2"
CATALOGUE = ROOT / "ios" / "Sophia" / "Resources" / "Locales" / "courses.en.json"
OUT_DIR = ROOT / "supabase" / "queries"

HEADER = """\
-- {what}
--
-- Generated by scripts/build_course_titles_sql.py -- re-run it when the
-- catalogue changes. Self-contained: paste and run, nothing to set up first.
-- Export the result with the editor's CSV button.
--
-- Reading the columns:
--   readers            users who advanced at least one lesson. ProgressManager
--                      writes a courseProgress entry when "continue" is tapped,
--                      not when the course opens, so a course opened and closed
--                      on its first page is in nobody's count.
--   finishers          users who reached the end (isCompleted).
--   avg_lessons_read   average furthest lesson reached, counting from 1. The
--                      stored value is a 0-based high-water mark, so this is
--                      lastLessonIndex + 1.
--   avg_progress_pct   the same against the course's own length, which is what
--                      lets a four-lesson course be compared with a five.
--   saves              users with the course in their favourites right now.
--   quiz_takers        users who finished the quiz for it.
--   avg_quiz_score     their best score, averaged.
--
-- What this data cannot tell you:
--   * Nothing per language. The reading language is stored nowhere -- not in
--     user_progress, not in profiles (which holds only id and handle). It would
--     take the app sending it before any of this can be split that way.
--   * Signed-in users only. Sync never runs for anonymous users.
--   * Distinct users, not volume: a course read ten times by one person counts
--     once. The snapshot keeps no history, so there are no dates, no repeat
--     counts, and no trace of a course saved and then unsaved.

with catalogue (course_id, title, subject, subcategory, lesson_count) as (
  values
{rows}
),
read as (
  select key as course_id,
         count(*) as readers,
         count(*) filter (where (value ->> 'isCompleted')::boolean) as finishers,
         avg((value ->> 'lastLessonIndex')::int) as avg_index,
         count(*) filter (where (value ->> 'bestQuizScore')::int > 0) as quiz_takers,
         avg((value ->> 'bestQuizScore')::int)
           filter (where (value ->> 'bestQuizScore')::int > 0) as avg_quiz_score
  from user_progress up
  cross join lateral jsonb_each(up.progress::jsonb -> 'courseProgress')
  group by key
),
saved as (
  select course_id, count(*) as saves
  from user_progress up
  cross join lateral jsonb_array_elements_text(
    coalesce(up.progress::jsonb -> 'favoriteCourseIds', '[]'::jsonb)
  ) as course_id
  group by course_id
)
"""

ALL_COURSES = """\
select
  c.subject,
  c.subcategory,
  c.title                                              as course,
  c.course_id,
  c.lesson_count,
  coalesce(r.readers, 0)                               as readers,
  coalesce(r.finishers, 0)                             as finishers,
  round(100.0 * r.finishers / nullif(r.readers, 0), 1) as completion_pct,
  round((r.avg_index + 1)::numeric, 2)                 as avg_lessons_read,
  round(100.0 * (r.avg_index + 1) / nullif(c.lesson_count, 0), 1) as avg_progress_pct,
  coalesce(s.saves, 0)                                 as saves,
  coalesce(r.quiz_takers, 0)                           as quiz_takers,
  round(r.avg_quiz_score::numeric, 1)                  as avg_quiz_score
from catalogue c
left join read r on r.course_id = c.course_id
left join saved s on s.course_id = c.course_id
order by coalesce(r.readers, 0) desc, coalesce(s.saves, 0) desc, c.title;
"""

TOP = """\
select
  c.subject,
  c.title                                              as course,
  coalesce(r.readers, 0)                               as readers,
  coalesce(r.finishers, 0)                             as finishers,
  round(100.0 * r.finishers / nullif(r.readers, 0), 1) as completion_pct,
  round((r.avg_index + 1)::numeric, 2)                 as avg_lessons_read,
  round(100.0 * (r.avg_index + 1) / nullif(c.lesson_count, 0), 1) as avg_progress_pct,
  coalesce(s.saves, 0)                                 as saves
from catalogue c
join read r on r.course_id = c.course_id
left join saved s on s.course_id = c.course_id
order by r.readers desc, r.finishers desc
limit 10;
"""

BY_GROUP = """\
select
  c.{group_by},
  count(*)                                              as courses,
  count(*) filter (where r.readers is not null)         as courses_opened,
  coalesce(sum(r.readers), 0)                           as reads,
  coalesce(sum(r.finishers), 0)                         as finishes,
  round(100.0 * sum(r.finishers) / nullif(sum(r.readers), 0), 1) as completion_pct,
  -- Weighted by readers, so a course with three readers does not swing the
  -- subject as hard as one with three hundred.
  round(
    (sum((r.avg_index + 1) * r.readers) / nullif(sum(r.readers), 0))::numeric
  , 2)                                                  as avg_lessons_read,
  coalesce(sum(s.saves), 0)                             as saves,
  round(
    (sum(r.avg_quiz_score * r.quiz_takers) / nullif(sum(r.quiz_takers), 0))::numeric
  , 1)                                                  as avg_quiz_score
from catalogue c
left join read r on r.course_id = c.course_id
left join saved s on s.course_id = c.course_id
group by c.{group_by}
order by reads desc;
"""


def catalogue_rows() -> list[str]:
    meta = {
        course["id"]: (
            course.get("subject") or "",
            course.get("subcategory") or "",
            len(course.get("lessons") or []),
        )
        for course in json.loads(CATALOGUE.read_text(encoding="utf-8"))
    }
    rows = []
    for path in sorted(COURSES_V2.glob("*.fr.json")):
        course_id = path.name[: -len(".fr.json")]
        title = (json.loads(path.read_text(encoding="utf-8")).get("title") or "").strip()
        subject, subcategory, lessons = meta.get(course_id, ("", "", 0))
        if not (title and lessons):
            continue

        def q(value: str) -> str:
            return value.replace("'", "''")

        rows.append(
            f"    ('{course_id}', '{q(title)}', '{q(subject)}', "
            f"'{q(subcategory)}', {lessons})"
        )
    return rows


def main() -> int:
    rows = ",\n".join(catalogue_rows())
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    files = (
        ("all_courses.sql",
         "Every course, one row each, with its subject and every metric.",
         ALL_COURSES),
        ("top_courses.sql", "The ten most-read courses.", TOP),
        ("by_subject.sql", "Every metric aggregated per subject.",
         BY_GROUP.format(group_by="subject")),
        ("by_subcategory.sql", "Every metric aggregated per subcategory.",
         BY_GROUP.format(group_by="subcategory")),
    )
    for name, what, tail in files:
        (OUT_DIR / name).write_text(HEADER.format(what=what, rows=rows) + tail, encoding="utf-8")
        print(f"  {name}")
    print(f"{len(catalogue_rows())} course(s) inlined")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
