#!/usr/bin/env python3
"""Split ``ios/Sophia/Services/CourseData.swift`` into small compiled chunks.

``CourseData.swift`` stays the source of truth for the content pipeline (the import and
fix scripts read and write it), but it is **not compiled**: a single 1.6 MB array literal
of 309 courses takes the Swift type-checker past 250 GB of memory on a development Mac.
The Xcode project excludes it from the Sophia target, and compiles instead what this
script writes under ``ios/Sophia/Services/CourseDataChunks/``:

  * ``CourseDataCatalog.swift`` – the ``CourseData`` enum whose ``allCourses`` flattens
    the chunks, in the original order;
  * ``CourseData+ChunkNN.swift`` – one ``[Course]`` literal of at most 15 courses each.

Run it after any script that rewrites ``CourseData.swift`` (they call it themselves).
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
COURSE_DATA = ROOT / "ios/Sophia/Services/CourseData.swift"
OUT_DIR = ROOT / "ios/Sophia/Services/CourseDataChunks"
COURSES_PER_CHUNK = 15

HEADER_LINE = "    static let allCourses: [Course] = ["
COURSE_START = "        Course("


def split() -> int:
    lines = COURSE_DATA.read_text(encoding="utf-8").split("\n")
    try:
        header_end = next(i for i, l in enumerate(lines) if l.strip() == HEADER_LINE.strip())
    except StopIteration:
        raise SystemExit("CourseData.swift: 'static let allCourses: [Course] = [' not found")
    # Footer: the array's closing bracket and the enum's closing brace.
    tail = [l for l in lines[-4:]]
    if not (lines[-1] == "" and lines[-2] == "}" and lines[-3] == "    ]"):
        raise SystemExit(f"CourseData.swift does not end as expected: {tail!r}")
    body = lines[header_end + 1:-3]

    starts = [i for i, l in enumerate(body) if l == COURSE_START]
    if not starts:
        raise SystemExit("CourseData.swift: no top-level 'Course(' found")

    chunks: list[list[str]] = []
    for k in range(0, len(starts), COURSES_PER_CHUNK):
        a = starts[k]
        b = starts[k + COURSES_PER_CHUNK] if k + COURSES_PER_CHUNK < len(starts) else len(body)
        chunks.append(body[a:b])

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for stale in OUT_DIR.glob("CourseData+Chunk*.swift"):
        stale.unlink()

    names = []
    for n, chunk in enumerate(chunks, start=1):
        name = f"chunk{n:02d}"
        names.append(name)
        text = "\n".join(chunk).rstrip()
        src = (
            "import Foundation\n\n"
            "// GENERATED by scripts/split_course_data.py from Services/CourseData.swift.\n"
            "// Do not edit: change CourseData.swift and rerun the script.\n"
            "nonisolated extension CourseData {\n"
            f"    static let {name}: [Course] = [\n"
            f"{text}\n"
            "    ]\n"
            "}\n"
        )
        (OUT_DIR / f"CourseData+Chunk{n:02d}.swift").write_text(src, encoding="utf-8")

    catalog = (
        "import Foundation\n\n"
        "// GENERATED by scripts/split_course_data.py from Services/CourseData.swift.\n"
        "// Do not edit: change CourseData.swift and rerun the script.\n"
        "//\n"
        "// `CourseData.swift` itself is excluded from the Sophia target: one 1.6 MB array\n"
        "// literal took the Swift type-checker past 250 GB of memory. The chunks are small\n"
        "// literals; flattening keeps the original order.\n"
        "nonisolated enum CourseData {\n"
        "    static let allCourses: [Course] = [\n"
        + "".join(f"        {name},\n" for name in names)
        + "    ].flatMap { $0 }\n"
        "}\n"
    )
    (OUT_DIR / "CourseDataCatalog.swift").write_text(catalog, encoding="utf-8")
    return len(starts)


if __name__ == "__main__":
    count = split()
    print(f"split_course_data: {count} courses → {OUT_DIR.relative_to(ROOT)}", file=sys.stderr)
