import Foundation

// GENERATED by scripts/split_course_data.py from Services/CourseData.swift.
// Do not edit: change CourseData.swift and rerun the script.
nonisolated extension CourseData {
    static let chunk11: [Course] = [
        Course(
            id: "course_152_la_liberte_guidant_le_peuple_delacroix",
            title: "Que célèbre « La Liberté guidant le peuple » de Delacroix ?",
            description: "«La Liberté guidant le peuple» (1830) d'Eugène Delacroix est l'image politique française la plus connue et la plus reproduite. Femme allégorique brandissant...",
            subject: .art,
            subcategory: "Cinéma, photo & architecture + œuvres iconiques",
            lessons: [
                LessonPage(id: "course_152_la_liberte_guidant_le_peuple_delacroix_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_152_la_liberte_guidant_le_peuple_delacroix_p1", title: "L'insurrection de 1830 : de la rue à l'atelier", content: ""),
                LessonPage(id: "course_152_la_liberte_guidant_le_peuple_delacroix_p2", title: "L'esthétique de la Liberté : entre allégorie et réalisme", content: ""),
                LessonPage(id: "course_152_la_liberte_guidant_le_peuple_delacroix_p3", title: "Une réception politique ambivalente", content: ""),
                LessonPage(id: "course_152_la_liberte_guidant_le_peuple_delacroix_p4", title: "Une icône mondiale et mémorielle", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_152_la_liberte_guidant_le_peuple_delacroix_q1", question: "Quel événement de 1830 pousse Delacroix à peindre ce tableau ?", options: ["Les Trois Glorieuses qui chassent Charles X", "La prise de la Bastille", "Le sacre de Napoléon", "La Commune de Paris"], correctIndex: 0, explanation: "En 1830, les Trois Glorieuses chassent le roi Charles X et Delacroix peint aussitôt La Liberté guidant le peuple."),
        QuizQuestion(id: "course_152_la_liberte_guidant_le_peuple_delacroix_q2", question: "Quel mouvement artistique ce tableau incarne-t-il, mêlant allégorie et reportage ?", options: ["Le romantisme", "Le classicisme", "L'impressionnisme", "Le symbolisme"], correctIndex: 0, explanation: "Allégorie et reportage se mêlent dans ce tableau, c'est le romantisme en acte."),
        QuizQuestion(id: "course_152_la_liberte_guidant_le_peuple_delacroix_q3", question: "Que symbolise la femme au bonnet phrygien au centre du tableau ?", options: ["La Marianne, allégorie de la République", "La Vierge Marie", "La déesse Athéna", "La reine Marie-Antoinette"], correctIndex: 0, explanation: "La femme au bonnet phrygien incarne la Marianne, symbole de la République française."),
        QuizQuestion(id: "course_152_la_liberte_guidant_le_peuple_delacroix_q4", type: .trueFalse, question: "Vrai ou faux : dans le tableau, la Liberté est représentée comme une déesse lointaine, séparée du peuple.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "La Liberté, sein nu, n'est pas une déesse lointaine : elle marche dans la boue avec le peuple."),
        QuizQuestion(id: "course_152_la_liberte_guidant_le_peuple_delacroix_q5", question: "Qu'est-ce que Delacroix place au premier plan pour montrer le prix de l'insurrection ?", options: ["Des corps morts", "Des fleurs", "Des soldats en parade", "Des bâtiments en flammes"], correctIndex: 0, explanation: "Delacroix place des corps morts au premier plan : la victoire a un prix."),
        QuizQuestion(id: "course_152_la_liberte_guidant_le_peuple_delacroix_q6", type: .trueFalse, question: "Vrai ou faux : Delacroix aurait déclaré avoir entrepris « un sujet moderne, une barricade ».", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Delacroix aurait bien déclaré avoir entrepris un sujet moderne, une barricade."),
        QuizQuestion(id: "course_152_la_liberte_guidant_le_peuple_delacroix_q7", question: "Pourquoi le tableau est-il retiré des cimaises après le Salon ?", options: ["Il gêne le nouveau roi Louis-Philippe d'Orléans", "Il est jugé trop mal peint", "Delacroix le retire lui-même par superstition", "Il est vendu à un collectionneur étranger"], correctIndex: 0, explanation: "Exposé au Salon, le tableau gêne vite Louis-Philippe d'Orléans, le nouveau roi, qui le fait ranger."),
        QuizQuestion(id: "course_152_la_liberte_guidant_le_peuple_delacroix_q8", question: "Quel régime politique la Révolution de 1830 vient-elle de renverser ?", options: ["La Restauration des Bourbons", "Le Premier Empire", "La Troisième République", "Le Directoire"], correctIndex: 0, explanation: "La Restauration des Bourbons, qui avait déçu, est renversée en trois jours d'insurrection à Paris."),
        QuizQuestion(id: "course_152_la_liberte_guidant_le_peuple_delacroix_q9", question: "Quels types sociaux se mêlent autour de la Liberté dans la composition ?", options: ["Un ouvrier, un bourgeois et un gamin proche de Gavroche", "Uniquement des soldats professionnels", "Des aristocrates en habits de cour", "Des paysans isolés à la campagne"], correctIndex: 0, explanation: "Autour de la Marianne se mêlent un ouvrier, un bourgeois et un gamin proche du futur Gavroche, unissant les classes dans l'insurrection.")
    ]
        ),
        Course(
            id: "course_153_la_creation_d_adam_michel_ange",
            title: "La Création d'Adam, Michel-Ange",
            description: "«La Création d'Adam» est la fresque centrale du plafond de la Chapelle Sixtine : l'image la plus reproduite de la peinture de la Renaissance et l'une des ima...",
            subject: .art,
            subcategory: "Cinéma, photo & architecture + œuvres iconiques",
            lessons: [
                LessonPage(id: "course_153_la_creation_d_adam_michel_ange_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_153_la_creation_d_adam_michel_ange_p1", title: "Un défi monumental imposé par Jules II", content: ""),
                LessonPage(id: "course_153_la_creation_d_adam_michel_ange_p2", title: "L'esthétique de l'étincelle et la géométrie de la vie", content: ""),
                LessonPage(id: "course_153_la_creation_d_adam_michel_ange_p3", title: "La science cachée sous le pinceau", content: ""),
                LessonPage(id: "course_153_la_creation_d_adam_michel_ange_p4", title: "Une postérité universelle : de la Sixtine à la Pop Culture", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_153_la_creation_d_adam_michel_ange_q1", question: "Qui commande à Michel-Ange la fresque du plafond de la Chapelle Sixtine ?", options: ["Le pape Jules II", "Le pape Léon X", "Le roi François Ier", "Le doge de Venise"], correctIndex: 0, explanation: "Le pape Jules II veut un plafond grandiose et impose la commande à Michel-Ange."),
        QuizQuestion(id: "course_153_la_creation_d_adam_michel_ange_q2", type: .trueFalse, question: "Vrai ou faux : Michel-Ange, avant tout sculpteur, accepte immédiatement et sans réticence la commande du plafond.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "Michel-Ange, surtout sculpteur, proteste d'abord avant d'accepter la commande."),
        QuizQuestion(id: "course_153_la_creation_d_adam_michel_ange_q3", type: .numericSlider, question: "En quelle année Michel-Ange achève-t-il le plafond de la Chapelle Sixtine ?", explanation: "Michel-Ange peint le plafond de la Chapelle Sixtine entre 1508 et 1512, achevant l'œuvre en 1512.", correctValue: 1512, sliderMin: 1480, sliderMax: 1550, tolerance: 3, unit: ""),
        QuizQuestion(id: "course_153_la_creation_d_adam_michel_ange_q4", question: "Quelle technique picturale exige de peindre sur un enduit encore frais, comme pour ce plafond ?", options: ["La fresque", "La peinture à l'huile", "La mosaïque", "L'aquarelle"], correctIndex: 0, explanation: "La fresque exige de peindre sur l'enduit frais, ce qui impose à Michel-Ange un rythme de travail éprouvant."),
        QuizQuestion(id: "course_153_la_creation_d_adam_michel_ange_q5", question: "Que raconte l'ensemble du plafond de la Sixtine, dont La Création d'Adam n'est qu'un panneau ?", options: ["La Genèse", "La vie du Christ", "La mythologie romaine", "L'histoire de Rome antique"], correctIndex: 0, explanation: "Le plafond entier raconte la Genèse, et La Création d'Adam n'en est que le panneau le plus photographié."),
        QuizQuestion(id: "course_153_la_creation_d_adam_michel_ange_q6", question: "Qu'est-ce qui crée la tension visuelle centrale entre Dieu et Adam ?", options: ["L'espace qui sépare leurs deux index sans qu'ils se touchent", "Un rayon de lumière divine", "Un ange qui les sépare physiquement", "Un voile qui cache leurs mains"], correctIndex: 0, explanation: "L'espace entre les deux index crée la tension : Adam touche presque Dieu, mais l'écart reste."),
        QuizQuestion(id: "course_153_la_creation_d_adam_michel_ange_q7", question: "Comment les études d'anatomie de Michel-Ange influencent-elles sa peinture des corps ?", options: ["Elles donnent aux muscles une vérité rare, proche de la dissection", "Elles le poussent à peindre des corps toujours drapés", "Elles l'éloignent de la représentation du corps humain", "Elles n'ont aucune influence sur son style pictural"], correctIndex: 0, explanation: "Ses études d'anatomie, proches de la dissection, donnent aux muscles peints une vérité rare."),
        QuizQuestion(id: "course_153_la_creation_d_adam_michel_ange_q8", type: .trueFalse, question: "Vrai ou faux : la théorie qui voit dans le manteau de Dieu la forme d'un cerveau est aujourd'hui scientifiquement prouvée.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "Cette théorie du manteau en forme de cerveau reste une hypothèse moderne séduisante, mais non prouvée."),
        QuizQuestion(id: "course_153_la_creation_d_adam_michel_ange_q9", question: "Pourquoi le travail de Michel-Ange sur ce plafond est-il physiquement éprouvant ?", options: ["Il doit peindre allongé, le dos courbé, pendant des mois", "Il doit travailler la nuit à la bougie", "Il peint debout sur une échelle sans repos", "Il doit transporter seul les pigments depuis Florence"], correctIndex: 0, explanation: "Michel-Ange travaille allongé sous la voûte pendant des mois, et ses lettres témoignent de cette souffrance physique.")
    ]
        ),
        Course(
            id: "course_154_impression_soleil_levant_monet",
            title: "Impression, soleil levant, Monet",
            description: "«Impression, soleil levant» de Claude Monet (1872) est le tableau qui a donné son nom à l'impressionnisme - et par là à tout le mouvement d'avant-garde de la...",
            subject: .art,
            subcategory: "Cinéma, photo & architecture + œuvres iconiques",
            lessons: [
                LessonPage(id: "course_154_impression_soleil_levant_monet_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_154_impression_soleil_levant_monet_p1", title: "La capture de l'instant : le port du Havre en 1872", content: ""),
                LessonPage(id: "course_154_impression_soleil_levant_monet_p2", title: "Le scandale de 1874 et le baptême par l'insulte", content: ""),
                LessonPage(id: "course_154_impression_soleil_levant_monet_p3", title: "L'évolution du regard : de l'impression à l'abstraction", content: ""),
                LessonPage(id: "course_154_impression_soleil_levant_monet_p4", title: "Héritage scientifique et postérité d'une icône", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_154_impression_soleil_levant_monet_q1", question: "Où Monet peint-il la scène représentée dans Impression, soleil levant ?", options: ["Le port du Havre", "Le port de Marseille", "La Seine à Paris", "La baie de Naples"], correctIndex: 0, explanation: "Monet peint le port du Havre au petit matin vers 1872."),
        QuizQuestion(id: "course_154_impression_soleil_levant_monet_q2", question: "Qui, en se moquant du tableau en 1874, donne involontairement son nom à l'impressionnisme ?", options: ["Le critique Louis Leroy", "Le peintre Édouard Manet", "Le marchand Paul Durand-Ruel", "Le photographe Nadar"], correctIndex: 0, explanation: "Le critique Louis Leroy se moque du tableau en 1874 et baptise malgré lui l'impressionnisme."),
        QuizQuestion(id: "course_154_impression_soleil_levant_monet_q3", type: .trueFalse, question: "Vrai ou faux : le tableau est présenté au Salon officiel de peinture en 1874.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "Le tableau est exposé chez Nadar en 1874, hors du Salon officiel."),
        QuizQuestion(id: "course_154_impression_soleil_levant_monet_q4", question: "Qu'est-ce que Monet cherche avant tout à saisir dans ce tableau ?", options: ["La vibration lumineuse d'un instant, plus que le détail documentaire du port", "Une reconstitution historique précise du port", "Un portrait des ouvriers du chantier naval", "Une carte postale touristique du Havre"], correctIndex: 0, explanation: "L'essentiel n'est pas le Havre documentaire, mais la vibration orange dans la brume grise."),
        QuizQuestion(id: "course_154_impression_soleil_levant_monet_q5", type: .numericSlider, question: "En quelle année le tableau est-il exposé chez Nadar, provoquant le scandale qui donne son nom au mouvement ?", explanation: "Le tableau est exposé chez Nadar en 1874, où Louis Leroy ironise sur son titre.", correctValue: 1874, sliderMin: 1850, sliderMax: 1900, tolerance: 3, unit: ""),
        QuizQuestion(id: "course_154_impression_soleil_levant_monet_q6", question: "Qui soutient financièrement Monet quand le public français hésite encore devant sa peinture ?", options: ["Le marchand Paul Durand-Ruel", "Le pape Pie IX", "L'État français", "Le roi d'Angleterre"], correctIndex: 0, explanation: "Le marchand Paul Durand-Ruel soutient Monet quand le public français hésite encore."),
        QuizQuestion(id: "course_154_impression_soleil_levant_monet_q7", type: .trueFalse, question: "Vrai ou faux : en 2014, un astrophysicien a réussi à dater précisément la scène du tableau grâce aux marées et à la position du soleil.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "En 2014, un astrophysicien a daté la scène du 13 novembre 1872 vers 7 h 35, grâce aux marées et au soleil."),
        QuizQuestion(id: "course_154_impression_soleil_levant_monet_q8", question: "Que peint Monet en pleine industrialisation du port, loin d'une marine idéalisée ?", options: ["Des cheminées, des navires et du brouillard", "Des pêcheurs en costume traditionnel", "Des falaises désertes", "Des voiliers antiques"], correctIndex: 0, explanation: "Monet peint cheminées, navires et brouillard du port du Havre en pleine industrialisation.")
    ]
        ),
        Course(
            id: "course_155_nighthawks_hopper",
            title: "Que dit « Nighthawks » de Hopper sur la solitude urbaine ?",
            description: "«Nighthawks» (1942) d'Edward Hopper est le tableau américain le plus reproduit du XXe siècle : un comptoir de diner new-yorkais la nuit, quatre personnages i...",
            subject: .art,
            subcategory: "Cinéma, photo & architecture + œuvres iconiques",
            lessons: [
                LessonPage(id: "course_155_nighthawks_hopper_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_155_nighthawks_hopper_p1", title: "Edward Hopper : Peintre de l'absence", content: ""),
                LessonPage(id: "course_155_nighthawks_hopper_p2", title: "La géométrie de l'enfermement", content: ""),
                LessonPage(id: "course_155_nighthawks_hopper_p3", title: "Une icône de la culture populaire", content: ""),
                LessonPage(id: "course_155_nighthawks_hopper_p4", title: "L'héritage et la technique du voyeur", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_155_nighthawks_hopper_q1", question: "Quel événement historique précède de peu l'achèvement de Nighthawks en 1942 ?", options: ["L'attaque de Pearl Harbor", "Le débarquement de Normandie", "La fin de la Première Guerre mondiale", "La crise de 1929"], correctIndex: 0, explanation: "Le tableau est achevé peu après l'attaque de Pearl Harbor, alors que la nation entre en guerre."),
        QuizQuestion(id: "course_155_nighthawks_hopper_q2", question: "Que montre Hopper de l'Amérique en guerre, plutôt que des scènes de bataille ?", options: ["L'arrière-front émotionnel, fait d'insomnie et de silence", "Des soldats au combat", "Des usines d'armement en pleine activité", "Des défilés patriotiques"], correctIndex: 0, explanation: "Hopper montre l'arrière-front émotionnel : insomniaques, café brûlant, silence."),
        QuizQuestion(id: "course_155_nighthawks_hopper_q3", type: .trueFalse, question: "Vrai ou faux : le diner peint par Hopper possède une porte clairement visible qui ouvre sur la rue.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "Le diner n'a pas de porte visible, ce qui rend l'espace éclairé, exposé et isolé à la fois."),
        QuizQuestion(id: "course_155_nighthawks_hopper_q4", question: "De qui Hopper a-t-il été l'élève, avant de développer son style personnel ?", options: ["Robert Henri", "Pablo Picasso", "Claude Monet", "Salvador Dalí"], correctIndex: 0, explanation: "Hopper est l'élève de Robert Henri avant de peindre motels, stations-service et fenêtres avec sa clarté froide."),
        QuizQuestion(id: "course_155_nighthawks_hopper_q5", question: "Comment Hopper compose-t-il ses scènes, selon le cours ?", options: ["Comme des plateaux de cinéma, avec angles nets et personnages coupés les uns des autres", "Comme des fresques religieuses surchargées", "Comme des collages abstraits sans figuration", "Comme des caricatures politiques"], correctIndex: 0, explanation: "Hopper construit des scènes comme des plateaux de cinéma, avec angles nets et personnages coupés les uns des autres."),
        QuizQuestion(id: "course_155_nighthawks_hopper_q6", type: .trueFalse, question: "Vrai ou faux : Hopper s'est inspiré d'un restaurant réel de Greenwich Village pour peindre ce diner.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Hopper a dit s'être inspiré d'un restaurant de Greenwich Village, simplifié jusqu'à l'essentiel."),
        QuizQuestion(id: "course_155_nighthawks_hopper_q7", question: "Quels réalisateurs ont plus tard recyclé la lumière et la solitude de Nighthawks ?", options: ["Ridley Scott et Wim Wenders", "Alfred Hitchcock et Charlie Chaplin", "Steven Spielberg et George Lucas", "Federico Fellini et Ingmar Bergman"], correctIndex: 0, explanation: "Ridley Scott et Wim Wenders, entre autres, ont recyclé la lumière de néon et la solitude du tableau."),
        QuizQuestion(id: "course_155_nighthawks_hopper_q8", type: .numericSlider, question: "En quelle année Hopper achève-t-il Nighthawks ?", explanation: "Edward Hopper achève Nighthawks en 1942, peu après l'entrée en guerre des États-Unis.", correctValue: 1942, sliderMin: 1900, sliderMax: 1970, tolerance: 3, unit: "")
    ]
        ),
        Course(
            id: "course_156_les_demoiselles_d_avignon_picasso",
            title: "Les Demoiselles d'Avignon, Picasso",
            description: "«Les Demoiselles d'Avignon» (1907) est le tableau le plus radical et le plus révolutionnaire de l'histoire de l'art moderne : le coup de pistolet qui tue la...",
            subject: .art,
            subcategory: "Cinéma, photo & architecture + œuvres iconiques",
            lessons: [
                LessonPage(id: "course_156_les_demoiselles_d_avignon_picasso_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_156_les_demoiselles_d_avignon_picasso_p1", title: "L'élaboration d'une rupture : du récit à l'icône", content: ""),
                LessonPage(id: "course_156_les_demoiselles_d_avignon_picasso_p2", title: "Le choc des masques et la puissance de l'exorcisme", content: ""),
                LessonPage(id: "course_156_les_demoiselles_d_avignon_picasso_p3", title: "Un scandale au cœur de la modernité", content: ""),
                LessonPage(id: "course_156_les_demoiselles_d_avignon_picasso_p4", title: "La portée mémorielle et l'héritage universel", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_156_les_demoiselles_d_avignon_picasso_q1", question: "En quelle ville Picasso peint-il Les Demoiselles d'Avignon en 1907 ?", options: ["Paris (Montmartre)", "Barcelone", "Madrid", "Londres"], correctIndex: 0, explanation: "Picasso travaille au Bateau-Lavoir, à Montmartre, où il achève le tableau en 1907."),
        QuizQuestion(id: "course_156_les_demoiselles_d_avignon_picasso_q2", question: "D'où vient le titre Demoiselles d'Avignon ?", options: ["D'une rue de Barcelone liée à la prostitution", "D'un village du sud de la France", "Du nom du modèle principal", "D'une commande de la ville d'Avignon"], correctIndex: 0, explanation: "Le titre renvoie à une rue de Barcelone liée à la prostitution."),
        QuizQuestion(id: "course_156_les_demoiselles_d_avignon_picasso_q3", type: .trueFalse, question: "Vrai ou faux : le tableau représente des nus selon l'idéal classique grec, doux et harmonieux.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "Le nu n'est plus idéal grec : il est frontal et inquiétant, brisant la mimesis classique."),
        QuizQuestion(id: "course_156_les_demoiselles_d_avignon_picasso_q4", question: "Qu'est-ce qui inspire les visages masqués des deux figures de droite ?", options: ["Les arts premiers africains et ibériques", "La peinture vénitienne de la Renaissance", "Les icônes byzantines", "L'art japonais du ukiyo-e"], correctIndex: 0, explanation: "Les visages de droite s'inspirent des arts premiers africains et ibériques, dans une logique primitiviste."),
        QuizQuestion(id: "course_156_les_demoiselles_d_avignon_picasso_q5", type: .trueFalse, question: "Vrai ou faux : Picasso a peint ce tableau d'un seul jet, sans étude préparatoire.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "Des dizaines d'études précèdent la toile : Picasso hésite, corrige et durcit sa composition."),
        QuizQuestion(id: "course_156_les_demoiselles_d_avignon_picasso_q6", question: "Quel mouvement artistique ce tableau annonce-t-il par ses formes en facettes ?", options: ["Le cubisme analytique", "L'impressionnisme", "Le surréalisme", "Le romantisme"], correctIndex: 0, explanation: "Les facettes du tableau annoncent le cubisme analytique."),
        QuizQuestion(id: "course_156_les_demoiselles_d_avignon_picasso_q7", question: "Comment les proches de Picasso réagissent-ils en découvrant le tableau ?", options: ["Ils sont choqués", "Ils applaudissent immédiatement l'œuvre", "Ils l'ignorent totalement", "Ils la trouvent trop académique"], correctIndex: 0, explanation: "Même les proches de Picasso sont choqués, car la mimesis, l'imitation douce du réel, est morte."),
        QuizQuestion(id: "course_156_les_demoiselles_d_avignon_picasso_q8", question: "Quel peintre, d'abord stupéfait par l'œuvre, rejoint ensuite Picasso dans la déconstruction cubiste de l'espace ?", options: ["Georges Braque", "Henri Matisse", "Marc Chagall", "Fernand Léger"], correctIndex: 0, explanation: "Braque, d'abord stupéfait, rejoint bientôt Picasso dans la déconstruction cubiste de l'espace."),
        QuizQuestion(id: "course_156_les_demoiselles_d_avignon_picasso_q9", type: .numericSlider, question: "En quelle année Picasso achève-t-il Les Demoiselles d'Avignon ?", explanation: "Picasso achève le tableau en 1907, à Montmartre.", correctValue: 1907, sliderMin: 1880, sliderMax: 1930, tolerance: 3, unit: "")
    ]
        ),
        Course(
            id: "course_157_la_persistance_de_la_memoire_dali",
            title: "La Persistance de la mémoire, Dalí",
            description: "«La Persistance de la mémoire» (1931) de Salvador Dalí est le tableau surréaliste le plus célèbre : une vue de la baie de Port Lligat en Catalogne avec trois...",
            subject: .art,
            subcategory: "Cinéma, photo & architecture + œuvres iconiques",
            lessons: [
                LessonPage(id: "course_157_la_persistance_de_la_memoire_dali_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_157_la_persistance_de_la_memoire_dali_p1", title: "La genèse : entre fromage et paranoïa-critique", content: ""),
                LessonPage(id: "course_157_la_persistance_de_la_memoire_dali_p2", title: "La liquéfaction du temps : psychologie et physique", content: ""),
                LessonPage(id: "course_157_la_persistance_de_la_memoire_dali_p3", title: "L'énigme du visage central", content: ""),
                LessonPage(id: "course_157_la_persistance_de_la_memoire_dali_p4", title: "Un succès fulgurant et durable", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_157_la_persistance_de_la_memoire_dali_q1", question: "Où se situe le décor du tableau, inspiré d'un lieu réel où vivait Dalí ?", options: ["Le Cap de Creus, en Catalogne", "Le désert du Sahara", "Les Alpes suisses", "La Provence française"], correctIndex: 0, explanation: "Le décor rappelle le Cap de Creus et Port Lligat, en Catalogne, où Dalí vit avec Gala."),
        QuizQuestion(id: "course_157_la_persistance_de_la_memoire_dali_q2", question: "Que symbolisent les montres molles du tableau ?", options: ["Le temps intérieur, vécu, différent du temps mesuré par les horloges", "La précision scientifique du temps", "La richesse matérielle de Dalí", "Le passage des saisons"], correctIndex: 0, explanation: "Les montres illustrent le temps mou : le temps vécu n'est pas celui des horloges."),
        QuizQuestion(id: "course_157_la_persistance_de_la_memoire_dali_q3", type: .trueFalse, question: "Vrai ou faux : Dalí peint ces scènes impossibles avec une technique volontairement grossière et peu soignée.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "Dalí peint l'impossible avec un fini digne de la Renaissance, ce qui rend l'image crédible et troublante."),
        QuizQuestion(id: "course_157_la_persistance_de_la_memoire_dali_q4", question: "Comment Dalí décrit-il lui-même ce qu'il peint ?", options: ["Des « photographies de rêves »", "Des « cauchemars sans queue ni tête »", "Des « études scientifiques du temps »", "Des « hommages à la Renaissance italienne »"], correctIndex: 0, explanation: "Dalí affirme peindre des « photographies de rêves », mêlant décor réel et inconscient."),
        QuizQuestion(id: "course_157_la_persistance_de_la_memoire_dali_q5", type: .trueFalse, question: "Vrai ou faux : Dalí a prétendu s'être inspiré d'un camembert trop fait pour imaginer les montres molles.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Dalí a prétendu s'être inspiré d'un camembert trop fait, entre blague et méthode."),
        QuizQuestion(id: "course_157_la_persistance_de_la_memoire_dali_q6", question: "Quelle institution américaine acquiert le tableau, contribuant à sa célébrité mondiale ?", options: ["Le MoMA", "Le Metropolitan Museum", "La National Gallery", "Le Guggenheim"], correctIndex: 0, explanation: "L'œuvre est acquise par le MoMA, ce qui l'aide à entrer dans la culture populaire."),
        QuizQuestion(id: "course_157_la_persistance_de_la_memoire_dali_q7", question: "Avec qui Dalí vit-il à Port Lligat, en Catalogne, à l'époque du tableau ?", options: ["Gala", "Frida Kahlo", "Amanda Lear", "Coco Chanel"], correctIndex: 0, explanation: "Dalí vit alors avec Gala à Port Lligat, en Catalogne."),
        QuizQuestion(id: "course_157_la_persistance_de_la_memoire_dali_q8", type: .numericSlider, question: "En quelle année Dalí peint-il La Persistance de la mémoire ?", explanation: "Dalí peint le tableau en 1931.", correctValue: 1931, sliderMin: 1900, sliderMax: 1960, tolerance: 3, unit: "")
    ]
        ),
        Course(
            id: "course_158_la_tragedie_grecque_et_le_theatre_antiqu",
            title: "À quoi servait la tragédie grecque ?",
            description: "Le théâtre grec antique (Ve siècle av. J.-C.) est l'ancêtre direct de tout le théâtre occidental - cinéma inclus. Ses formes (tragédie, comédie), ses convent...",
            subject: .art,
            subcategory: "Cinéma, photo & architecture + œuvres iconiques",
            lessons: [
                LessonPage(id: "course_158_la_tragedie_grecque_et_le_theatre_antiqu_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_158_la_tragedie_grecque_et_le_theatre_antiqu_p1", title: "L'éclosion du théâtre : entre rite et politique", content: ""),
                LessonPage(id: "course_158_la_tragedie_grecque_et_le_theatre_antiqu_p2", title: "Conventions scéniques et mécanique de la tragédie", content: ""),
                LessonPage(id: "course_158_la_tragedie_grecque_et_le_theatre_antiqu_p3", title: "Le triumvirat tragique et la naissance de la psychologie", content: ""),
                LessonPage(id: "course_158_la_tragedie_grecque_et_le_theatre_antiqu_p4", title: "Postérité et héritage de l'espace théâtral", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_158_la_tragedie_grecque_et_le_theatre_antiqu_q1", question: "Qui finance la mise en scène des tragédies grecques, à travers la chorégie ?", options: ["Un citoyen riche", "L'État romain", "Le grand prêtre du temple", "Les acteurs eux-mêmes"], correctIndex: 0, explanation: "Un citoyen riche finance le spectacle : c'est la chorégie."),
        QuizQuestion(id: "course_158_la_tragedie_grecque_et_le_theatre_antiqu_q2", question: "Dans quel cadre religieux et civique la tragédie grecque prend-elle place ?", options: ["Les Dionysies, fêtes en l'honneur de Dionysos", "Les Jeux olympiques", "Les funérailles publiques", "Les mariages royaux"], correctIndex: 0, explanation: "Les Dionysies, fêtes de Dionysos, organisent les concours où naît la tragédie."),
        QuizQuestion(id: "course_158_la_tragedie_grecque_et_le_theatre_antiqu_q3", question: "Comment se nomme la démesure qui pousse le héros tragique vers sa chute ?", options: ["L'hubris", "La catharsis", "La chorégie", "La mimesis"], correctIndex: 0, explanation: "Le héros tragique cède souvent à l'hubris, la démesure qui défie l'ordre."),
        QuizQuestion(id: "course_158_la_tragedie_grecque_et_le_theatre_antiqu_q4", question: "Selon Aristote, quel effet la tragédie produit-elle sur le spectateur ?", options: ["La catharsis, une purification par la pitié et la terreur", "Un simple divertissement sans effet moral", "Un endormissement progressif", "Une colère durable contre la cité"], correctIndex: 0, explanation: "Selon Aristote, la tragédie provoque la catharsis, une purification par la pitié et la terreur."),
        QuizQuestion(id: "course_158_la_tragedie_grecque_et_le_theatre_antiqu_q5", type: .trueFalse, question: "Vrai ou faux : le public athénien découvre en général une intrigue totalement inconnue, sans connaître le mythe à l'avance.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "Le public connaît souvent le mythe : l'intérêt n'est pas le twist, mais la manière de le raconter."),
        QuizQuestion(id: "course_158_la_tragedie_grecque_et_le_theatre_antiqu_q6", question: "Quel dispositif scénique permettait de faire descendre un dieu par une grue pour dénouer l'intrigue ?", options: ["Le deus ex machina", "Le chœur", "La chorégie", "Le masque tragique"], correctIndex: 0, explanation: "Le deus ex machina faisait descendre un dieu par une grue pour dénouer l'intrigue."),
        QuizQuestion(id: "course_158_la_tragedie_grecque_et_le_theatre_antiqu_q7", question: "Que fait le chœur pendant la représentation ?", options: ["Il chante, danse et commente l'action", "Il reste immobile et silencieux", "Il remplace les acteurs principaux", "Il choisit le vainqueur du concours"], correctIndex: 0, explanation: "Le chœur chante, danse et commente l'action tout au long de la pièce."),
        QuizQuestion(id: "course_158_la_tragedie_grecque_et_le_theatre_antiqu_q8", type: .trueFalse, question: "Vrai ou faux : Eschyle, Sophocle et Euripide ont chacun apporté une évolution différente à la tragédie.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Eschyle ajoute des acteurs, Sophocle raffine la psychologie, Euripide trouble les certitudes.")
    ]
        ),
        Course(
            id: "course_159_le_theatre_de_shakespeare",
            title: "Pourquoi joue-t-on encore Shakespeare partout ?",
            description: "William Shakespeare (1564-1616) est le plus grand dramaturge de la littérature mondiale : ses 37 pièces forment le corpus littéraire le plus étudié, le plus...",
            subject: .art,
            subcategory: "Cinéma, photo & architecture + œuvres iconiques",
            lessons: [
                LessonPage(id: "course_159_le_theatre_de_shakespeare_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_159_le_theatre_de_shakespeare_p1", title: "L'écrin du Globe et les contraintes du plein air", content: ""),
                LessonPage(id: "course_159_le_theatre_de_shakespeare_p2", title: "Innovation linguistique et archétypes humains", content: ""),
                LessonPage(id: "course_159_le_theatre_de_shakespeare_p3", title: "La fixation du canon : l'acte de naissance du First Folio", content: ""),
                LessonPage(id: "course_159_le_theatre_de_shakespeare_p4", title: "Un héritage mondial par-delà les frontières et les arts", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_159_le_theatre_de_shakespeare_q1", question: "Pour quel public Shakespeare écrit-il principalement ses pièces ?", options: ["Le public populaire du théâtre londonien", "Les cours royales étrangères uniquement", "Les universités d'Oxford et Cambridge", "L'Église anglicane"], correctIndex: 0, explanation: "Shakespeare écrit pour la scène londonienne, non pour l'école, devant un public populaire."),
        QuizQuestion(id: "course_159_le_theatre_de_shakespeare_q2", question: "Comment s'appelle le théâtre à ciel ouvert où joue la troupe de Shakespeare ?", options: ["Le Globe Theatre", "Le Old Vic", "Le Royal Albert Hall", "Le Drury Lane"], correctIndex: 0, explanation: "Avec les Lord Chamberlain's Men, Shakespeare joue au Globe Theatre, cercle à ciel ouvert."),
        QuizQuestion(id: "course_159_le_theatre_de_shakespeare_q3", question: "Qui sont les groundlings au Globe Theatre ?", options: ["Les spectateurs les moins riches, qui restent debout près de la scène", "Les acteurs principaux de la troupe", "Les musiciens de l'orchestre", "Les censeurs royaux du théâtre"], correctIndex: 0, explanation: "Les groundlings paient peu et restent debout, près de la scène."),
        QuizQuestion(id: "course_159_le_theatre_de_shakespeare_q4", type: .trueFalse, question: "Vrai ou faux : Shakespeare écrit ses pièces en prose rimée, sans mètre régulier.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "Shakespeare écrit souvent en vers blanc, un pentamètre iambique sans rime."),
        QuizQuestion(id: "course_159_le_theatre_de_shakespeare_q5", question: "Grâce à quel recueil, publié après sa mort, plusieurs pièces de Shakespeare nous sont-elles parvenues ?", options: ["Le First Folio de 1623", "Les Sonnets de 1609", "Le Livre des rois", "L'Encyclopédie de Diderot"], correctIndex: 0, explanation: "Plusieurs pièces ne nous sont parvenues que grâce au First Folio de 1623, publié après sa mort."),
        QuizQuestion(id: "course_159_le_theatre_de_shakespeare_q6", question: "D'où Shakespeare tire-t-il souvent la matière de ses intrigues ?", options: ["De chroniques, nouvelles italiennes et pièces anciennes déjà existantes", "D'une pure invention personnelle sans aucune source", "De ses propres rêves, selon ses carnets", "De commandes du roi d'Angleterre"], correctIndex: 0, explanation: "Il recycle chroniques, nouvelles italiennes et pièces anciennes ; son originalité tient au langage et aux caractères."),
        QuizQuestion(id: "course_159_le_theatre_de_shakespeare_q7", type: .trueFalse, question: "Vrai ou faux : Shakespeare mêle souvent le comique et le tragique dans une même pièce, par exemple à travers le personnage du fou qui dit la vérité.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Comédies et tragédies se répondent chez Shakespeare : le fou dit la vérité, le roi devient fou."),
        QuizQuestion(id: "course_159_le_theatre_de_shakespeare_q8", type: .numericSlider, question: "En quelle année Shakespeare meurt-il ?", explanation: "William Shakespeare meurt en 1616.", correctValue: 1616, sliderMin: 1550, sliderMax: 1650, tolerance: 3, unit: "")
    ]
        ),
        Course(
            id: "course_160_la_liberte_de_la_presse_et_le_journalism",
            title: "Le photojournalisme peut-il changer le regard sur une guerre ?",
            description: "Le photojournalisme est né avec la guerre. Des images comme «La Petite Fille au napalm» ou le «Tank Man» de Tiananmen ont changé le cours de l'histoire. La p...",
            subject: .art,
            subcategory: "Cinéma, photo & architecture + œuvres iconiques",
            lessons: [
                LessonPage(id: "course_160_la_liberte_de_la_presse_et_le_journalism_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_160_la_liberte_de_la_presse_et_le_journalism_p1", title: "Le temps long de la guerre : de la Crimée à la Sécession", content: ""),
                LessonPage(id: "course_160_la_liberte_de_la_presse_et_le_journalism_p2", title: "L'ère Robert Capa : l'éthique de la proximité", content: ""),
                LessonPage(id: "course_160_la_liberte_de_la_presse_et_le_journalism_p3", title: "Le choc des images et le basculement de l'opinion", content: ""),
                LessonPage(id: "course_160_la_liberte_de_la_presse_et_le_journalism_p4", title: "Les nouveaux défis : entre surveillance et post-vérité", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_160_la_liberte_de_la_presse_et_le_journalism_q1", question: "Comment Henri Cartier-Bresson nomme-t-il sa théorie du bon moment, bon endroit, bon cadrage ?", options: ["L'instant décisif", "Le regard absolu", "La photographie totale", "L'œil du témoin"], correctIndex: 0, explanation: "Cartier-Bresson théorise l'« instant décisif » : être au bon endroit, au bon moment, avec le bon cadrage."),
        QuizQuestion(id: "course_160_la_liberte_de_la_presse_et_le_journalism_q2", question: "Qui meurt en couvrant la guerre d'Espagne aux côtés de Robert Capa ?", options: ["Gerda Taro", "Nick Ut", "Louis Leroy", "Paul Durand-Ruel"], correctIndex: 0, explanation: "Gerda Taro, aux côtés de Capa, meurt en couvrant la guerre d'Espagne."),
        QuizQuestion(id: "course_160_la_liberte_de_la_presse_et_le_journalism_q3", question: "Quelle photo de la guerre du Vietnam bouleverse l'opinion en montrant une fillette brûlée au napalm ?", options: ["La photo de Nick Ut", "La photo de Cartier-Bresson", "La photo de Gerda Taro", "La photo de Robert Capa"], correctIndex: 0, explanation: "La photo de Nick Ut montrant une fillette brûlée au napalm bouleverse l'opinion pendant la guerre du Vietnam."),
        QuizQuestion(id: "course_160_la_liberte_de_la_presse_et_le_journalism_q4", type: .trueFalse, question: "Vrai ou faux : selon le cours, la photo de Nick Ut a seule et immédiatement mis fin à la guerre du Vietnam.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "L'image ne met pas fin seule à la guerre, mais elle rend le coût humain impossible à nier."),
        QuizQuestion(id: "course_160_la_liberte_de_la_presse_et_le_journalism_q5", question: "Que révèle la manière dont les dictatures traitent la photographie de presse, selon le cours ?", options: ["Elles contrôlent le viseur, contrairement aux démocraties qui protègent en théorie la presse", "Elles encouragent une totale liberté des photographes", "Elles financent généreusement les agences photo indépendantes", "Elles n'ont aucun intérêt pour l'image"], correctIndex: 0, explanation: "Les grandes démocraties protègent théoriquement la presse, tandis que les dictatures contrôlent le viseur."),
        QuizQuestion(id: "course_160_la_liberte_de_la_presse_et_le_journalism_q6", type: .trueFalse, question: "Vrai ou faux : beaucoup de clichés aujourd'hui célèbres ont d'abord été censurés ou discutés avant de devenir des évidences historiques.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Beaucoup de clichés célèbres ont d'abord été censurés ou discutés avant de devenir évidences historiques."),
        QuizQuestion(id: "course_160_la_liberte_de_la_presse_et_le_journalism_q7", question: "À l'âge numérique, quelles pratiques s'imposent pour vérifier l'authenticité d'une photo de presse ?", options: ["L'analyse des métadonnées et la recherche d'image inversée", "La seule confiance dans la réputation du photographe", "L'interdiction totale de la photographie numérique", "La publication immédiate sans vérification"], correctIndex: 0, explanation: "À l'âge numérique, la vérification s'impose : métadonnées, recherche d'image inversée, contexte."),
        QuizQuestion(id: "course_160_la_liberte_de_la_presse_et_le_journalism_q8", question: "Que professionnalise l'apparition des magazines illustrés et des agences photo ?", options: ["Le métier de reporter-photographe", "Le métier de peintre officiel", "Le métier d'imprimeur uniquement", "Le métier de censeur d'État"], correctIndex: 0, explanation: "L'apparition des magazines illustrés et des agences photo professionnalise le métier de reporter-photographe.")
    ]
        ),
        Course(
            id: "course_161_la_naissance_des_dieux_grecs_cronos_zeus",
            title: "Du Chaos à Zeus : comment sont nés les dieux grecs ?",
            description: "Avant les dieux de l'Olympe, il y avait le Chaos. Et avant Zeus, son propre père dévorait ses enfants. La cosmogonie grecque est une histoire de violence, de...",
            subject: .mythologie,
            subcategory: "Grèce : les dieux",
            lessons: [
                LessonPage(id: "course_161_la_naissance_des_dieux_grecs_cronos_zeus_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_161_la_naissance_des_dieux_grecs_cronos_zeus_p1", title: "Le Chaos et l'émergence des puissances primordiales", content: ""),
                LessonPage(id: "course_161_la_naissance_des_dieux_grecs_cronos_zeus_p2", title: "L'ère de Cronos : la violence comme mode de gouvernement", content: ""),
                LessonPage(id: "course_161_la_naissance_des_dieux_grecs_cronos_zeus_p3", title: "L'avènement de Zeus et la structuration de l'ordre", content: ""),
                LessonPage(id: "course_161_la_naissance_des_dieux_grecs_cronos_zeus_p4", title: "L'héritage d'un système de pensée", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_161_la_naissance_des_dieux_grecs_cronos_zeus_q1", question: "Qui sépare le Ciel (Ouranos) de la Terre (Gaïa) en castrant son propre père ?", options: ["Cronos", "Zeus", "Poséidon", "Atlas"], correctIndex: 0, explanation: "Cronos, le plus jeune des Titans, utilise la faucille forgée par Gaïa pour castrer Ouranos et séparer le Ciel de la Terre."),
        QuizQuestion(id: "course_161_la_naissance_des_dieux_grecs_cronos_zeus_q2", type: .trueFalse, question: "Vrai ou faux : Cronos dévore ses propres enfants par peur d'être un jour détrôné par l'un d'eux.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Une prophétie annonce à Cronos qu'un de ses fils le détrônera : il dévore donc ses enfants dès leur naissance pour l'éviter."),
        QuizQuestion(id: "course_161_la_naissance_des_dieux_grecs_cronos_zeus_q3", question: "Comment Rhéa parvient-elle à sauver le bébé Zeus de son père Cronos ?", options: ["Elle fait avaler à Cronos une pierre emmaillotée à la place du bébé", "Elle envoie Zeus directement sur l'Olympe", "Elle transforme Zeus en aigle", "Elle demande l'aide d'Athéna"], correctIndex: 0, explanation: "Rhéa trompe Cronos avec une pierre enveloppée de linges, tandis que le vrai Zeus grandit en secret dans une grotte de Crète."),
        QuizQuestion(id: "course_161_la_naissance_des_dieux_grecs_cronos_zeus_q4", question: "Quelle arme les Cyclopes offrent-ils à Zeus pour vaincre les Titans ?", options: ["La foudre", "Le trident", "Une épée d'or", "Un bouclier magique"], correctIndex: 0, explanation: "Les Cyclopes forgent la foudre, l'arme décisive qui permet à Zeus de l'emporter lors de la Titanomachie."),
        QuizQuestion(id: "course_161_la_naissance_des_dieux_grecs_cronos_zeus_q5", type: .chronological, question: "Remets ces étapes de la mythologie grecque dans l'ordre chronologique.", explanation: "De ce vide originel à la victoire de Zeus, la mythologie grecque raconte une suite de crises et de prises de pouvoir familiales.", items: ["Le Chaos originel", "Gaïa et Ouranos engendrent les Titans", "Cronos devient roi en castrant son père", "Zeus vainc les Titans grâce à la foudre"]),
        QuizQuestion(id: "course_161_la_naissance_des_dieux_grecs_cronos_zeus_q6", question: "Comment naît la déesse Athéna ?", options: ["Zeus avale la déesse Métis, et Athéna sort tout armée de son crâne", "Elle naît de l'écume de la mer", "Elle est la fille de Cronos", "Elle naît du sang d'Ouranos"], correctIndex: 0, explanation: "Par peur d'un fils plus puissant que lui, Zeus avale son épouse Métis enceinte : Athéna naît alors tout armée, sortie de son crâne."),
        QuizQuestion(id: "course_161_la_naissance_des_dieux_grecs_cronos_zeus_q7", question: "Dans quel texte le poète Hésiode raconte-t-il la naissance des dieux grecs ?", options: ["La Théogonie", "L'Iliade", "Les Métamorphoses", "La République"], correctIndex: 0, explanation: "Hésiode raconte dans la Théogonie, au VIIIe siècle avant notre ère, comment le monde passe du Chaos à la cour de Zeus."),
        QuizQuestion(id: "course_161_la_naissance_des_dieux_grecs_cronos_zeus_q8", type: .trueFalse, question: "Vrai ou faux : le mot français « panique » vient du dieu Pan, dont le cri aurait semé une terreur soudaine.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Lors d'une guerre contre les Géants, le cri du dieu Pan aurait provoqué une terreur irrationnelle chez les ennemis, d'où le mot « panique ».")
    ]
        ),
        Course(
            id: "course_162_promethee_le_voleur_de_feu",
            title: "Pourquoi Prométhée a-t-il volé le feu aux dieux ?",
            description: "Prométhée est le Titan qui vola le feu aux dieux pour le donner aux hommes, et qui fut condamné à une torture éternelle pour ce geste. C'est l'un des mythes...",
            subject: .mythologie,
            subcategory: "Grèce : les dieux",
            lessons: [
                LessonPage(id: "course_162_promethee_le_voleur_de_feu_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_162_promethee_le_voleur_de_feu_p1", title: "La genèse de l'humanité et le partage inégal", content: ""),
                LessonPage(id: "course_162_promethee_le_voleur_de_feu_p2", title: "Le rapt du feu et la naissance de la raison", content: ""),
                LessonPage(id: "course_162_promethee_le_voleur_de_feu_p3", title: "Soumission divine et rédemption héroïque", content: ""),
                LessonPage(id: "course_162_promethee_le_voleur_de_feu_p4", title: "Héritage littéraire et modernité prométhéenne", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_162_promethee_le_voleur_de_feu_q1", question: "Qui est puni par Zeus pour avoir donné le feu aux hommes ?", options: ["Prométhée", "Épiméthée", "Héphaïstos", "Atlas"], correctIndex: 0, explanation: "Prométhée vole le feu de l'Olympe pour le donner aux hommes, un acte que Zeus ne pardonne pas."),
        QuizQuestion(id: "course_162_promethee_le_voleur_de_feu_q2", type: .trueFalse, question: "Vrai ou faux : lors du sacrifice à Mékoné, c'est Prométhée qui trompe Zeus en cachant la bonne viande sous une peau laide.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Prométhée dissimule la viande sous une peau peu appétissante et les os sous une graisse alléchante, poussant Zeus à choisir la mauvaise part."),
        QuizQuestion(id: "course_162_promethee_le_voleur_de_feu_q3", question: "Où Prométhée cache-t-il l'étincelle volée sur l'Olympe ?", options: ["Dans une tige de férule creuse", "Dans une amphore scellée", "Sous sa cape", "Dans une corne de chèvre"], correctIndex: 0, explanation: "Prométhée dérobe une étincelle et la cache dans une tige de férule, dont la moelle brûle très lentement."),
        QuizQuestion(id: "course_162_promethee_le_voleur_de_feu_q4", question: "Quel animal dévore chaque jour le foie de Prométhée enchaîné au Caucase ?", options: ["Un aigle", "Un vautour", "Un serpent", "Un lion"], correctIndex: 0, explanation: "Zeus condamne Prométhée à se faire dévorer le foie par un aigle chaque jour, sur le rocher du Caucase."),
        QuizQuestion(id: "course_162_promethee_le_voleur_de_feu_q5", type: .trueFalse, question: "Vrai ou faux : le foie de Prométhée repousse chaque nuit, rendant son supplice sans fin.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Chaque nuit l'organe renaît, si bien que le supplice recommence à l'aube, indéfiniment."),
        QuizQuestion(id: "course_162_promethee_le_voleur_de_feu_q6", question: "Quel héros délivre finalement Prométhée de ses chaînes ?", options: ["Héraclès", "Persée", "Thésée", "Jason"], correctIndex: 0, explanation: "Héraclès, fils de Zeus, abat l'aigle d'une flèche et libère Prométhée du Caucase."),
        QuizQuestion(id: "course_162_promethee_le_voleur_de_feu_q7", question: "Quel secret Prométhée révèle-t-il à Zeus en échange de sa liberté ?", options: ["Le nom de la nymphe dont le fils serait plus puissant que Zeus", "L'emplacement d'un trésor caché", "Le moyen de vaincre définitivement les Titans", "La formule pour redevenir mortel"], correctIndex: 0, explanation: "Prométhée révèle que la nymphe Thétis pourrait enfanter un fils plus puissant que Zeus, qui évite ainsi sa propre chute."),
        QuizQuestion(id: "course_162_promethee_le_voleur_de_feu_q8", type: .chronological, question: "Remets ces étapes du mythe de Prométhée dans l'ordre.", explanation: "De la ruse du sacrifice au vol du feu, puis au supplice et à la libération, le mythe de Prométhée suit une progression claire.", items: ["Prométhée trompe Zeus lors du sacrifice à Mékoné", "Prométhée dérobe le feu de l'Olympe pour les hommes", "Prométhée est enchaîné au Caucase et livré à l'aigle", "Héraclès délivre Prométhée de ses chaînes"])
    ]
        ),
        Course(
            id: "course_163_pandore_et_la_boite",
            title: "Que contenait vraiment la boîte de Pandore ?",
            description: "Pandore est la première femme de la mythologie grecque, créée par les dieux comme instrument de punition pour les hommes qui avaient reçu le feu de Prométhée...",
            subject: .mythologie,
            subcategory: "Grèce : les dieux",
            lessons: [
                LessonPage(id: "course_163_pandore_et_la_boite_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_163_pandore_et_la_boite_p1", title: "La naissance de la « première femme » ou le châtiment divin", content: ""),
                LessonPage(id: "course_163_pandore_et_la_boite_p2", title: "L'ouverture du pithos et la libération des fléaux", content: ""),
                LessonPage(id: "course_163_pandore_et_la_boite_p3", title: "Ambiguïté de l'Elpis : don ou malédiction ?", content: ""),
                LessonPage(id: "course_163_pandore_et_la_boite_p4", title: "Postérité : de la misogynie à la curiosité intellectuelle", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_163_pandore_et_la_boite_q1", question: "Qui fabrique Pandore sur ordre de Zeus ?", options: ["Héphaïstos", "Prométhée", "Hermès", "Zeus lui-même"], correctIndex: 0, explanation: "Zeus ordonne à Héphaïstos, dieu de la forge, de modeler Pandore dans l'argile et l'eau."),
        QuizQuestion(id: "course_163_pandore_et_la_boite_q2", question: "Quel dieu offre à Pandore la ruse et le mensonge ?", options: ["Hermès", "Athéna", "Aphrodite", "Apollon"], correctIndex: 0, explanation: "Hermès, messager des dieux, glisse la ruse et le mensonge parmi les dons de Pandore."),
        QuizQuestion(id: "course_163_pandore_et_la_boite_q3", type: .trueFalse, question: "Vrai ou faux : Épiméthée refuse le cadeau de Zeus, comme le lui avait recommandé son frère Prométhée.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "Malgré l'avertissement de Prométhée, Épiméthée tombe sous le charme de Pandore et l'accueille."),
        QuizQuestion(id: "course_163_pandore_et_la_boite_q4", question: "Que contenait réellement le récipient de Pandore, selon les textes grecs originaux ?", options: ["Un pithos, une grande jarre de stockage", "Un petit coffret en bois", "Un panier tressé", "Une amphore à vin"], correctIndex: 0, explanation: "Le récit original parle d'un « pithos », une grande jarre de stockage, et non d'une boîte."),
        QuizQuestion(id: "course_163_pandore_et_la_boite_q5", question: "D'où vient l'erreur qui a transformé la jarre de Pandore en « boîte » ?", options: ["Une confusion d'Érasme de Rotterdam au XVIe siècle", "Une erreur commise par Hésiode lui-même", "Une traduction anglaise du XIXe siècle", "Une invention tardive de Zeus"], correctIndex: 0, explanation: "En traduisant Hésiode, Érasme de Rotterdam confond « pithos » (jarre) et « pyxis » (petit coffret)."),
        QuizQuestion(id: "course_163_pandore_et_la_boite_q6", question: "Qu'est-ce qui reste seul au fond de la jarre, une fois tous les maux envolés ?", options: ["L'Espoir", "La Sagesse", "La Beauté", "La Vengeance"], correctIndex: 0, explanation: "Seule Elpis, l'Espoir, reste accrochée au fond de la jarre après la fuite des fléaux."),
        QuizQuestion(id: "course_163_pandore_et_la_boite_q7", type: .trueFalse, question: "Vrai ou faux : chez Hésiode, Pandore est présentée comme un cadeau bienveillant destiné à rendre les hommes heureux.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "Pandore est conçue comme un « beau mal », une punition destinée à frapper l'humanité, non comme un cadeau bienveillant."),
        QuizQuestion(id: "course_163_pandore_et_la_boite_q8", type: .chronological, question: "Remets ces étapes du mythe de Pandore dans l'ordre.", explanation: "De sa création à l'ouverture fatale de la jarre, le mythe de Pandore suit une progression bien précise.", items: ["Les dieux fabriquent Pandore sur ordre de Zeus", "Épiméthée accueille Pandore malgré l'avertissement de Prométhée", "Pandore soulève le couvercle de la jarre", "Seul l'Espoir reste enfermé au fond"])
    ]
        ),
        Course(
            id: "course_164_demeter_et_persephone_les_saisons",
            title: "Déméter et Perséphone : d'où viennent les saisons ?",
            description: "Le mythe de Déméter et Perséphone est l'explication mythologique des saisons, et l'une des histoires d'amour maternel les plus touchantes de la mythologie gr...",
            subject: .mythologie,
            subcategory: "Grèce : les dieux",
            lessons: [
                LessonPage(id: "course_164_demeter_et_persephone_les_saisons_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_164_demeter_et_persephone_les_saisons_p1", title: "Le rapt de Koré et la désolation de la terre", content: ""),
                LessonPage(id: "course_164_demeter_et_persephone_les_saisons_p2", title: "La ruse de la grenade et le partage du monde", content: ""),
                LessonPage(id: "course_164_demeter_et_persephone_les_saisons_p3", title: "Éleusis : l'espoir au cœur des ténèbres", content: ""),
                LessonPage(id: "course_164_demeter_et_persephone_les_saisons_p4", title: "Une allégorie universelle de la renaissance", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_164_demeter_et_persephone_les_saisons_q1", question: "Qui enlève Perséphone pour l'emmener aux Enfers ?", options: ["Hadès", "Zeus", "Poséidon", "Arès"], correctIndex: 0, explanation: "Hadès, roi du monde souterrain, surgit sur son char et emporte Perséphone avec l'accord secret de Zeus."),
        QuizQuestion(id: "course_164_demeter_et_persephone_les_saisons_q2", question: "Que fait Déméter en apprenant l'enlèvement de sa fille ?", options: ["Elle empêche la terre de produire, provoquant une famine", "Elle demande à Zeus de la tuer", "Elle se réfugie sur l'Olympe sans réagir", "Elle transforme Hadès en monstre"], correctIndex: 0, explanation: "Inconsolable, Déméter interdit à la terre de germer, ce qui provoque une famine menaçant les humains."),
        QuizQuestion(id: "course_164_demeter_et_persephone_les_saisons_q3", question: "Quel piège Hadès utilise-t-il pour garder Perséphone liée aux Enfers ?", options: ["Il lui fait manger des pépins de grenade", "Il lui offre une pomme empoisonnée", "Il lui donne un anneau magique", "Il lui fait boire une potion d'oubli"], correctIndex: 0, explanation: "Quiconque mange dans le royaume des morts lui appartient : Hadès offre des pépins de grenade à Perséphone avant son départ."),
        QuizQuestion(id: "course_164_demeter_et_persephone_les_saisons_q4", type: .trueFalse, question: "Vrai ou faux : à cause des pépins de grenade, Perséphone doit désormais passer une partie de chaque année aux Enfers.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Un compromis s'impose : Perséphone partage l'année entre Hadès et sa mère Déméter."),
        QuizQuestion(id: "course_164_demeter_et_persephone_les_saisons_q5", question: "Quel dieu Zeus envoie-t-il exiger le retour de Perséphone ?", options: ["Hermès", "Apollon", "Arès", "Dionysos"], correctIndex: 0, explanation: "Zeus envoie Hermès, messager des dieux, réclamer le retour de Perséphone auprès d'Hadès."),
        QuizQuestion(id: "course_164_demeter_et_persephone_les_saisons_q6", question: "Comment le mythe explique-t-il l'arrivée de l'automne et de l'hiver ?", options: ["Quand Perséphone redescend aux Enfers, Déméter retire sa grâce à la nature", "Quand Zeus se fâche contre les hommes", "Quand Hadès punit la terre par vengeance", "Quand Déméter part en voyage sur l'Olympe"], correctIndex: 0, explanation: "Le départ de Perséphone chez Hadès pousse Déméter à retirer sa grâce aux cultures : c'est l'automne et l'hiver."),
        QuizQuestion(id: "course_164_demeter_et_persephone_les_saisons_q7", question: "Que sont les Mystères d'Éleusis ?", options: ["Des rites secrets nés du passage de Déméter à Éleusis, promettant un espoir après la mort", "Un temple construit par Hadès pour Perséphone", "Une fête célébrant l'enlèvement de Perséphone", "Un tribunal jugeant les âmes des morts"], correctIndex: 0, explanation: "Lors de son errance, Déméter s'arrête à Éleusis, où naissent des rites secrets promettant aux initiés un sort meilleur dans l'au-delà."),
        QuizQuestion(id: "course_164_demeter_et_persephone_les_saisons_q8", type: .chronological, question: "Remets ces étapes du mythe de Déméter et Perséphone dans l'ordre.", explanation: "De l'enlèvement au partage de l'année, ce mythe explique l'alternance des saisons.", items: ["L'enlèvement de Perséphone par Hadès", "La famine provoquée par le chagrin de Déméter", "Perséphone mange des pépins de grenade aux Enfers", "Le partage de l'année entre Hadès et Déméter"])
    ]
        ),
        Course(
            id: "course_165_orphee_et_eurydice",
            title: "Orphée et Eurydice",
            description: "Le mythe d'Orphée et Eurydice est l'une des histoires d'amour les plus déchirantes de toute la mythologie : celle d'un musicien qui descend aux Enfers pour r...",
            subject: .mythologie,
            subcategory: "Grèce : les dieux",
            lessons: [
                LessonPage(id: "course_165_orphee_et_eurydice_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_165_orphee_et_eurydice_p1", title: "Orphée : l'harmonie comme puissance cosmique", content: ""),
                LessonPage(id: "course_165_orphee_et_eurydice_p2", title: "La catabase : charmer l'inacceptable", content: ""),
                LessonPage(id: "course_165_orphee_et_eurydice_p3", title: "Le regard interdit et la chute finale", content: ""),
                LessonPage(id: "course_165_orphee_et_eurydice_p4", title: "Héritage et portée symbolique", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_165_orphee_et_eurydice_q1", question: "Qui offre sa lyre à Orphée ?", options: ["Apollon", "Zeus", "Hermès", "Dionysos"], correctIndex: 0, explanation: "La lyre d'Orphée est un cadeau d'Apollon, dieu des arts."),
        QuizQuestion(id: "course_165_orphee_et_eurydice_q2", question: "Comment meurt Eurydice ?", options: ["Mordue par un serpent alors qu'elle fuit le berger Aristée", "Noyée dans un fleuve", "Foudroyée par Zeus", "Enlevée directement par Hadès"], correctIndex: 0, explanation: "Le jour des noces, Eurydice fuit le berger Aristée, marche sur un serpent et meurt du venin."),
        QuizQuestion(id: "course_165_orphee_et_eurydice_q3", type: .trueFalse, question: "Vrai ou faux : la musique d'Orphée parvient à endormir Cerbère et à fléchir Charon, le batelier des morts.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Sans arme, Orphée franchit les Enfers uniquement grâce à sa musique, qui endort Cerbère et attendrit Charon."),
        QuizQuestion(id: "course_165_orphee_et_eurydice_q4", question: "Quelle condition Hadès impose-t-il à Orphée pour laisser remonter Eurydice ?", options: ["Ne pas se retourner avant d'avoir atteint la lumière", "Ne jamais reparler à Eurydice", "Remonter en une seule nuit", "Offrir sa lyre en échange"], correctIndex: 0, explanation: "Hadès accepte le retour d'Eurydice à la condition qu'Orphée marche devant elle sans se retourner avant la lumière."),
        QuizQuestion(id: "course_165_orphee_et_eurydice_q5", type: .trueFalse, question: "Vrai ou faux : Orphée se retourne vers Eurydice avant d'être sorti des Enfers, ce qui la fait retourner définitivement dans le monde des morts.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Près de la sortie, le doute l'emporte : Orphée se retourne, et Eurydice est happée par les ténèbres pour toujours."),
        QuizQuestion(id: "course_165_orphee_et_eurydice_q6", question: "Comment meurt Orphée à la fin du mythe ?", options: ["Déchiré par les Ménades, prêtresses de Dionysos", "Dévoré par Cerbère", "Foudroyé par Zeus", "Noyé dans le Styx"], correctIndex: 0, explanation: "Le refus d'Orphée de tout nouvel amour provoque la fureur des Ménades, qui le déchirent."),
        QuizQuestion(id: "course_165_orphee_et_eurydice_q7", question: "Quel courant religieux naît de la mort d'Orphée ?", options: ["L'Orphisme", "Le Stoïcisme", "Les Mystères d'Éleusis", "Le Pythagorisme"], correctIndex: 0, explanation: "De la mort d'Orphée naît l'Orphisme, courant religieux promettant le salut de l'âme par des rites de purification."),
        QuizQuestion(id: "course_165_orphee_et_eurydice_q8", type: .chronological, question: "Remets ces étapes du mythe d'Orphée et Eurydice dans l'ordre.", explanation: "Du mariage à la perte définitive d'Eurydice, ce mythe suit une trame tragique et précise.", items: ["Orphée épouse la nymphe Eurydice", "Eurydice meurt mordue par un serpent", "Orphée charme les Enfers avec sa musique pour la ramener", "Orphée se retourne et perd Eurydice pour toujours"])
    ]
        ),
        Course(
            id: "course_166_narcisse_et_echo",
            title: "D'où vient le mythe de Narcisse ?",
            description: "Le mythe de Narcisse et Écho est l'une des plus belles histoires de la mythologie grecque sur l'amour impossible. C'est la source directe du mot «narcissisme...",
            subject: .mythologie,
            subcategory: "Grèce : les dieux",
            lessons: [
                LessonPage(id: "course_166_narcisse_et_echo_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_166_narcisse_et_echo_p1", title: "Écho : la voix volée et le poids du silence", content: ""),
                LessonPage(id: "course_166_narcisse_et_echo_p2", title: "L'orgueil de Narcisse et l'échec de la rencontre", content: ""),
                LessonPage(id: "course_166_narcisse_et_echo_p3", title: "La source de l'illusion et le châtiment divin", content: ""),
                LessonPage(id: "course_166_narcisse_et_echo_p4", title: "Postérité : de la fleur aux profondeurs du Moi", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_166_narcisse_et_echo_q1", question: "Pourquoi Héra punit-elle la nymphe Écho ?", options: ["Elle avait aidé Zeus à cacher ses infidélités en la distrayant par de longues conversations", "Elle avait insulté Héra publiquement", "Elle avait volé un objet sacré sur l'Olympe", "Elle avait refusé d'épouser un dieu"], correctIndex: 0, explanation: "Écho retenait Héra par d'interminables conversations pendant que Zeus rejoignait d'autres nymphes."),
        QuizQuestion(id: "course_166_narcisse_et_echo_q2", question: "Quelle punition Héra infoge-t-elle à Écho ?", options: ["Elle ne peut plus que répéter les derniers mots des autres", "Elle perd totalement la voix", "Elle se transforme immédiatement en pierre", "Elle est bannie de la forêt"], correctIndex: 0, explanation: "Écho ne peut plus commencer une phrase : elle ne peut que répéter les derniers mots d'autrui."),
        QuizQuestion(id: "course_166_narcisse_et_echo_q3", question: "Comment Narcisse réagit-il quand Écho tente de l'étreindre ?", options: ["Il la rejette avec mépris", "Il tombe immédiatement amoureux d'elle", "Il la transforme en fleur", "Il fuit sans un mot"], correctIndex: 0, explanation: "Quand Écho s'approche pour l'étreindre, Narcisse la rejette avec mépris."),
        QuizQuestion(id: "course_166_narcisse_et_echo_q4", type: .trueFalse, question: "Vrai ou faux : après le rejet de Narcisse, le corps d'Écho se dessèche jusqu'à ne laisser qu'une voix.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Humiliée, Écho se retire dans les grottes, cesse de manger et son corps se dessèche jusqu'à ne laisser qu'une voix errante."),
        QuizQuestion(id: "course_166_narcisse_et_echo_q5", question: "Quelle déesse est priée de punir Narcisse pour sa cruauté ?", options: ["Némésis", "Aphrodite", "Athéna", "Héra"], correctIndex: 0, explanation: "Une victime de Narcisse prie Némésis, déesse de la juste vengeance, pour qu'il subisse un amour impossible."),
        QuizQuestion(id: "course_166_narcisse_et_echo_q6", question: "De quoi Narcisse tombe-t-il amoureux au bord d'une source ?", options: ["De son propre reflet", "D'une nymphe des eaux", "D'Écho enfin réapparue", "D'un esprit invisible"], correctIndex: 0, explanation: "Narcisse se penche sur une source, découvre son visage et en tombe amoureux, croyant voir un esprit des eaux."),
        QuizQuestion(id: "course_166_narcisse_et_echo_q7", type: .trueFalse, question: "Vrai ou faux : le devin Tirésias avait prédit que Narcisse vivrait longtemps s'il ne se connaissait jamais lui-même.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Tirésias avait prévenu la mère de Narcisse : « Il vivra vieux s'il ne se connaît pas »."),
        QuizQuestion(id: "course_166_narcisse_et_echo_q8", question: "Qu'est-ce qui naît à la place du corps de Narcisse après sa mort ?", options: ["Une fleur, le narcisse", "Une source nouvelle", "Un rocher", "Un arbre"], correctIndex: 0, explanation: "À la place du corps disparu de Narcisse pousse une fleur au cœur jaune et aux pétales blancs, le narcisse.")
    ]
        ),
    ]
}
