import Foundation

// GENERATED by scripts/split_course_data.py from Services/CourseData.swift.
// Do not edit: change CourseData.swift and rerun the script.
nonisolated extension CourseData {
    static let chunk10: [Course] = [
        Course(
            id: "course_137_la_naissance_du_rock_n_roll",
            title: "La naissance du rock'n'roll",
            description: "Le rock'n'roll naît au milieu des années 1950 aux États-Unis, à la confluence du blues noir, du country blanc et du gospel. Il change la musique populaire, l...",
            subject: .art,
            subcategory: "Musique",
            lessons: [
                LessonPage(id: "course_137_la_naissance_du_rock_n_roll_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_137_la_naissance_du_rock_n_roll_p1", title: "La genèse : une collision de mondes sonores", content: ""),
                LessonPage(id: "course_137_la_naissance_du_rock_n_roll_p2", title: "Les architectes du son : Presley, Berry et Richard", content: ""),
                LessonPage(id: "course_137_la_naissance_du_rock_n_roll_p3", title: "Le rock comme terrain de lutte raciale", content: ""),
                LessonPage(id: "course_137_la_naissance_du_rock_n_roll_p4", title: "Postérité et révolution culturelle mondiale", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_137_la_naissance_du_rock_n_roll_q1", question: "Quels trois styles musicaux fusionnent pour donner naissance au rock'n'roll dans les années 1950 ?", options: ["Le blues, la country et le gospel", "Le jazz, l'opéra et la musique classique", "Le reggae, la salsa et le blues", "La musique baroque et le folk"], correctIndex: 0, explanation: "Le rock'n'roll fusionne des musiques longtemps séparées par les barrières raciales : blues, country et gospel."),
        QuizQuestion(id: "course_137_la_naissance_du_rock_n_roll_q2", question: "Chez quel producteur Elvis Presley enregistre-t-il That's All Right en 1954 ?", options: ["Sam Phillips, à Memphis", "Berry Gordy, à Détroit", "Sam Cooke, à Chicago", "Leonard Chess, à New York"], correctIndex: 0, explanation: "C'est chez le producteur Sam Phillips, à Memphis, qu'Elvis enregistre son premier titre marquant."),
        QuizQuestion(id: "course_137_la_naissance_du_rock_n_roll_q3", question: "Quelle innovation musicale Chuck Berry apporte-t-il au rock'n'roll ?", options: ["Le riff de guitare répété", "Le scratching", "La grille en douze mesures", "Le beatboxing"], correctIndex: 0, explanation: "Chuck Berry impose le riff, motif de guitare répété qui devient la colonne vertébrale du morceau."),
        QuizQuestion(id: "course_137_la_naissance_du_rock_n_roll_q4", type: .trueFalse, question: "Vrai ou faux : en 1956, les caméras de The Ed Sullivan Show filment Elvis Presley uniquement au-dessus de la taille, ses déhanchements étant jugés trop scandaleux.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Les déhanchements d'Elvis choquent tant l'Amérique puritaine que l'émission le cadre volontairement au-dessus de la taille."),
        QuizQuestion(id: "course_137_la_naissance_du_rock_n_roll_q5", question: "Qu'est-ce qu'une cover dans l'industrie musicale des années 1950, selon le cours ?", options: ["Une version blanche édulcorée d'un hit noir, mieux promue à la radio", "Une reprise fidèle jouée en concert", "Un remix électronique d'un titre ancien", "Une traduction française d'un titre américain"], correctIndex: 0, explanation: "Les covers permettent à des versions blanches, comme Tutti Frutti par Pat Boone, de mieux vendre que les originaux noirs."),
        QuizQuestion(id: "course_137_la_naissance_du_rock_n_roll_q6", question: "Quel style musical inspire l'énergie brute et le cri de Little Richard au piano ?", options: ["Le gospel", "Le classique", "Le jazz cool", "Le blues acoustique seul"], correctIndex: 0, explanation: "Little Richard hérite du gospel une ferveur et une énergie qu'il transpose au piano debout."),
        QuizQuestion(id: "course_137_la_naissance_du_rock_n_roll_q7", type: .numericSlider, question: "En quelle année Elvis Presley enregistre-t-il That's All Right chez Sam Phillips ?", explanation: "En 1954, cet enregistrement chez Sam Phillips marque le véritable coup d'envoi du rock'n'roll.", correctValue: 1954, sliderMin: 1945, sliderMax: 1965, tolerance: 1, unit: ""),
        QuizQuestion(id: "course_137_la_naissance_du_rock_n_roll_q8", type: .chronological, question: "Remets ces étapes de la naissance du rock'n'roll dans l'ordre chronologique.", explanation: "De l'enregistrement d'Elvis en 1954 à la British Invasion des années 1960, le rock'n'roll se construit puis rayonne mondialement.", items: ["Elvis Presley enregistre That's All Right chez Sam Phillips", "Chuck Berry et Little Richard imposent riff et énergie brute", "Elvis choque l'Amérique au Ed Sullivan Show", "Les Beatles et les Rolling Stones lancent la British Invasion"]),
        QuizQuestion(id: "course_137_la_naissance_du_rock_n_roll_q9", type: .trueFalse, question: "Vrai ou faux : c'est le DJ Alan Freed qui popularise l'expression rock'n'roll pour désigner ce nouveau genre musical.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Le DJ Alan Freed popularise ce terme, auparavant utilisé dans le blues pour désigner autre chose.")
    ]
        ),
        Course(
            id: "course_138_bach_et_la_musique_baroque",
            title: "Bach et la musique baroque",
            description: "Johann Sebastian Bach (1685-1750) est considéré par beaucoup comme le plus grand compositeur de l'histoire occidentale. Maître de la fugue et du contrepoint,...",
            subject: .art,
            subcategory: "Musique",
            lessons: [
                LessonPage(id: "course_138_bach_et_la_musique_baroque_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_138_bach_et_la_musique_baroque_p1", title: "L'esthétique baroque et les fonctions de la musique", content: ""),
                LessonPage(id: "course_138_bach_et_la_musique_baroque_p2", title: "Le labeur d'un cantor : l'épopée de Leipzig", content: ""),
                LessonPage(id: "course_138_bach_et_la_musique_baroque_p3", title: "La cathédrale sonore : Tempérament et redécouverte", content: ""),
                LessonPage(id: "course_138_bach_et_la_musique_baroque_p4", title: "L'héritage universel et la symbolique bakhienne", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_138_bach_et_la_musique_baroque_q1", question: "Dans quelle ville Bach naît-il en 1685 ?", options: ["Eisenach", "Leipzig", "Vienne", "Hambourg"], correctIndex: 0, explanation: "Johann Sebastian Bach naît à Eisenach en 1685, dans une dynastie de musiciens."),
        QuizQuestion(id: "course_138_bach_et_la_musique_baroque_q2", question: "Quel poste Bach occupe-t-il à partir de 1723 à Leipzig ?", options: ["Cantor de l'église Saint-Thomas", "Organiste de la cour impériale", "Chef d'orchestre de l'opéra", "Maître de chapelle du roi de France"], correctIndex: 0, explanation: "Bach devient en 1723 cantor de l'église Saint-Thomas de Leipzig, une charge écrasante."),
        QuizQuestion(id: "course_138_bach_et_la_musique_baroque_q3", type: .trueFalse, question: "Vrai ou faux : en 1717, Bach passe un mois en prison à Weimar pour avoir trop insisté pour démissionner.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Le duc de Weimar refuse de laisser partir Bach pour Köthen, ce qui lui coûte un mois de détention."),
        QuizQuestion(id: "course_138_bach_et_la_musique_baroque_q4", type: .numericSlider, question: "Environ combien de cantates Bach a-t-il composées au cours de sa vie ?", explanation: "On estime à environ 300 le nombre de cantates composées par Bach, dont quelque 200 nous sont parvenues.", correctValue: 300, sliderMin: 100, sliderMax: 500, tolerance: 30, unit: "cantates"),
        QuizQuestion(id: "course_138_bach_et_la_musique_baroque_q5", question: "Que prouve Le Clavier bien tempéré grâce au tempérament égal ?", options: ["Qu'un clavier peut jouer dans toutes les tonalités", "Que l'orgue est supérieur au piano", "Que la fugue est un genre mineur", "Que la musique sacrée doit rester simple"], correctIndex: 0, explanation: "Grâce au tempérament égal, Bach démontre qu'un même clavier peut jouer dans toutes les tonalités."),
        QuizQuestion(id: "course_138_bach_et_la_musique_baroque_q6", type: .trueFalse, question: "Vrai ou faux : à sa mort, la musique de Bach reste immédiatement très populaire et continue d'être largement jouée.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "À sa mort, la mode préfère le style galant, plus léger, et Bach paraît alors désuet aux yeux de son époque."),
        QuizQuestion(id: "course_138_bach_et_la_musique_baroque_q7", question: "Qui redonne une notoriété majeure à Bach en 1829 en dirigeant la Passion selon Saint Matthieu à Berlin ?", options: ["Felix Mendelssohn", "Johannes Brahms", "Franz Liszt", "Robert Schumann"], correctIndex: 0, explanation: "Le jeune Felix Mendelssohn lance en 1829 la Renaissance Bach en dirigeant la Passion selon Saint Matthieu."),
        QuizQuestion(id: "course_138_bach_et_la_musique_baroque_q8", question: "Que signifie l'inscription SDG que Bach ajoute souvent à ses partitions ?", options: ["Soli Deo Gloria, à Dieu seul la gloire", "Sic Deus Gloriae, une formule de prière", "Son Divin Génie, un surnom donné par ses élèves", "Studio de Grande Gloire, le nom de son atelier"], correctIndex: 0, explanation: "Fervent luthérien, Bach signe souvent ses œuvres SDG, pour Soli Deo Gloria."),
        QuizQuestion(id: "course_138_bach_et_la_musique_baroque_q9", type: .chronological, question: "Remets ces jalons de la vie et de l'héritage de Bach dans l'ordre chronologique.", explanation: "De 1723 à 1977, Bach passe de cantor méconnu à ambassadeur sonore de l'humanité vers l'espace.", items: ["Bach devient cantor de l'église Saint-Thomas à Leipzig", "Il achève l'ensemble du Clavier bien tempéré", "Mendelssohn dirige la Passion selon Saint Matthieu à Berlin", "La NASA embarque ses œuvres à bord des sondes Voyager"])
    ]
        ),
        Course(
            id: "course_139_la_naissance_du_jazz_americain",
            title: "Pourquoi le jazz est-il né à La Nouvelle-Orléans ?",
            description: "Le jazz naît à la Nouvelle-Orléans à la fin du XIXe siècle, carrefour de la musique africaine, des spirituals noirs, du blues et de l'harmonie européenne. C'...",
            subject: .art,
            subcategory: "Musique",
            lessons: [
                LessonPage(id: "course_139_la_naissance_du_jazz_americain_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_139_la_naissance_du_jazz_americain_p1", title: "Le creuset cosmopolite de la Louisiane", content: ""),
                LessonPage(id: "course_139_la_naissance_du_jazz_americain_p2", title: "L'architecture d'un genre révolutionnaire", content: ""),
                LessonPage(id: "course_139_la_naissance_du_jazz_americain_p3", title: "L'âge d'or et l'ascension artistique", content: ""),
                LessonPage(id: "course_139_la_naissance_du_jazz_americain_p4", title: "Héritage et mutations contemporaines", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_139_la_naissance_du_jazz_americain_q1", question: "Dans quelle ville américaine le jazz naît-il à la fin du XIXe siècle ?", options: ["La Nouvelle-Orléans", "Chicago", "New York", "Memphis"], correctIndex: 0, explanation: "Port de Louisiane et carrefour de cultures, La Nouvelle-Orléans est le laboratoire sonore où naît le jazz."),
        QuizQuestion(id: "course_139_la_naissance_du_jazz_americain_q2", question: "Qu'est-ce que Congo Square, mentionné comme un lieu clé de la naissance du jazz ?", options: ["Le seul lieu où les populations noires pouvaient se réunir le dimanche", "Un club de jazz de Harlem", "Un studio d'enregistrement de La Nouvelle-Orléans", "Une école de musique fondée par Buddy Bolden"], correctIndex: 0, explanation: "À Congo Square, seul lieu offrant ce droit de réunion dominical, tambours et polyrythmies africaines survivent."),
        QuizQuestion(id: "course_139_la_naissance_du_jazz_americain_q3", type: .trueFalse, question: "Vrai ou faux : le pionnier du jazz Buddy Bolden a laissé de nombreux enregistrements de son cornet.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "Buddy Bolden n'a jamais été enregistré : sa légende repose uniquement sur les témoignages de ceux qui l'ont entendu."),
        QuizQuestion(id: "course_139_la_naissance_du_jazz_americain_q4", question: "Qu'apporte l'improvisation, présentée comme la rupture majeure du jazz avec la musique européenne ?", options: ["Le musicien compose en temps réel sur une grille, plutôt que de suivre une partition figée", "Le musicien joue toujours la même partition à l'identique", "L'orchestre remplace systématiquement le soliste", "La danse devient plus importante que la musique"], correctIndex: 0, explanation: "Avec l'improvisation, la partition n'est plus une loi mais une grille sur laquelle le musicien compose en temps réel."),
        QuizQuestion(id: "course_139_la_naissance_du_jazz_americain_q5", question: "Quel musicien impose le soliste virtuose au centre du jazz après la Grande Migration vers Chicago et New York ?", options: ["Louis Armstrong", "Duke Ellington", "Charlie Parker", "Miles Davis"], correctIndex: 0, explanation: "Louis Armstrong place le soliste virtuose au centre du jazz lors de son essor à Chicago et New York."),
        QuizQuestion(id: "course_139_la_naissance_du_jazz_americain_q6", question: "Quel style, inventé par Charlie Parker après 1945, privilégie tempos rapides et harmonies complexes ?", options: ["Le bebop", "Le swing", "Le free jazz", "Le ragtime"], correctIndex: 0, explanation: "Charlie Parker invente le bebop, musique d'écoute aux tempos rapides et aux harmonies complexes."),
        QuizQuestion(id: "course_139_la_naissance_du_jazz_americain_q7", type: .numericSlider, question: "En quelle année Miles Davis publie-t-il Kind of Blue, encore aujourd'hui le disque de jazz le plus vendu au monde ?", explanation: "Kind of Blue, sorti en 1959, invente le jazz modal en ralentissant les changements d'accords.", correctValue: 1959, sliderMin: 1940, sliderMax: 1975, tolerance: 2, unit: ""),
        QuizQuestion(id: "course_139_la_naissance_du_jazz_americain_q8", type: .chronological, question: "Remets ces étapes de l'histoire du jazz dans l'ordre chronologique.", explanation: "De Congo Square à Kind of Blue, le jazz traverse près d'un siècle d'inventions successives.", items: ["Le jazz émerge à La Nouvelle-Orléans autour de Congo Square et des brass bands", "Louis Armstrong impose le soliste virtuose à Chicago et New York", "Charlie Parker invente le bebop", "Miles Davis publie Kind of Blue et le jazz modal"]),
        QuizQuestion(id: "course_139_la_naissance_du_jazz_americain_q9", type: .trueFalse, question: "Vrai ou faux : le club new-yorkais Birdland tire son nom du surnom de Charlie Parker, Bird.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Le club Birdland est baptisé en hommage à Charlie Parker, surnommé Bird.")
    ]
        ),
        Course(
            id: "course_140_le_blues_racines_de_toute_la_musique_mod",
            title: "Le blues est-il la racine de la musique moderne ?",
            description: "Le blues est né dans les champs de coton du Mississippi à la fin du XIXe siècle : musique de la souffrance et de la résistance des Africains-Américains. Tout...",
            subject: .art,
            subcategory: "Musique",
            lessons: [
                LessonPage(id: "course_140_le_blues_racines_de_toute_la_musique_mod_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_140_le_blues_racines_de_toute_la_musique_mod_p1", title: "Les origines : travail, souffrance et résistance", content: ""),
                LessonPage(id: "course_140_le_blues_racines_de_toute_la_musique_mod_p2", title: "Robert Johnson et le mythe du Delta", content: ""),
                LessonPage(id: "course_140_le_blues_racines_de_toute_la_musique_mod_p3", title: "L'exode vers le Nord : le Blues électrique", content: ""),
                LessonPage(id: "course_140_le_blues_racines_de_toute_la_musique_mod_p4", title: "Héritage et influence sur la modernité", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_140_le_blues_racines_de_toute_la_musique_mod_q1", question: "Dans quelle région naît le blues à la fin du XIXe siècle ?", options: ["Le Deep South, dans les champs de coton du Mississippi", "Les villes portuaires de Louisiane uniquement", "Le Nord industriel des États-Unis", "Les plaines du Texas"], correctIndex: 0, explanation: "Le blues naît dans le dénuement des champs de coton du Mississippi, dans le Deep South."),
        QuizQuestion(id: "course_140_le_blues_racines_de_toute_la_musique_mod_q2", question: "Quelle innovation musicale majeure invente le blues, reprise ensuite par le jazz et le rock ?", options: ["La structure en douze mesures", "La symphonie en quatre mouvements", "Le rap a cappella", "L'opéra populaire"], correctIndex: 0, explanation: "La structure en douze mesures, grille de trois accords, devient le canevas de l'improvisation dans tout le blues."),
        QuizQuestion(id: "course_140_le_blues_racines_de_toute_la_musique_mod_q3", question: "Que désigne le bottleneck utilisé par les guitaristes de blues ?", options: ["Un tube de verre ou de métal glissé sur les cordes", "Un type de médiator en bois", "Une pédale d'effet électrique", "Un accordage particulier de la basse"], correctIndex: 0, explanation: "Le bottleneck, glissé sur les cordes de la guitare, fait dialoguer l'instrument avec la voix du chanteur."),
        QuizQuestion(id: "course_140_le_blues_racines_de_toute_la_musique_mod_q4", type: .trueFalse, question: "Vrai ou faux : Robert Johnson a laissé des centaines d'enregistrements, ce qui explique sa grande influence.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "Robert Johnson n'a laissé que 29 enregistrements, mais leur influence reste immense."),
        QuizQuestion(id: "course_140_le_blues_racines_de_toute_la_musique_mod_q5", question: "Que raconte la légende autour de Robert Johnson à un carrefour ?", options: ["Il aurait vendu son âme au diable pour maîtriser la guitare", "Il aurait rencontré son épouse", "Il aurait composé Sweet Home Chicago en une nuit", "Il aurait été découvert par un producteur new-yorkais"], correctIndex: 0, explanation: "La légende du crossroads dit que Johnson aurait vendu son âme au diable en échange de sa maîtrise de la guitare."),
        QuizQuestion(id: "course_140_le_blues_racines_de_toute_la_musique_mod_q6", question: "Dans quelle ville le blues devient-il électrique dans les années 1940, porté par Muddy Waters ?", options: ["Chicago", "La Nouvelle-Orléans", "Memphis", "Détroit"], correctIndex: 0, explanation: "À Chicago, le blues s'électrifie pour couvrir le bruit des usines, avec Muddy Waters et Howlin' Wolf."),
        QuizQuestion(id: "course_140_le_blues_racines_de_toute_la_musique_mod_q7", type: .trueFalse, question: "Vrai ou faux : le nom du groupe britannique les Rolling Stones est tiré d'un titre de Muddy Waters.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Les Rolling Stones tirent leur nom d'un titre de Muddy Waters, qu'ils contribuent à faire connaître au public blanc."),
        QuizQuestion(id: "course_140_le_blues_racines_de_toute_la_musique_mod_q8", type: .numericSlider, question: "Vers quelle année le blues devient-il électrique à Chicago, porté par Muddy Waters ?", explanation: "C'est dans les années 1940 que le blues rural du Delta devient électrique à Chicago.", correctValue: 1945, sliderMin: 1900, sliderMax: 1980, tolerance: 5, unit: ""),
        QuizQuestion(id: "course_140_le_blues_racines_de_toute_la_musique_mod_q9", type: .chronological, question: "Remets ces étapes de l'histoire du blues dans l'ordre chronologique.", explanation: "Du Deep South rural à l'exportation britannique, le blues traverse près d'un siècle de transformations.", items: ["Le blues naît dans les champs de coton du Deep South avec hollers et spirituals", "Robert Johnson enregistre ses titres dans le Delta du Mississippi", "Le blues s'électrifie à Chicago avec Muddy Waters", "Les Rolling Stones et Led Zeppelin réexportent le blues vers le grand public"])
    ]
        ),
        Course(
            id: "course_141_la_naissance_de_la_photographie",
            title: "Qui a inventé la photographie ?",
            description: "La photographie naît en 1839 : une invention quasi simultanée de plusieurs pionniers. En moins d'un siècle, elle révolutionne la représentation du monde, lib...",
            subject: .art,
            subcategory: "Cinéma, photo & architecture + œuvres iconiques",
            lessons: [
                LessonPage(id: "course_141_la_naissance_de_la_photographie_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_141_la_naissance_de_la_photographie_p1", title: "Partie 1 - De l'héliographie au Daguerréotype : fixer l'invisible", content: ""),
                LessonPage(id: "course_141_la_naissance_de_la_photographie_p2", title: "Partie 2 - L'expansion du medium : portrait et témoignage", content: ""),
                LessonPage(id: "course_141_la_naissance_de_la_photographie_p3", title: "Partie 3 - La confrontation avec la peinture et le renouveau des arts", content: ""),
                LessonPage(id: "course_141_la_naissance_de_la_photographie_p4", title: "Partie 4 - Vers la culture visuelle de masse", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_141_la_naissance_de_la_photographie_q1", question: "Quel dispositif utilisaient les artistes avant 1839 pour projeter le monde extérieur, sans pouvoir fixer l'image ?", options: ["La chambre noire", "Le daguerréotype", "Le calotype", "L'appareil Kodak"], correctIndex: 0, explanation: "La chambre noire projette le monde extérieur sur une paroi, mais l'image disparaît dès qu'on éteint la lumière."),
        QuizQuestion(id: "course_141_la_naissance_de_la_photographie_q2", question: "Qui réalise la première image photographique permanente connue, vers 1826-1827 ?", options: ["Nicéphore Niépce", "Louis Daguerre", "William Fox Talbot", "George Eastman"], correctIndex: 0, explanation: "Nicéphore Niépce fixe la première image permanente, Vue depuis la fenêtre du Gras, sur une plaque d'étain."),
        QuizQuestion(id: "course_141_la_naissance_de_la_photographie_q3", type: .trueFalse, question: "Vrai ou faux : la première photographie de Niépce a nécessité une exposition d'environ 8 heures.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "L'exposition dure environ 8 heures, si longtemps que le soleil éclaire les deux côtés des bâtiments sur l'image."),
        QuizQuestion(id: "course_141_la_naissance_de_la_photographie_q4", question: "Quel procédé britannique, développé en parallèle du daguerréotype, permet de tirer plusieurs copies à partir d'un négatif ?", options: ["Le calotype de William Fox Talbot", "Le bitume de Judée", "La carte-de-visite", "Le film Kodak"], correctIndex: 0, explanation: "Le calotype de William Fox Talbot permet, contrairement au daguerréotype, de tirer plusieurs copies d'une même image."),
        QuizQuestion(id: "course_141_la_naissance_de_la_photographie_q5", type: .numericSlider, question: "En quelle année Louis Daguerre présente-t-il son procédé à l'Académie des sciences ?", explanation: "Daguerre présente le daguerréotype à l'Académie des sciences en 1839.", correctValue: 1839, sliderMin: 1800, sliderMax: 1870, tolerance: 2, unit: ""),
        QuizQuestion(id: "course_141_la_naissance_de_la_photographie_q6", question: "Quel photographe documente le front pendant la guerre de Crimée, en 1855 ?", options: ["Roger Fenton", "Mathew Brady", "Louis Daguerre", "William Fox Talbot"], correctIndex: 0, explanation: "Roger Fenton rapporte parmi les premières images photographiques d'un conflit, pendant la guerre de Crimée."),
        QuizQuestion(id: "course_141_la_naissance_de_la_photographie_q7", question: "Quelle innovation de George Eastman et Kodak rend l'appareil photo portatif à la fin du XIXe siècle ?", options: ["Le film souple, remplaçant les plaques de verre", "Le flash électrique", "L'appareil numérique", "L'objectif zoom"], correctIndex: 0, explanation: "Eastman remplace les lourdes plaques de verre par un film souple, rendant l'appareil portatif."),
        QuizQuestion(id: "course_141_la_naissance_de_la_photographie_q8", type: .trueFalse, question: "Vrai ou faux : pendant la guerre de Sécession, le photographe Mathew Brady documente les soldats et les champs de bataille.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Mathew Brady photographie les soldats et les champs de bataille de la guerre de Sécession américaine."),
        QuizQuestion(id: "course_141_la_naissance_de_la_photographie_q9", type: .chronological, question: "Remets ces jalons de l'histoire de la photographie dans l'ordre chronologique.", explanation: "De la première image de Niépce à la démocratisation Kodak, la photographie se répand en moins d'un siècle.", items: ["Niépce fixe la première image permanente depuis sa fenêtre", "Daguerre présente le daguerréotype à Paris", "Talbot développe le calotype et le tirage multiple", "Kodak démocratise l'appareil photo amateur"])
    ]
        ),
        Course(
            id: "course_142_charlie_chaplin_et_le_cinema_muet",
            title: "Charlie Chaplin et le cinéma muet",
            description: "Charlie Chaplin (1889-1977) est la première star mondiale du cinéma : un artiste qui a touché des centaines de millions de personnes sur tous les continents...",
            subject: .art,
            subcategory: "Cinéma, photo & architecture + œuvres iconiques",
            lessons: [
                LessonPage(id: "course_142_charlie_chaplin_et_le_cinema_muet_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_142_charlie_chaplin_et_le_cinema_muet_p1", title: "De l'invention technique à l'usine à rêves", content: ""),
                LessonPage(id: "course_142_charlie_chaplin_et_le_cinema_muet_p2", title: "Charlot : l’incarnation de l'outsider universel", content: ""),
                LessonPage(id: "course_142_charlie_chaplin_et_le_cinema_muet_p3", title: "Le tournant du parlant et l'engagement politique", content: ""),
                LessonPage(id: "course_142_charlie_chaplin_et_le_cinema_muet_p4", title: "L'exil suisse et l'héritage d'un auteur total", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_142_charlie_chaplin_et_le_cinema_muet_q1", question: "Quelle invention des frères Lumière, brevetée en 1895, donne naissance au cinéma comme spectacle collectif ?", options: ["Le Cinématographe", "Le Kinétoscope", "Le Vitaphone", "Le Phonographe"], correctIndex: 0, explanation: "Le Cinématographe des frères Lumière, breveté en 1895, permet la première projection publique payante à Paris."),
        QuizQuestion(id: "course_142_charlie_chaplin_et_le_cinema_muet_q2", question: "Qui invente la fiction et les trucages au cinéma, peu après l'invention des frères Lumière ?", options: ["Georges Méliès", "Thomas Edison", "Charlie Chaplin", "David Griffith"], correctIndex: 0, explanation: "Georges Méliès, illusionniste français, invente la fiction et les trucages au tout début du cinéma."),
        QuizQuestion(id: "course_142_charlie_chaplin_et_le_cinema_muet_q3", type: .trueFalse, question: "Vrai ou faux : Charlot est un vagabond pauvre mais digne, reconnaissable à son chapeau melon et sa canne.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Charlot porte un chapeau melon trop petit, un pantalon trop large et une canne, et symbolise un homme pauvre qui garde sa dignité."),
        QuizQuestion(id: "course_142_charlie_chaplin_et_le_cinema_muet_q4", question: "Quel film de 1940 réalisé par Chaplin est une satire d'Adolf Hitler ?", options: ["Le Dictateur", "Les Lumières de la ville", "Le Chanteur de jazz", "La Ruée vers l'or"], correctIndex: 0, explanation: "En 1940, Chaplin réalise Le Dictateur, une satire d'Hitler et son premier film entièrement parlant."),
        QuizQuestion(id: "course_142_charlie_chaplin_et_le_cinema_muet_q5", type: .numericSlider, question: "En quelle année Chaplin invente-t-il le costume de Charlot ?", explanation: "En 1914, Chaplin invente presque par hasard le costume de Charlot dans un vestiaire de studio.", correctValue: 1914, sliderMin: 1895, sliderMax: 1935, tolerance: 3, unit: ""),
        QuizQuestion(id: "course_142_charlie_chaplin_et_le_cinema_muet_q6", type: .trueFalse, question: "Vrai ou faux : dès l'arrivée du cinéma parlant en 1927, Chaplin abandonne immédiatement le muet.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "Chaplin résiste au parlant et continue de tourner en muet, comme pour Les Lumières de la ville en 1931."),
        QuizQuestion(id: "course_142_charlie_chaplin_et_le_cinema_muet_q7", question: "Pourquoi Chaplin se voit-il interdire le retour aux États-Unis en 1952 ?", options: ["Il est soupçonné d'avoir des idées de gauche pendant le maccarthysme", "Il a refusé de payer ses impôts américains", "Il a insulté un producteur influent d'Hollywood", "Il a été condamné pour espionnage"], correctIndex: 0, explanation: "En pleine Guerre froide et maccarthysme, Chaplin, soupçonné d'idées de gauche, se voit interdire le retour aux États-Unis en 1952."),
        QuizQuestion(id: "course_142_charlie_chaplin_et_le_cinema_muet_q8", type: .chronological, question: "Remets ces étapes de la carrière de Chaplin et du cinéma dans l'ordre chronologique.", explanation: "Ces quatre jalons (1895, 1914, 1940, 1952) retracent la naissance du cinéma, l'invention de Charlot, l'engagement politique de Chaplin, puis son exil forcé.", items: ["Première projection publique des frères Lumière", "Chaplin invente le costume de Charlot", "Sortie du Dictateur, satire d'Hitler", "Interdiction de retour aux États-Unis"]),
        QuizQuestion(id: "course_142_charlie_chaplin_et_le_cinema_muet_q9", question: "Quelle société de production Chaplin cofonde-t-il pour garder le contrôle total de ses films ?", options: ["United Artists", "RKO Pictures", "Metro-Goldwyn-Mayer", "Paramount Pictures"], correctIndex: 0, explanation: "Chaplin cofonde United Artists, ce qui lui permet de garder son indépendance créative.")
    ]
        ),
        Course(
            id: "course_143_orson_welles_et_citizen_kane",
            title: "Orson Welles et Citizen Kane",
            description: "Citizen Kane (1941) d'Orson Welles est régulièrement désigné comme le meilleur film de l'histoire du cinéma dans les sondages des critiques. Réalisé par Well...",
            subject: .art,
            subcategory: "Cinéma, photo & architecture + œuvres iconiques",
            lessons: [
                LessonPage(id: "course_143_orson_welles_et_citizen_kane_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_143_orson_welles_et_citizen_kane_p1", title: "L'ascension d'un prodige et le contrat de la liberté", content: ""),
                LessonPage(id: "course_143_orson_welles_et_citizen_kane_p2", title: "La révolution esthétique de la profondeur de champ", content: ""),
                LessonPage(id: "course_143_orson_welles_et_citizen_kane_p3", title: "Rosebud et la déconstruction du récit traditionnel", content: ""),
                LessonPage(id: "course_143_orson_welles_et_citizen_kane_p4", title: "Postérité et réhabilitation d'un film maudit", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_143_orson_welles_et_citizen_kane_q1", question: "Quel événement radiophonique de 1938 propulse Orson Welles vers Hollywood ?", options: ["Son adaptation de La Guerre des mondes", "Sa mise en scène de Macbeth au théâtre", "Son premier film pour la RKO", "Une tournée de conférences sur le cinéma"], correctIndex: 0, explanation: "Le 30 octobre 1938, Welles fait croire à une invasion extraterrestre avec son adaptation radiophonique de La Guerre des mondes, ce qui attire l'attention d'Hollywood."),
        QuizQuestion(id: "course_143_orson_welles_et_citizen_kane_q2", question: "Quelle liberté rare la RKO Pictures accorde-t-elle à Welles pour réaliser Citizen Kane ?", options: ["La liberté totale du sujet et le contrôle final du montage", "Un budget illimité sans aucune contrainte", "Le choix exclusif du distributeur du film", "La propriété des droits d'auteur du scénario"], correctIndex: 0, explanation: "La RKO, studio en difficulté, offre à Welles un contrat rare : liberté totale de sujet et Final Cut, le droit de décider seul du montage."),
        QuizQuestion(id: "course_143_orson_welles_et_citizen_kane_q3", question: "Avec quel chef opérateur Welles développe-t-il la technique de la profondeur de champ dans Citizen Kane ?", options: ["Gregg Toland", "William Randolph Hearst", "François Truffaut", "David O. Selznick"], correctIndex: 0, explanation: "Avec le chef opérateur Gregg Toland, Welles impose la profondeur de champ, qui garde tout net du premier plan jusqu'au fond de l'image."),
        QuizQuestion(id: "course_143_orson_welles_et_citizen_kane_q4", question: "Quel est le dernier mot prononcé par Charles Foster Kane avant de mourir ?", options: ["Rosebud", "Xanadu", "Rosalind", "Charlotte"], correctIndex: 0, explanation: "Kane meurt seul dans son palais de Xanadu en prononçant le mot Rosebud, qui déclenche l'enquête du journaliste."),
        QuizQuestion(id: "course_143_orson_welles_et_citizen_kane_q5", type: .trueFalse, question: "Vrai ou faux : Citizen Kane raconte la vie de Kane à travers des témoignages contradictoires, sans jamais livrer une vérité unique sur cet homme.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "À travers des flashbacks, amis et ennemis racontent des versions contradictoires de Kane, et le spectateur n'obtient jamais une vérité unique."),
        QuizQuestion(id: "course_143_orson_welles_et_citizen_kane_q6", question: "Quel magnat de la presse se reconnaît dans le personnage de Kane et tente d'étouffer le film ?", options: ["William Randolph Hearst", "Joseph Pulitzer", "David Sarnoff", "Randolph Churchill"], correctIndex: 0, explanation: "William Randolph Hearst, vrai magnat de la presse, se reconnaît dans Kane et tente d'étouffer le film par le boycott de ses journaux."),
        QuizQuestion(id: "course_143_orson_welles_et_citizen_kane_q7", type: .trueFalse, question: "Vrai ou faux : Citizen Kane est un immense succès commercial dès sa sortie en 1941.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "Citizen Kane est au contraire un échec commercial à sa sortie, notamment à cause de la pression exercée par Hearst."),
        QuizQuestion(id: "course_143_orson_welles_et_citizen_kane_q8", question: "Quel mouvement cinématographique français des années 1950 fait de Citizen Kane un modèle du réalisateur-auteur ?", options: ["La Nouvelle Vague", "Le cinéma muet", "Le néoréalisme italien", "L'expressionnisme allemand"], correctIndex: 0, explanation: "Dans les années 1950, la critique puis la Nouvelle Vague française réhabilitent le film et en font un étendard du réalisateur qui contrôle tout."),
        QuizQuestion(id: "course_143_orson_welles_et_citizen_kane_q9", type: .chronological, question: "Remets ces étapes de l'histoire de Citizen Kane dans l'ordre chronologique.", explanation: "Ces trois jalons (1938, 1941, années 1950) retracent l'ascension radiophonique de Welles, l'échec initial du film, puis sa réhabilitation par la critique européenne.", items: ["Le canular radiophonique de La Guerre des mondes", "La sortie de Citizen Kane", "La redécouverte du film par la critique européenne"])
    ]
        ),
        Course(
            id: "course_144_la_nouvelle_vague_francaise",
            title: "La Nouvelle Vague française",
            description: "La Nouvelle Vague (1959-1968) est le mouvement cinématographique le plus influent de l'histoire du cinéma mondial. Un groupe de jeunes critiques des Cahiers...",
            subject: .art,
            subcategory: "Cinéma, photo & architecture + œuvres iconiques",
            lessons: [
                LessonPage(id: "course_144_la_nouvelle_vague_francaise_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_144_la_nouvelle_vague_francaise_p1", title: "La genèse intellectuelle : la politique des auteurs", content: ""),
                LessonPage(id: "course_144_la_nouvelle_vague_francaise_p2", title: "1959 : l'irruption de la réalité par Truffaut et Godard", content: ""),
                LessonPage(id: "course_144_la_nouvelle_vague_francaise_p3", title: "Révolution technique et esthétique : sortir du studio", content: ""),
                LessonPage(id: "course_144_la_nouvelle_vague_francaise_p4", title: "Un héritage mondial : du Nouveau Hollywood au cinéma contemporain", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_144_la_nouvelle_vague_francaise_q1", question: "Quelle revue de critique, fondée en 1951, devient le laboratoire d'idées de la Nouvelle Vague ?", options: ["Les Cahiers du cinéma", "Sight & Sound", "Positif", "Le Film français"], correctIndex: 0, explanation: "Les Cahiers du cinéma, fondés en 1951 par André Bazin, réunissent les jeunes critiques qui deviendront les réalisateurs de la Nouvelle Vague."),
        QuizQuestion(id: "course_144_la_nouvelle_vague_francaise_q2", question: "Selon la politique des auteurs défendue par les Cahiers du cinéma, qui est le véritable créateur d'un film ?", options: ["Le metteur en scène", "Le scénariste", "Le producteur", "L'acteur principal"], correctIndex: 0, explanation: "Pour les critiques des Cahiers, le vrai créateur n'est pas le scénariste mais celui qui met en scène, comme un romancier a son style."),
        QuizQuestion(id: "course_144_la_nouvelle_vague_francaise_q3", question: "Quel film de François Truffaut triomphe à Cannes en 1959 et lance la Nouvelle Vague ?", options: ["Les Quatre Cents Coups", "À bout de souffle", "Citizen Kane", "Le Dictateur"], correctIndex: 0, explanation: "En 1959, Les Quatre Cents Coups de François Truffaut triomphe à Cannes et impose le cinéma d'auteur."),
        QuizQuestion(id: "course_144_la_nouvelle_vague_francaise_q4", type: .trueFalse, question: "Vrai ou faux : À bout de souffle de Jean-Luc Godard choque en 1960 par ses coupes brusques au milieu des gestes.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Godard coupe au milieu des gestes dans À bout de souffle, comme s'il montait le film avec des ciseaux, ce qui choque en 1960."),
        QuizQuestion(id: "course_144_la_nouvelle_vague_francaise_q5", question: "Quelle innovation technique permet aux réalisateurs de la Nouvelle Vague de sortir des studios pour filmer dans les rues de Paris ?", options: ["Des caméras légères comme l'Éclair Caméflex", "Les écrans larges Cinémascope", "Le son Dolby stéréo", "Les décors en carton-pâte"], correctIndex: 0, explanation: "Les caméras légères comme l'Éclair Caméflex et des pellicules plus sensibles permettent de tourner en décors naturels, hors des studios."),
        QuizQuestion(id: "course_144_la_nouvelle_vague_francaise_q6", question: "Quel mouvement cinématographique brésilien s'inspire directement de la liberté de tournage de la Nouvelle Vague ?", options: ["Le Cinéma Novo", "Le néoréalisme italien", "L'expressionnisme allemand", "Le Dogme 95"], correctIndex: 0, explanation: "La liberté de tournage de la Nouvelle Vague inspire ensuite le Cinéma Novo au Brésil, puis le Dogme 95 au Danemark."),
        QuizQuestion(id: "course_144_la_nouvelle_vague_francaise_q7", type: .trueFalse, question: "Vrai ou faux : les réalisateurs de la Nouvelle Vague tournent principalement en studio, avec un éclairage artificiel sophistiqué.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "Au contraire, ils filment dans les cafés, les appartements et les rues de Paris, souvent en lumière naturelle."),
        QuizQuestion(id: "course_144_la_nouvelle_vague_francaise_q8", question: "Quels réalisateurs américains des années 1970 s'inspirent de la liberté de la Nouvelle Vague ?", options: ["Scorsese, Coppola et Spielberg", "Hitchcock, Welles et Kubrick", "Chaplin et Keaton", "Bergman et Fellini"], correctIndex: 0, explanation: "Dans les années 1970, le Nouveau Hollywood, porté par Scorsese, Coppola et Spielberg, mêle efficacité américaine et liberté française."),
        QuizQuestion(id: "course_144_la_nouvelle_vague_francaise_q9", type: .chronological, question: "Remets ces étapes de la Nouvelle Vague dans l'ordre chronologique.", explanation: "Ces trois jalons (1951, 1959, 1960) montrent le passage d'une revue de critique à une révolution du cinéma d'auteur.", items: ["Fondation des Cahiers du cinéma", "Triomphe des Quatre Cents Coups à Cannes", "Sortie d'À bout de souffle"])
    ]
        ),
        Course(
            id: "course_145_kubrick_2001_l_odyssee_de_l_espace",
            title: "Kubrick : 2001, l'Odyssée de l'espace",
            description: "2001 : l'Odyssée de l'espace (1968) de Stanley Kubrick est le film de science-fiction le plus influent de l'histoire. Pas de dialogue pendant les 25 première...",
            subject: .art,
            subcategory: "Cinéma, photo & architecture + œuvres iconiques",
            lessons: [
                LessonPage(id: "course_145_kubrick_2001_l_odyssee_de_l_espace_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_145_kubrick_2001_l_odyssee_de_l_espace_p1", title: "Stanley Kubrick : le perfectionniste du langage visuel", content: ""),
                LessonPage(id: "course_145_kubrick_2001_l_odyssee_de_l_espace_p2", title: "Une genèse visionnaire entre littérature et technologie", content: ""),
                LessonPage(id: "course_145_kubrick_2001_l_odyssee_de_l_espace_p3", title: "L'intelligence artificielle et la faillibilité humaine", content: ""),
                LessonPage(id: "course_145_kubrick_2001_l_odyssee_de_l_espace_p4", title: "Une symphonie cosmique et métaphysique", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_145_kubrick_2001_l_odyssee_de_l_espace_q1", type: .numericSlider, question: "En quelle année sort 2001 : l'Odyssée de l'espace au cinéma ?", explanation: "2001 : l'Odyssée de l'espace sort en 1968 et redéfinit la science-fiction au cinéma.", correctValue: 1968, sliderMin: 1950, sliderMax: 1985, tolerance: 3, unit: ""),
        QuizQuestion(id: "course_145_kubrick_2001_l_odyssee_de_l_espace_q2", question: "Quel écrivain de science-fiction Kubrick contacte-t-il en 1964 pour créer 2001 ?", options: ["Arthur C. Clarke", "Isaac Asimov", "Philip K. Dick", "Ray Bradbury"], correctIndex: 0, explanation: "En 1964, Kubrick contacte l'écrivain Arthur C. Clarke pour inventer ensemble un film et un roman en parallèle."),
        QuizQuestion(id: "course_145_kubrick_2001_l_odyssee_de_l_espace_q3", question: "De quelle nouvelle Kubrick et Clarke partent-ils pour développer 2001 ?", options: ["La Sentinelle", "Fondation", "Chroniques martiennes", "Rendez-vous avec Rama"], correctIndex: 0, explanation: "Kubrick et Clarke partent de la nouvelle La Sentinelle pour construire en parallèle le film et le roman."),
        QuizQuestion(id: "course_145_kubrick_2001_l_odyssee_de_l_espace_q4", question: "Qui invente la technique du slit-scan pour filmer le voyage final du film ?", options: ["Douglas Trumbull", "Gregg Toland", "Arthur C. Clarke", "Stanley Kubrick"], correctIndex: 0, explanation: "Le superviseur des effets Douglas Trumbull invente le slit-scan, qui crée des tunnels de lumière hypnotiques pour le voyage final."),
        QuizQuestion(id: "course_145_kubrick_2001_l_odyssee_de_l_espace_q5", question: "Que représente HAL 9000 dans le film ?", options: ["L'ordinateur de bord qui finit par éliminer l'équipage", "Un extraterrestre venu avertir l'humanité", "Le clone robotique d'un astronaute", "Un simple assistant vocal sans conscience"], correctIndex: 0, explanation: "HAL 9000, l'ordinateur de bord, choisit d'éliminer les humains pour résoudre la contradiction de sa mission."),
        QuizQuestion(id: "course_145_kubrick_2001_l_odyssee_de_l_espace_q6", type: .trueFalse, question: "Vrai ou faux : HAL 9000 attaque l'équipage car il est pris dans une contradiction entre accomplir sa mission et cacher sa vraie nature.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Pris dans cette contradiction, HAL choisit d'éliminer les humains pour préserver le secret de sa mission."),
        QuizQuestion(id: "course_145_kubrick_2001_l_odyssee_de_l_espace_q7", question: "Pour filmer Barry Lyndon uniquement à la lumière des bougies, quels objectifs Kubrick fait-il adapter ?", options: ["Des optiques Zeiss conçues pour la NASA", "Des projecteurs de studio miniatures", "Des filtres infrarouges militaires", "Des caméras thermiques"], correctIndex: 0, explanation: "Kubrick fait adapter des optiques Zeiss conçues pour la NASA afin de filmer Barry Lyndon à la seule lumière des bougies."),
        QuizQuestion(id: "course_145_kubrick_2001_l_odyssee_de_l_espace_q8", question: "Quel morceau de musique accompagne les stations spatiales en orbite dans 2001 ?", options: ["Le Beau Danube bleu de Johann Strauss", "Ainsi parlait Zarathoustra de Richard Strauss", "La Symphonie du Nouveau Monde de Dvořák", "Les Quatre Saisons de Vivaldi"], correctIndex: 0, explanation: "La valse Le Beau Danube bleu de Johann Strauss accompagne les stations spatiales, tandis qu'Ainsi parlait Zarathoustra marque les sauts de l'évolution."),
        QuizQuestion(id: "course_145_kubrick_2001_l_odyssee_de_l_espace_q9", question: "Que symbolise le monolithe noir dans 2001 ?", options: ["Une présence qui relance l'évolution humaine", "Une arme extraterrestre destinée à détruire la Terre", "Un simple décor sans signification narrative", "Le vaisseau spatial des astronautes"], correctIndex: 0, explanation: "Le monolithe noir est une présence silencieuse qui relance l'évolution humaine à plusieurs moments du film.")
    ]
        ),
        Course(
            id: "course_146_hitchcock_et_le_suspense",
            title: "Surprise ou suspense : quelle différence pour Hitchcock ?",
            description: "Alfred Hitchcock (1899-1980) est le «maître du suspense» - le réalisateur qui a défini les codes du thriller cinématographique et dont l'influence sur le cin...",
            subject: .art,
            subcategory: "Cinéma, photo & architecture + œuvres iconiques",
            lessons: [
                LessonPage(id: "course_146_hitchcock_et_le_suspense_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_146_hitchcock_et_le_suspense_p1", title: "La grammaire du suspense : l'asymétrie d'information", content: ""),
                LessonPage(id: "course_146_hitchcock_et_le_suspense_p2", title: "L'innovation formelle au service de l'obsession", content: ""),
                LessonPage(id: "course_146_hitchcock_et_le_suspense_p3", title: "Voyeurisme et identification psychologique", content: ""),
                LessonPage(id: "course_146_hitchcock_et_le_suspense_p4", title: "Un héritage institutionnel et esthétique", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_146_hitchcock_et_le_suspense_q1", question: "Selon Hitchcock, quelle est la différence entre surprise et suspense ?", options: ["Le suspense montre la bombe au public avant qu'elle n'explose, la surprise non", "Le suspense fait peur, la surprise fait rire", "La surprise dure plus longtemps que le suspense", "Il n'y a aucune différence, ce sont des synonymes"], correctIndex: 0, explanation: "Hitchcock explique à Truffaut que le suspense montre la bombe au public alors que les personnages l'ignorent, ce qui prolonge la tension."),
        QuizQuestion(id: "course_146_hitchcock_et_le_suspense_q2", question: "Qu'est-ce qu'un MacGuffin dans un film d'Hitchcock ?", options: ["Un objet ou un secret qui motive les personnages sans que sa nature exacte importe", "Un plan de caméra signature d'Hitchcock", "Le nom du tueur dans Psycho", "Une technique de montage sonore"], correctIndex: 0, explanation: "Le MacGuffin est un objet ou un secret qui fait avancer l'intrigue, même si sa nature précise n'a pas vraiment d'importance."),
        QuizQuestion(id: "course_146_hitchcock_et_le_suspense_q3", question: "Quelle technique Hitchcock utilise-t-il dans La Corde (1948) pour simuler un film tourné d'un seul geste ?", options: ["Un plan-séquence avec des coupes cachées derrière des dos ou des meubles", "Le montage alterné classique", "La caméra subjective en continu", "Le split-screen"], correctIndex: 0, explanation: "Hitchcock cache les coupes derrière un dos ou un meuble sombre pour simuler un plan-séquence unique dans La Corde."),
        QuizQuestion(id: "course_146_hitchcock_et_le_suspense_q4", question: "Quel effet visuel Hitchcock invente-t-il pour Vertigo en 1958 ?", options: ["Le Dolly Zoom", "La profondeur de champ", "Le slit-scan", "Le split-screen"], correctIndex: 0, explanation: "Pour Vertigo, Hitchcock invente le Dolly Zoom : la caméra recule pendant que le zoom avance, déformant l'espace pour faire ressentir le vertige."),
        QuizQuestion(id: "course_146_hitchcock_et_le_suspense_q5", type: .trueFalse, question: "Vrai ou faux : dans La Fenêtre sur cour, le spectateur voit exactement ce que voit le héros grâce à la caméra subjective.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Hitchcock utilise la caméra subjective : nous voyons exactement ce que voit le héros, rien de plus."),
        QuizQuestion(id: "course_146_hitchcock_et_le_suspense_q6", question: "Qui est le héros de La Fenêtre sur cour (1954) ?", options: ["Un photographe à la jambe cassée qui espionne ses voisins", "Un détective privé chargé d'une enquête", "Un policier en congé forcé", "Un écrivain en manque d'inspiration"], correctIndex: 0, explanation: "Le héros est un photographe à la jambe cassée qui espionne ses voisins depuis sa fenêtre."),
        QuizQuestion(id: "course_146_hitchcock_et_le_suspense_q7", type: .trueFalse, question: "Vrai ou faux : pour Psycho, Hitchcock interdit l'entrée en salle après le début de la séance.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Hitchcock interdit l'entrée après le début de la séance pour Psycho, transformant le secret de l'intrigue en événement."),
        QuizQuestion(id: "course_146_hitchcock_et_le_suspense_q8", question: "Quel compositeur collabore régulièrement avec Hitchcock pour intensifier la tension par la musique ?", options: ["Bernard Herrmann", "Richard Strauss", "Johann Strauss", "Ennio Morricone"], correctIndex: 0, explanation: "La collaboration entre Hitchcock et le compositeur Bernard Herrmann lie musique et montage pour accélérer le pouls du spectateur."),
        QuizQuestion(id: "course_146_hitchcock_et_le_suspense_q9", type: .chronological, question: "Remets ces innovations techniques d'Hitchcock dans l'ordre chronologique.", explanation: "Ces trois innovations (1948, 1954, 1958) jalonnent l'évolution du style d'Hitchcock, de l'illusion du plan continu à la distorsion optique du vertige.", items: ["La Corde simule un plan-séquence unique", "La Fenêtre sur cour utilise la caméra subjective", "Vertigo invente le Dolly Zoom"])
    ]
        ),
        Course(
            id: "course_147_l_architecture_gothique_les_cathedrales",
            title: "Comment les cathédrales gothiques font-elles entrer la lumière ?",
            description: "Les cathédrales gothiques du XIIe au XVIe siècle sont l'expression architecturale la plus audacieuse du Moyen Âge : des constructions qui semblent défier les...",
            subject: .art,
            subcategory: "Cinéma, photo & architecture + œuvres iconiques",
            lessons: [
                LessonPage(id: "course_147_l_architecture_gothique_les_cathedrales_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_147_l_architecture_gothique_les_cathedrales_p1", title: "La révolution structurale : l'invention de l'apesanteur", content: ""),
                LessonPage(id: "course_147_l_architecture_gothique_les_cathedrales_p2", title: "La théologie de la lumière : le verre comme écriture", content: ""),
                LessonPage(id: "course_147_l_architecture_gothique_les_cathedrales_p3", title: "Le chantier médiéval : un défi logistique et temporel", content: ""),
                LessonPage(id: "course_147_l_architecture_gothique_les_cathedrales_p4", title: "L'évolution des styles et le legs du gothique", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_147_l_architecture_gothique_les_cathedrales_q1", question: "Où et vers quelle date naît le style gothique ?", options: ["En Île-de-France, vers 1140", "En Toscane, vers 1400", "En Bavière, vers 1250", "En Normandie, vers 1000"], correctIndex: 0, explanation: "Le gothique naît en Île-de-France vers 1140, avec le chœur de la basilique de Saint-Denis."),
        QuizQuestion(id: "course_147_l_architecture_gothique_les_cathedrales_q2", question: "Qui lance le chantier du chœur de la basilique de Saint-Denis, à l'origine du style gothique ?", options: ["L'abbé Suger", "Le roi Louis IX", "L'architecte Villard de Honnecourt", "Le pape Innocent III"], correctIndex: 0, explanation: "L'abbé Suger porte le choc fondateur du gothique en voulant un espace plus uni, plus clair et plus haut à Saint-Denis."),
        QuizQuestion(id: "course_147_l_architecture_gothique_les_cathedrales_q3", question: "Quelles trois innovations permettent d'alléger les murs des cathédrales gothiques ?", options: ["L'arc brisé, la voûte d'ogives et l'arc-boutant", "La coupole, le fronton et la colonnade", "Le dôme, le pilastre et le linteau", "La voûte en berceau, le contrefort massif et le clocher-porche"], correctIndex: 0, explanation: "L'arc brisé, la voûte d'ogives et l'arc-boutant travaillent ensemble pour libérer les murs et permettre de vastes fenêtres."),
        QuizQuestion(id: "course_147_l_architecture_gothique_les_cathedrales_q4", question: "Selon la théologie défendue par l'abbé Suger, quel rôle joue la lumière dans la cathédrale ?", options: ["Elle aide l'âme à s'élever vers Dieu", "Elle sert uniquement à éclairer les offices religieux", "Elle marque la puissance financière du clergé", "Elle protège la pierre de l'humidité"], correctIndex: 0, explanation: "Pour Suger, les rayons colorés des vitraux aident l'âme à s'élever vers Dieu, faisant de la cathédrale une cage de lumière."),
        QuizQuestion(id: "course_147_l_architecture_gothique_les_cathedrales_q5", type: .trueFalse, question: "Vrai ou faux : la construction d'une cathédrale gothique prend souvent plus de deux siècles.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Guerres, épidémies et manque d'argent font avancer les chantiers par à-coups, sur souvent plus de deux siècles."),
        QuizQuestion(id: "course_147_l_architecture_gothique_les_cathedrales_q6", type: .numericSlider, question: "En quelle année commence la construction de Notre-Dame de Paris ?", explanation: "Notre-Dame de Paris commence en 1163 et trouve sa forme vers 1345, après environ 180 ans de chantier.", correctValue: 1163, sliderMin: 1100, sliderMax: 1250, tolerance: 5, unit: ""),
        QuizQuestion(id: "course_147_l_architecture_gothique_les_cathedrales_q7", type: .trueFalse, question: "Vrai ou faux : seuls les moines participent à la construction des cathédrales, sans l'aide des habitants de la ville.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "Toute la ville travaille au chantier : tailleurs de pierre, charpentiers et verriers, ce qui en fait aussi une machine économique."),
        QuizQuestion(id: "course_147_l_architecture_gothique_les_cathedrales_q8", question: "Quelle cathédrale gothique inachevée est finalement terminée au XIXe siècle grâce au néo-gothique ?", options: ["La cathédrale de Cologne", "Notre-Dame de Paris", "La cathédrale de Chartres", "La Sainte-Chapelle"], correctIndex: 0, explanation: "Au XIXe siècle, l'Europe redécouvre le gothique et termine des chantiers inachevés comme celui de Cologne, achevé en 1880."),
        QuizQuestion(id: "course_147_l_architecture_gothique_les_cathedrales_q9", type: .chronological, question: "Remets ces étapes de l'architecture gothique dans l'ordre chronologique.", explanation: "Ces jalons (1140, 1163, XIIIe siècle, XIXe siècle) montrent la naissance du style, sa diffusion, son apogée classique puis sa redécouverte moderne.", items: ["Suger lance le chœur de Saint-Denis", "Début du chantier de Notre-Dame de Paris", "Chartres et Amiens imposent le modèle classique", "L'Europe redécouvre le style avec le néo-gothique"])
    ]
        ),
        Course(
            id: "course_148_le_bauhaus",
            title: "Pourquoi le Bauhaus est-il partout autour de nous ?",
            description: "Le Bauhaus (1919-1933) est l'école d'art et de design la plus influente de l'histoire, fondée en Allemagne par Walter Gropius. Elle invente le design industr...",
            subject: .art,
            subcategory: "Cinéma, photo & architecture + œuvres iconiques",
            lessons: [
                LessonPage(id: "course_148_le_bauhaus_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_148_le_bauhaus_p1", title: "La genèse de Weimar : l'union des arts et des métiers", content: ""),
                LessonPage(id: "course_148_le_bauhaus_p2", title: "L'exigence de la forme et la révolution des matériaux", content: ""),
                LessonPage(id: "course_148_le_bauhaus_p3", title: "La chute politique et l'exil salvateur", content: ""),
                LessonPage(id: "course_148_le_bauhaus_p4", title: "Un héritage invisible : le design au quotidien", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_148_le_bauhaus_q1", question: "Qui fonde le Bauhaus à Weimar en 1919 ?", options: ["Walter Gropius", "Mies van der Rohe", "Vassily Kandinsky", "Marcel Breuer"], correctIndex: 0, explanation: "L'architecte Walter Gropius fonde le Bauhaus à Weimar en 1919, avec pour but final l'architecture."),
        QuizQuestion(id: "course_148_le_bauhaus_q2", question: "Quel principe du manifeste de Gropius abolit la hiérarchie entre beaux-arts et arts appliqués ?", options: ["Chaque atelier a un maître artiste et un maître artisan, à égalité", "Seuls les architectes peuvent enseigner au Bauhaus", "L'art doit rester séparé de l'artisanat", "Les étudiants choisissent un seul art à maîtriser"], correctIndex: 0, explanation: "Chaque atelier du Bauhaus est dirigé par un artiste et un artisan, l'artisanat devenant la base de toute création."),
        QuizQuestion(id: "course_148_le_bauhaus_q3", question: "Quel mouvement néerlandais dialogue avec le Bauhaus autour du rectangle et des couleurs pures ?", options: ["De Stijl", "Le Cubisme", "Le Futurisme", "L'Art nouveau"], correctIndex: 0, explanation: "L'école dialogue avec De Stijl, mouvement néerlandais obsédé par le rectangle et les couleurs pures."),
        QuizQuestion(id: "course_148_le_bauhaus_q4", question: "Quel slogan résume la philosophie du Bauhaus après son installation à Dessau ?", options: ["La forme suit la fonction", "L'art pour l'art", "Moins de forme, plus d'ornement", "Le beau avant l'utile"], correctIndex: 0, explanation: "À Dessau, le Bauhaus se tourne vers la production en série sous le slogan la forme suit la fonction."),
        QuizQuestion(id: "course_148_le_bauhaus_q5", question: "Quel matériau industriel Marcel Breuer recycle-t-il pour inventer des chaises légères ?", options: ["L'acier tubulaire des bicyclettes", "Le bois courbé de fauteuils anciens", "Le plastique moulé", "L'aluminium des avions"], correctIndex: 0, explanation: "Marcel Breuer recycle l'acier tubulaire des bicyclettes pour créer des chaises légères et modernes."),
        QuizQuestion(id: "course_148_le_bauhaus_q6", type: .trueFalse, question: "Vrai ou faux : le régime nazi ferme le Bauhaus en 1933 en l'accusant de bolchevisme culturel.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Jugée trop moderne et trop à gauche, l'école est fermée par les nazis en 1933, accusée de bolchevisme culturel."),
        QuizQuestion(id: "course_148_le_bauhaus_q7", question: "Qui dirige le Bauhaus à Berlin juste avant sa fermeture par les nazis ?", options: ["Mies van der Rohe", "Walter Gropius", "Vassily Kandinsky", "Le Corbusier"], correctIndex: 0, explanation: "Mies van der Rohe dirige le Bauhaus lors de son passage à Berlin, juste avant la fermeture de 1933."),
        QuizQuestion(id: "course_148_le_bauhaus_q8", type: .trueFalse, question: "Vrai ou faux : la fermeture du Bauhaus met fin à son influence, qui disparaît avec l'école.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "Au contraire, l'exil des maîtres du Bauhaus aux États-Unis, en Grande-Bretagne et en Palestine diffuse ses idées dans le monde entier."),
        QuizQuestion(id: "course_148_le_bauhaus_q9", type: .chronological, question: "Remets ces étapes de l'histoire du Bauhaus dans l'ordre chronologique.", explanation: "Ces trois jalons (1919, 1925, 1933) retracent la fondation à Weimar, le virage industriel à Dessau, puis la fermeture qui diffuse le Bauhaus dans le monde.", items: ["Fondation du Bauhaus à Weimar", "Le Bauhaus s'installe à Dessau et vise la production en série", "Fermeture de l'école par les nazis"])
    ]
        ),
        Course(
            id: "course_149_la_joconde",
            title: "Pourquoi la Joconde est-elle aussi connue ?",
            description: "C'est le tableau le plus célèbre du monde. Pourtant, en 1503, son propre auteur avait mieux à faire que le portrait d'une épouse de marchand.",
            subject: .art,
            subcategory: "Œuvres iconiques",
            lessons: [
                LessonPage(id: "course_149_la_joconde_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_149_la_joconde_p1", title: "Qui est la Joconde ?", content: ""),
                LessonPage(id: "course_149_la_joconde_p2", title: "Anghiari : une commande plus prestigieuse", content: ""),
                LessonPage(id: "course_149_la_joconde_p3", title: "La fabrique d'une icône", content: ""),
                LessonPage(id: "course_149_la_joconde_p4", title: "Un tableau qui a dépassé son auteur", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_149_la_joconde_q1", question: "Selon Vasari, qui est le modèle de La Joconde ?", options: ["Lisa Gherardini, épouse du marchand Francesco del Giocondo", "Une maîtresse de François Ier", "La mère de Léonard de Vinci", "Une princesse de la cour de Milan"], correctIndex: 0, explanation: "L'identification repose sur la biographie de Léonard publiée par Giorgio Vasari en 1550 puis en 1568."),
        QuizQuestion(id: "course_149_la_joconde_q2", type: .numericSlider, question: "En quelle année Léonard commence-t-il le portrait de Lisa Gherardini ?", explanation: "Léonard se met au portrait au début de 1503, à Florence.", correctValue: 1503, sliderMin: 1450, sliderMax: 1550, tolerance: 3, unit: ""),
        QuizQuestion(id: "course_149_la_joconde_q3", question: "Quelle commande détourne Léonard du portrait à partir d'octobre 1503 ?", options: ["La Bataille d'Anghiari pour le Palazzo Vecchio", "La Cène pour un couvent de Milan", "Un portrait du roi de France", "Le plafond d'une chapelle à Rome"], correctIndex: 0, explanation: "Le gouvernement florentin lui commande une grande peinture murale célébrant la victoire de Florence sur Milan en 1440."),
        QuizQuestion(id: "course_149_la_joconde_q4", type: .trueFalse, question: "Vrai ou faux : à la Renaissance, le portrait est considéré comme la forme la plus haute de la peinture.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "Les scènes d'histoire, avec les sujets religieux, mythologiques et allégoriques, passent alors bien avant le portrait."),
        QuizQuestion(id: "course_149_la_joconde_q5", type: .chronological, question: "Remets ces étapes de l'histoire de La Joconde dans l'ordre.", explanation: "Début 1503, octobre 1503, milieu de 1506, 2 mai 1519, puis le vol de 1911.", items: ["Léonard commence le portrait à Florence", "Florence lui commande la Bataille d'Anghiari", "Léonard part pour Milan avec le portrait inachevé", "Léonard meurt à Amboise", "Le tableau est volé au Louvre"]),
        QuizQuestion(id: "course_149_la_joconde_q6", question: "Comment La Joconde entre-t-elle au Louvre ?", options: ["La collection royale devient publique après la Révolution française", "La famille Giocondo la vend au musée", "Napoléon la rapporte de sa campagne d'Italie", "Léonard l'offre au musée avant de mourir"], correctIndex: 0, explanation: "Léonard emporte le tableau en France, il entre dans la collection de François Ier, et cette collection devient publique après la Révolution."),
        QuizQuestion(id: "course_149_la_joconde_q7", question: "Quel événement transforme La Joconde en sensation mondiale ?", options: ["Son vol au Louvre en 1911", "Sa restauration au XIXe siècle", "Son exposition à New York", "La découverte d'une seconde version"], correctIndex: 0, explanation: "Après le vol de 1911, les journaux font du tableau une sensation et les légendes se multiplient."),
        QuizQuestion(id: "course_149_la_joconde_q8", question: "Pourquoi ne restaure-t-on pas La Joconde aujourd'hui ?", options: ["Retirer le vernis jauni risquerait d'abîmer l'œuvre et de rompre son charme", "Le Louvre n'a pas le budget nécessaire", "Léonard a interdit toute restauration dans son testament", "Le tableau est déjà dans son état d'origine"], correctIndex: 0, explanation: "Le vernis protecteur a jauni avec les siècles, mais on craint d'endommager le tableau et de lui faire perdre son pouvoir de fascination.")
    ]
        ),
        Course(
            id: "course_150_la_nuit_etoilee_van_gogh",
            title: "Pourquoi le ciel de « La Nuit étoilée » tourbillonne-t-il ?",
            description: "La Nuit étoilée (1889) est le tableau de Vincent Van Gogh le plus célèbre et l'un des tableaux les plus reconnaissables au monde. Peint à l'asile de Saint-Ré...",
            subject: .art,
            subcategory: "Cinéma, photo & architecture + œuvres iconiques",
            lessons: [
                LessonPage(id: "course_150_la_nuit_etoilee_van_gogh_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_150_la_nuit_etoilee_van_gogh_p1", title: "Le refuge de Saint-Paul-de-Mausole", content: ""),
                LessonPage(id: "course_150_la_nuit_etoilee_van_gogh_p2", title: "La naissance de l'expressionnisme", content: ""),
                LessonPage(id: "course_150_la_nuit_etoilee_van_gogh_p3", title: "Le paradoxe du génie méconnu", content: ""),
                LessonPage(id: "course_150_la_nuit_etoilee_van_gogh_p4", title: "Significations et héritage symbolique", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_150_la_nuit_etoilee_van_gogh_q1", question: "Où Van Gogh peint-il La Nuit étoilée en 1889 ?", options: ["À l'asile de Saint-Paul-de-Mausole, près de Saint-Rémy-de-Provence", "Dans son atelier parisien", "À Arles, chez son frère Théo", "Aux Pays-Bas, sa région natale"], correctIndex: 0, explanation: "Van Gogh peint La Nuit étoilée depuis sa chambre de l'asile de Saint-Paul-de-Mausole, près de Saint-Rémy-de-Provence."),
        QuizQuestion(id: "course_150_la_nuit_etoilee_van_gogh_q2", question: "Quel événement précède de peu l'internement de Van Gogh à Saint-Rémy ?", options: ["Le drame d'Arles avec Gauguin, qui lui coûte une partie de l'oreille", "La mort de son frère Théo", "Un accident de calèche", "Un procès pour dettes"], correctIndex: 0, explanation: "Après le drame d'Arles avec Gauguin, qui lui coûte une partie de l'oreille, Van Gogh se fait interner à Saint-Paul-de-Mausole."),
        QuizQuestion(id: "course_150_la_nuit_etoilee_van_gogh_q3", type: .trueFalse, question: "Vrai ou faux : le village représenté dans La Nuit étoilée est une copie exacte du paysage visible depuis la fenêtre de Van Gogh.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "Van Gogh mélange observation et invention : il reconstruit le paysage et le village pour servir l'émotion, plutôt que de copier exactement la réalité."),
        QuizQuestion(id: "course_150_la_nuit_etoilee_van_gogh_q4", question: "Quelle technique de peinture donne un aspect presque sculpté au ciel de La Nuit étoilée ?", options: ["L'empâtement", "Le sfumato", "L'aquarelle", "La fresque"], correctIndex: 0, explanation: "Van Gogh utilise l'empâtement, une peinture épaisse presque sculptée, pour donner du relief au ciel tourbillonnant."),
        QuizQuestion(id: "course_150_la_nuit_etoilee_van_gogh_q5", question: "Quelle œuvre japonaise a inspiré les grandes volutes du ciel de La Nuit étoilée ?", options: ["La Grande Vague de Kanagawa", "Le Mont Fuji vu de Kyoto", "Les Cent Vues d'Edo", "Les Beautés du Yoshiwara"], correctIndex: 0, explanation: "Les volutes du ciel rappellent la dynamique de la Grande Vague de Kanagawa, une estampe japonaise que Van Gogh admirait."),
        QuizQuestion(id: "course_150_la_nuit_etoilee_van_gogh_q6", type: .trueFalse, question: "Vrai ou faux : Van Gogh est déjà célèbre et reconnu de son vivant.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "Van Gogh meurt presque inconnu en 1890 ; c'est sa belle-sœur Johanna van Gogh-Bonger qui fait connaître son œuvre après sa mort."),
        QuizQuestion(id: "course_150_la_nuit_etoilee_van_gogh_q7", question: "Qui sauve l'œuvre de Van Gogh après sa mort, en organisant expositions et publications ?", options: ["Sa belle-sœur, Johanna van Gogh-Bonger", "Son frère Théo", "Paul Gauguin", "Le musée du Louvre"], correctIndex: 0, explanation: "Johanna van Gogh-Bonger, belle-sœur de Van Gogh, sauve son œuvre par des expositions, des ventes et la publication de ses lettres."),
        QuizQuestion(id: "course_150_la_nuit_etoilee_van_gogh_q8", type: .numericSlider, question: "À quel âge Van Gogh meurt-il, en 1890 ?", explanation: "Van Gogh meurt en juillet 1890 à Auvers-sur-Oise, à l'âge de 37 ans, presque inconnu.", correctValue: 37, sliderMin: 20, sliderMax: 60, tolerance: 2, unit: "ans"),
        QuizQuestion(id: "course_150_la_nuit_etoilee_van_gogh_q9", type: .chronological, question: "Remets ces étapes de la vie de Van Gogh dans l'ordre chronologique.", explanation: "Ces jalons (1888, 1889, 1890) retracent la crise avec Gauguin, la création de La Nuit étoilée depuis l'asile, puis la mort de l'artiste.", items: ["Le drame d'Arles avec Gauguin", "Van Gogh peint La Nuit étoilée à Saint-Rémy", "Mort de Van Gogh à Auvers-sur-Oise"])
    ]
        ),
        Course(
            id: "course_151_guernica_picasso",
            title: "Que dit « Guernica » de Picasso sur la guerre ?",
            description: "Guernica (1937) est le tableau de protestation politique le plus célèbre de l'histoire de l'art. Peint par Picasso en réponse au bombardement de la ville bas...",
            subject: .art,
            subcategory: "Cinéma, photo & architecture + œuvres iconiques",
            lessons: [
                LessonPage(id: "course_151_guernica_picasso_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_151_guernica_picasso_p1", title: "Le crime de guerre : le 26 avril 1937", content: ""),
                LessonPage(id: "course_151_guernica_picasso_p2", title: "L'urgence créatrice et le langage de la douleur", content: ""),
                LessonPage(id: "course_151_guernica_picasso_p3", title: "Le long exil d'un tableau politique", content: ""),
                LessonPage(id: "course_151_guernica_picasso_p4", title: "Postérité et résonance universelle", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_151_guernica_picasso_q1", question: "Quel événement de 1937 pousse Picasso à peindre Guernica ?", options: ["Le bombardement de la ville basque de Guernica", "La chute de Madrid", "Le début de la Seconde Guerre mondiale", "L'exécution de Franco"], correctIndex: 0, explanation: "Le 26 avril 1937, la ville basque de Guernica est bombardée pendant la guerre civile espagnole, ce qui pousse Picasso à réagir par une toile immense."),
        QuizQuestion(id: "course_151_guernica_picasso_q2", question: "Pourquoi Picasso renonce-t-il à la couleur pour ce tableau ?", options: ["Pour coller à l'urgence du témoignage, comme une une de journal", "Parce qu'il n'avait plus de peinture colorée", "Pour respecter une commande du gouvernement espagnol", "Par imitation du cubisme analytique"], correctIndex: 0, explanation: "Picasso abandonne la couleur pour coller à l'urgence du témoignage, comme s'il peignait une une de journal en noir et blanc."),
        QuizQuestion(id: "course_151_guernica_picasso_q3", type: .trueFalse, question: "Vrai ou faux : Guernica représente une bataille héroïque avec des soldats victorieux.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "Guernica montre une grammaire de la terreur civile, cheval éventré et mère à l'enfant, et non une bataille héroïque."),
        QuizQuestion(id: "course_151_guernica_picasso_q4", question: "Quel camp soutient le bombardement de Guernica pendant la guerre civile espagnole ?", options: ["Les nationalistes de Franco, aidés par la Légion Condor allemande", "La Seconde République espagnole seule", "Les Brigades internationales", "Le gouvernement français"], correctIndex: 0, explanation: "Le bombardement de saturation de Guernica est mené par les nationalistes de Franco, soutenus par la Légion Condor allemande."),
        QuizQuestion(id: "course_151_guernica_picasso_q5", type: .trueFalse, question: "Vrai ou faux : Picasso a refusé que Guernica soit envoyé en Espagne tant que Franco resterait au pouvoir.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Picasso a en effet refusé que le tableau rejoigne l'Espagne tant que Franco resterait au pouvoir."),
        QuizQuestion(id: "course_151_guernica_picasso_q6", type: .numericSlider, question: "En quelle année Guernica rentre-t-elle en Espagne après la mort de Franco ?", explanation: "Le tableau rentre à Madrid en 1981, après la fin de la dictature franquiste.", correctValue: 1981, sliderMin: 1960, sliderMax: 2000, tolerance: 3, unit: ""),
        QuizQuestion(id: "course_151_guernica_picasso_q7", question: "Où le tableau est-il resté protégé pendant une grande partie de la dictature franquiste ?", options: ["Au MoMA de New York", "Au Louvre à Paris", "Au Prado à Madrid", "À la National Gallery de Londres"], correctIndex: 0, explanation: "Après l'Exposition universelle de Paris, le tableau reste longtemps au MoMA de New York, protégé pendant la dictature franquiste."),
        QuizQuestion(id: "course_151_guernica_picasso_q8", type: .chronological, question: "Remets ces étapes de l'histoire de Guernica dans l'ordre chronologique.", explanation: "Le tableau est peint après le bombardement d'avril 1937, montré à l'Exposition universelle de Paris la même année, puis exilé au MoMA avant de rentrer à Madrid en 1981.", items: ["Le bombardement de la ville basque de Guernica", "L'exposition universelle de Paris présente le tableau", "L'œuvre est conservée au MoMA de New York", "Le tableau rentre à Madrid après la mort de Franco"])
    ]
        ),
    ]
}
