import Foundation

// GENERATED by scripts/split_course_data.py from Services/CourseData.swift.
// Do not edit: change CourseData.swift and rerun the script.
//
// `CourseData.swift` itself is excluded from the Sophia target: one 1.6 MB array
// literal took the Swift type-checker past 250 GB of memory. The chunks are small
// literals; flattening keeps the original order.
nonisolated enum CourseData {
    static let allCourses: [Course] = [
        chunk01,
        chunk02,
        chunk03,
        chunk04,
        chunk05,
        chunk06,
        chunk07,
        chunk08,
        chunk09,
        chunk10,
        chunk11,
        chunk12,
        chunk13,
        chunk14,
        chunk15,
        chunk16,
        chunk17,
        chunk18,
        chunk19,
        chunk20,
        chunk21,
    ].flatMap { $0 }
}
