import Foundation

// GENERATED by scripts/split_course_data.py from Services/CourseData.swift.
// Do not edit: change CourseData.swift and rerun the script.
nonisolated extension CourseData {
    static let chunk21: [Course] = [
        Course(
            id: "course_303_pourquoi_certains_detestent_ils_la",
            title: "Pourquoi certains détestent-ils la coriandre ?",
            description: "Pour une partie de l'humanité, la coriandre a un goût de savon. En cause : une seule lettre qui change dans un gène de l'odorat, et peut-être un héritage de nos ancêtres.",
            subject: .sciences,
            subcategory: "Notre quotidien expliqué",
            lessons: [
                LessonPage(id: "course_303_pourquoi_certains_detestent_ils_la_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_303_pourquoi_certains_detestent_ils_la_p1", title: "Les récepteurs olfactifs, du nez au cerveau", content: ""),
                LessonPage(id: "course_303_pourquoi_certains_detestent_ils_la_p2", title: "OR6A2, le gène du goût de savon", content: ""),
                LessonPage(id: "course_303_pourquoi_certains_detestent_ils_la_p3", title: "Pourquoi cette mutation a-t-elle survécu ?", content: ""),
                LessonPage(id: "course_303_pourquoi_certains_detestent_ils_la_p4", title: "Peut-on apprendre à aimer la coriandre ?", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_303_pourquoi_certains_detestent_ils_la_q1", question: "Où se trouvent les récepteurs olfactifs ?", options: ["Sur des cellules de la cavité nasale", "Sur la langue", "Dans l'estomac", "Dans l'oreille interne"], correctIndex: 0, explanation: "Les récepteurs olfactifs sont portés par des cellules de la cavité nasale : ils détectent les molécules des aliments et envoient un signal au cerveau."),
        QuizQuestion(id: "course_303_pourquoi_certains_detestent_ils_la_q2", question: "Quel gène est responsable du goût de savon de la coriandre ?", options: ["OR6A2", "BRCA1", "FOXP2", "HLA-B27"], correctIndex: 0, explanation: "Les généticiens ont identifié le gène OR6A2, qui code un récepteur olfactif sensible aux aldéhydes de la coriandre."),
        QuizQuestion(id: "course_303_pourquoi_certains_detestent_ils_la_q3", question: "Quelles molécules de la coriandre le récepteur OR6A2 détecte-t-il ?", options: ["Des aldéhydes insaturés", "Des sucres", "De la caféine", "Des acides gras"], correctIndex: 0, explanation: "Le récepteur OR6A2 est sensible aux aldéhydes insaturés, que la plupart des gens perçoivent comme une note fraîche et herbacée."),
        QuizQuestion(id: "course_303_pourquoi_certains_detestent_ils_la_q4", type: .trueFalse, question: "Vrai ou faux : chez les personnes concernées, le récepteur OR6A2 ne fonctionne plus du tout.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "Le récepteur fonctionne encore et envoie bien un signal au cerveau, mais ce signal est inexact : il est interprété comme un goût de savon."),
        QuizQuestion(id: "course_303_pourquoi_certains_detestent_ils_la_q5", question: "Qu'est-ce qu'un polymorphisme nucléotidique, ou SNP ?", options: ["Une variation d'une seule lettre de l'ADN", "Un gène présent en double exemplaire", "Un chromosome manquant", "Une protéine mal repliée"], correctIndex: 0, explanation: "Un SNP est une variation d'une seule « lettre » de l'ADN, qui suffit à modifier la façon dont un gène s'exprime."),
        QuizQuestion(id: "course_303_pourquoi_certains_detestent_ils_la_q6", type: .percentageSlider, question: "Dans les régions du monde les plus concernées, quelle part de la population porte la variante du gène ?", explanation: "Selon la région du monde, 4 % à 20 % de la population porte cette variante du gène OR6A2.", correctValue: 20, sliderMin: 0, sliderMax: 100, tolerance: 3, unit: "%"),
        QuizQuestion(id: "course_303_pourquoi_certains_detestent_ils_la_q7", question: "Selon certains biologistes de l'évolution, à quoi aurait servi cette variante génétique ?", options: ["À éviter des plantes toxiques au goût de savon", "À mieux digérer les épices", "À reconnaître les plantes médicinales", "À résister aux infections"], correctIndex: 0, explanation: "L'hypothèse est celle d'un mécanisme de survie : le dégoût du goût de savon détournait nos ancêtres de plantes toxiques qui dégagent la même saveur."),
        QuizQuestion(id: "course_303_pourquoi_certains_detestent_ils_la_q8", type: .trueFalse, question: "Vrai ou faux : on peut apprendre à supporter la coriandre en l'associant à des plats que l'on aime déjà.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "En ajoutant la coriandre à des plats appréciés, ou en la masquant avec du citron ou du vinaigre, on apprend au cerveau qu'elle n'est pas une menace.")
    ]
        ),
        Course(
            id: "course_304_pourquoi_rougit_on",
            title: "Pourquoi rougit-on ?",
            description: "Une remarque gênante, un compliment : dans les deux cas, les joues chauffent et rosissent. Ce que le corps fabrique à cet instant, et pourquoi on ne peut presque rien y faire.",
            subject: .sciences,
            subcategory: "Notre quotidien expliqué",
            lessons: [
                LessonPage(id: "course_304_pourquoi_rougit_on_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_304_pourquoi_rougit_on_p1", title: "Un coup de chaud sous la peau", content: ""),
                LessonPage(id: "course_304_pourquoi_rougit_on_p2", title: "La gêne, un réflexe de fuite", content: ""),
                LessonPage(id: "course_304_pourquoi_rougit_on_p3", title: "Rougir aussi de plaisir", content: ""),
                LessonPage(id: "course_304_pourquoi_rougit_on_p4", title: "Peut-on s'empêcher de rougir ?", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_304_pourquoi_rougit_on_q1", question: "Qu'est-ce qui donne directement sa couleur rouge au visage quand on rougit ?", options: ["Un afflux de sang dans des vaisseaux proches de la surface de la peau", "Une contraction des muscles du visage", "Une réaction allergique de la peau", "Une baisse de la température du visage"], correctIndex: 0, explanation: "Le volume de sang qui circule dans les petits vaisseaux du visage augmente ; comme ils affleurent sous la peau, la rougeur se voit."),
        QuizQuestion(id: "course_304_pourquoi_rougit_on_q2", question: "Quelle partie du système nerveux commande le rougissement ?", options: ["Le système nerveux sympathique", "Le nerf optique", "La moelle épinière", "Le cervelet"], correctIndex: 0, explanation: "Le rougissement est piloté par le système nerveux sympathique, la branche qui déclenche la réaction de lutte ou de fuite."),
        QuizQuestion(id: "course_304_pourquoi_rougit_on_q3", type: .trueFalse, question: "Vrai ou faux : quand le système nerveux sympathique s'active, la température du corps baisse.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "C'est l'inverse : le cœur accélère et la température monte, ce qui pousse les vaisseaux du visage à se dilater pour évacuer la chaleur."),
        QuizQuestion(id: "course_304_pourquoi_rougit_on_q4", type: .chronological, question: "Remets dans l'ordre les étapes qui mènent au rougissement.", explanation: "La menace perçue active le système sympathique, le corps chauffe, les vaisseaux du visage se dilatent pour évacuer la chaleur, et la peau rougit.", items: ["Le cerveau perçoit une situation gênante comme une menace", "Le système nerveux sympathique s'active", "Le cœur accélère et la température monte", "Les vaisseaux du visage se dilatent", "La peau prend une teinte rose ou rouge"]),
        QuizQuestion(id: "course_304_pourquoi_rougit_on_q5", question: "Pourquoi les personnes souffrant d'anxiété sociale rougissent-elles plus facilement ?", options: ["Un regard plus négatif sur elles-mêmes amplifie la réponse du système sympathique", "Leurs vaisseaux sanguins sont plus larges", "Leur peau est plus fine", "Leur cœur bat naturellement plus lentement"], correctIndex: 0, explanation: "Leur biais négatif envers elles-mêmes renforce la réponse du système sympathique, et la peur de rougir entretient ensuite la boucle."),
        QuizQuestion(id: "course_304_pourquoi_rougit_on_q6", type: .trueFalse, question: "Vrai ou faux : un compliment en public peut faire rougir autant qu'une remarque humiliante.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "L'attention positive déclenche le même mécanisme : on se sent exposé au regard des autres, et le système sympathique lance la réponse d'urgence."),
        QuizQuestion(id: "course_304_pourquoi_rougit_on_q7", question: "Face à un éloge public, que se passe-t-il selon le cours ?", options: ["Le cerveau reconnaît l'attention positive, mais le système sympathique hésite encore entre fuir ou rester", "Le cerveau confond l'éloge avec une insulte", "Le système sympathique se met en veille", "Les vaisseaux du visage se resserrent"], correctIndex: 0, explanation: "Le cerveau distingue très bien félicitation et humiliation, mais le système sympathique, plus fruste, n'a pas encore décidé s'il faut fuir."),
        QuizQuestion(id: "course_304_pourquoi_rougit_on_q8", question: "Quelles approches peuvent aider à réduire la peur de rougir ?", options: ["La thérapie d'exposition et la pleine conscience", "Les antibiotiques et le repos", "Le sport intensif et le jeûne", "Les compresses froides et le maquillage"], correctIndex: 0, explanation: "La thérapie d'exposition et la pleine conscience aident le cerveau à ne plus classer les situations gênantes comme dangereuses et désamorcent la peur de rougir.")
    ]
        ),
        Course(
            id: "course_305_pourquoi_deteste_t_on_entendre_sa_voix",
            title: "Pourquoi déteste-t-on entendre sa voix enregistrée ?",
            description: "Sur un enregistrement, ta voix te paraît étrangère, presque gênante. Le coupable n'est pas le micro : c'est ton crâne, et la façon dont ton cerveau se reconnaît.",
            subject: .sciences,
            subcategory: "Notre quotidien expliqué",
            lessons: [
                LessonPage(id: "course_305_pourquoi_deteste_t_on_entendre_sa_voix_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_305_pourquoi_deteste_t_on_entendre_sa_voix_p1", title: "Parler et entendre : de l'air qui vibre", content: ""),
                LessonPage(id: "course_305_pourquoi_deteste_t_on_entendre_sa_voix_p2", title: "S'entendre par les os", content: ""),
                LessonPage(id: "course_305_pourquoi_deteste_t_on_entendre_sa_voix_p3", title: "La vallée de l'étrange", content: ""),
                LessonPage(id: "course_305_pourquoi_deteste_t_on_entendre_sa_voix_p4", title: "Une voix, mille versions de soi", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_305_pourquoi_deteste_t_on_entendre_sa_voix_q1", question: "Qu'est-ce qui fait vibrer les cordes vocales quand on parle ?", options: ["L'air chassé des poumons par le diaphragme", "Les battements du cœur", "Les mouvements de la langue", "Les os du crâne"], correctIndex: 0, explanation: "Le diaphragme pousse l'air des poumons vers la gorge ; en passant entre les cordes vocales, cet air les fait vibrer à grande vitesse."),
        QuizQuestion(id: "course_305_pourquoi_deteste_t_on_entendre_sa_voix_q2", type: .chronological, question: "Remets dans l'ordre le trajet d'un son entendu par conduction aérienne.", explanation: "Le son traverse le conduit auditif, fait vibrer le tympan, est amplifié par les os de l'oreille moyenne, devient un signal électrique dans la cochlée, puis rejoint le cerveau par le nerf auditif.", items: ["Les ondes sonores traversent le conduit auditif", "Le tympan se met à vibrer", "Les os de l'oreille moyenne amplifient les vibrations", "La cochlée produit un signal électrique", "Le nerf auditif transmet le signal au cerveau"]),
        QuizQuestion(id: "course_305_pourquoi_deteste_t_on_entendre_sa_voix_q3", question: "Comment s'appellent les minuscules cils de la cochlée qui se plient sous les vibrations ?", options: ["Les stéréocils", "Les neurones", "Les osselets", "Les alvéoles"], correctIndex: 0, explanation: "Les cellules ciliées de la cochlée portent des stéréocils, qui se plient au rythme des vibrations et produisent le signal électrique."),
        QuizQuestion(id: "course_305_pourquoi_deteste_t_on_entendre_sa_voix_q4", question: "Qu'est-ce que la conduction osseuse ?", options: ["La transmission des vibrations de la voix par les os du crâne jusqu'à l'oreille interne", "La transmission du son par l'air jusqu'au tympan", "L'amplification du son par les os de l'oreille moyenne", "La vibration des cordes vocales"], correctIndex: 0, explanation: "Quand on parle, les vibrations de la voix se propagent à travers les os du crâne directement jusqu'à l'oreille interne, sans passer par le tympan."),
        QuizQuestion(id: "course_305_pourquoi_deteste_t_on_entendre_sa_voix_q5", type: .trueFalse, question: "Vrai ou faux : quand on écoute un enregistrement de sa voix, le cerveau reçoit à la fois la conduction aérienne et la conduction osseuse.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "Un enregistrement ne passe que par la conduction aérienne ; la conduction osseuse n'existe que lorsqu'on parle soi-même."),
        QuizQuestion(id: "course_305_pourquoi_deteste_t_on_entendre_sa_voix_q6", question: "De quels domaines vient le concept de vallée de l'étrange ?", options: ["De la robotique et de l'animation", "De la géologie", "De la musique classique", "De la médecine du sport"], correctIndex: 0, explanation: "La vallée de l'étrange est une notion utilisée en robotique et en animation pour décrire le malaise face à une imitation presque humaine."),
        QuizQuestion(id: "course_305_pourquoi_deteste_t_on_entendre_sa_voix_q7", type: .trueFalse, question: "Vrai ou faux : les chercheurs ont une explication définitive au malaise que provoque notre voix enregistrée.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "Ils n'ont pas encore de réponse définitive ; la vallée de l'étrange est une piste, pas une certitude."),
        QuizQuestion(id: "course_305_pourquoi_deteste_t_on_entendre_sa_voix_q8", question: "Selon le cours, comment la voix change-t-elle selon le contexte ?", options: ["Plus grave dans un cadre professionnel, plus aiguë avec un bébé ou un animal", "Plus aiguë dans un cadre professionnel, plus grave avec un bébé", "Elle ne change jamais", "Elle devient plus forte avec les animaux"], correctIndex: 0, explanation: "On baisse le ton pour paraître plus posé au travail, et la voix monte dans les aigus face à un bébé ou à un animal de compagnie.")
    ]
        ),
        Course(
            id: "course_306_pourquoi_rit_on_quand_on_nous_chatouille",
            title: "Pourquoi rit-on quand on nous chatouille ?",
            description: "Un frôlement de plume agace, une main sous les aisselles fait éclater de rire. Ce que la peau, le cerveau et le jeu fabriquent ensemble, et pourquoi tu ne peux pas te chatouiller toi-même.",
            subject: .sciences,
            subcategory: "Notre quotidien expliqué",
            lessons: [
                LessonPage(id: "course_306_pourquoi_rit_on_quand_on_nous_chatouille_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_306_pourquoi_rit_on_quand_on_nous_chatouille_p1", title: "Deux chatouilles : knismesis et gargalesis", content: ""),
                LessonPage(id: "course_306_pourquoi_rit_on_quand_on_nous_chatouille_p2", title: "Du toucher au rire : le circuit du cerveau", content: ""),
                LessonPage(id: "course_306_pourquoi_rit_on_quand_on_nous_chatouille_p3", title: "Pourquoi ne peut-on pas se chatouiller soi-même ?", content: ""),
                LessonPage(id: "course_306_pourquoi_rit_on_quand_on_nous_chatouille_p4", title: "À quoi servent les chatouilles ?", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_306_pourquoi_rit_on_quand_on_nous_chatouille_q1", question: "Laquelle de ces deux chatouilles déclenche le rire involontaire ?", options: ["La gargalesis", "La knismesis", "La kinesthésie", "La proprioception"], correctIndex: 0, explanation: "La gargalesis, faite de mouvements rapides et appuyés, provoque tortillements et rire involontaire ; la knismesis, légère, ne fait pas rire."),
        QuizQuestion(id: "course_306_pourquoi_rit_on_quand_on_nous_chatouille_q2", type: .trueFalse, question: "Vrai ou faux : la knismesis, la chatouille légère « comme une plume », déclenche généralement le rire.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "La knismesis ressemble à une démangeaison et peut se ressentir partout sur le corps, mais elle ne provoque pas le rire propre au jeu."),
        QuizQuestion(id: "course_306_pourquoi_rit_on_quand_on_nous_chatouille_q3", question: "Sur quelles zones du corps la gargalesis fonctionne-t-elle ?", options: ["Les aisselles, le cou, le torse, le ventre et les pieds", "Toute la surface de la peau, sans distinction", "Uniquement la paume des mains", "Uniquement le visage et le cuir chevelu"], correctIndex: 0, explanation: "La gargalesis est localisée aux aisselles, au cou, au torse, au ventre et aux pieds, alors que la knismesis se ressent largement sur le corps."),
        QuizQuestion(id: "course_306_pourquoi_rit_on_quand_on_nous_chatouille_q4", question: "Que sont les mécanorécepteurs ?", options: ["Des capteurs de la peau qui réagissent à une pression ou à un mouvement", "Des neurones du cerveau qui déclenchent le rire", "Des muscles qui font se tortiller le corps", "Des cellules qui produisent la dopamine"], correctIndex: 0, explanation: "Les mécanorécepteurs sont des récepteurs sensoriels de la peau activés par une stimulation mécanique ; c'est par eux que commence la chatouille."),
        QuizQuestion(id: "course_306_pourquoi_rit_on_quand_on_nous_chatouille_q5", type: .chronological, question: "Remets dans l'ordre les étapes qui mènent du contact au rire.", explanation: "Tout commence dans la peau, le signal rejoint ensuite les circuits du cerveau liés au jeu et à la récompense, et le rire est enfin déclenché dans l'opercule frontal et l'aire motrice supplémentaire.", items: ["Les mécanorécepteurs de la peau captent le contact", "Le signal se mêle dans le cerveau aux signaux du jeu", "L'opercule frontal et l'aire motrice supplémentaire déclenchent le rire"]),
        QuizQuestion(id: "course_306_pourquoi_rit_on_quand_on_nous_chatouille_q6", question: "Selon l'hypothèse de la prévisibilité, pourquoi ne peut-on pas se chatouiller soi-même ?", options: ["Parce que le cerveau anticipe la sensation et atténue le signal", "Parce que nos doigts ne bougent pas assez vite", "Parce que la peau des pieds n'a pas de mécanorécepteurs", "Parce que le rire a besoin d'une respiration profonde"], correctIndex: 0, explanation: "Quand la sensation est attendue, comme ses propres doigts sur son pied, le signal sensoriel est atténué dans le traitement nerveux ; l'autre hypothèse invoque l'absence de contexte social."),
        QuizQuestion(id: "course_306_pourquoi_rit_on_quand_on_nous_chatouille_q7", type: .trueFalse, question: "Vrai ou faux : pour étudier la gargalesis, les chercheurs chatouillent des rats.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Les rats servent de modèle parce que leurs vocalisations et leur comportement de jeu sont bien documentés."),
        QuizQuestion(id: "course_306_pourquoi_rit_on_quand_on_nous_chatouille_q8", question: "Selon l'hypothèse de la survie, à quoi serviraient les chatouilles ?", options: ["À apprendre, lors de fausses bagarres, où sont les zones vulnérables du corps", "À renforcer les muscles du ventre et du cou", "À signaler la présence d'insectes sur la peau", "À réguler la température du corps"], correctIndex: 0, explanation: "Dans cette hypothèse, les chatouilles des fausses bagarres apprennent à protéger les zones vulnérables et à préparer des stratégies de défense ; l'autre hypothèse y voit un simple jeu qui crée des liens.")
    ]
        ),
        Course(
            id: "course_307_comment_le_christianisme_est_il_devenu",
            title: "Comment le christianisme est-il devenu religion d'État ?",
            description: "En 313, Constantin accorde aux chrétiens le droit de pratiquer leur foi. En 380, Théodose fait du christianisme de Nicée la religion officielle de l'empire : entre les deux, un concile, des querelles sans fin et un empereur qui tente de ramener les anciens dieux.",
            subject: .histoire,
            subcategory: "Antiquité & Moyen Âge",
            lessons: [
                LessonPage(id: "course_307_comment_le_christianisme_est_il_devenu_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_307_comment_le_christianisme_est_il_devenu_p1", title: "Constantin et le concile de Nicée", content: ""),
                LessonPage(id: "course_307_comment_le_christianisme_est_il_devenu_p2", title: "Un empire encore païen", content: ""),
                LessonPage(id: "course_307_comment_le_christianisme_est_il_devenu_p3", title: "Théodose impose la foi de Nicée", content: ""),
                LessonPage(id: "course_307_comment_le_christianisme_est_il_devenu_p4", title: "Une société changée en profondeur", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_307_comment_le_christianisme_est_il_devenu_q1", question: "Que décide l'édit de Milan, en 313 ?", options: ["Les chrétiens peuvent pratiquer librement leur foi et récupèrent leurs biens confisqués", "Le christianisme devient la religion officielle de l'empire", "Les cultes païens sont interdits dans tout l'empire", "Tous les habitants de l'empire doivent se faire baptiser"], correctIndex: 0, explanation: "L'édit de Milan légalise le culte chrétien et ordonne la restitution des biens des Églises, mais il ne fait pas du christianisme la religion officielle."),
        QuizQuestion(id: "course_307_comment_le_christianisme_est_il_devenu_q2", type: .numericSlider, question: "En quelle année Constantin réunit-il le concile de Nicée ?", explanation: "Constantin convoque le concile de Nicée en 325 pour trancher la question de la nature de Jésus.", correctValue: 325, sliderMin: 300, sliderMax: 400, tolerance: 5, unit: ""),
        QuizQuestion(id: "course_307_comment_le_christianisme_est_il_devenu_q3", question: "Quelle question le concile de Nicée devait-il trancher ?", options: ["Qui est Jésus et quel est son lien avec Dieu le Père", "Si les évêques ont le droit de se marier", "Quelle langue utiliser pendant les offices", "Si les chrétiens peuvent servir dans l'armée"], correctIndex: 0, explanation: "Les évêques réunis à Nicée débattent de la nature de Jésus et de sa relation au Père, et adoptent le Credo de Nicée."),
        QuizQuestion(id: "course_307_comment_le_christianisme_est_il_devenu_q4", type: .trueFalse, question: "Vrai ou faux : après le concile de Nicée, les chrétiens cessent de se disputer sur la nature de Jésus.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "Les querelles théologiques durent encore des décennies, et certains empereurs soutiennent des positions opposées à la formule de Nicée."),
        QuizQuestion(id: "course_307_comment_le_christianisme_est_il_devenu_q5", question: "Que fait l'empereur Julien entre 361 et 363 ?", options: ["Il rétablit la religion traditionnelle de Rome et coupe les subventions aux institutions chrétiennes", "Il fait fermer tous les temples païens", "Il convoque un nouveau concile pour unir les chrétiens", "Il transfère la capitale de l'empire à Constantinople"], correctIndex: 0, explanation: "Julien honore les anciens dieux et retire le soutien impérial aux institutions chrétiennes, d'où son surnom d'Apostat."),
        QuizQuestion(id: "course_307_comment_le_christianisme_est_il_devenu_q6", question: "En quoi l'édit de Thessalonique de 380 va-t-il plus loin que l'édit de Milan ?", options: ["Il réserve le soutien de l'État au christianisme fidèle à Nicée et le lie au pouvoir impérial", "Il accorde seulement la liberté de culte aux chrétiens", "Il autorise de nouveau les sacrifices païens", "Il supprime la fonction d'évêque"], correctIndex: 0, explanation: "Constantin avait donné la liberté aux chrétiens ; Théodose choisit quelle forme de christianisme l'État reconnaît et en fait la religion officielle."),
        QuizQuestion(id: "course_307_comment_le_christianisme_est_il_devenu_q7", type: .chronological, question: "Remets ces événements dans l'ordre.", explanation: "Pont Milvius en 312, concile de Nicée en 325, règne de Julien de 361 à 363, édit de Thessalonique en 380.", items: ["Bataille du pont Milvius", "Concile de Nicée", "Règne de Julien", "Édit de Thessalonique"]),
        QuizQuestion(id: "course_307_comment_le_christianisme_est_il_devenu_q8", type: .trueFalse, question: "Vrai ou faux : Constantin s'est fait baptiser juste après sa victoire du pont Milvius.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "Constantin n'a été baptisé qu'à la fin de sa vie : protéger politiquement les chrétiens et devenir soi-même chrétien n'allaient pas de pair.")
    ]
        ),
        Course(
            id: "course_308_quelle_a_ete_la_guerre_la_plus",
            title: "Quelle a été la guerre la plus meurtrière de l'histoire ?",
            description: "On pense à la Seconde Guerre mondiale. Pourtant, selon la façon de compter les morts, le conflit le plus meurtrier de l'histoire est une guerre civile chinoise du XIXe siècle, née des visions d'un candidat recalé aux examens impériaux.",
            subject: .histoire,
            subcategory: "Époque moderne & XIXe siècle",
            lessons: [
                LessonPage(id: "course_308_quelle_a_ete_la_guerre_la_plus_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_308_quelle_a_ete_la_guerre_la_plus_p1", title: "Hong Xiuquan, frère cadet de Jésus", content: ""),
                LessonPage(id: "course_308_quelle_a_ete_la_guerre_la_plus_p2", title: "Un mouvement religieux devenu État", content: ""),
                LessonPage(id: "course_308_quelle_a_ete_la_guerre_la_plus_p3", title: "Nankin, la capitale céleste", content: ""),
                LessonPage(id: "course_308_quelle_a_ete_la_guerre_la_plus_p4", title: "La fin du Royaume de Dieu", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_308_quelle_a_ete_la_guerre_la_plus_q1", question: "Selon le cours, quel conflit est le principal candidat au titre de guerre la plus meurtrière de l'histoire ?", options: ["La révolte des Taiping", "La Seconde Guerre mondiale", "La Première Guerre mondiale", "Les guerres napoléoniennes"], correctIndex: 0, explanation: "Si l'on compte aussi les civils morts de faim et de maladie, la révolte des Taiping, entre 1850 et 1864, dépasse les autres conflits."),
        QuizQuestion(id: "course_308_quelle_a_ete_la_guerre_la_plus_q2", type: .numericSlider, question: "Selon les estimations prudentes, combien de millions de morts la révolte des Taiping a-t-elle fait au minimum ?", explanation: "Les sources prudentes comptent 20 à 30 millions de morts ; d'autres vont plus haut, et le chiffre exact reste inconnu.", correctValue: 20, sliderMin: 1, sliderMax: 60, tolerance: 3, unit: "millions"),
        QuizQuestion(id: "course_308_quelle_a_ete_la_guerre_la_plus_q3", question: "Qui Hong Xiuquan prétend-il être ?", options: ["Le frère cadet de Jésus", "La réincarnation de Confucius", "Un descendant de la dynastie Ming", "Le fils de l'empereur Qing"], correctIndex: 0, explanation: "Après avoir lu des textes chrétiens, Hong conclut que Dieu est son père céleste et Jésus son frère aîné."),
        QuizQuestion(id: "course_308_quelle_a_ete_la_guerre_la_plus_q4", question: "Quel échec précède les visions de Hong Xiuquan ?", options: ["Il rate les examens impériaux", "Il est chassé de l'armée Qing", "Il perd sa ferme dans une inondation", "Il est exclu d'une mission chrétienne"], correctIndex: 0, explanation: "Hong est un candidat malheureux aux examens impériaux, les concours qui ouvrent les portes de l'administration chinoise."),
        QuizQuestion(id: "course_308_quelle_a_ete_la_guerre_la_plus_q5", type: .trueFalse, question: "Vrai ou faux : les Taiping ont pris Pékin, la capitale des Qing.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "Leur Marche vers le Nord approche de Pékin mais échoue ; les Taiping ne prennent jamais la capitale impériale."),
        QuizQuestion(id: "course_308_quelle_a_ete_la_guerre_la_plus_q6", question: "Quel nom les Taiping donnent-ils à Nankin après l'avoir prise en 1853 ?", options: ["Tianjing, la Capitale céleste", "Shangdi, la Cité de Dieu", "Taiping, la Ville de la Grande Paix", "Jinling, la Colline d'or"], correctIndex: 0, explanation: "Rebaptiser Nankin Tianjing, la « Capitale céleste », signale que Dieu soutient la révolte et son royaume nouveau."),
        QuizQuestion(id: "course_308_quelle_a_ete_la_guerre_la_plus_q7", type: .chronological, question: "Remets ces étapes de la révolte des Taiping dans l'ordre.", explanation: "Les échecs de Hong précèdent le soulèvement ; Nankin tombe en 1853, Anqing est reprise en 1861 et Nankin en juillet 1864.", items: ["Hong Xiuquan échoue aux examens impériaux", "Les Taiping s'emparent de Nankin", "Les Qing reprennent Anqing", "Les troupes impériales entrent dans Nankin"]),
        QuizQuestion(id: "course_308_quelle_a_ete_la_guerre_la_plus_q8", type: .trueFalse, question: "Vrai ou faux : la religion des Taiping était une copie fidèle du christianisme européen.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "Elle mêle des idées protestantes et des traditions chinoises, avec ses propres doctrines et ses propres rites, loin du christianisme classique.")
    ]
        ),
        Course(
            id: "course_309_d_ou_vient_la_science_fiction",
            title: "D'où vient la science-fiction ?",
            description: "Au IIe siècle, Lucien de Samosate envoyait déjà son narrateur sur la Lune. Mais il faut la révolution scientifique, puis le monstre de Mary Shelley, pour que ces rêves deviennent une façon nouvelle d'interroger le changement.",
            subject: .litterature,
            subcategory: "Anglo-saxons & littérature mondiale",
            lessons: [
                LessonPage(id: "course_309_d_ou_vient_la_science_fiction_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_309_d_ou_vient_la_science_fiction_p1", title: "La lunette change la question", content: ""),
                LessonPage(id: "course_309_d_ou_vient_la_science_fiction_p2", title: "Frankenstein donne sa forme au genre", content: ""),
                LessonPage(id: "course_309_d_ou_vient_la_science_fiction_p3", title: "Un nom venu bien plus tard", content: ""),
                LessonPage(id: "course_309_d_ou_vient_la_science_fiction_p4", title: "Une façon de penser le changement", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_309_d_ou_vient_la_science_fiction_q1", question: "Quel auteur du IIe siècle envoie déjà son narrateur sur la Lune ?", options: ["Lucien de Samosate", "Homère", "Ovide", "Plutarque"], correctIndex: 0, explanation: "Dans son Histoire véritable, Lucien de Samosate raconte un voyage satirique jusqu'à la Lune, près de deux mille ans avant les vols spatiaux."),
        QuizQuestion(id: "course_309_d_ou_vient_la_science_fiction_q2", question: "Qu'est-ce que le Somnium de Kepler ?", options: ["Un récit de voyage vers la Lune, publié après la mort de l'auteur", "Un traité sur les orbites des planètes", "Un manuel de fabrication des lunettes", "Un poème sur les comètes"], correctIndex: 0, explanation: "Publié en 1634, le Somnium imagine un voyage vers la Lune et décrit la Terre vue de l'espace."),
        QuizQuestion(id: "course_309_d_ou_vient_la_science_fiction_q3", type: .numericSlider, question: "En quelle année Mary Shelley publie-t-elle Frankenstein ?", explanation: "Frankenstein paraît en 1818, en pleine révolution industrielle.", correctValue: 1818, sliderMin: 1750, sliderMax: 1900, tolerance: 5, unit: ""),
        QuizQuestion(id: "course_309_d_ou_vient_la_science_fiction_q4", question: "Quelle est la question centrale de Frankenstein, selon le cours ?", options: ["Ce qui arrive quand un savant utilise ses connaissances pour créer la vie", "Comment voyager dans le temps", "Si d'autres planètes sont habitées", "Comment une machine peut apprendre à penser"], correctIndex: 0, explanation: "Victor Frankenstein franchit une frontière tenue pour contre-nature, et son succès scientifique tourne au désastre."),
        QuizQuestion(id: "course_309_d_ou_vient_la_science_fiction_q5", type: .trueFalse, question: "Vrai ou faux : Hugo Gernsback a inventé la science-fiction.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "Gernsback n'a pas créé le genre : il lui a donné un nom reconnu, des magazines et un public."),
        QuizQuestion(id: "course_309_d_ou_vient_la_science_fiction_q6", question: "Quel mot Gernsback emploie-t-il avant que « science fiction » ne s'impose ?", options: ["Scientifiction", "Futurofiction", "Technoroman", "Astrofiction"], correctIndex: 0, explanation: "Gernsback parle d'abord de « scientifiction » ; l'expression « science fiction » s'impose avec Science Wonder Stories en 1929."),
        QuizQuestion(id: "course_309_d_ou_vient_la_science_fiction_q7", type: .chronological, question: "Remets ces œuvres dans l'ordre de leur parution.", explanation: "L'Histoire véritable date du IIe siècle, le Somnium de 1634, Frankenstein de 1818 et Amazing Stories de 1926.", items: ["L'Histoire véritable de Lucien", "Le Somnium de Kepler", "Frankenstein de Mary Shelley", "Le premier numéro d'Amazing Stories"]),
        QuizQuestion(id: "course_309_d_ou_vient_la_science_fiction_q8", question: "Selon le cours, quel est le sujet le plus profond de la science-fiction ?", options: ["Le changement", "Les vaisseaux spatiaux", "Les extraterrestres", "Les robots"], correctIndex: 0, explanation: "Vaisseaux, robots et extraterrestres ne sont que des décors : la science-fiction demande ce qui arrive quand une découverte transforme la vie humaine.")
    ]
        ),
        Course(
            id: "course_310_qui_a_trace_les_frontieres_de_l_afrique",
            title: "Qui a tracé les frontières de l'Afrique ?",
            description: "Sur la carte, les frontières africaines semblent tirées à la règle. Elles sont pourtant nées de traités, de guerres locales et d'un choix des États indépendants, pas d'une seule réunion à Berlin.",
            subject: .histoire,
            subcategory: "Époque moderne & XIXe siècle",
            lessons: [
                LessonPage(id: "course_310_qui_a_trace_les_frontieres_de_l_afrique_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_310_qui_a_trace_les_frontieres_de_l_afrique_p1", title: "Revendiquer n'est pas gouverner", content: ""),
                LessonPage(id: "course_310_qui_a_trace_les_frontieres_de_l_afrique_p2", title: "Des frontières nées de conflits locaux", content: ""),
                LessonPage(id: "course_310_qui_a_trace_les_frontieres_de_l_afrique_p3", title: "Les nouveaux États héritent des cartes", content: ""),
                LessonPage(id: "course_310_qui_a_trace_les_frontieres_de_l_afrique_p4", title: "Des frontières aux nombreux auteurs", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_310_qui_a_trace_les_frontieres_de_l_afrique_q1", question: "Qu'est-ce que la conférence de Berlin de 1884-1885 a réellement décidé ?", options: ["Les règles que les puissances européennes devaient suivre pour acquérir des colonies", "Le tracé définitif de toutes les frontières africaines", "L'indépendance des premiers États africains", "Le partage de l'Afrique entre deux puissances seulement"], correctIndex: 0, explanation: "La conférence fixe des règles du jeu entre Européens ; la plupart des frontières sont tracées ensuite, par traités, échanges de territoires et guerres."),
        QuizQuestion(id: "course_310_qui_a_trace_les_frontieres_de_l_afrique_q2", type: .trueFalse, question: "Vrai ou faux : les souverains africains ont participé à la conférence de Berlin sur un pied d'égalité avec les Européens.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "Les discussions se tiennent entre Européens ; les États et souverains africains n'y sont pas admis sur un pied d'égalité."),
        QuizQuestion(id: "course_310_qui_a_trace_les_frontieres_de_l_afrique_q3", question: "Que signifie le principe d'« occupation effective » adopté à Berlin ?", options: ["Un État doit prouver qu'il exerce réellement le pouvoir sur le territoire qu'il revendique", "Une colonie doit être peuplée de colons européens", "Un territoire appartient au premier explorateur qui l'a traversé", "Une frontière doit suivre un fleuve ou une montagne"], correctIndex: 0, explanation: "Colorier une carte ne suffit pas : il faut une armée, des fonctionnaires et un pouvoir réel sur place pour que la revendication soit reconnue."),
        QuizQuestion(id: "course_310_qui_a_trace_les_frontieres_de_l_afrique_q4", question: "Quel royaume d'Afrique de l'Ouest a longtemps résisté à la conquête britannique ?", options: ["Le royaume ashanti", "Le royaume du Kongo", "L'Empire éthiopien", "Le royaume zoulou"], correctIndex: 0, explanation: "Les Ashanti repoussent longtemps les Britanniques, qui finissent par intégrer leur territoire au système colonial."),
        QuizQuestion(id: "course_310_qui_a_trace_les_frontieres_de_l_afrique_q5", type: .trueFalse, question: "Vrai ou faux : toutes les frontières coloniales ont été tracées au hasard.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "Certaines suivent un fleuve, un lac, une montagne ou une limite politique plus ancienne, et les États précoloniaux ont pesé sur le tracé."),
        QuizQuestion(id: "course_310_qui_a_trace_les_frontieres_de_l_afrique_q6", question: "Que prévoit le principe de l'uti possidetis ?", options: ["Un nouvel État conserve le territoire qu'il possédait au moment de son indépendance", "Les frontières doivent être renégociées après chaque indépendance", "Chaque communauté a le droit de former son propre État", "Les anciennes puissances coloniales gardent un droit de regard sur les frontières"], correctIndex: 0, explanation: "Les dirigeants africains acceptent ce principe latin pour éviter que la remise en cause de chaque tracé ne mène à des guerres sans fin."),
        QuizQuestion(id: "course_310_qui_a_trace_les_frontieres_de_l_afrique_q7", type: .numericSlider, question: "En quelle année l'Organisation de l'unité africaine est-elle fondée ?", explanation: "L'OUA est fondée à Addis-Abeba en 1963 ; un an plus tard, ses dirigeants s'engagent à respecter les frontières héritées.", correctValue: 1963, sliderMin: 1945, sliderMax: 1990, tolerance: 2, unit: ""),
        QuizQuestion(id: "course_310_qui_a_trace_les_frontieres_de_l_afrique_q8", type: .chronological, question: "Remets ces événements dans l'ordre.", explanation: "1874, 1884-1885, 1963, puis 1964 : la conquête précède la conférence, et les indépendances confirment les tracés.", items: ["Les troupes britanniques marchent sur Kumasi, capitale ashanti", "La conférence de Berlin fixe les règles du partage colonial", "L'Organisation de l'unité africaine est fondée à Addis-Abeba", "Les dirigeants africains s'engagent à respecter les frontières héritées"])
    ]
        ),
        Course(
            id: "course_311_qui_a_invente_les_zombies",
            title: "Qui a inventé les zombies ?",
            description: "Le mort-vivant lent et affamé du cinéma n'a pas cent ans. Derrière lui se cache une figure haïtienne bien plus ancienne, et bien plus triste : une personne à qui l'on a volé son âme.",
            subject: .mythologie,
            subcategory: "Légendes & créatures",
            lessons: [
                LessonPage(id: "course_311_qui_a_invente_les_zombies_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_311_qui_a_invente_les_zombies_p1", title: "Un mot venu d'Haïti", content: ""),
                LessonPage(id: "course_311_qui_a_invente_les_zombies_p2", title: "Les Américains réinventent la créature", content: ""),
                LessonPage(id: "course_311_qui_a_invente_les_zombies_p3", title: "Hollywood lui donne un corps", content: ""),
                LessonPage(id: "course_311_qui_a_invente_les_zombies_p4", title: "Une métaphore mondiale", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_311_qui_a_invente_les_zombies_q1", question: "Dans la tradition vaudou haïtienne, qu'est-ce qu'un zonbi ?", options: ["Une personne à qui l'on a pris son âme ou son libre arbitre", "Un cadavre affamé qui dévore les vivants", "Un esprit protecteur qui habite les tambours", "Un prêtre chargé de parler aux morts"], correctIndex: 0, explanation: "Le zonbi haïtien n'est pas un monstre affamé mais une figure triste : une personne privée de sa liberté intérieure, contrôlée par un bokor."),
        QuizQuestion(id: "course_311_qui_a_invente_les_zombies_q2", type: .trueFalse, question: "Vrai ou faux : dans les traditions haïtiennes, on devient zonbi après avoir été mordu.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "La morsure et la contagion appartiennent à la culture populaire plus tardive ; en Haïti, le zonbi tient à des rituels secrets qui touchent l'âme et le corps."),
        QuizQuestion(id: "course_311_qui_a_invente_les_zombies_q3", question: "D'où vient le mot « zombi » ?", options: ["De langues africaines parlées par les personnes réduites en esclavage arrivées en Haïti", "Du latin des missionnaires catholiques", "D'un roman américain des années 1920", "Du nom d'un réalisateur de films d'horreur"], correctIndex: 0, explanation: "Le mot est arrivé en Haïti avec les esclaves africains ; il s'écrit zonbi en créole haïtien et zombi en français."),
        QuizQuestion(id: "course_311_qui_a_invente_les_zombies_q4", type: .numericSlider, question: "En quelle année William Seabrook publie-t-il The Magic Island ?", explanation: "Paru en 1929, pendant l'occupation américaine d'Haïti, le livre présente l'île comme un lieu mystérieux et dangereux.", correctValue: 1929, sliderMin: 1900, sliderMax: 1960, tolerance: 3, unit: ""),
        QuizQuestion(id: "course_311_qui_a_invente_les_zombies_q5", type: .trueFalse, question: "Vrai ou faux : dans White Zombie (1932), le zombi est un mort qui sort de sa tombe pour dévorer les vivants.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "Dans ce film, le zombi est un vivant transformé en instrument obéissant, contrôlé par un autre homme."),
        QuizQuestion(id: "course_311_qui_a_invente_les_zombies_q6", question: "Qu'est-ce qui change avec La Nuit des morts-vivants de George A. Romero ?", options: ["Les morts se relèvent et attaquent les vivants sans qu'aucun maître les contrôle", "Le zombi obéit désormais à un sorcier vaudou", "Le zombi retrouve son âme à la fin du film", "L'action se déroule pour la première fois en Haïti"], correctIndex: 0, explanation: "En 1968, Romero supprime le maître : les morts se relèvent d'eux-mêmes et attaquent, ce qui fonde le zombie moderne."),
        QuizQuestion(id: "course_311_qui_a_invente_les_zombies_q7", type: .chronological, question: "Remets ces étapes de l'histoire du zombie dans l'ordre.", explanation: "1915, 1929, 1932 puis 1968 : de l'occupation américaine au film de Romero.", items: ["Les États-Unis occupent Haïti", "William Seabrook publie The Magic Island", "White Zombie sort au cinéma", "George A. Romero tourne La Nuit des morts-vivants"]),
        QuizQuestion(id: "course_311_qui_a_invente_les_zombies_q8", question: "Selon le cours, que peut représenter le zombie aujourd'hui ?", options: ["La peur de la contagion ou une masse qui suit des chefs manipulateurs", "Le retour des ancêtres protecteurs parmi les vivants", "La victoire de la science sur la mort", "La liberté retrouvée d'un peuple opprimé"], correctIndex: 0, explanation: "Devenu métaphore, le zombie parle de contagion, de manipulation des foules, de surconsommation, d'effondrement ou de perte de contrôle.")
    ]
        )
    ]
}
