import Foundation

// GENERATED by scripts/split_course_data.py from Services/CourseData.swift.
// Do not edit: change CourseData.swift and rerun the script.
nonisolated extension CourseData {
    static let chunk07: [Course] = [
        Course(
            id: "course_92_madame_bovary_flaubert",
            title: "Qu'est-ce que le bovarysme, le mal d'Emma Bovary ?",
            description: "Madame Bovary (1857) est le roman du désir impossible : d'une femme qui confond la vie réelle avec les romans sentimentaux qu'elle a lus. Flaubert révolution...",
            subject: .litterature,
            subcategory: "Classiques français & européens",
            lessons: [
                LessonPage(id: "course_92_madame_bovary_flaubert_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_92_madame_bovary_flaubert_p1", title: "Flaubert et l'ascèse de l'écriture", content: ""),
                LessonPage(id: "course_92_madame_bovary_flaubert_p2", title: "Le drame d'Emma : le conflit entre imaginaire et réel", content: ""),
                LessonPage(id: "course_92_madame_bovary_flaubert_p3", title: "La naissance du roman moderne et la censure", content: ""),
                LessonPage(id: "course_92_madame_bovary_flaubert_p4", title: "Le bovarysme : une postérité psychologique", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_92_madame_bovary_flaubert_q1", question: "Qui est l'auteur de Madame Bovary ?", options: ["Gustave Flaubert", "Stendhal", "Honoré de Balzac", "Émile Zola"], correctIndex: 0, explanation: "Gustave Flaubert publie Madame Bovary en 1857, marquant la naissance du réalisme moderne."),
        QuizQuestion(id: "course_92_madame_bovary_flaubert_q2", question: "Qui Emma épouse-t-elle au début du roman ?", options: ["Charles Bovary, médecin de province", "Rodolphe, un riche propriétaire", "Léon, un clerc de notaire", "Homais, l'apothicaire"], correctIndex: 0, explanation: "Emma épouse Charles Bovary, un médecin de province honnête mais terne, avec qui elle s'installe à Yonville."),
        QuizQuestion(id: "course_92_madame_bovary_flaubert_q3", question: "Quel procédé narratif Flaubert invente-t-il dans ce roman, mêlant la voix du narrateur à celle d'un personnage sans guillemets ?", options: ["Le style indirect libre", "Le monologue intérieur", "Le récit épistolaire", "La narration à la première personne"], correctIndex: 0, explanation: "Flaubert invente le style indirect libre : la voix du narrateur se fond avec celle d'Emma, tout en gardant une distance ironique."),
        QuizQuestion(id: "course_92_madame_bovary_flaubert_q4", type: .trueFalse, question: "Vrai ou faux : Flaubert est condamné lors de son procès de 1857 pour Madame Bovary.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "Flaubert est acquitté du chef d'accusation d'« outrage à la morale publique » en 1857."),
        QuizQuestion(id: "course_92_madame_bovary_flaubert_q5", question: "Qu'est-ce qui pousse Emma vers le rêve et l'adultère, selon le roman ?", options: ["Les romans sentimentaux qu'elle a lus au couvent", "Les conseils de sa mère", "Son ambition politique", "Sa passion pour la peinture"], correctIndex: 0, explanation: "Élevée au couvent avec des romans sentimentaux, Emma confond la vie réelle avec les fictions qu'elle a lues, ce qui alimente son insatisfaction."),
        QuizQuestion(id: "course_92_madame_bovary_flaubert_q6", question: "Qui pousse Emma à s'endetter en lui vendant des marchandises à crédit ?", options: ["Le marchand Lheureux", "Le médecin Charles", "L'apothicaire Homais", "Le clerc Léon"], correctIndex: 0, explanation: "Le marchand Lheureux pousse Emma à s'endetter de plus en plus, jusqu'à la ruine financière du couple."),
        QuizQuestion(id: "course_92_madame_bovary_flaubert_q7", question: "Comment Emma se donne-t-elle la mort à la fin du roman ?", options: ["Elle avale de l'arsenic volé chez l'apothicaire Homais", "Elle se jette dans la Seine", "Elle meurt de chagrin", "Elle est tuée par Charles"], correctIndex: 0, explanation: "Emma se suicide à l'arsenic qu'elle vole chez l'apothicaire Homais, incapable de faire face à ses dettes et à ses désillusions."),
        QuizQuestion(id: "course_92_madame_bovary_flaubert_q8", type: .numericSlider, question: "Combien d'années Flaubert a-t-il consacrées à l'écriture de Madame Bovary ?", explanation: "Flaubert s'isole à Croisset et consacre cinq ans, de 1851 à 1856, à la rédaction de ce roman.", correctValue: 5, sliderMin: 1, sliderMax: 12, tolerance: 1, unit: "ans"),
        QuizQuestion(id: "course_92_madame_bovary_flaubert_q9", question: "Quel terme le philosophe Jules de Gaultier forge-t-il pour désigner l'insatisfaction chronique d'Emma ?", options: ["Le bovarysme", "Le romantisme", "Le spleen", "L'absurde"], correctIndex: 0, explanation: "Jules de Gaultier forge le terme « bovarysme » pour désigner l'insatisfaction de celui qui préfère le fantasme au réel.")
    ]
        ),
        Course(
            id: "course_93_le_rouge_et_le_noir_stendhal",
            title: "« Le Rouge et le Noir » : jusqu'où ira Julien Sorel ?",
            description: "Le Rouge et le Noir (1830) est le roman de l'ambition et de l'hypocrisie. Julien Sorel, fils de charpentier intelligent et ambitieux dans une société fermée,...",
            subject: .litterature,
            subcategory: "Classiques français & européens",
            lessons: [
                LessonPage(id: "course_93_le_rouge_et_le_noir_stendhal_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_93_le_rouge_et_le_noir_stendhal_p1", title: "Stendhal et l'esthétique du Code civil", content: ""),
                LessonPage(id: "course_93_le_rouge_et_le_noir_stendhal_p2", title: "Julien Sorel : l'énergie contre le système", content: ""),
                LessonPage(id: "course_93_le_rouge_et_le_noir_stendhal_p3", title: "De la province aux salons parisiens", content: ""),
                LessonPage(id: "course_93_le_rouge_et_le_noir_stendhal_p4", title: "Le dénouement : la vérité au pied de l'échafaud", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_93_le_rouge_et_le_noir_stendhal_q1", question: "Qui est l'auteur du Rouge et le Noir, de son vrai nom Henri Beyle ?", options: ["Stendhal", "Honoré de Balzac", "Gustave Flaubert", "Victor Hugo"], correctIndex: 0, explanation: "Stendhal, de son vrai nom Henri Beyle, publie Le Rouge et le Noir en 1830."),
        QuizQuestion(id: "course_93_le_rouge_et_le_noir_stendhal_q2", question: "Quelle est l'origine sociale de Julien Sorel, le héros du roman ?", options: ["Fils de charpentier, il veut s'élever dans la société", "Fils d'un noble ruiné", "Fils d'un riche marchand", "Fils d'un général napoléonien"], correctIndex: 0, explanation: "Julien Sorel, fils de charpentier méprisé, possède une intelligence rare et rêve de s'élever dans une société qui lui est fermée."),
        QuizQuestion(id: "course_93_le_rouge_et_le_noir_stendhal_q3", question: "Que symbolisent le rouge et le noir du titre ?", options: ["L'uniforme militaire et la robe ecclésiastique, seuls chemins d'ascension pour un roturier", "Le sang et le deuil", "La passion et la mort", "Les couleurs de la Restauration"], correctIndex: 0, explanation: "Le rouge de l'uniforme militaire et le noir de la robe ecclésiastique sont, sous la Restauration, les seuls vecteurs de pouvoir pour un roturier instruit."),
        QuizQuestion(id: "course_93_le_rouge_et_le_noir_stendhal_q4", type: .trueFalse, question: "Vrai ou faux : Stendhal appelle son style sec et sans emphase le « beylisme ».", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Stendhal revendique un style sec influencé par sa carrière militaire, qu'il appelle lui-même le beylisme."),
        QuizQuestion(id: "course_93_le_rouge_et_le_noir_stendhal_q5", question: "Chez qui Julien devient-il précepteur, à Verrières ?", options: ["Chez la famille de Rênal", "Chez le marquis de La Mole", "Chez l'évêque de Besançon", "Chez un riche négociant"], correctIndex: 0, explanation: "Julien entre au séminaire puis devient précepteur des enfants de M. et Mme de Rênal, à Verrières."),
        QuizQuestion(id: "course_93_le_rouge_et_le_noir_stendhal_q6", question: "À Paris, qui Julien séduit-il au service du marquis de La Mole ?", options: ["Mathilde de La Mole", "Mme de Rênal", "Une actrice parisienne", "La fille d'un ministre"], correctIndex: 0, explanation: "Julien devient secrétaire du marquis de La Mole et séduit sa fille Mathilde, aristocrate fière qui aime le danger."),
        QuizQuestion(id: "course_93_le_rouge_et_le_noir_stendhal_q7", question: "Qu'est-ce qui provoque la chute finale de Julien ?", options: ["Une lettre de Mme de Rênal dénonçant ses mensonges", "La découverte de ses origines", "Une dette de jeu impayée", "Un duel perdu contre un rival"], correctIndex: 0, explanation: "Alors que Julien s'apprête à épouser Mathilde, une lettre de Mme de Rênal révèle ses mensonges passés et brise son ascension."),
        QuizQuestion(id: "course_93_le_rouge_et_le_noir_stendhal_q8", question: "Quel fait divers réel a inspiré l'intrigue du roman ?", options: ["L'affaire Antoine Berthet, séminariste condamné à mort", "Le procès de Flaubert", "L'assassinat du duc de Berry", "L'affaire Delphine Delamare"], correctIndex: 0, explanation: "Stendhal s'inspire de l'affaire Antoine Berthet, un séminariste condamné à mort en 1827."),
        QuizQuestion(id: "course_93_le_rouge_et_le_noir_stendhal_q9", type: .numericSlider, question: "En quelle année Le Rouge et le Noir est-il publié ?", explanation: "Le roman paraît en 1830, peu avant les Trois Glorieuses.", correctValue: 1830, sliderMin: 1810, sliderMax: 1840, tolerance: 3, unit: ""),
        QuizQuestion(id: "course_93_le_rouge_et_le_noir_stendhal_q10", type: .trueFalse, question: "Vrai ou faux : face à la mort, Julien redouble d'efforts pour échapper à l'échafaud par la ruse.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "En prison, Julien cesse de calculer : face à la mort, il refuse de sauver sa tête par l'intrigue et accepte son destin.")
    ]
        ),
        Course(
            id: "course_94_candide_voltaire",
            title: "« Candide » : pourquoi faut-il cultiver notre jardin ?",
            description: "Candide ou l'Optimisme (1759) est le conte philosophique le plus célèbre de la littérature française. En 30 chapitres d'une ironie corrosive, Voltaire démoli...",
            subject: .litterature,
            subcategory: "Classiques français & européens",
            lessons: [
                LessonPage(id: "course_94_candide_voltaire_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_94_candide_voltaire_p1", title: "Le choc de 1755 et la genèse du conte", content: ""),
                LessonPage(id: "course_94_candide_voltaire_p2", title: "L'ironie comme arme de déconstruction", content: ""),
                LessonPage(id: "course_94_candide_voltaire_p3", title: "L'Eldorado et la confrontation des modèles", content: ""),
                LessonPage(id: "course_94_candide_voltaire_p4", title: "Le jardin final : une éthique de l'action", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_94_candide_voltaire_q1", question: "Qui est l'auteur de Candide ?", options: ["Voltaire", "Diderot", "Rousseau", "Montesquieu"], correctIndex: 0, explanation: "Voltaire publie Candide ou l'Optimisme en 1759, chef-d'œuvre du conte philosophique."),
        QuizQuestion(id: "course_94_candide_voltaire_q2", question: "Quel événement réel de 1755 a bouleversé Voltaire et nourri l'écriture de Candide ?", options: ["Le tremblement de terre de Lisbonne", "La Révolution française", "La guerre de Sept Ans", "L'éruption du Vésuve"], correctIndex: 0, explanation: "Le séisme de Lisbonne du 1er novembre 1755, qui tue environ 60 000 personnes, brise la confiance de Voltaire dans un monde parfaitement ordonné."),
        QuizQuestion(id: "course_94_candide_voltaire_q3", question: "Quelle théorie philosophique Voltaire attaque-t-il à travers le personnage de Pangloss ?", options: ["L'optimisme de Leibniz", "Le scepticisme de Montaigne", "Le rationalisme de Descartes", "L'empirisme de Locke"], correctIndex: 0, explanation: "Pangloss est une caricature de Leibniz : Voltaire attaque l'idée que tout mal serait la condition d'un bien supérieur."),
        QuizQuestion(id: "course_94_candide_voltaire_q4", type: .trueFalse, question: "Vrai ou faux : selon Pangloss, tout événement, même terrible, a une cause bénéfique.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Pangloss prétend que tout événement, aussi atroce soit-il, a une cause bénéfique, jusqu'à affirmer que la syphilis est indispensable pour le chocolat."),
        QuizQuestion(id: "course_94_candide_voltaire_q5", question: "Pourquoi Candide est-il chassé du château au début du conte ?", options: ["Parce qu'il aime Cunégonde", "Parce qu'il a insulté le baron", "Parce qu'il a été enrôlé de force", "Parce qu'il a trahi Pangloss"], correctIndex: 0, explanation: "Candide est chassé du château pour avoir aimé Cunégonde, la fille du baron, ce qui déclenche son errance à travers le monde."),
        QuizQuestion(id: "course_94_candide_voltaire_q6", question: "Que démontre l'Eldorado dans le récit ?", options: ["Que l'optimisme peut fonctionner dans une société rationnelle", "Que l'argent rend toujours heureux", "Que la religion est indispensable au bonheur", "Que la guerre est nécessaire au progrès"], correctIndex: 0, explanation: "L'Eldorado, utopie sud-américaine rationnelle, prouve que l'optimisme peut fonctionner, mais Candide la quitte tout de même pour retrouver Cunégonde."),
        QuizQuestion(id: "course_94_candide_voltaire_q7", question: "Que pousse le sort du « nègre de Surinam », esclave mutilé pour le sucre européen, Candide à faire ?", options: ["Définir l'optimisme comme « la rage de soutenir que tout est bien quand on est mal »", "Abandonner définitivement Cunégonde", "Rejoindre l'Inquisition", "Retourner en Eldorado"], correctIndex: 0, explanation: "Face à cet esclave mutilé, Candide définit enfin l'optimisme comme « la rage de soutenir que tout est bien quand on est mal »."),
        QuizQuestion(id: "course_94_candide_voltaire_q8", question: "Quelle phrase célèbre conclut le conte ?", options: ["« Il faut cultiver notre jardin »", "« Tout est bien qui finit bien »", "« La vie est un songe »", "« L'enfer, c'est les autres »"], correctIndex: 0, explanation: "Le conte se conclut sur « Il faut cultiver notre jardin » : Voltaire abandonne la spéculation métaphysique au profit de l'action concrète."),
        QuizQuestion(id: "course_94_candide_voltaire_q9", type: .numericSlider, question: "En quelle année Candide est-il publié ?", explanation: "Candide paraît en 1759, sans nom d'auteur, quatre ans après le séisme de Lisbonne.", correctValue: 1759, sliderMin: 1740, sliderMax: 1780, tolerance: 3, unit: ""),
        QuizQuestion(id: "course_94_candide_voltaire_q10", type: .trueFalse, question: "Vrai ou faux : Candide est interdit par le Parlement de Paris mais circule tout de même clandestinement.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Malgré l'interdiction du Parlement de Paris, le conte circule dans la clandestinité, avec plus de 20 000 exemplaires dès la première année.")
    ]
        ),
        Course(
            id: "course_95_les_confessions_rousseau",
            title: "Qu'ose avouer Rousseau dans « Les Confessions » ?",
            description: "Les Confessions de Jean-Jacques Rousseau (publiées posthumément en 1782-1789) sont la première grande autobiographie moderne : une œuvre qui inaugure le genr...",
            subject: .litterature,
            subcategory: "Classiques français & européens",
            lessons: [
                LessonPage(id: "course_95_les_confessions_rousseau_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_95_les_confessions_rousseau_p1", title: "La naissance du pacte autobiographique", content: ""),
                LessonPage(id: "course_95_les_confessions_rousseau_p2", title: "L'audace de la transparence et le rôle de l'enfance", content: ""),
                LessonPage(id: "course_95_les_confessions_rousseau_p3", title: "Une écriture sous tension : la paranoïa et la justification", content: ""),
                LessonPage(id: "course_95_les_confessions_rousseau_p4", title: "L'héritage : du romantisme à la psychanalyse", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_95_les_confessions_rousseau_q1", question: "Qui est l'auteur des Confessions ?", options: ["Jean-Jacques Rousseau", "Voltaire", "Diderot", "Chateaubriand"], correctIndex: 0, explanation: "Jean-Jacques Rousseau écrit Les Confessions, publiées à titre posthume entre 1782 et 1789."),
        QuizQuestion(id: "course_95_les_confessions_rousseau_q2", question: "Quel genre littéraire Les Confessions inventent-elles ?", options: ["L'autobiographie moderne", "Le roman épistolaire", "Le conte philosophique", "La tragédie classique"], correctIndex: 0, explanation: "Les Confessions marquent l'acte de naissance de l'autobiographie moderne : le « moi » devient objet d'investigation littéraire."),
        QuizQuestion(id: "course_95_les_confessions_rousseau_q3", question: "Selon le pacte autobiographique de Rousseau, pourquoi raconte-t-il sa vie ?", options: ["Pour elle-même, pas pour glorifier l'Histoire à travers lui", "Pour dénoncer ses ennemis politiques", "Pour obtenir le pardon de l'Église", "Pour instruire les jeunes nobles"], correctIndex: 0, explanation: "Rousseau écrit : « Je forme une entreprise qui n'eut jamais d'exemple » ; il raconte sa vie pour elle-même, non pour glorifier l'Histoire."),
        QuizQuestion(id: "course_95_les_confessions_rousseau_q4", type: .trueFalse, question: "Vrai ou faux : comme dans les Confessions d'Augustin, le juge de l'aveu reste Dieu chez Rousseau.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "Contrairement à Augustin, le juge n'est plus Dieu mais le lecteur : Rousseau laïcise l'aveu et invente l'authenticité comme valeur suprême."),
        QuizQuestion(id: "course_95_les_confessions_rousseau_q5", question: "Quel surnom Rousseau donne-t-il à Mme de Warens ?", options: ["« Maman »", "« Ma muse »", "« Ma bienfaitrice »", "« Ma sœur »"], correctIndex: 0, explanation: "Rousseau appelle Mme de Warens « Maman », une relation qui marque profondément sa jeunesse."),
        QuizQuestion(id: "course_95_les_confessions_rousseau_q6", question: "Que confesse Rousseau au sujet de ses cinq enfants ?", options: ["Il les a abandonnés aux Enfants-Trouvés", "Il les a envoyés étudier à l'étranger", "Il les a confiés à sa sœur", "Il les a reniés publiquement"], correctIndex: 0, explanation: "Rousseau avoue avoir abandonné ses cinq enfants aux Enfants-Trouvés, un aveu douloureux au cœur de son entreprise de sincérité."),
        QuizQuestion(id: "course_95_les_confessions_rousseau_q7", question: "Qui révèle publiquement, dans un pamphlet anonyme, l'abandon des enfants de Rousseau ?", options: ["Voltaire", "Diderot", "D'Alembert", "L'évêque de Paris"], correctIndex: 0, explanation: "Voltaire révèle dans un pamphlet anonyme l'abandon des enfants de Rousseau, le forçant à un aveu public dans Les Confessions."),
        QuizQuestion(id: "course_95_les_confessions_rousseau_q8", question: "Quel rôle joue la nature dans Les Confessions ?", options: ["Elle devient le miroir d'une sensibilité nouvelle, à la source du romantisme", "Elle sert de simple décor sans importance", "Elle symbolise uniquement la punition divine", "Elle représente la civilisation urbaine"], correctIndex: 0, explanation: "Le paysage devient chez Rousseau le miroir d'une sensibilité nouvelle, qui deviendra le socle du romantisme."),
        QuizQuestion(id: "course_95_les_confessions_rousseau_q9", type: .trueFalse, question: "Vrai ou faux : Les Confessions sont publiées du vivant de Rousseau.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "Les Confessions sont publiées à titre posthume, entre 1782 et 1789, après la mort de Rousseau en 1778.")
    ]
        ),
        Course(
            id: "course_96_l_etranger_camus",
            title: "« L'Étranger » : Meursault est-il jugé pour son crime ?",
            description: "L'Étranger (1942) est le premier roman d'Albert Camus et l'un des textes fondateurs de la littérature française du XXe siècle. En 123 pages d'une sécheresse...",
            subject: .litterature,
            subcategory: "Classiques français & européens",
            lessons: [
                LessonPage(id: "course_96_l_etranger_camus_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_96_l_etranger_camus_p1", title: "Camus et la genèse de la pensée absurde", content: ""),
                LessonPage(id: "course_96_l_etranger_camus_p2", title: "Meursault ou l'homme sans masque", content: ""),
                LessonPage(id: "course_96_l_etranger_camus_p3", title: "La machine judiciaire et le procès de l'âme", content: ""),
                LessonPage(id: "course_96_l_etranger_camus_p4", title: "L'héritage d'un choc littéraire et philosophique", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_96_l_etranger_camus_q1", question: "Qui est l'auteur de L'Étranger ?", options: ["Albert Camus", "Jean-Paul Sartre", "André Malraux", "Georges Bernanos"], correctIndex: 0, explanation: "Albert Camus publie L'Étranger en 1942, son premier roman."),
        QuizQuestion(id: "course_96_l_etranger_camus_q2", question: "Quel est le métier de Meursault, le narrateur du roman ?", options: ["Employé de bureau à Alger", "Médecin colonial", "Professeur de philosophie", "Avocat"], correctIndex: 0, explanation: "Meursault est un employé de bureau à Alger, dont l'indifférence aux conventions le mène à sa perte."),
        QuizQuestion(id: "course_96_l_etranger_camus_q3", question: "Qu'est-ce que Meursault refuse de faire, à l'enterrement de sa mère comme dans sa relation avec Marie ?", options: ["Mentir sur ses sentiments", "Assister aux événements importants", "Parler de son passé", "Quitter Alger"], correctIndex: 0, explanation: "Meursault refuse de mentir sur ses sentiments, vivant le présent et ses sensations physiques plus que la morale attendue."),
        QuizQuestion(id: "course_96_l_etranger_camus_q4", question: "Dans quelles circonstances Meursault tue-t-il un homme sur la plage ?", options: ["Ébloui par le soleil, dans un geste sans haine ni vengeance", "Pour venger un ami", "Lors d'un vol qui échoue", "Par accident, en manipulant une arme"], correctIndex: 0, explanation: "Ébloui par le soleil sur la plage, Meursault tire sur un homme dans un geste que le roman présente comme une coïncidence tragique, sans haine ni vengeance."),
        QuizQuestion(id: "course_96_l_etranger_camus_q5", question: "De quoi le procureur accuse-t-il aussi Meursault lors du procès ?", options: ["D'avoir bu du café au lait devant le cercueil de sa mère", "D'avoir menacé un policier", "D'avoir menti sur son identité", "D'avoir un casier judiciaire"], correctIndex: 0, explanation: "Le procureur accuse Meursault d'avoir bu du café au lait devant le cercueil de sa mère et d'être allé au cinéma le lendemain de l'enterrement."),
        QuizQuestion(id: "course_96_l_etranger_camus_q6", type: .trueFalse, question: "Vrai ou faux : Meursault est condamné uniquement pour le meurtre qu'il a commis.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "La société condamne surtout Meursault pour avoir refusé les rituels collectifs, comme s'il avait enterré sa mère « avec un cœur de criminel »."),
        QuizQuestion(id: "course_96_l_etranger_camus_q7", question: "Quel concept philosophique le roman met-il en fiction ?", options: ["L'absurde chez Camus", "L'existentialisme sartrien", "Le nihilisme nietzschéen", "Le stoïcisme antique"], correctIndex: 0, explanation: "L'Étranger met en fiction l'absurde chez Camus : le divorce entre notre appel au sens et le silence du monde."),
        QuizQuestion(id: "course_96_l_etranger_camus_q8", type: .trueFalse, question: "Vrai ou faux : pour Camus, l'absurde doit mener au nihilisme et au renoncement.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "Pour Camus, l'absurde n'aboutit pas au nihilisme mais à la révolte : il s'agit de vivre malgré l'absence de sens."),
        QuizQuestion(id: "course_96_l_etranger_camus_q9", type: .numericSlider, question: "À quel âge Camus reçoit-il le prix Nobel de littérature ?", explanation: "Camus reçoit le prix Nobel de littérature en 1957, à l'âge de 44 ans.", correctValue: 44, sliderMin: 30, sliderMax: 60, tolerance: 3, unit: "ans"),
        QuizQuestion(id: "course_96_l_etranger_camus_q10", question: "Quel écrivain algérien contemporain relit L'Étranger du point de vue de la victime anonyme, dans « Meursault, contre-enquête » ?", options: ["Kamel Daoud", "Yasmina Khadra", "Assia Djebar", "Kateb Yacine"], correctIndex: 0, explanation: "Kamel Daoud relit L'Étranger du point de vue de la victime anonyme dans son roman « Meursault, contre-enquête ».")
    ]
        ),
        Course(
            id: "course_97_le_mythe_de_sisyphe_camus",
            title: "Pourquoi faut-il imaginer Sisyphe heureux, selon Camus ?",
            description: "Le Mythe de Sisyphe (1942) est l'essai philosophique le plus célèbre de Camus. En partant du personnage mythologique condamné à rouler éternellement son roch...",
            subject: .litterature,
            subcategory: "Classiques français & européens",
            lessons: [
                LessonPage(id: "course_97_le_mythe_de_sisyphe_camus_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_97_le_mythe_de_sisyphe_camus_p1", title: "Le divorce entre l'homme et le monde", content: ""),
                LessonPage(id: "course_97_le_mythe_de_sisyphe_camus_p2", title: "La critique des solutions de fuite", content: ""),
                LessonPage(id: "course_97_le_mythe_de_sisyphe_camus_p3", title: "Le héros absurde et la victoire de la conscience", content: ""),
                LessonPage(id: "course_97_le_mythe_de_sisyphe_camus_p4", title: "L'héritage et la postérité de l'œuvre", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_97_le_mythe_de_sisyphe_camus_q1", question: "Qui est l'auteur du Mythe de Sisyphe ?", options: ["Albert Camus", "Jean-Paul Sartre", "Simone de Beauvoir", "Emmanuel Levinas"], correctIndex: 0, explanation: "Albert Camus publie Le Mythe de Sisyphe en 1942, essai fondateur de la pensée de l'absurde."),
        QuizQuestion(id: "course_97_le_mythe_de_sisyphe_camus_q2", question: "Par quelle affirmation célèbre Camus ouvre-t-il son essai ?", options: ["« Il n'y a qu'un problème philosophique vraiment sérieux, c'est le suicide »", "« L'enfer, c'est les autres »", "« Dieu est mort »", "« L'existence précède l'essence »"], correctIndex: 0, explanation: "Camus ouvre son essai en affirmant que le seul problème philosophique vraiment sérieux est de juger si la vie vaut la peine d'être vécue."),
        QuizQuestion(id: "course_97_le_mythe_de_sisyphe_camus_q3", question: "Où réside l'absurde, selon Camus ?", options: ["Dans la confrontation entre l'aspiration humaine à l'ordre et le silence du monde", "Uniquement dans l'esprit humain", "Uniquement dans le chaos du monde extérieur", "Dans l'absence totale de raison chez l'homme"], correctIndex: 0, explanation: "Pour Camus, l'absurde n'est ni dans le monde ni dans l'homme seul, mais dans leur confrontation : l'esprit aspire à l'ordre, le monde reste muet."),
        QuizQuestion(id: "course_97_le_mythe_de_sisyphe_camus_q4", question: "Quelle est, selon Camus, la seule réponse authentique face à l'absurde ?", options: ["La révolte absurde", "Le suicide", "La foi religieuse", "L'indifférence totale"], correctIndex: 0, explanation: "La seule réponse authentique est la révolte absurde : rester debout face au silence du monde, sans consolation ni fuite."),
        QuizQuestion(id: "course_97_le_mythe_de_sisyphe_camus_q5", type: .trueFalse, question: "Vrai ou faux : pour Camus, le suicide philosophique consiste à fuir vers la foi ou l'irrationnel.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Le suicide philosophique, ou « saut » selon Kierkegaard, fuit l'absurde vers la foi ou l'irrationnel plutôt que de l'affronter."),
        QuizQuestion(id: "course_97_le_mythe_de_sisyphe_camus_q6", question: "Pourquoi Sisyphe est-il condamné, dans le mythe grec repris par Camus ?", options: ["À rouler éternellement un rocher qui redescend toujours", "À porter le monde sur ses épaules", "À errer sans fin loin de son royaume", "À affronter des monstres marins"], correctIndex: 0, explanation: "Sisyphe, roi de Corinthe, est condamné à rouler éternellement un rocher jusqu'au sommet, d'où il redescend toujours."),
        QuizQuestion(id: "course_97_le_mythe_de_sisyphe_camus_q7", question: "À quel moment précis Camus s'intéresse-t-il dans le mythe de Sisyphe ?", options: ["Au moment de la descente, quand Sisyphe est conscient de son destin", "Au moment où Sisyphe pousse le rocher vers le haut", "Au moment de sa condamnation par les dieux", "Au moment de sa mort"], correctIndex: 0, explanation: "Camus s'intéresse au moment de la descente : Sisyphe y est supérieur à son destin car il en a pleine conscience."),
        QuizQuestion(id: "course_97_le_mythe_de_sisyphe_camus_q8", question: "Quelle phrase célèbre conclut l'essai ?", options: ["« Il faut imaginer Sisyphe heureux »", "« Sisyphe est un homme puni »", "« Le rocher est une malédiction »", "« Il faut fuir la montagne »"], correctIndex: 0, explanation: "L'essai se conclut sur « Il faut imaginer Sisyphe heureux » : un bonheur qui naît de la lucidité et de l'acceptation de la lutte."),
        QuizQuestion(id: "course_97_le_mythe_de_sisyphe_camus_q9", question: "Quels dramaturges du théâtre de l'absurde Camus influence-t-il ?", options: ["Samuel Beckett et Eugène Ionesco", "Jean Racine et Molière", "Bertolt Brecht et Antonin Artaud", "Jean Anouilh et Jean Giraudoux"], correctIndex: 0, explanation: "Le Mythe de Sisyphe influence le théâtre de l'absurde de Samuel Beckett et Eugène Ionesco, où les personnages tournent en boucle.")
    ]
        ),
        Course(
            id: "course_98_a_la_recherche_du_temps_perdu_proust",
            title: "Comment la madeleine de Proust fait-elle revivre le passé ?",
            description: "À la recherche du temps perdu (1913-1927) est le plus long roman de la littérature française : 7 volumes, 3 200 pages, 1,5 million de mots. C'est aussi l'une...",
            subject: .litterature,
            subcategory: "Classiques français & européens",
            lessons: [
                LessonPage(id: "course_98_a_la_recherche_du_temps_perdu_proust_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_98_a_la_recherche_du_temps_perdu_proust_p1", title: "L'homme et la chambre de liège : une vie dédiée à l'œuvre", content: ""),
                LessonPage(id: "course_98_a_la_recherche_du_temps_perdu_proust_p2", title: "La mémoire involontaire : de la sensation au souvenir vivant", content: ""),
                LessonPage(id: "course_98_a_la_recherche_du_temps_perdu_proust_p3", title: "L'architecture des thèmes : amour, snobisme et jalousie", content: ""),
                LessonPage(id: "course_98_a_la_recherche_du_temps_perdu_proust_p4", title: "Le Temps retrouvé : la révélation finale de l'art", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_98_a_la_recherche_du_temps_perdu_proust_q1", question: "Qui est l'auteur d'À la recherche du temps perdu ?", options: ["Marcel Proust", "André Gide", "Marcel Pagnol", "Anatole France"], correctIndex: 0, explanation: "Marcel Proust écrit À la recherche du temps perdu entre 1913 et 1927."),
        QuizQuestion(id: "course_98_a_la_recherche_du_temps_perdu_proust_q2", question: "Quel type de mémoire, déclenchée par une sensation, Proust place-t-il au centre du roman ?", options: ["La mémoire involontaire", "La mémoire collective", "La mémoire volontaire", "La mémoire photographique"], correctIndex: 0, explanation: "Proust distingue la mémoire volontaire, froide, de la mémoire involontaire, provoquée par une sensation et qui ressuscite le passé dans son intégralité affective."),
        QuizQuestion(id: "course_98_a_la_recherche_du_temps_perdu_proust_q3", question: "Quel aliment trempé dans le thé déclenche le souvenir le plus célèbre du roman ?", options: ["La madeleine", "Le croissant", "La brioche", "Le pain d'épice"], correctIndex: 0, explanation: "La madeleine trempée dans du thé ressuscite chez le narrateur tout le souvenir affectif de Combray."),
        QuizQuestion(id: "course_98_a_la_recherche_du_temps_perdu_proust_q4", question: "Pourquoi Proust tapisse-t-il sa chambre de liège ?", options: ["Pour se protéger du bruit et du pollen", "Pour mieux entendre les bruits de la rue", "Pour décorer son intérieur", "Pour isoler ses manuscrits de l'humidité"], correctIndex: 0, explanation: "Proust s'isole après la mort de sa mère et tapisse sa chambre de liège pour se protéger du bruit et du pollen."),
        QuizQuestion(id: "course_98_a_la_recherche_du_temps_perdu_proust_q5", type: .trueFalse, question: "Vrai ou faux : le premier tome, Du côté de chez Swann, est immédiatement accepté par les éditeurs.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "Du côté de chez Swann essuie plusieurs refus et doit être publié à compte d'auteur en 1913."),
        QuizQuestion(id: "course_98_a_la_recherche_du_temps_perdu_proust_q6", question: "Quel écrivain reconnaît plus tard avoir commis une grave erreur en refusant le manuscrit de Proust ?", options: ["André Gide", "Anatole France", "Paul Valéry", "Émile Zola"], correctIndex: 0, explanation: "André Gide, qui avait dédaigné le manuscrit, admettra plus tard avoir commis une grave erreur."),
        QuizQuestion(id: "course_98_a_la_recherche_du_temps_perdu_proust_q7", question: "Que révèle le septième et dernier volume au narrateur ?", options: ["Sa vocation d'écrivain, celle d'écrire l'œuvre que nous venons de lire", "La véritable identité de Swann", "Un secret de famille caché depuis l'enfance", "La trahison de Gilberte"], correctIndex: 0, explanation: "Le Temps retrouvé révèle au narrateur sa vocation d'écrivain : écrire l'œuvre que le lecteur vient de lire."),
        QuizQuestion(id: "course_98_a_la_recherche_du_temps_perdu_proust_q8", type: .numericSlider, question: "Combien de volumes compte À la recherche du temps perdu ?", explanation: "Le roman compte sept volumes, publiés entre 1913 et 1927.", correctValue: 7, sliderMin: 3, sliderMax: 12, tolerance: 1, unit: "volumes"),
        QuizQuestion(id: "course_98_a_la_recherche_du_temps_perdu_proust_q9", question: "Quel personnage introduit dans le roman des thèmes jusque-là tabous ?", options: ["Monsieur de Charlus", "Swann", "Le baron de Guermantes", "Le docteur Cottard"], correctIndex: 0, explanation: "Monsieur de Charlus introduit dans La Recherche des thèmes autrefois tabous dans la littérature."),
        QuizQuestion(id: "course_98_a_la_recherche_du_temps_perdu_proust_q10", question: "Quel prix littéraire Proust reçoit-il en 1919 ?", options: ["Le prix Goncourt", "Le prix Nobel", "Le prix Femina", "Le prix Interallié"], correctIndex: 0, explanation: "Proust reçoit le prix Goncourt en 1919 pour À l'ombre des jeunes filles en fleurs.")
    ]
        ),
        Course(
            id: "course_99_le_pere_goriot_balzac",
            title: "Le Père Goriot, Balzac",
            description: "Le Père Goriot (1835) est le roman central de La Comédie humaine de Balzac : celui où naît Rastignac, l'archétype de l'ambitieux provincial montant à Paris,...",
            subject: .litterature,
            subcategory: "Classiques français & européens",
            lessons: [
                LessonPage(id: "course_99_le_pere_goriot_balzac_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_99_le_pere_goriot_balzac_p1", title: "Balzac et l'invention du monde total", content: ""),
                LessonPage(id: "course_99_le_pere_goriot_balzac_p2", title: "Le calvaire de la paternité absolue", content: ""),
                LessonPage(id: "course_99_le_pere_goriot_balzac_p3", title: "L'éducation sentimentale et cynique de Rastignac", content: ""),
                LessonPage(id: "course_99_le_pere_goriot_balzac_p4", title: "Un tournant dans l'esthétique réaliste", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_99_le_pere_goriot_balzac_q1", question: "Qui est l'auteur du Père Goriot ?", options: ["Honoré de Balzac", "Victor Hugo", "Gustave Flaubert", "Stendhal"], correctIndex: 0, explanation: "Honoré de Balzac publie Le Père Goriot en 1835."),
        QuizQuestion(id: "course_99_le_pere_goriot_balzac_q2", question: "À quel ensemble romanesque Le Père Goriot appartient-il ?", options: ["La Comédie humaine", "Les Rougon-Macquart", "La Légende des siècles", "Les Contes drolatiques"], correctIndex: 0, explanation: "Le Père Goriot est le pivot de la Comédie humaine, où Balzac introduit pour la première fois le retour de personnages récurrents."),
        QuizQuestion(id: "course_99_le_pere_goriot_balzac_q3", question: "Pour qui le père Goriot sacrifie-t-il toute sa fortune ?", options: ["Ses filles Anastasie et Delphine", "Son fils unique", "Ses anciens employés", "L'Église de sa paroisse"], correctIndex: 0, explanation: "Ancien vermicellier, Goriot a tout sacrifié pour ses filles Anastasie et Delphine, qui l'abandonnent une fois riches."),
        QuizQuestion(id: "course_99_le_pere_goriot_balzac_q4", question: "Où habite le père Goriot, tandis que ses ressources s'épuisent ?", options: ["À la pension Vauquer", "Dans un hôtel particulier", "Chez sa fille Delphine", "Dans un couvent"], correctIndex: 0, explanation: "Goriot descend d'étage en étage à la pension Vauquer à mesure que ses ressources s'épuisent, jusqu'à la chambre la plus modeste."),
        QuizQuestion(id: "course_99_le_pere_goriot_balzac_q5", type: .trueFalse, question: "Vrai ou faux : les filles de Goriot restent à son chevet jusqu'à sa mort.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "Ses filles ne reviennent que pour réclamer de l'argent et vont au bal pendant que leur père meurt seul à la pension."),
        QuizQuestion(id: "course_99_le_pere_goriot_balzac_q6", question: "Qui est Vautrin, personnage qui propose un pacte cynique à Rastignac ?", options: ["Un bagnard évadé, de son vrai nom Jacques Collin", "Un ancien notaire ruiné", "Un noble déchu", "Un médecin sans scrupules"], correctIndex: 0, explanation: "Vautrin, de son vrai nom Jacques Collin, est un bagnard évadé qui propose à Rastignac de faire fortune par un meurtre."),
        QuizQuestion(id: "course_99_le_pere_goriot_balzac_q7", question: "Que propose Vautrin à Rastignac pour faire fortune rapidement ?", options: ["Faire fortune par un meurtre", "Épouser une riche héritière", "Voler la caisse de la pension Vauquer", "Truquer un jeu de cartes"], correctIndex: 0, explanation: "Vautrin propose à Rastignac un pacte cynique : faire fortune en organisant un meurtre, ce que Rastignac finit par refuser."),
        QuizQuestion(id: "course_99_le_pere_goriot_balzac_q8", question: "Que lance Rastignac depuis le cimetière du Père-Lachaise à la fin du roman ?", options: ["« À nous deux maintenant ! »", "« Je vous maudis, Paris ! »", "« Adieu, mon père ! »", "« Vautrin avait raison ! »"], correctIndex: 0, explanation: "Depuis le Père-Lachaise, après la mort de Goriot, Rastignac lance son défi à Paris : « À nous deux maintenant ! »"),
        QuizQuestion(id: "course_99_le_pere_goriot_balzac_q9", question: "Quelle technique romanesque Balzac inaugure-t-il avec ce roman ?", options: ["Le retour des personnages d'un roman à l'autre", "Le monologue intérieur", "Le roman épistolaire", "La narration à la première personne"], correctIndex: 0, explanation: "Le Père Goriot inaugure dans la Comédie humaine le retour des personnages, qui reparaissent d'un roman à l'autre."),
        QuizQuestion(id: "course_99_le_pere_goriot_balzac_q10", type: .numericSlider, question: "Combien de personnages Balzac ambitionne-t-il de créer dans l'ensemble de la Comédie humaine ?", explanation: "Balzac veut archiver tous les types sociaux de son époque à travers 90 romans et environ 2 000 personnages.", correctValue: 2000, sliderMin: 1000, sliderMax: 3000, tolerance: 200, unit: "personnages")
    ]
        ),
        Course(
            id: "course_100_les_fleurs_du_mal_baudelaire",
            title: "Les Fleurs du Mal, Baudelaire",
            description: "Les Fleurs du Mal (1857) sont le recueil de poésie le plus important du XIXe siècle français. Condamné pour immoralité dès sa publication, ce recueil révolut...",
            subject: .litterature,
            subcategory: "Classiques français & européens",
            lessons: [
                LessonPage(id: "course_100_les_fleurs_du_mal_baudelaire_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_100_les_fleurs_du_mal_baudelaire_p1", title: "Baudelaire : le dandy à l'épreuve du siècle", content: ""),
                LessonPage(id: "course_100_les_fleurs_du_mal_baudelaire_p2", title: "L'architecture du recueil : de l'ennui à la révolte", content: ""),
                LessonPage(id: "course_100_les_fleurs_du_mal_baudelaire_p3", title: "La poétique des correspondances et l'alchimie du verbe", content: ""),
                LessonPage(id: "course_100_les_fleurs_du_mal_baudelaire_p4", title: "La modernité et la postérité du poète-phare", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_100_les_fleurs_du_mal_baudelaire_q1", question: "Qui est l'auteur des Fleurs du Mal ?", options: ["Charles Baudelaire", "Paul Verlaine", "Stéphane Mallarmé", "Arthur Rimbaud"], correctIndex: 0, explanation: "Charles Baudelaire publie Les Fleurs du Mal en 1857, acte de naissance de la poésie moderne."),
        QuizQuestion(id: "course_100_les_fleurs_du_mal_baudelaire_q2", question: "Pourquoi Les Fleurs du Mal sont-elles condamnées en 1857 ?", options: ["Pour « outrage à la morale publique »", "Pour plagiat", "Pour incitation à la violence politique", "Pour atteinte à la sûreté de l'État"], correctIndex: 0, explanation: "Le recueil est condamné pour « outrage à la morale publique », un scandale qui ne sera officiellement levé qu'en 1949."),
        QuizQuestion(id: "course_100_les_fleurs_du_mal_baudelaire_q3", type: .numericSlider, question: "En quelle année les six poèmes condamnés des Fleurs du Mal sont-ils officiellement réhabilités ?", explanation: "Les six poèmes condamnés en 1857 ne sont officiellement réhabilités qu'en 1949, soit 92 ans plus tard.", correctValue: 1949, sliderMin: 1920, sliderMax: 1970, tolerance: 5, unit: ""),
        QuizQuestion(id: "course_100_les_fleurs_du_mal_baudelaire_q4", question: "Que représente l'albatros dans la section « Spleen et Idéal » ?", options: ["Le poète, majestueux en vol mais ridicule au sol", "La liberté totale de l'artiste", "La mort inévitable", "La beauté inaccessible"], correctIndex: 0, explanation: "L'albatros, majestueux en vol mais ridicule une fois posé au sol, représente le poète dans un monde qui ne le comprend pas."),
        QuizQuestion(id: "course_100_les_fleurs_du_mal_baudelaire_q5", question: "Quelle section du recueil fait de Paris un paysage psychologique ?", options: ["« Tableaux parisiens »", "« Spleen et Idéal »", "« Le Vin »", "« La Mort »"], correctIndex: 0, explanation: "« Tableaux parisiens » fait de la ville un paysage psychologique. Le poète y erre en flâneur, observateur de la vie parisienne sous Haussmann."),
        QuizQuestion(id: "course_100_les_fleurs_du_mal_baudelaire_q6", question: "Quel poème décrit la nature comme un « temple » de signes reliant parfums, couleurs et sons ?", options: ["« Correspondances »", "« L'Albatros »", "« Spleen »", "« Recueillement »"], correctIndex: 0, explanation: "« Correspondances » décrit la nature comme un temple de signes. Les sens s'y mélangent : parfums, couleurs et sons se répondent."),
        QuizQuestion(id: "course_100_les_fleurs_du_mal_baudelaire_q7", type: .trueFalse, question: "Vrai ou faux : Baudelaire rejette entièrement les formes poétiques classiques comme le sonnet.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "Baudelaire lie au contraire la forme classique, comme le sonnet et l'alexandrin, à une vision poétique radicalement nouvelle."),
        QuizQuestion(id: "course_100_les_fleurs_du_mal_baudelaire_q8", question: "Quel courant poétique la poétique des correspondances de Baudelaire fonde-t-elle, porté ensuite par Verlaine et Mallarmé ?", options: ["Le symbolisme", "Le romantisme", "Le naturalisme", "Le classicisme"], correctIndex: 0, explanation: "Cette poétique des correspondances fonde le symbolisme, porté ensuite par Verlaine et Mallarmé."),
        QuizQuestion(id: "course_100_les_fleurs_du_mal_baudelaire_q9", question: "Quel écrivain américain, qualifié de « frère d'âme », Baudelaire traduit-il ?", options: ["Edgar Allan Poe", "Herman Melville", "Nathaniel Hawthorne", "Walt Whitman"], correctIndex: 0, explanation: "Baudelaire traduit Edgar Poe, qu'il considère comme un « frère d'âme » partageant son goût du macabre."),
        QuizQuestion(id: "course_100_les_fleurs_du_mal_baudelaire_q10", question: "Comment Baudelaire résume-t-il son alchimie poétique, consistant à extraire la beauté de la boue ?", options: ["« Tu m'as donné ta boue et j'en ai fait de l'or »", "« La beauté est éternelle »", "« Le mal engendre le mal »", "« L'art pour l'art »"], correctIndex: 0, explanation: "Baudelaire résume son projet par cette formule : « Tu m'as donné ta boue et j'en ai fait de l'or ».")
    ]
        ),
        Course(
            id: "course_101_1984_george_orwell",
            title: "« 1984 » : comment Winston finit-il par aimer Big Brother ?",
            description: "1984 (1949) est le roman dystopique le plus influent du XXe siècle. Big Brother, la Novlangue, le Ministère de la Vérité : Orwell a créé un vocabulaire polit...",
            subject: .litterature,
            subcategory: "Anglo-saxons & littérature mondiale",
            lessons: [
                LessonPage(id: "course_101_1984_george_orwell_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_101_1984_george_orwell_p1", title: "Le traumatisme d'Espagne : la genèse de la pensée orwellienne", content: ""),
                LessonPage(id: "course_101_1984_george_orwell_p2", title: "L'architecture du contrôle : le système Oceania", content: ""),
                LessonPage(id: "course_101_1984_george_orwell_p3", title: "Winston et Julia : la fragilité de la dissidence intérieure", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_101_1984_george_orwell_q1", question: "Quel est le vrai nom de George Orwell ?", options: ["Eric Arthur Blair", "George Bernard Shaw", "Aldous Huxley", "Herbert George Wells"], correctIndex: 0, explanation: "George Orwell est le pseudonyme d'Eric Arthur Blair."),
        QuizQuestion(id: "course_101_1984_george_orwell_q2", question: "Dans quel conflit Orwell combat-il avant d'écrire 1984 ?", options: ["La guerre civile espagnole", "La Première Guerre mondiale", "La guerre des Boers", "La guerre d'Algérie"], correctIndex: 0, explanation: "Orwell combat en 1936-1937 dans les milices du POUM pendant la guerre civile espagnole, où il est blessé."),
        QuizQuestion(id: "course_101_1984_george_orwell_q3", question: "Qu'est-ce qui marque le plus Orwell durant cette expérience, au-delà de la violence ?", options: ["La falsification des faits et du passé par la propagande", "Le manque de nourriture", "La trahison de ses camarades", "La censure de la presse étrangère"], correctIndex: 0, explanation: "Ce qui marque le plus Orwell, c'est de voir les journaux réécrire le passé et effacer des combattants, une obsession du mensonge d'État qui nourrit le roman."),
        QuizQuestion(id: "course_101_1984_george_orwell_q4", question: "Quel régime totalitaire réel inspire le système d'Oceania ?", options: ["Le totalitarisme soviétique", "Le fascisme italien", "Le régime de Vichy", "L'Empire britannique"], correctIndex: 0, explanation: "Le système d'Oceania s'inspire notamment du totalitarisme soviétique comme modèle."),
        QuizQuestion(id: "course_101_1984_george_orwell_q5", question: "Quel est le nom du parti unique qui dirige Oceania ?", options: ["L'Ingsoc", "Le Parti du Peuple", "La Ligue Rouge", "Le Bloc Central"], correctIndex: 0, explanation: "Oceania est dirigée par l'Ingsoc, qui repose sur quatre ministères paradoxaux : Paix, Abondance, Amour et Vérité."),
        QuizQuestion(id: "course_101_1984_george_orwell_q6", question: "Que fait Winston Smith comme travail au Ministère de la Vérité ?", options: ["Il efface et réécrit le passé pour qu'il corresponde au présent du Parti", "Il surveille les citoyens via les télécrans", "Il rédige les discours de Big Brother", "Il forme les nouveaux membres du Parti"], correctIndex: 0, explanation: "Winston Smith travaille au Ministère de la Vérité, où il efface le passé pour qu'il corresponde au présent défini par le Parti."),
        QuizQuestion(id: "course_101_1984_george_orwell_q7", question: "Comment appelle-t-on la capacité d'accepter deux vérités contradictoires à la fois, dans 1984 ?", options: ["La doublepensée", "La novlangue", "Le télécran", "L'Ingsoc"], correctIndex: 0, explanation: "La doublepensée désigne la capacité d'accepter deux vérités contradictoires à la fois, un pilier du contrôle mental du Parti."),
        QuizQuestion(id: "course_101_1984_george_orwell_q8", question: "Pourquoi le Parti réduit-il le vocabulaire à travers la novlangue ?", options: ["Pour rendre la pensée critique impossible", "Pour simplifier l'administration", "Pour faciliter le commerce international", "Pour unifier les dialectes régionaux"], correctIndex: 0, explanation: "La novlangue réduit le vocabulaire disponible pour rendre la pensée critique elle-même impossible à formuler."),
        QuizQuestion(id: "course_101_1984_george_orwell_q9", type: .chronological, question: "Remets ces étapes de la vie et de l'œuvre d'Orwell dans l'ordre.", explanation: "Ces quatre étapes jalonnent le parcours d'Orwell : la guerre d'Espagne (1936-1937), La Ferme des animaux (1945), 1984 (1949), puis sa mort en 1950.", items: ["Orwell combat dans les milices du POUM pendant la guerre d'Espagne", "Il publie La Ferme des animaux", "Il publie 1984", "Il meurt en Écosse peu après la publication de son roman"]),
        QuizQuestion(id: "course_101_1984_george_orwell_q10", type: .trueFalse, question: "Vrai ou faux : à la fin du roman, Winston Smith finit par aimer Big Brother.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Le totalitarisme gagne sur le plan psychologique : Winston n'obéit pas seulement, il en vient à aimer Big Brother.")
    ]
        ),
        Course(
            id: "course_102_la_ferme_des_animaux_george_orwell",
            title: "Qui sont les cochons de « La Ferme des animaux » ?",
            description: "La Ferme des animaux (1945) est l'une des allégories politiques les plus parfaites jamais écrites. En 30 000 mots et le style d'un conte pour enfants, Orwell...",
            subject: .litterature,
            subcategory: "Anglo-saxons & littérature mondiale",
            lessons: [
                LessonPage(id: "course_102_la_ferme_des_animaux_george_orwell_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_102_la_ferme_des_animaux_george_orwell_p1", title: "Une allégorie chirurgicale de l'histoire soviétique", content: ""),
                LessonPage(id: "course_102_la_ferme_des_animaux_george_orwell_p2", title: "Le basculement : de l'utopie à la dictature", content: ""),
                LessonPage(id: "course_102_la_ferme_des_animaux_george_orwell_p3", title: "La modification du langage et la trahison finale", content: ""),
                LessonPage(id: "course_102_la_ferme_des_animaux_george_orwell_p4", title: "Un avertissement universel sur le pouvoir", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_102_la_ferme_des_animaux_george_orwell_q1", question: "Quel événement historique La Ferme des animaux met-il en scène sous forme d'allégorie ?", options: ["La Révolution russe", "La Révolution française", "La guerre civile espagnole", "La révolution industrielle anglaise"], correctIndex: 0, explanation: "Orwell transpose les grandes étapes de la Révolution russe et de la trahison stalinienne dans une fable animalière."),
        QuizQuestion(id: "course_102_la_ferme_des_animaux_george_orwell_q2", question: "Quel animal représente Staline dans l'allégorie d'Orwell ?", options: ["Napoléon", "Le Vieux Major", "Boule de neige", "Malabar"], correctIndex: 0, explanation: "Napoléon, le cochon qui prend le pouvoir par la force après avoir chassé Boule de neige, calque la figure de Staline."),
        QuizQuestion(id: "course_102_la_ferme_des_animaux_george_orwell_q3", type: .trueFalse, question: "Vrai ou faux : l'éditeur T.S. Eliot refusa de publier le manuscrit d'Orwell, craignant que des cochons intelligents n'offensent des hommes d'État.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "T.S. Eliot, alors éditeur, rejeta effectivement le manuscrit pour cette raison."),
        QuizQuestion(id: "course_102_la_ferme_des_animaux_george_orwell_q4", question: "Que représentent les chiens de Napoléon dans l'allégorie ?", options: ["La police secrète", "L'armée régulière du Tsar", "Les paysans révoltés", "Les journalistes officiels"], correctIndex: 0, explanation: "Les chiens dressés par Napoléon pour chasser Boule de neige et terroriser la ferme figurent la police secrète soviétique."),
        QuizQuestion(id: "course_102_la_ferme_des_animaux_george_orwell_q5", question: "Quel animal incarne le prolétariat exploité jusqu'à l'épuisement ?", options: ["Malabar, le cheval laborieux", "Brille-Babil, le propagandiste", "Le Vieux Major", "Boule de neige"], correctIndex: 0, explanation: "Malabar, cheval de trait dévoué et infatigable, symbolise un prolétariat qui travaille sans jamais remettre l'autorité en question."),
        QuizQuestion(id: "course_102_la_ferme_des_animaux_george_orwell_q6", type: .chronological, question: "Remets ces étapes de La Ferme des animaux dans l'ordre.", explanation: "Cette séquence montre le basculement progressif de la révolution égalitaire vers la dictature des cochons.", items: ["Les animaux chassent le fermier Jones", "Napoléon chasse Boule de neige à l'aide de ses chiens", "Les cochons modifient les Sept Commandements en secret", "Les cochons se mettent à marcher sur deux pattes"]),
        QuizQuestion(id: "course_102_la_ferme_des_animaux_george_orwell_q7", question: "Quelle formule finale résume, à la fin du roman, la trahison de l'idéal égalitaire ?", options: ["« Tous les animaux sont égaux, mais certains animaux sont plus égaux que d'autres »", "« Les cochons doivent servir les autres animaux »", "« Napoléon a toujours raison »", "« Le moulin sera notre salut »"], correctIndex: 0, explanation: "Cette formule paradoxale, inscrite sur le mur de la grange, révèle que l'égalité proclamée a été vidée de son sens."),
        QuizQuestion(id: "course_102_la_ferme_des_animaux_george_orwell_q8", type: .trueFalse, question: "Vrai ou faux : à la fin du roman, les autres animaux ne parviennent plus à distinguer les cochons des humains.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Les cochons marchent sur deux pattes, s'habillent et banquettent avec les fermiers, brouillant totalement la frontière entre eux."),
        QuizQuestion(id: "course_102_la_ferme_des_animaux_george_orwell_q9", type: .numericSlider, question: "Environ combien de mots compte La Ferme des animaux, un texte volontairement très court ?", explanation: "Orwell livre son allégorie en à peine 30 000 mots, ce qui renforce l'efficacité de la fable.", correctValue: 30000, sliderMin: 15000, sliderMax: 50000, tolerance: 5000, unit: "mots")
    ]
        ),
        Course(
            id: "course_103_hamlet_shakespeare",
            title: "Hamlet, Shakespeare",
            description: "Hamlet, Prince de Danemark (vers 1601) est peut-être la pièce la plus jouée et la plus commentée de l'histoire du théâtre. «Être ou ne pas être» : cette ques...",
            subject: .litterature,
            subcategory: "Anglo-saxons & littérature mondiale",
            lessons: [
                LessonPage(id: "course_103_hamlet_shakespeare_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_103_hamlet_shakespeare_p1", title: "Le contexte élisabéthain : un théâtre du monde", content: ""),
                LessonPage(id: "course_103_hamlet_shakespeare_p2", title: "La spirale de la vengeance et le poids de l'hésitation", content: ""),
                LessonPage(id: "course_103_hamlet_shakespeare_p3", title: "La mélancolie et la corruption du Danemark", content: ""),
                LessonPage(id: "course_103_hamlet_shakespeare_p4", title: "Héritage et postérité d'un mythe universel", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_103_hamlet_shakespeare_q1", question: "Qui assassine le roi du Danemark, père d'Hamlet ?", options: ["Claudius", "Polonius", "Laërte", "Fortinbras"], correctIndex: 0, explanation: "Claudius tue son frère, le roi, puis épouse la reine Gertrude et prend le trône."),
        QuizQuestion(id: "course_103_hamlet_shakespeare_q2", question: "Qui révèle à Hamlet le meurtre de son père ?", options: ["Le fantôme de son père", "Sa mère Gertrude", "Ophélie", "Horatio"], correctIndex: 0, explanation: "Le fantôme du roi défunt apparaît à Hamlet pour lui révéler le crime de Claudius."),
        QuizQuestion(id: "course_103_hamlet_shakespeare_q3", question: "Quelle stratégie Hamlet adopte-t-il pour enquêter sur le crime sans se dévoiler ?", options: ["Il simule la folie", "Il s'exile à Wittenberg", "Il accuse publiquement Claudius", "Il rejoint une troupe de théâtre"], correctIndex: 0, explanation: "Hamlet simule la folie pour observer la cour sans éveiller les soupçons, une stratégie qui finit par échouer."),
        QuizQuestion(id: "course_103_hamlet_shakespeare_q4", type: .trueFalse, question: "Vrai ou faux : sous le règne d'Élisabeth Ire, les rôles féminins comme Ophélie étaient joués par des femmes sur scène.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "Les femmes étaient interdites de scène : les rôles féminins étaient tenus par des hommes, souvent des adolescents."),
        QuizQuestion(id: "course_103_hamlet_shakespeare_q5", question: "Que met en scène Hamlet pour piéger Claudius et confirmer sa culpabilité ?", options: ["Une pièce dans la pièce, la « Souricière »", "Un duel public", "Un procès devant la cour", "Une lettre anonyme"], correctIndex: 0, explanation: "Hamlet fait jouer une pièce reproduisant le meurtre de son père pour observer la réaction de Claudius."),
        QuizQuestion(id: "course_103_hamlet_shakespeare_q6", question: "Qui Hamlet tue-t-il par erreur, précipitant l'engrenage tragique ?", options: ["Polonius", "Laërte", "Claudius", "Horatio"], correctIndex: 0, explanation: "Hamlet tue Polonius, le conseiller du roi, croyant frapper un espion caché derrière un rideau."),
        QuizQuestion(id: "course_103_hamlet_shakespeare_q7", question: "Selon la médecine de l'époque, qu'est-ce qui explique la mélancolie d'Hamlet ?", options: ["Un excès de bile noire", "Une possession démoniaque", "Un déséquilibre du sang chaud", "Une malédiction familiale"], correctIndex: 0, explanation: "La médecine élisabéthaine attribuait la mélancolie à un excès de bile noire, rendant le sujet brillant mais paralysé."),
        QuizQuestion(id: "course_103_hamlet_shakespeare_q8", question: "Quelle lecture Freud propose-t-il d'Hamlet, plusieurs siècles après Shakespeare ?", options: ["Il y voit une expression du complexe d'Œdipe", "Il y voit une critique du capitalisme naissant", "Il y voit une allégorie religieuse", "Il y voit un plaidoyer pour la monarchie"], correctIndex: 0, explanation: "Freud interprète l'hésitation d'Hamlet à travers le complexe d'Œdipe, popularisant une lecture psychanalytique de la pièce."),
        QuizQuestion(id: "course_103_hamlet_shakespeare_q9", type: .trueFalse, question: "Vrai ou faux : le monologue « Être ou ne pas être » est resté la question existentielle la plus célèbre du théâtre occidental.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Ce monologue est devenu emblématique de l'interrogation existentielle au théâtre, opposant agir et subir.")
    ]
        ),
        Course(
            id: "course_104_romeo_et_juliette_shakespeare",
            title: "Qui est responsable de la mort de Roméo et Juliette ?",
            description: "Roméo et Juliette (vers 1595) est la tragédie amoureuse la plus célèbre de l'histoire du théâtre. La mort des deux amants n'est pas le fruit du destin ou de...",
            subject: .litterature,
            subcategory: "Anglo-saxons & littérature mondiale",
            lessons: [
                LessonPage(id: "course_104_romeo_et_juliette_shakespeare_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_104_romeo_et_juliette_shakespeare_p1", title: "L'alchimie shakespearienne : de la nouvelle au drame", content: ""),
                LessonPage(id: "course_104_romeo_et_juliette_shakespeare_p2", title: "Une mécanique tragique : entre hasard et nécessité", content: ""),
                LessonPage(id: "course_104_romeo_et_juliette_shakespeare_p3", title: "La responsabilité sociale et le sacrifice de la jeunesse", content: ""),
                LessonPage(id: "course_104_romeo_et_juliette_shakespeare_p4", title: "Une postérité universelle : du lyrisme aux gangs modernes", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_104_romeo_et_juliette_shakespeare_q1", question: "Sur quelle source Shakespeare s'appuie-t-il principalement pour écrire Roméo et Juliette ?", options: ["Une nouvelle de Matteo Bandello", "Un mythe antique grec", "Une pièce de Christopher Marlowe", "Un fait divers londonien contemporain"], correctIndex: 0, explanation: "Shakespeare s'inspire du conteur italien Matteo Bandello, mais resserre l'action sur cinq jours pour intensifier la tragédie."),
        QuizQuestion(id: "course_104_romeo_et_juliette_shakespeare_q2", type: .numericSlider, question: "Sur combien de jours Shakespeare condense-t-il toute l'action de la pièce ?", explanation: "Shakespeare resserre l'intrigue sur cinq jours, rendant la catastrophe finale d'autant plus inéluctable.", correctValue: 5, sliderMin: 1, sliderMax: 14, tolerance: 1, unit: "jours"),
        QuizQuestion(id: "course_104_romeo_et_juliette_shakespeare_q3", question: "Quel événement fait basculer le ton de la pièce, de la comédie vers la tragédie ?", options: ["La mort de Mercutio", "Le bal masqué chez les Capulet", "Le mariage secret des amants", "Le bannissement de Roméo"], correctIndex: 0, explanation: "La mort de Mercutio, tué par Tybalt, fait disparaître l'insouciance et bascule définitivement la pièce dans la tragédie."),
        QuizQuestion(id: "course_104_romeo_et_juliette_shakespeare_q4", question: "Qui célèbre le mariage secret de Roméo et Juliette, en espérant réconcilier les deux familles ?", options: ["Le Frère Laurent", "Le Prince de Vérone", "Mercutio", "La nourrice de Juliette"], correctIndex: 0, explanation: "Le Frère Laurent marie secrètement les amants en espérant que leur union apaise la haine entre les clans."),
        QuizQuestion(id: "course_104_romeo_et_juliette_shakespeare_q5", question: "Qu'est-ce qui empêche le message du Frère Laurent d'arriver à temps auprès de Roméo ?", options: ["Une épidémie de peste qui retarde le messager", "Une tempête en mer", "L'arrestation du messager par le Prince", "Une erreur d'adresse"], correctIndex: 0, explanation: "Une épidémie de peste retarde le messager chargé de prévenir Roméo, précipitant le double suicide final."),
        QuizQuestion(id: "course_104_romeo_et_juliette_shakespeare_q6", type: .trueFalse, question: "Vrai ou faux : chez Bandello, la source italienne de Shakespeare, Juliette se réveille avant la mort de Roméo, contrairement à la pièce.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Shakespeare supprime cet adieu présent chez Bandello pour rendre la fin de la pièce plus cruelle."),
        QuizQuestion(id: "course_104_romeo_et_juliette_shakespeare_q7", question: "Qui tue Tybalt, provoquant le bannissement de Roméo hors de Vérone ?", options: ["Roméo lui-même", "Mercutio", "Le comte Pâris", "Le Prince de Vérone"], correctIndex: 0, explanation: "Roméo tue Tybalt pour venger Mercutio, ce qui lui vaut d'être banni de la cité."),
        QuizQuestion(id: "course_104_romeo_et_juliette_shakespeare_q8", question: "Quelle œuvre du XXe siècle transpose le conflit des clans de Vérone dans les rues de New York ?", options: ["West Side Story", "Grease", "Le Parrain", "La Fureur de vivre"], correctIndex: 0, explanation: "West Side Story remplace les Montague et les Capulet par les gangs des Sharks et des Jets."),
        QuizQuestion(id: "course_104_romeo_et_juliette_shakespeare_q9", type: .trueFalse, question: "Vrai ou faux : Dante évoquait déjà les familles Montecchi et Cappelletti deux siècles avant Shakespeare.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Dante mentionne ces deux familles véronaises dans son œuvre, bien avant que Shakespeare n'en fasse une tragédie universelle.")
    ]
        ),
        Course(
            id: "course_105_le_meilleur_des_mondes_aldous_huxley",
            title: "« Le Meilleur des mondes » : peut-on être heureux sans liberté ?",
            description: "Le Meilleur des Mondes (1932) est l'autre grande dystopie du XXe siècle avec 1984. Là où Orwell imagine une oppression par la terreur, Huxley imagine une opp...",
            subject: .litterature,
            subcategory: "Anglo-saxons & littérature mondiale",
            lessons: [
                LessonPage(id: "course_105_le_meilleur_des_mondes_aldous_huxley_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_105_le_meilleur_des_mondes_aldous_huxley_p1", title: "Aux racines de la prophétie huxleyenne", content: ""),
                LessonPage(id: "course_105_le_meilleur_des_mondes_aldous_huxley_p2", title: "L'organisation de l'An 632 après Ford", content: ""),
                LessonPage(id: "course_105_le_meilleur_des_mondes_aldous_huxley_p3", title: "John le Sauvage : le choc du tragique et du confort", content: ""),
                LessonPage(id: "course_105_le_meilleur_des_mondes_aldous_huxley_p4", title: "Héritage et actualité du meilleur des mondes", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_105_le_meilleur_des_mondes_aldous_huxley_q1", question: "En quoi la domination imaginée par Huxley diffère-t-elle de celle d'Orwell dans 1984 ?", options: ["Elle repose sur le plaisir et le confort plutôt que sur la terreur", "Elle repose sur la famine organisée", "Elle repose sur une guerre permanente", "Elle repose sur la surveillance policière constante"], correctIndex: 0, explanation: "Là où Orwell décrit une terreur policière, Huxley imagine une soumission volontaire obtenue par le plaisir et le confort."),
        QuizQuestion(id: "course_105_le_meilleur_des_mondes_aldous_huxley_q2", question: "Quel modèle industriel inspire Huxley pour organiser sa société future ?", options: ["Le fordisme et le taylorisme", "Le colonialisme britannique", "Le militarisme prussien", "L'artisanat traditionnel"], correctIndex: 0, explanation: "Huxley transpose la logique des chaînes de montage et de la standardisation industrielle à la reproduction humaine elle-même."),
        QuizQuestion(id: "course_105_le_meilleur_des_mondes_aldous_huxley_q3", type: .trueFalse, question: "Vrai ou faux : le titre original, Brave New World, cite ironiquement une pièce de Shakespeare.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Le titre cite La Tempête de Shakespeare, dont l'émerveillement naïf masque ici un futur déshumanisé."),
        QuizQuestion(id: "course_105_le_meilleur_des_mondes_aldous_huxley_q4", question: "Comment les castes sociales, des Alphas aux Epsilons, sont-elles déterminées dans le roman ?", options: ["Dès la conception, grâce au procédé Bokanovsky", "Par un examen passé à l'âge adulte", "Par l'hérédité familiale", "Par un tirage au sort à la naissance"], correctIndex: 0, explanation: "Le procédé Bokanovsky permet de produire et conditionner chaque caste dès la conception, pour qu'elle aime sa condition."),
        QuizQuestion(id: "course_105_le_meilleur_des_mondes_aldous_huxley_q5", question: "Quel rôle joue le soma dans cette société ?", options: ["C'est une drogue de confort qui supprime toute frustration", "C'est un carburant réservé à l'industrie", "C'est un vaccin obligatoire pour tous", "C'est un aliment de base rationné"], correctIndex: 0, explanation: "Le soma est une drogue sans effet secondaire qui dissout instantanément toute frustration ou souffrance."),
        QuizQuestion(id: "course_105_le_meilleur_des_mondes_aldous_huxley_q6", question: "Qui est John le Sauvage ?", options: ["Un homme né naturellement dans une Réserve, qui a lu Shakespeare", "Le Contrôleur mondial du système", "Un Alpha rebelle élevé dans la capitale", "Un scientifique qui a créé le soma"], correctIndex: 0, explanation: "John, né hors du système dans une Réserve, incarne l'humaniste capable de douleur et d'extase, formé par la lecture de Shakespeare."),
        QuizQuestion(id: "course_105_le_meilleur_des_mondes_aldous_huxley_q7", question: "Que revendique John face à Mustapha Mond, le Contrôleur mondial ?", options: ["Le droit d'être malheureux", "Le droit de posséder plus de soma", "Le droit de diriger le monde", "Le droit de vivre dans la capitale"], correctIndex: 0, explanation: "John refuse le confort artificiel et revendique le droit de souffrir, de créer et d'aimer vraiment."),
        QuizQuestion(id: "course_105_le_meilleur_des_mondes_aldous_huxley_q8", type: .trueFalse, question: "Vrai ou faux : à la fin du roman, John accepte de vivre dans le confort du Meilleur des Mondes.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "John refuse le soma et le paradis artificiel proposé par Mond : il se donne la mort, sans réconciliation possible."),
        QuizQuestion(id: "course_105_le_meilleur_des_mondes_aldous_huxley_q9", type: .numericSlider, question: "En quelle année Aldous Huxley publie-t-il Le Meilleur des Mondes ?", explanation: "Huxley publie ce roman en 1932, après l'avoir écrit l'année précédente.", correctValue: 1932, sliderMin: 1900, sliderMax: 1960, tolerance: 3, unit: "")
    ]
        ),
        Course(
            id: "course_106_frankenstein_mary_shelley",
            title: "Qui est le vrai monstre de « Frankenstein » ?",
            description: "Frankenstein ou le Prométhée moderne (1818) est le premier roman de science-fiction de l'histoire, écrit par une jeune femme de 18 ans lors d'une nuit orageu...",
            subject: .litterature,
            subcategory: "Anglo-saxons & littérature mondiale",
            lessons: [
                LessonPage(id: "course_106_frankenstein_mary_shelley_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_106_frankenstein_mary_shelley_p1", title: "Le laboratoire du lac Léman : une genèse apocalyptique", content: ""),
                LessonPage(id: "course_106_frankenstein_mary_shelley_p2", title: "Victor Frankenstein ou l'hubris scientifique", content: ""),
                LessonPage(id: "course_106_frankenstein_mary_shelley_p3", title: "L'éveil de la créature : une conscience sans nom", content: ""),
                LessonPage(id: "course_106_frankenstein_mary_shelley_p4", title: "Un mythe moderne et sa postérité universelle", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_106_frankenstein_mary_shelley_q1", question: "Quel événement climatique force Mary Shelley et ses amis à rester enfermés à la Villa Diodati en 1816 ?", options: ["L'éruption du volcan Tambora, provoquant une année sans été", "Une épidémie de choléra en Europe", "Une guerre napoléonienne", "Un hiver rigoureux mais habituel"], correctIndex: 0, explanation: "L'éruption du Tambora plonge l'Europe dans une année sans été en 1816, poussant le groupe à rester enfermé au bord du lac Léman."),
        QuizQuestion(id: "course_106_frankenstein_mary_shelley_q2", question: "Qui propose le concours d'histoires effrayantes à l'origine de Frankenstein ?", options: ["Lord Byron", "Percy Shelley", "John Polidori", "Mary Shelley elle-même"], correctIndex: 0, explanation: "C'est Lord Byron qui propose ce concours pour tromper l'ennui pendant les intempéries de 1816."),
        QuizQuestion(id: "course_106_frankenstein_mary_shelley_q3", type: .numericSlider, question: "Quel âge a Mary Shelley lorsqu'elle écrit Frankenstein ?", explanation: "Mary Shelley n'a que 18 ans quand elle écrit ce roman, au croisement du romantisme noir et des débats scientifiques de son temps.", correctValue: 18, sliderMin: 10, sliderMax: 30, tolerance: 2, unit: "ans"),
        QuizQuestion(id: "course_106_frankenstein_mary_shelley_q4", question: "De quel domaine scientifique Mary Shelley s'inspire-t-elle pour l'éveil de la créature ?", options: ["Le galvanisme, ces expériences électriques sur la matière morte", "La chimie industrielle naissante", "L'astronomie newtonienne", "La médecine tropicale"], correctIndex: 0, explanation: "Le galvanisme, qui semblait animer la matière morte par l'électricité, inspire directement la scène de création de la créature."),
        QuizQuestion(id: "course_106_frankenstein_mary_shelley_q5", question: "Pourquoi Victor Frankenstein cherche-t-il le secret de la vie à Ingolstadt ?", options: ["Pour devenir un Prométhée moderne, non pour s'enrichir", "Pour guérir une maladie de sa famille", "Pour obtenir une reconnaissance financière", "Pour venger la mort de son père"], correctIndex: 0, explanation: "Victor est animé par l'ambition de défier l'ordre naturel et de devenir un créateur, un « Prométhée moderne »."),
        QuizQuestion(id: "course_106_frankenstein_mary_shelley_q6", question: "Comment la créature apprend-elle le langage et les sentiments humains ?", options: ["En observant une famille de paysans et en lisant Le Paradis perdu de Milton", "En suivant des cours à l'université d'Ingolstadt", "En lisant les journaux intimes de Victor", "En écoutant des prêtres itinérants"], correctIndex: 0, explanation: "La créature s'instruit seule, en secret, en observant une famille de paysans et en lisant Le Paradis perdu."),
        QuizQuestion(id: "course_106_frankenstein_mary_shelley_q7", question: "Que demande la créature à Victor, qui la lui refuse ?", options: ["Une compagne de sa condition", "De l'argent pour voyager", "Un nom pour exister socialement", "Un pardon public de ses crimes"], correctIndex: 0, explanation: "La créature demande une compagne pour ne plus être seule ; le refus de Victor déclenche sa vengeance destructrice."),
        QuizQuestion(id: "course_106_frankenstein_mary_shelley_q8", type: .trueFalse, question: "Vrai ou faux : dans le roman, le nom « Frankenstein » désigne le créateur, tandis que la créature elle-même n'a pas de nom.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "La créature n'a jamais de nom propre, signe du déni de paternité de Victor : appeler le monstre « Frankenstein » est donc un contresens."),
        QuizQuestion(id: "course_106_frankenstein_mary_shelley_q9", question: "Où le roman se termine-t-il, entre la mort de Victor et la disparition de la créature ?", options: ["Dans l'Arctique", "À Genève", "À Ingolstadt", "En pleine mer Méditerranée"], correctIndex: 0, explanation: "Le roman se conclut dans les glaces de l'Arctique, où Victor meurt et où la créature disparaît dans les brumes.")
    ]
        ),
    ]
}
