import Foundation

// GENERATED by scripts/split_course_data.py from Services/CourseData.swift.
// Do not edit: change CourseData.swift and rerun the script.
nonisolated extension CourseData {
    static let chunk09: [Course] = [
        Course(
            id: "course_122_la_naissance_de_l_impressionnisme",
            title: "Comment l'impressionnisme est-il né contre le Salon ?",
            description: "En 1874, un groupe de peintres refusés par le Salon officiel organise leur propre exposition. Un critique les raille en se moquant du tableau de Monet intitu...",
            subject: .art,
            subcategory: "Peinture & mouvements",
            lessons: [
                LessonPage(id: "course_122_la_naissance_de_l_impressionnisme_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_122_la_naissance_de_l_impressionnisme_p1", title: "Le poids de l'académisme et la rupture de 1863", content: ""),
                LessonPage(id: "course_122_la_naissance_de_l_impressionnisme_p2", title: "La mutation technique : optique et plein air", content: ""),
                LessonPage(id: "course_122_la_naissance_de_l_impressionnisme_p3", title: "De l'insulte au triomphe : l'indépendance organisée", content: ""),
                LessonPage(id: "course_122_la_naissance_de_l_impressionnisme_p4", title: "L'héritage d'une vision nouvelle", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_122_la_naissance_de_l_impressionnisme_q1", question: "Quel critique invente le mot « impressionnistes » en se moquant d'un tableau de Monet ?", options: ["Louis Leroy", "Émile Zola", "Charles Baudelaire", "Théophile Gautier"], correctIndex: 0, explanation: "Louis Leroy raille le titre Impression, soleil levant de Monet, ce qui donne involontairement son nom au mouvement."),
        QuizQuestion(id: "course_122_la_naissance_de_l_impressionnisme_q2", question: "Quel tableau de Manet scandalise le Salon des Refusés en 1863 ?", options: ["Le Déjeuner sur l'herbe", "Impression, soleil levant", "Les Nymphéas", "Le Radeau de la Méduse"], correctIndex: 0, explanation: "Manet choque en mêlant un nu féminin et deux hommes en costume moderne dans Le Déjeuner sur l'herbe."),
        QuizQuestion(id: "course_122_la_naissance_de_l_impressionnisme_q3", type: .trueFalse, question: "Vrai ou faux : en 1863, le jury du Salon refuse plus de 3 000 tableaux.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Ce refus massif pousse Napoléon III à autoriser en réaction le Salon des Refusés."),
        QuizQuestion(id: "course_122_la_naissance_de_l_impressionnisme_q4", question: "Quelle innovation matérielle permet aux impressionnistes de peindre en extérieur ?", options: ["Les tubes de peinture", "La photographie", "Le papier mâché", "La lithographie"], correctIndex: 0, explanation: "Les tubes de peinture transportables libèrent les peintres de l'atelier et leur permettent de travailler en plein air."),
        QuizQuestion(id: "course_122_la_naissance_de_l_impressionnisme_q5", question: "Quel chimiste inspire les impressionnistes dans leur usage des couleurs complémentaires ?", options: ["Michel-Eugène Chevreul", "Louis Pasteur", "Antoine Lavoisier", "Marie Curie"], correctIndex: 0, explanation: "Les recherches de Chevreul sur les couleurs complémentaires poussent les impressionnistes à bannir le noir des ombres."),
        QuizQuestion(id: "course_122_la_naissance_de_l_impressionnisme_q6", question: "Où se déroule la première exposition impressionniste de 1874 ?", options: ["Dans l'atelier du photographe Nadar", "Au Salon officiel du Louvre", "Au musée d'Orsay", "À l'Académie des beaux-arts"], correctIndex: 0, explanation: "Le groupe expose dans l'ancien atelier du photographe Nadar, faute d'accès au Salon officiel."),
        QuizQuestion(id: "course_122_la_naissance_de_l_impressionnisme_q7", question: "Quelle influence artistique venue d'Asie inspire les cadrages asymétriques des impressionnistes ?", options: ["Les estampes japonaises", "La calligraphie chinoise", "Les miniatures persanes", "Les mosaïques byzantines"], correctIndex: 0, explanation: "Les estampes japonaises apportent des cadrages asymétriques et des vues en plongée inédits en Europe."),
        QuizQuestion(id: "course_122_la_naissance_de_l_impressionnisme_q8", type: .chronological, question: "Remets ces étapes de l'impressionnisme dans l'ordre chronologique.", explanation: "Ces trois jalons s'échelonnent de 1863 à 1886, du scandale initial à la fin des expositions collectives du groupe.", items: ["Le scandale du Déjeuner sur l'herbe de Manet", "La première exposition indépendante chez Nadar", "La dernière des huit expositions du groupe"]),
        QuizQuestion(id: "course_122_la_naissance_de_l_impressionnisme_q9", type: .numericSlider, question: "En quelle année les impressionnistes organisent-ils leur première exposition indépendante ?", explanation: "La première exposition indépendante du groupe a lieu en avril 1874 dans l'atelier du photographe Nadar.", correctValue: 1874, sliderMin: 1850, sliderMax: 1900, tolerance: 3, unit: "")
    ]
        ),
        Course(
            id: "course_123_le_caravage_et_le_clair_obscur",
            title: "Le Caravage et le clair-obscur",
            description: "Le Caravage (1571-1610) révolutionne la peinture européenne en introduisant un réalisme brutal et un usage dramatique du contraste lumière-ombre, le clair-ob...",
            subject: .art,
            subcategory: "Peinture & mouvements",
            lessons: [
                LessonPage(id: "course_123_le_caravage_et_le_clair_obscur_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_123_le_caravage_et_le_clair_obscur_p1", title: "Une trajectoire fulgurante entre génie et marginalité", content: ""),
                LessonPage(id: "course_123_le_caravage_et_le_clair_obscur_p2", title: "La naissance du ténébrisme et la théologie de la lumière", content: ""),
                LessonPage(id: "course_123_le_caravage_et_le_clair_obscur_p3", title: "Un réalisme sans compromis face aux enjeux de la foi", content: ""),
                LessonPage(id: "course_123_le_caravage_et_le_clair_obscur_p4", title: "Le caravagisme : héritage et réhabilitation d'un précurseur", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_123_le_caravage_et_le_clair_obscur_q1", question: "Quel est le vrai nom du peintre connu comme Le Caravage ?", options: ["Michelangelo Merisi", "Michelangelo Buonarroti", "Domenico Fetti", "Annibale Carracci"], correctIndex: 0, explanation: "Le Caravage se nomme en réalité Michelangelo Merisi, originaire de la région de Milan."),
        QuizQuestion(id: "course_123_le_caravage_et_le_clair_obscur_q2", question: "Comment appelle-t-on la forme extrême de clair-obscur inventée par Le Caravage ?", options: ["Le ténébrisme", "Le sfumato", "Le pointillisme", "Le maniérisme"], correctIndex: 0, explanation: "Le ténébrisme plonge la scène dans une obscurité opaque d'où les corps jaillissent avec une force sculpturale."),
        QuizQuestion(id: "course_123_le_caravage_et_le_clair_obscur_q3", type: .trueFalse, question: "Vrai ou faux : Le Caravage choisit ses modèles parmi les mendiants et les gens du peuple pour peindre ses saints.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Il refuse d'idéaliser ses personnages religieux et prend ses modèles dans la rue, ce qui scandalise ses contemporains."),
        QuizQuestion(id: "course_123_le_caravage_et_le_clair_obscur_q4", question: "Quel tableau de 1600 sidère Rome par son sacré au visage de la rue ?", options: ["La Vocation de saint Matthieu", "La Ronde de nuit", "Les Demoiselles d'Avignon", "Le Radeau de la Méduse"], correctIndex: 0, explanation: "La Vocation de saint Matthieu, peinte pour la chapelle Contarelli, impose un sacré incarné par des gens ordinaires."),
        QuizQuestion(id: "course_123_le_caravage_et_le_clair_obscur_q5", question: "Pourquoi Le Caravage doit-il fuir Rome en 1606 ?", options: ["Il tue Ranuccio Tomassoni lors d'une rixe", "Il est accusé d'hérésie", "Il vole une commande royale", "Il insulte le pape publiquement"], correctIndex: 0, explanation: "Lors d'une rixe en 1606, il tue Ranuccio Tomassoni et est condamné à mort, ce qui le force à l'exil."),
        QuizQuestion(id: "course_123_le_caravage_et_le_clair_obscur_q6", question: "Quel style Le Caravage rejette-t-il, jugé trop gracieux et artificiel ?", options: ["Le maniérisme", "Le baroque", "Le néoclassicisme", "Le romantisme"], correctIndex: 0, explanation: "Il refuse les artifices du maniérisme, ce style gracieux et déformé qui l'a précédé."),
        QuizQuestion(id: "course_123_le_caravage_et_le_clair_obscur_q7", question: "Quel peintre hollandais hérite plus tard de la poésie de l'ombre du Caravage ?", options: ["Rembrandt", "Vermeer", "Van Eyck", "Bruegel"], correctIndex: 0, explanation: "Rembrandt reprend et approfondit l'héritage du clair-obscur caravagesque dans son propre style."),
        QuizQuestion(id: "course_123_le_caravage_et_le_clair_obscur_q8", type: .numericSlider, question: "À quel âge Le Caravage meurt-il, en fuite, à Porto Ercole ?", explanation: "Traqué et blessé, Le Caravage meurt à 38 ans, quelques jours avant une grâce papale.", correctValue: 38, sliderMin: 20, sliderMax: 60, tolerance: 2, unit: "ans"),
        QuizQuestion(id: "course_123_le_caravage_et_le_clair_obscur_q9", type: .chronological, question: "Remets ces événements de la vie du Caravage dans l'ordre chronologique.", explanation: "Cette trajectoire couvre son arrivée vers 1593, son triomphe en 1600, son exil après 1606 et sa mort en 1610.", items: ["Arrivée à Rome", "La Vocation de saint Matthieu sidère la ville", "Meurtre de Ranuccio Tomassoni et fuite", "Mort à Porto Ercole"])
    ]
        ),
        Course(
            id: "course_124_rembrandt_et_l_ecole_flamande",
            title: "Comment Rembrandt a-t-il fait de l'ombre un langage de l'âme ?",
            description: "Rembrandt van Rijn (1606-1669) est le plus grand peintre de l'école hollandaise du Siècle d'Or - peut-être le plus grand portraitiste de l'histoire. Ses auto...",
            subject: .art,
            subcategory: "Peinture & mouvements",
            lessons: [
                LessonPage(id: "course_124_rembrandt_et_l_ecole_flamande_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_124_rembrandt_et_l_ecole_flamande_p1", title: "Le Siècle d'Or et l'émergence d'un marché bourgeois", content: ""),
                LessonPage(id: "course_124_rembrandt_et_l_ecole_flamande_p2", title: "La technique Rembrandt : lumière et impasto", content: ""),
                LessonPage(id: "course_124_rembrandt_et_l_ecole_flamande_p3", title: "La Ronde de nuit : une révolution du portrait de groupe", content: ""),
                LessonPage(id: "course_124_rembrandt_et_l_ecole_flamande_p4", title: "L'autoportrait comme journal métaphysique", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_124_rembrandt_et_l_ecole_flamande_q1", question: "Dans quel espace politique Rembrandt exerce-t-il, porté par un marché d'art bourgeois ?", options: ["Les Provinces-Unies (Pays-Bas)", "La France", "L'Espagne", "L'Italie"], correctIndex: 0, explanation: "Au XVIIe siècle, la bourgeoisie protestante hollandaise commande des tableaux pour ses maisons, sans passer par l'Église ou la cour."),
        QuizQuestion(id: "course_124_rembrandt_et_l_ecole_flamande_q2", question: "Comment appelle-t-on la technique de peinture épaisse et en relief signature de Rembrandt ?", options: ["L'impasto", "Le sfumato", "La grisaille", "L'aquarelle"], correctIndex: 0, explanation: "L'impasto est cette peinture posée si épaisse qu'elle crée un relief, à contre-courant du goût pour les surfaces lisses."),
        QuizQuestion(id: "course_124_rembrandt_et_l_ecole_flamande_q3", type: .trueFalse, question: "Vrai ou faux : La Ronde de nuit représente en réalité une scène de jour.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Le titre est un contresens : la scène est diurne, mais des siècles de vernis sale ont assombri la toile jusqu'à suggérer la nuit."),
        QuizQuestion(id: "course_124_rembrandt_et_l_ecole_flamande_q4", question: "Que représente vraiment le tableau connu sous le nom de La Ronde de nuit ?", options: ["Une compagnie de milice bourgeoise en mouvement", "Un autoportrait de Rembrandt", "Une scène biblique nocturne", "Un paysage hollandais"], correctIndex: 0, explanation: "Il s'agit de La Compagnie du capitaine Frans Banning Cocq, une milice montrée en mouvement plutôt qu'alignée comme l'exigeait la convention."),
        QuizQuestion(id: "course_124_rembrandt_et_l_ecole_flamande_q5", question: "Quel événement financier frappe Rembrandt en 1656 ?", options: ["Sa faillite personnelle", "Son anoblissement", "Son mariage", "Son exil"], correctIndex: 0, explanation: "En 1656, la faillite personnelle de Rembrandt entraîne la vente aux enchères de sa maison et de ses collections."),
        QuizQuestion(id: "course_124_rembrandt_et_l_ecole_flamande_q6", type: .numericSlider, question: "Environ combien d'autoportraits Rembrandt a-t-il peints au cours de sa vie ?", explanation: "Rembrandt a peint environ 80 à 90 autoportraits en près de quarante ans, un témoignage unique de son évolution.", correctValue: 85, sliderMin: 50, sliderMax: 120, tolerance: 10, unit: ""),
        QuizQuestion(id: "course_124_rembrandt_et_l_ecole_flamande_q7", question: "Quel peintre du XVIIe siècle influence le clair-obscur de Rembrandt ?", options: ["Le Caravage", "Botticelli", "Titien", "Giotto"], correctIndex: 0, explanation: "Rembrandt réinvente le clair-obscur hérité du Caravage en le rendant plus intérieur et émotionnel."),
        QuizQuestion(id: "course_124_rembrandt_et_l_ecole_flamande_q8", type: .trueFalse, question: "Vrai ou faux : Rembrandt adoucit son style à la fin de sa vie pour plaire à la mode et sauver sa fortune.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "Il refuse au contraire d'adoucir son style malgré son train de vie ruineux, restant fidèle à sa vision artistique."),
        QuizQuestion(id: "course_124_rembrandt_et_l_ecole_flamande_q9", type: .chronological, question: "Remets ces étapes de la vie de Rembrandt dans l'ordre chronologique.", explanation: "Ces jalons s'étendent de 1631 à 1669, de son installation triomphale à Amsterdam jusqu'à sa mort.", items: ["Arrivée à Amsterdam", "La Ronde de nuit", "Faillite personnelle", "Mort du peintre"])
    ]
        ),
        Course(
            id: "course_125_le_romantisme_en_peinture_delacroix_geri",
            title: "Romantisme : qu'ont changé Géricault et Delacroix en peinture ?",
            description: "Le romantisme en peinture (1810-1850) est la grande révolte contre la froideur académique du néoclassicisme. Couleur contre dessin, passion contre raison, mo...",
            subject: .art,
            subcategory: "Peinture & mouvements",
            lessons: [
                LessonPage(id: "course_125_le_romantisme_en_peinture_delacroix_geri_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_125_le_romantisme_en_peinture_delacroix_geri_p1", title: "La rupture avec l'ordre académique", content: ""),
                LessonPage(id: "course_125_le_romantisme_en_peinture_delacroix_geri_p2", title: "Géricault et l'éclosion du drame moderne", content: ""),
                LessonPage(id: "course_125_le_romantisme_en_peinture_delacroix_geri_p3", title: "Delacroix : la ferveur et l'orientalisme", content: ""),
                LessonPage(id: "course_125_le_romantisme_en_peinture_delacroix_geri_p4", title: "Héritage et postérité du romantisme", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_125_le_romantisme_en_peinture_delacroix_geri_q1", question: "Contre quel mouvement le romantisme se positionne-t-il en réaction ?", options: ["Le néoclassicisme", "Le baroque", "L'impressionnisme", "Le pop art"], correctIndex: 0, explanation: "Le romantisme s'oppose à la rigueur froide du néoclassicisme incarné par Jacques-Louis David."),
        QuizQuestion(id: "course_125_le_romantisme_en_peinture_delacroix_geri_q2", question: "Quel événement réel inspire Le Radeau de la Méduse de Géricault ?", options: ["Le naufrage de la frégate Méduse", "La bataille de Waterloo", "La révolution de Juillet", "Le siège de Paris"], correctIndex: 0, explanation: "Géricault s'inspire du naufrage réel de la Méduse en 1816, où un capitaine abandonne environ 150 marins sur un radeau."),
        QuizQuestion(id: "course_125_le_romantisme_en_peinture_delacroix_geri_q3", type: .trueFalse, question: "Vrai ou faux : Delacroix peint La Liberté guidant le peuple pour célébrer la révolution de Juillet 1830.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Le tableau célèbre les Trois Glorieuses, les journées révolutionnaires de juillet 1830."),
        QuizQuestion(id: "course_125_le_romantisme_en_peinture_delacroix_geri_q4", question: "Quel voyage transforme la palette de Delacroix en 1832 ?", options: ["Un voyage au Maroc", "Un voyage en Italie", "Un voyage en Égypte", "Un voyage en Grèce"], correctIndex: 0, explanation: "Son voyage au Maroc en 1832 lui révèle une lumière nouvelle et fonde en partie l'orientalisme."),
        QuizQuestion(id: "course_125_le_romantisme_en_peinture_delacroix_geri_q5", question: "Quel peintre académique s'oppose à Delacroix en défendant la ligne plutôt que la couleur ?", options: ["Ingres", "David", "Géricault", "Manet"], correctIndex: 0, explanation: "Jean-Auguste-Dominique Ingres, rival de Delacroix, défend la ligne lisse et précise contre la couleur émotive."),
        QuizQuestion(id: "course_125_le_romantisme_en_peinture_delacroix_geri_q6", question: "Pour peindre la vérité des corps du Radeau de la Méduse, que fait Géricault ?", options: ["Il étudie des cadavres", "Il consulte des médecins militaires", "Il copie des statues antiques", "Il interroge uniquement des survivants"], correctIndex: 0, explanation: "Géricault étudie des cadavres pour représenter avec réalisme l'agonie des naufragés."),
        QuizQuestion(id: "course_125_le_romantisme_en_peinture_delacroix_geri_q7", type: .numericSlider, question: "Environ combien de marins sont abandonnés sur le radeau de la Méduse en 1816 ?", explanation: "Un capitaine nommé par faveur royale abandonne environ 150 marins sur un radeau de fortune.", correctValue: 150, sliderMin: 50, sliderMax: 300, tolerance: 20, unit: ""),
        QuizQuestion(id: "course_125_le_romantisme_en_peinture_delacroix_geri_q8", question: "Qui prend la tête du mouvement romantique après la mort prématurée de Géricault ?", options: ["Eugène Delacroix", "Ingres", "David", "Manet"], correctIndex: 0, explanation: "Après la mort prématurée de Géricault, Delacroix devient le chef de file du mouvement romantique."),
        QuizQuestion(id: "course_125_le_romantisme_en_peinture_delacroix_geri_q9", type: .chronological, question: "Remets ces œuvres et événements du romantisme dans l'ordre chronologique.", explanation: "Ces jalons vont de 1816 à 1832, du naufrage réel à la transformation de la palette de Delacroix par l'Orient.", items: ["Le naufrage de la frégate Méduse", "Le Radeau de la Méduse est exposé", "La révolution de Juillet et La Liberté guidant le peuple", "Le voyage de Delacroix au Maroc"])
    ]
        ),
        Course(
            id: "course_126_le_cubisme_picasso_et_braque",
            title: "Comment Picasso et Braque ont-ils inventé le cubisme ?",
            description: "Le cubisme (1907-1920) est peut-être la révolution artistique la plus radicale depuis la Renaissance. En brisant l'objet en fragments géométriques vus simult...",
            subject: .art,
            subcategory: "Peinture & mouvements",
            lessons: [
                LessonPage(id: "course_126_le_cubisme_picasso_et_braque_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_126_le_cubisme_picasso_et_braque_p1", title: "L'héritage de Cézanne et le choc des arts premiers", content: ""),
                LessonPage(id: "course_126_le_cubisme_picasso_et_braque_p2", title: "L'audace du cubisme analytique", content: ""),
                LessonPage(id: "course_126_le_cubisme_picasso_et_braque_p3", title: "L'innovation du cubisme synthétique", content: ""),
                LessonPage(id: "course_126_le_cubisme_picasso_et_braque_p4", title: "Un héritage universel", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_126_le_cubisme_picasso_et_braque_q1", question: "Quel peintre conseille de traiter la nature par le cylindre, la sphère et le cône, influençant le cubisme ?", options: ["Paul Cézanne", "Claude Monet", "Édouard Manet", "Henri Matisse"], correctIndex: 0, explanation: "Cézanne cherche la solidité des formes derrière la lumière et inspire directement la géométrisation cubiste."),
        QuizQuestion(id: "course_126_le_cubisme_picasso_et_braque_q2", question: "Quelle découverte au musée du Trocadéro en 1907 marque Picasso ?", options: ["Les arts africains et océaniens", "L'art égyptien", "L'art byzantin", "L'art précolombien"], correctIndex: 0, explanation: "Picasso découvre au Trocadéro des masques africains et océaniens qui conceptualisent le visage plutôt que de le copier."),
        QuizQuestion(id: "course_126_le_cubisme_picasso_et_braque_q3", question: "Quel tableau de 1907 marque le point de départ du cubisme ?", options: ["Les Demoiselles d'Avignon", "Guernica", "La Liberté guidant le peuple", "Le Déjeuner sur l'herbe"], correctIndex: 0, explanation: "Les Demoiselles d'Avignon, avec ses nus aux facettes tranchantes, sidère jusqu'aux proches de Picasso."),
        QuizQuestion(id: "course_126_le_cubisme_picasso_et_braque_q4", type: .trueFalse, question: "Vrai ou faux : dans le cubisme analytique, la couleur presque disparaît au profit des gris et des ocres.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Entre 1908 et 1912, Picasso et Braque réduisent la couleur pour forcer le regard sur la construction de l'espace."),
        QuizQuestion(id: "course_126_le_cubisme_picasso_et_braque_q5", question: "Comment appelle-t-on la technique qui introduit journaux et papiers peints dans les toiles cubistes vers 1912 ?", options: ["Le collage", "La sérigraphie", "La fresque", "Le pochoir"], correctIndex: 0, explanation: "Le collage, apparu avec le cubisme synthétique, fait entrer des matériaux réels comme le papier journal dans le tableau."),
        QuizQuestion(id: "course_126_le_cubisme_picasso_et_braque_q6", question: "Quel cubiste apporte une rigueur mathématique particulière au mouvement ?", options: ["Juan Gris", "Fernand Léger", "Robert Delaunay", "Marcel Duchamp"], correctIndex: 0, explanation: "Juan Gris développe une approche du cubisme marquée par une rigueur géométrique et mathématique."),
        QuizQuestion(id: "course_126_le_cubisme_picasso_et_braque_q7", question: "Quelle profession antérieure de Georges Braque explique son talent pour imiter les matières dans ses collages ?", options: ["Peintre-décorateur", "Photographe", "Sculpteur", "Architecte"], correctIndex: 0, explanation: "Ancien peintre-décorateur, Braque savait peindre de faux bois si parfaits qu'ils semblaient plus vrais que le bois réellement collé."),
        QuizQuestion(id: "course_126_le_cubisme_picasso_et_braque_q8", type: .chronological, question: "Remets ces étapes du cubisme dans l'ordre chronologique.", explanation: "Ces jalons vont de 1907 à 1912, de la rupture initiale à l'invention du collage.", items: ["Les Demoiselles d'Avignon", "Le cubisme analytique dissèque l'objet", "Le collage et le cubisme synthétique"]),
        QuizQuestion(id: "course_126_le_cubisme_picasso_et_braque_q9", type: .numericSlider, question: "Vers quelle année Picasso achève-t-il Les Demoiselles d'Avignon ?", explanation: "Picasso achève ce tableau fondateur du cubisme en 1907.", correctValue: 1907, sliderMin: 1880, sliderMax: 1930, tolerance: 3, unit: "")
    ]
        ),
        Course(
            id: "course_127_le_surrealisme_dali_et_magritte",
            title: "Que voulaient libérer les surréalistes, de Dalí à Magritte ?",
            description: "Le surréalisme (1924-1950) est un mouvement artistique et littéraire qui cherche à libérer l'inconscient - le rêve, les désirs refoulés, les associations irr...",
            subject: .art,
            subcategory: "Peinture & mouvements",
            lessons: [
                LessonPage(id: "course_127_le_surrealisme_dali_et_magritte_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_127_le_surrealisme_dali_et_magritte_p1", title: "Le manifeste surréaliste et la source freudienne", content: ""),
                LessonPage(id: "course_127_le_surrealisme_dali_et_magritte_p2", title: "Salvador Dalí : l'esthétique du délire maîtrisé", content: ""),
                LessonPage(id: "course_127_le_surrealisme_dali_et_magritte_p3", title: "René Magritte : la philosophie de l'image", content: ""),
                LessonPage(id: "course_127_le_surrealisme_dali_et_magritte_p4", title: "Héritage et portance du mouvement", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_127_le_surrealisme_dali_et_magritte_q1", question: "Qui fonde le surréalisme avec le Manifeste du surréalisme en 1924 ?", options: ["André Breton", "Salvador Dalí", "René Magritte", "Tristan Tzara"], correctIndex: 0, explanation: "Le poète André Breton fonde le mouvement avec son Manifeste du surréalisme publié en 1924."),
        QuizQuestion(id: "course_127_le_surrealisme_dali_et_magritte_q2", question: "Quelle méthode Dalí invente-t-il pour peindre son délire volontaire ?", options: ["La méthode paranoïaque-critique", "L'écriture automatique", "Le cadavre exquis", "Le collage"], correctIndex: 0, explanation: "Dalí invente la méthode paranoïaque-critique, un délire volontaire associant des éléments hétéroclites."),
        QuizQuestion(id: "course_127_le_surrealisme_dali_et_magritte_q3", type: .trueFalse, question: "Vrai ou faux : le surréalisme s'inspire des théories de Sigmund Freud sur l'inconscient.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Freud montre que l'inconscient domine la psyché, ce qui inspire directement les surréalistes."),
        QuizQuestion(id: "course_127_le_surrealisme_dali_et_magritte_q4", question: "Quel tableau de Dalí montre des montres molles dans un paysage catalan ?", options: ["La Persistance de la mémoire", "La Trahison des images", "Le Radeau de la Méduse", "Guernica"], correctIndex: 0, explanation: "La Persistance de la mémoire, peinte en 1931, montre des montres molles dans un paysage inspiré de Port Lligat."),
        QuizQuestion(id: "course_127_le_surrealisme_dali_et_magritte_q5", question: "Quelle phrase Magritte écrit-il sous une pipe peinte avec réalisme ?", options: ["Ceci n'est pas une pipe", "L'image est un mensonge", "Rien n'est réel", "Le rêve est la vérité"], correctIndex: 0, explanation: "Dans La Trahison des images, Magritte rappelle que l'image d'une pipe n'est qu'un signe, pas l'objet lui-même."),
        QuizQuestion(id: "course_127_le_surrealisme_dali_et_magritte_q6", question: "Quel mouvement précède et influence directement le surréalisme ?", options: ["Le dadaïsme", "Le cubisme", "Le fauvisme", "Le romantisme"], correctIndex: 0, explanation: "Après le dadaïsme, qui détruisait le sens, Breton veut reconstruire l'esprit en libérant la pensée."),
        QuizQuestion(id: "course_127_le_surrealisme_dali_et_magritte_q7", type: .trueFalse, question: "Vrai ou faux : André Breton surnomme Dalí Avida Dollars et l'exclut du mouvement en 1939.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Breton juge que Dalí s'est trop commercialisé et l'exclut du groupe surréaliste en 1939."),
        QuizQuestion(id: "course_127_le_surrealisme_dali_et_magritte_q8", question: "Quel jeu collectif inventent les surréalistes pour créer sans contrôle rationnel ?", options: ["Le cadavre exquis", "Le collage", "La sérigraphie", "Le happening"], correctIndex: 0, explanation: "Le cadavre exquis est un jeu où chacun ajoute une phrase ou un dessin sans voir la contribution précédente."),
        QuizQuestion(id: "course_127_le_surrealisme_dali_et_magritte_q9", type: .chronological, question: "Remets ces jalons du surréalisme dans l'ordre chronologique.", explanation: "Ces jalons vont de 1924 à 1939, de la fondation du mouvement à la rupture entre Breton et Dalí.", items: ["Le Manifeste du surréalisme de Breton", "Dalí rejoint le groupe surréaliste", "La Persistance de la mémoire", "L'exclusion de Dalí par Breton"])
    ]
        ),
        Course(
            id: "course_128_l_expressionnisme_munch_et_le_cri",
            title: "Quelle angoisse se cache derrière « Le Cri » de Munch ?",
            description: "L'expressionnisme (1880-1930) est le mouvement artistique qui fait primer l'émotion intérieure sur la représentation du monde extérieur - déformant la réalit...",
            subject: .art,
            subcategory: "Peinture & mouvements",
            lessons: [
                LessonPage(id: "course_128_l_expressionnisme_munch_et_le_cri_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_128_l_expressionnisme_munch_et_le_cri_p1", title: "Partie 1 - L'expressionnisme : une esthétique de la distorsion", content: ""),
                LessonPage(id: "course_128_l_expressionnisme_munch_et_le_cri_p2", title: "Partie 2 - Munch : la peinture comme catharsis du traumatisme", content: ""),
                LessonPage(id: "course_128_l_expressionnisme_munch_et_le_cri_p3", title: "Partie 3 - L'anatomie d'un cri silencieux", content: ""),
                LessonPage(id: "course_128_l_expressionnisme_munch_et_le_cri_p4", title: "Partie 4 - De l'angoisse intime à l'icône de la culture pop", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_128_l_expressionnisme_munch_et_le_cri_q1", question: "Quel peintre norvégien est le pionnier de l'expressionnisme avec Le Cri ?", options: ["Edvard Munch", "Vincent Van Gogh", "Paul Gauguin", "Wassily Kandinsky"], correctIndex: 0, explanation: "Le Norvégien Edvard Munch fait de l'angoisse et de la solitude modernes un symbole universel avec Le Cri."),
        QuizQuestion(id: "course_128_l_expressionnisme_munch_et_le_cri_q2", question: "Quels deux groupes allemands structurent l'expressionnisme au début du XXe siècle ?", options: ["Die Brücke et Der Blaue Reiter", "Les Nabis et les Fauves", "Le Bauhaus et De Stijl", "Les Cubistes et les Futuristes"], correctIndex: 0, explanation: "Die Brücke, plus brut, et Der Blaue Reiter, plus spirituel, structurent le mouvement en Allemagne."),
        QuizQuestion(id: "course_128_l_expressionnisme_munch_et_le_cri_q3", type: .trueFalse, question: "Vrai ou faux : Munch perd sa mère et sa sœur, emportées par la tuberculose.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Ces deuils précoces marquent profondément l'œuvre de Munch et nourrissent son angoisse existentielle."),
        QuizQuestion(id: "course_128_l_expressionnisme_munch_et_le_cri_q4", question: "Où Munch a-t-il la vision qui inspire Le Cri ?", options: ["Sur la colline d'Ekeberg à Oslo", "Sur les quais de Bergen", "Dans un fjord de Norvège du Nord", "À Paris"], correctIndex: 0, explanation: "L'origine du Cri remonte à une promenade sur la colline d'Ekeberg, où le ciel du couchant devient un incendie."),
        QuizQuestion(id: "course_128_l_expressionnisme_munch_et_le_cri_q5", question: "Quel événement naturel est parfois lié au ciel rouge à l'origine du Cri ?", options: ["L'éruption du Krakatoa", "Un tremblement de terre", "Une aurore boréale", "Une éclipse solaire"], correctIndex: 0, explanation: "Les cendres de l'éruption du Krakatoa en 1883 auraient teinté les couchers de soleil en rouge dans le monde entier."),
        QuizQuestion(id: "course_128_l_expressionnisme_munch_et_le_cri_q6", type: .numericSlider, question: "En quelle année le mot « expressionnisme » est-il utilisé pour la première fois, à la Sécession de Berlin ?", explanation: "Le mot apparaît en 1911 à la Sécession de Berlin pour distinguer les artistes refusant la douceur impressionniste.", correctValue: 1911, sliderMin: 1880, sliderMax: 1930, tolerance: 3, unit: ""),
        QuizQuestion(id: "course_128_l_expressionnisme_munch_et_le_cri_q7", question: "Combien de versions du Cri Munch peint-il au total ?", options: ["Quatre", "Deux", "Six", "Une seule"], correctIndex: 0, explanation: "Munch peint quatre versions du Cri, en tempera, pastel et huile, preuve que ce motif le hante durablement."),
        QuizQuestion(id: "course_128_l_expressionnisme_munch_et_le_cri_q8", type: .trueFalse, question: "Vrai ou faux : dans Le Cri, la figure se bouche les oreilles car le cri vient de l'extérieur, du paysage.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "Le cri est en réalité intérieur : la figure se bouche les oreilles face au hurlement du monde, pas l'inverse."),
        QuizQuestion(id: "course_128_l_expressionnisme_munch_et_le_cri_q9", question: "Quel mouvement artistique postérieur l'audace de Munch contribue-t-elle à ouvrir la voie ?", options: ["Le surréalisme", "Le cubisme", "L'impressionnisme", "Le néoclassicisme"], correctIndex: 0, explanation: "Cette audace à représenter la vérité psychologique plutôt que l'anatomie parfaite ouvre la voie au surréalisme.")
    ]
        ),
        Course(
            id: "course_129_l_art_abstrait_kandinsky_et_mondrian",
            title: "L'art abstrait : Kandinsky et Mondrian",
            description: "L'abstraction (années 1910-1920) est la révolution la plus radicale de l'histoire de la peinture : pour la première fois, un tableau ne représente plus rien...",
            subject: .art,
            subcategory: "Peinture & mouvements",
            lessons: [
                LessonPage(id: "course_129_l_art_abstrait_kandinsky_et_mondrian_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_129_l_art_abstrait_kandinsky_et_mondrian_p1", title: "Wassily Kandinsky : l'éveil de l'abstraction lyrique", content: ""),
                LessonPage(id: "course_129_l_art_abstrait_kandinsky_et_mondrian_p2", title: "Mondrian et la quête de l'équilibre universel", content: ""),
                LessonPage(id: "course_129_l_art_abstrait_kandinsky_et_mondrian_p3", title: "La synthèse art-industrie : le Bauhaus", content: ""),
                LessonPage(id: "course_129_l_art_abstrait_kandinsky_et_mondrian_p4", title: "Portée philosophique et héritage de l'immatériel", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_129_l_art_abstrait_kandinsky_et_mondrian_q1", question: "Quelle règle ancienne de la peinture l'art abstrait rompt-il ?", options: ["La mimésis, l'obligation de représenter le monde visible", "L'usage de la perspective", "L'usage de la couleur", "Le format du tableau"], correctIndex: 0, explanation: "L'abstraction brise la mimésis, cette obligation ancienne de représenter fidèlement le monde visible."),
        QuizQuestion(id: "course_129_l_art_abstrait_kandinsky_et_mondrian_q2", question: "Quel événement pousse Kandinsky vers l'abstraction vers 1910 ?", options: ["Il est bouleversé par une de ses toiles posée à l'envers, non reconnaissable", "Il visite une exposition de masques africains", "Il lit un traité de Freud", "Il rencontre Mondrian"], correctIndex: 0, explanation: "En rentrant au crépuscule, Kandinsky est bouleversé par une toile qu'il ne reconnaît pas : c'est l'une des siennes, posée à l'envers."),
        QuizQuestion(id: "course_129_l_art_abstrait_kandinsky_et_mondrian_q3", question: "Dans quel livre Kandinsky théorise-t-il l'abstraction lyrique en 1911 ?", options: ["Du Spirituel dans l'Art", "Le Manifeste du surréalisme", "De Stijl", "Les Demoiselles d'Avignon"], correctIndex: 0, explanation: "Kandinsky publie en 1911 Du Spirituel dans l'Art, où il théorise la vibration émotionnelle des couleurs."),
        QuizQuestion(id: "course_129_l_art_abstrait_kandinsky_et_mondrian_q4", type: .trueFalse, question: "Vrai ou faux : Mondrian arrive à l'abstraction en partant de séries de représentations d'arbres qu'il simplifie progressivement.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Entre 1908 et 1912, ses séries d'arbres montrent le tronc et les branches qui disparaissent au profit d'une trame de lignes."),
        QuizQuestion(id: "course_129_l_art_abstrait_kandinsky_et_mondrian_q5", question: "Comment appelle-t-on le mouvement fondé par Mondrian en 1917 ?", options: ["De Stijl", "Der Blaue Reiter", "Die Brücke", "Le Bauhaus"], correctIndex: 0, explanation: "Mondrian fonde en 1917 le mouvement De Stijl et théorise le néoplasticisme."),
        QuizQuestion(id: "course_129_l_art_abstrait_kandinsky_et_mondrian_q6", question: "Quelles couleurs et formes le néoplasticisme de Mondrian autorise-t-il exclusivement ?", options: ["La ligne droite et les trois couleurs primaires", "Les courbes et les couleurs pastel", "Les diagonales et le noir et blanc", "Les motifs floraux et les tons chauds"], correctIndex: 0, explanation: "Le néoplasticisme réduit l'art à la ligne droite et aux trois couleurs primaires, pour viser l'universel."),
        QuizQuestion(id: "course_129_l_art_abstrait_kandinsky_et_mondrian_q7", question: "Quelle école fondée par Walter Gropius en 1919 relie l'abstraction au design et à l'architecture ?", options: ["Le Bauhaus", "L'École des beaux-arts", "L'Académie de Florence", "L'Atelier des Batignolles"], correctIndex: 0, explanation: "Au Bauhaus, fondé par Walter Gropius en 1919, Kandinsky enseigne et l'esthétique de Mondrian inspire architectes et designers."),
        QuizQuestion(id: "course_129_l_art_abstrait_kandinsky_et_mondrian_q8", type: .chronological, question: "Remets ces jalons de l'art abstrait dans l'ordre chronologique.", explanation: "Ces jalons vont de 1910 à 1919, des débuts de Kandinsky à l'entrée de l'abstraction dans le design.", items: ["Kandinsky bascule vers l'abstraction", "Du Spirituel dans l'Art est publié", "Mondrian fonde De Stijl", "Fondation du Bauhaus"]),
        QuizQuestion(id: "course_129_l_art_abstrait_kandinsky_et_mondrian_q9", type: .numericSlider, question: "En quelle année Mondrian fonde-t-il le mouvement De Stijl ?", explanation: "Mondrian fonde De Stijl en 1917 et y théorise le néoplasticisme.", correctValue: 1917, sliderMin: 1900, sliderMax: 1930, tolerance: 3, unit: "")
    ]
        ),
        Course(
            id: "course_130_le_pop_art_warhol_et_lichtenstein",
            title: "Comment Warhol et Lichtenstein ont-ils fait du banal un art ?",
            description: "Le Pop Art (années 1950-1970) est la réponse de l'art à la société de consommation et à la culture de masse. En utilisant les images de la publicité, des com...",
            subject: .art,
            subcategory: "Peinture & mouvements",
            lessons: [
                LessonPage(id: "course_130_le_pop_art_warhol_et_lichtenstein_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_130_le_pop_art_warhol_et_lichtenstein_p1", title: "Partie 1 - L'émergence d'une esthétique du quotidien", content: ""),
                LessonPage(id: "course_130_le_pop_art_warhol_et_lichtenstein_p2", title: "Partie 2 - Andy Warhol : l'atelier comme entreprise", content: ""),
                LessonPage(id: "course_130_le_pop_art_warhol_et_lichtenstein_p3", title: "Partie 3 - Roy Lichtenstein : l'héroïsme de la trame", content: ""),
                LessonPage(id: "course_130_le_pop_art_warhol_et_lichtenstein_p4", title: "Partie 4 - Un héritage systémique sur le marché et la culture", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_130_le_pop_art_warhol_et_lichtenstein_q1", question: "Dans quel pays naît le Pop Art, avant d'exploser aux États-Unis ?", options: ["La Grande-Bretagne", "La France", "L'Allemagne", "L'Italie"], correctIndex: 0, explanation: "Le Pop Art naît en Grande-Bretagne avec l'Independent Group, avant d'exploser aux États-Unis dans les années 1960."),
        QuizQuestion(id: "course_130_le_pop_art_warhol_et_lichtenstein_q2", question: "Quel mouvement artistique le Pop Art rejette-t-il, jugé trop introspectif ?", options: ["L'expressionnisme abstrait", "Le cubisme", "Le surréalisme", "Le romantisme"], correctIndex: 0, explanation: "Les artistes pop s'opposent à l'expressionnisme abstrait, ces toiles introspectives alors dominantes."),
        QuizQuestion(id: "course_130_le_pop_art_warhol_et_lichtenstein_q3", question: "Comment se nomme l'atelier collectif d'Andy Warhol à New York ?", options: ["La Factory", "Le Bauhaus", "L'Atelier des Batignolles", "Le Studio 54"], correctIndex: 0, explanation: "La Factory de Warhol fonctionne comme une usine où assistants et amis produisent ensemble."),
        QuizQuestion(id: "course_130_le_pop_art_warhol_et_lichtenstein_q4", question: "Quelle technique Warhol utilise-t-il pour reproduire des dizaines de fois une image comme Marilyn Monroe ?", options: ["La sérigraphie", "La fresque", "L'aquarelle", "La mosaïque"], correctIndex: 0, explanation: "La sérigraphie permet à Warhol de multiplier une image, illustrant l'idée que la reproduction transforme l'aura d'une œuvre."),
        QuizQuestion(id: "course_130_le_pop_art_warhol_et_lichtenstein_q5", question: "Quel motif visuel signature Lichtenstein reproduit-il à la main dans ses toiles inspirées des comics ?", options: ["Le point Ben-Day", "Le collage de papier journal", "L'impasto", "Le sfumato"], correctIndex: 0, explanation: "Le point Ben-Day, imitation manuelle d'un procédé d'impression industrielle, est la signature visuelle de Lichtenstein."),
        QuizQuestion(id: "course_130_le_pop_art_warhol_et_lichtenstein_q6", type: .trueFalse, question: "Vrai ou faux : Richard Hamilton décrit le Pop Art en 1957 par des adjectifs comme éphémère, bon marché et sexy.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "En 1957, Hamilton résume ainsi un art pensé pour être consommé aussi vite qu'un magazine."),
        QuizQuestion(id: "course_130_le_pop_art_warhol_et_lichtenstein_q7", question: "Quel tableau de Lichtenstein transforme une case de bande dessinée de combat aérien en peinture monumentale ?", options: ["Whaam!", "La Persistance de la mémoire", "Le Cri", "Guernica"], correctIndex: 0, explanation: "Whaam! transforme une case de comic de diversion en une peinture d'histoire moderne de grand format."),
        QuizQuestion(id: "course_130_le_pop_art_warhol_et_lichtenstein_q8", type: .numericSlider, question: "En quelle année un portrait de Marilyn par Warhol atteint 195 millions de dollars aux enchères ?", explanation: "En 2022, ce portrait de Marilyn devient l'une des œuvres d'art américaines les plus chères jamais vendues.", correctValue: 2022, sliderMin: 1990, sliderMax: 2024, tolerance: 2, unit: ""),
        QuizQuestion(id: "course_130_le_pop_art_warhol_et_lichtenstein_q9", type: .chronological, question: "Remets ces jalons du Pop Art dans l'ordre chronologique.", explanation: "Ces jalons vont de 1957 à 2022, de la définition du mouvement à la consécration de ses icônes sur le marché de l'art.", items: ["Richard Hamilton définit le Pop Art", "Warhol et Lichtenstein imposent l'esthétique pop aux États-Unis", "Un portrait de Marilyn se vend 195 millions de dollars"])
    ]
        ),
        Course(
            id: "course_131_la_naissance_de_la_musique_electronique",
            title: "D'où vient la musique électronique, bien avant les clubs ?",
            description: "La musique électronique, née dans des laboratoires de recherche dans les années 1950, est aujourd'hui la forme de musique la plus écoutée dans le monde. Du s...",
            subject: .art,
            subcategory: "Musique",
            lessons: [
                LessonPage(id: "course_131_la_naissance_de_la_musique_electronique_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_131_la_naissance_de_la_musique_electronique_p1", title: "Les pionniers : du Theremin à la musique concrète", content: ""),
                LessonPage(id: "course_131_la_naissance_de_la_musique_electronique_p2", title: "L'ère du Moog et la révolution Kraftwerk", content: ""),
                LessonPage(id: "course_131_la_naissance_de_la_musique_electronique_p3", title: "Chicago et Detroit : l'émergence des cultures clubs", content: ""),
                LessonPage(id: "course_131_la_naissance_de_la_musique_electronique_p4", title: "Globalisation et postérité numérique", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_131_la_naissance_de_la_musique_electronique_q1", question: "Qui invente le Theremin en 1920, un instrument joué sans contact ?", options: ["Leon Theremin", "Robert Moog", "Pierre Schaeffer", "Karlheinz Stockhausen"], correctIndex: 0, explanation: "L'inventeur russe Leon Theremin conçoit en 1920 un appareil joué en bougeant les mains près d'antennes électromagnétiques."),
        QuizQuestion(id: "course_131_la_naissance_de_la_musique_electronique_q2", question: "Qui invente la musique concrète à Paris après 1945 ?", options: ["Pierre Schaeffer et Pierre Henry", "Ralf Hütter et Florian Schneider", "Juan Atkins et Derrick May", "Robert Moog et Wendy Carlos"], correctIndex: 0, explanation: "Pierre Schaeffer et Pierre Henry inventent la musique concrète en enregistrant et manipulant des bruits du quotidien sur bande magnétique."),
        QuizQuestion(id: "course_131_la_naissance_de_la_musique_electronique_q3", type: .trueFalse, question: "Vrai ou faux : la musique concrète repose sur des sons créés par des oscillateurs, sans aucune source acoustique réelle.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "C'est l'inverse : la musique concrète part de bruits réels enregistrés, tandis que la synthèse pure de Cologne utilise des oscillateurs."),
        QuizQuestion(id: "course_131_la_naissance_de_la_musique_electronique_q4", question: "Qui miniaturise le synthétiseur grâce aux transistors dans les années 1960 ?", options: ["Robert Moog", "Leon Theremin", "Pierre Henry", "Frankie Knuckles"], correctIndex: 0, explanation: "L'ingénieur américain Robert Moog miniaturise le synthétiseur avec des transistors, le rendant utilisable en studio."),
        QuizQuestion(id: "course_131_la_naissance_de_la_musique_electronique_q5", question: "Quel album de 1968 prouve que l'électronique peut porter la complexité de la musique classique ?", options: ["Switched-On Bach", "Autobahn", "The Man-Machine", "Trans-Europe Express"], correctIndex: 0, explanation: "Switched-On Bach de Wendy Carlos démontre en 1968 que le synthétiseur peut interpréter des œuvres classiques complexes."),
        QuizQuestion(id: "course_131_la_naissance_de_la_musique_electronique_q6", question: "Quel groupe allemand impose une pop froide et répétitive avec des albums comme Autobahn et The Man-Machine ?", options: ["Kraftwerk", "Die Brücke", "Der Blaue Reiter", "Tangerine Dream"], correctIndex: 0, explanation: "Le groupe Kraftwerk, fondé par Ralf Hütter et Florian Schneider à Düsseldorf, chante l'autoroute, le robot et la ville."),
        QuizQuestion(id: "course_131_la_naissance_de_la_musique_electronique_q7", question: "Quelle boîte à rythmes bon marché des années 1980 devient un outil clé de la house et de la techno ?", options: ["La Roland TR-808", "Le synthétiseur Moog", "Le Theremin", "L'orgue Hammond"], correctIndex: 0, explanation: "D'abord un échec commercial jugé irréaliste, la TR-808 devient l'arme bon marché des DJ de Chicago."),
        QuizQuestion(id: "course_131_la_naissance_de_la_musique_electronique_q8", question: "Quel DJ affine la house à Chicago dans les années 1980 ?", options: ["Frankie Knuckles", "Juan Atkins", "Derrick May", "Kevin Saunderson"], correctIndex: 0, explanation: "Frankie Knuckles affine la house de Chicago, avec son rythme régulier à 4/4 hérité du disco."),
        QuizQuestion(id: "course_131_la_naissance_de_la_musique_electronique_q9", question: "Quelle ville invente la techno, portée par trois amis d'université dans les années 1980 ?", options: ["Detroit", "Chicago", "Berlin", "Düsseldorf"], correctIndex: 0, explanation: "À Detroit, Juan Atkins, Derrick May et Kevin Saunderson inventent une esthétique électronique plus sombre : la techno."),
        QuizQuestion(id: "course_131_la_naissance_de_la_musique_electronique_q10", type: .chronological, question: "Remets ces jalons de la musique électronique dans l'ordre chronologique.", explanation: "Ces jalons vont de 1920 aux années 1980, des laboratoires pionniers à la naissance de la danse électronique moderne.", items: ["Invention du Theremin", "Naissance de la musique concrète à Paris", "Switched-On Bach popularise le synthétiseur", "La house et la techno naissent à Chicago et Detroit"])
    ]
        ),
        Course(
            id: "course_132_bob_dylan_et_la_folk_protest",
            title: "Comment Bob Dylan est-il passé de la folk au prix Nobel ?",
            description: "Bob Dylan (né Robert Zimmerman en 1941) est la figure la plus influente de la chanson américaine du XXe siècle : poète, prophète, caméléon. De la folk protes...",
            subject: .art,
            subcategory: "Musique",
            lessons: [
                LessonPage(id: "course_132_bob_dylan_et_la_folk_protest_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_132_bob_dylan_et_la_folk_protest_p1", title: "L'ascension à Greenwich Village et l'héritage de Woody Guthrie", content: ""),
                LessonPage(id: "course_132_bob_dylan_et_la_folk_protest_p2", title: "L'invention de la 'Protest Song' et la voix d'une génération", content: ""),
                LessonPage(id: "course_132_bob_dylan_et_la_folk_protest_p3", title: "Le séisme électrique du Festival de Newport", content: ""),
                LessonPage(id: "course_132_bob_dylan_et_la_folk_protest_p4", title: "L'héritage d'un prix Nobel et la postérité du poète-musicien", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_132_bob_dylan_et_la_folk_protest_q1", question: "Pourquoi le jeune Robert Zimmerman quitte-t-il le Minnesota pour New York en 1961 ?", options: ["Il veut rencontrer son idole Woody Guthrie, alors hospitalisé", "Il veut auditionner pour un télé-crochet new-yorkais", "Il fuit une dispute avec sa famille", "Il veut étudier la musique à l'université"], correctIndex: 0, explanation: "Dylan admire le chanteur folk Woody Guthrie, voix des travailleurs et des opprimés, et veut le rencontrer avant tout."),
        QuizQuestion(id: "course_132_bob_dylan_et_la_folk_protest_q2", question: "Dans quel quartier bohème de Manhattan Dylan s'installe-t-il et signe-t-il chez Columbia Records ?", options: ["Greenwich Village", "Harlem", "Brooklyn", "Times Square"], correctIndex: 0, explanation: "Greenwich Village, cœur du folk revival, est le quartier où Dylan écume les cafés avant de signer chez Columbia fin 1961."),
        QuizQuestion(id: "course_132_bob_dylan_et_la_folk_protest_q3", type: .trueFalse, question: "Vrai ou faux : en août 1963, Dylan chante lors de la Marche sur Washington juste avant le discours de Martin Luther King.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Dylan se produit devant 250 000 personnes, peu avant le fameux discours de Martin Luther King."),
        QuizQuestion(id: "course_132_bob_dylan_et_la_folk_protest_q4", type: .numericSlider, question: "En quelle année sort l'album The Freewheelin' Bob Dylan, qui contient Blowin' in the Wind ?", explanation: "The Freewheelin' Bob Dylan, sorti en 1963, impose Blowin' in the Wind comme un hymne de la contestation.", correctValue: 1963, sliderMin: 1958, sliderMax: 1970, tolerance: 1, unit: ""),
        QuizQuestion(id: "course_132_bob_dylan_et_la_folk_protest_q5", question: "Quel instrument Dylan sort-il au festival de Newport en 1965, provoquant les huées des puristes du folk ?", options: ["Une guitare électrique Fender Stratocaster", "Un piano électrique", "Une basse électrique", "Un synthétiseur"], correctIndex: 0, explanation: "En brancheant une Stratocaster électrique à Newport, Dylan invente le folk-rock et scandalise une partie du public."),
        QuizQuestion(id: "course_132_bob_dylan_et_la_folk_protest_q6", question: "Que reproche une partie du public folk à Dylan lors de Newport 1965 ?", options: ["D'avoir trahi la pureté acoustique du folk en jouant électrique", "D'avoir chanté en français", "D'avoir refusé de monter sur scène", "D'avoir critiqué Woody Guthrie"], correctIndex: 0, explanation: "Le public puriste juge l'électricité comme une trahison commerciale du folk traditionnel."),
        QuizQuestion(id: "course_132_bob_dylan_et_la_folk_protest_q7", type: .chronological, question: "Remets ces étapes de la carrière de Bob Dylan dans l'ordre chronologique.", explanation: "De 1961 à 2016, Dylan passe de l'arrivée à New York au Nobel de littérature, en traversant la Marche sur Washington et le virage électrique de Newport.", items: ["Arrivée à New York et découverte de Greenwich Village", "Participation à la Marche sur Washington", "Passage à la guitare électrique à Newport", "Obtention du prix Nobel de littérature"]),
        QuizQuestion(id: "course_132_bob_dylan_et_la_folk_protest_q8", type: .trueFalse, question: "Vrai ou faux : en 2016, Bob Dylan devient le premier auteur-compositeur de rock à recevoir le prix Nobel de littérature.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "L'Académie suédoise reconnaît pour la première fois un auteur-compositeur de rock comme un grand écrivain."),
        QuizQuestion(id: "course_132_bob_dylan_et_la_folk_protest_q9", question: "Quel titre de Dylan, sorti en 1963, devient un hymne de la contestation contre le racisme et la guerre ?", options: ["Blowin' in the Wind", "Like a Rolling Stone", "Hurricane", "Knockin' on Heaven's Door"], correctIndex: 0, explanation: "Blowin' in the Wind, sur l'album The Freewheelin' Bob Dylan, devient l'hymne de la protest song.")
    ]
        ),
        Course(
            id: "course_133_le_hip_hop_naissance_d_une_culture",
            title: "Hip-hop : que s'est-il passé dans le Bronx en 1973 ?",
            description: "Le hip-hop est né dans le Bronx à New York en 1973, dans l'une des zones les plus défavorisées d'Amérique. En cinquante ans, il est devenu la forme culturell...",
            subject: .art,
            subcategory: "Musique",
            lessons: [
                LessonPage(id: "course_133_le_hip_hop_naissance_d_une_culture_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_133_le_hip_hop_naissance_d_une_culture_p1", title: "Le chaos fertile : le South Bronx au tournant des années 1970", content: ""),
                LessonPage(id: "course_133_le_hip_hop_naissance_d_une_culture_p2", title: "La structuration d'une culture : les quatre piliers", content: ""),
                LessonPage(id: "course_133_le_hip_hop_naissance_d_une_culture_p3", title: "De l'underground au Billboard : l'explosion commerciale", content: ""),
                LessonPage(id: "course_133_le_hip_hop_naissance_d_une_culture_p4", title: "Hégémonie et héritage global du hip-hop", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_133_le_hip_hop_naissance_d_une_culture_q1", question: "Dans quel quartier de New York naît le hip-hop au début des années 1970 ?", options: ["Le Bronx", "Harlem", "Brooklyn", "Queens"], correctIndex: 0, explanation: "C'est dans le Bronx, ravagé par la destruction de logements et la spéculation immobilière, que naît le hip-hop."),
        QuizQuestion(id: "course_133_le_hip_hop_naissance_d_une_culture_q2", question: "Qui organise la fête du 11 août 1973 considérée comme la naissance du hip-hop ?", options: ["Kool DJ Herc", "Grandmaster Flash", "Afrika Bambaataa", "Grand Wizzard Theodore"], correctIndex: 0, explanation: "L'immigré jamaïcain Clive Campbell, dit Kool DJ Herc, organise cette fête au 1520 Sedgwick Avenue."),
        QuizQuestion(id: "course_133_le_hip_hop_naissance_d_une_culture_q3", question: "Quelle technique Kool Herc invente-t-il en isolant la partie rythmique d'un disque avec deux platines ?", options: ["Le breakbeat", "Le scratching", "Le sampling numérique", "Le beatboxing"], correctIndex: 0, explanation: "Kool Herc invente le breakbeat, qui isole et prolonge la partie la plus dansante d'un disque."),
        QuizQuestion(id: "course_133_le_hip_hop_naissance_d_une_culture_q4", type: .trueFalse, question: "Vrai ou faux : le hip-hop repose sur quatre disciplines, le DJing, le MCing, le breakdance et le graffiti.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Ces quatre piliers structurent la culture hip-hop dès ses débuts dans le Bronx."),
        QuizQuestion(id: "course_133_le_hip_hop_naissance_d_une_culture_q5", question: "Qui invente le scratching par accident en 1975, à seulement 12 ans ?", options: ["Grand Wizzard Theodore", "Kool Herc", "Grandmaster Flash", "Afrika Bambaataa"], correctIndex: 0, explanation: "Grand Wizzard Theodore bloque un disque à la main pour entendre sa mère, inventant ainsi le scratching."),
        QuizQuestion(id: "course_133_le_hip_hop_naissance_d_une_culture_q6", question: "Quelle organisation, fondée par Afrika Bambaataa, veut remplacer la violence des gangs par la compétition artistique ?", options: ["L'Universal Zulu Nation", "Les Furious Five", "Le Bronx United", "La Nation of Islam"], correctIndex: 0, explanation: "Afrika Bambaataa fonde l'Universal Zulu Nation autour des valeurs de paix, amour, unité et plaisir."),
        QuizQuestion(id: "course_133_le_hip_hop_naissance_d_une_culture_q7", type: .numericSlider, question: "En quelle année sort Rapper's Delight du Sugarhill Gang, premier grand succès commercial du rap ?", explanation: "Rapper's Delight, sorti en 1979, prouve que le rap peut être un hit mondial.", correctValue: 1979, sliderMin: 1970, sliderMax: 1990, tolerance: 2, unit: ""),
        QuizQuestion(id: "course_133_le_hip_hop_naissance_d_une_culture_q8", type: .chronological, question: "Remets ces jalons de l'histoire du hip-hop dans l'ordre chronologique.", explanation: "De la fête fondatrice de 1973 au Pulitzer de 2018, le hip-hop passe d'une culture de quartier à un art reconnu institutionnellement.", items: ["Kool Herc invente le breakbeat lors d'une fête du Bronx", "Rapper's Delight devient un succès international", "The Message impose la chronique sociale du rap", "Kendrick Lamar reçoit le prix Pulitzer de la musique"]),
        QuizQuestion(id: "course_133_le_hip_hop_naissance_d_une_culture_q9", type: .trueFalse, question: "Vrai ou faux : dans les années 1990, la rivalité entre les côtes Est et Ouest a notamment opposé The Notorious B.I.G. et Tupac Shakur.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Cette rivalité structure l'industrie du rap dans les années 1990, entre virtuosité lyrique new-yorkaise et gangsta rap californien.")
    ]
        ),
        Course(
            id: "course_134_l_opera_de_verdi",
            title: "Comment Verdi est-il devenu la voix de l'unité italienne ?",
            description: "Giuseppe Verdi (1813-1901) est le plus grand compositeur d'opéra italien du XIXe siècle. «Rigoletto», «La Traviata», «Aida», «Otello» : ses opéras sont les p...",
            subject: .art,
            subcategory: "Musique",
            lessons: [
                LessonPage(id: "course_134_l_opera_de_verdi_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_134_l_opera_de_verdi_p1", title: "L'évolution du spectacle lyrique au XIXe siècle", content: ""),
                LessonPage(id: "course_134_l_opera_de_verdi_p2", title: "Le musicien du Risorgimento", content: ""),
                LessonPage(id: "course_134_l_opera_de_verdi_p3", title: "La trilogie populaire et le scandale du réalisme", content: ""),
                LessonPage(id: "course_134_l_opera_de_verdi_p4", title: "L'apothéose et l'héritage d'un géant", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_134_l_opera_de_verdi_q1", question: "Quel opéra de 1842 rend Verdi célèbre grâce à son chœur Va, pensiero ?", options: ["Nabucco", "Rigoletto", "Aida", "Otello"], correctIndex: 0, explanation: "Nabucco triomphe en 1842 et son chœur Va, pensiero devient un hymne clandestin dans l'Italie occupée."),
        QuizQuestion(id: "course_134_l_opera_de_verdi_q2", question: "Que raconte le chœur Va, pensiero de Nabucco, devenu un hymne patriotique italien ?", options: ["L'exil des Hébreux à Babylone", "La bataille de Waterloo", "Le siège de Rome", "La révolution française"], correctIndex: 0, explanation: "Nabucco raconte l'exil des Hébreux à Babylone, une histoire qui résonne avec l'Italie occupée par l'Autriche."),
        QuizQuestion(id: "course_134_l_opera_de_verdi_q3", type: .trueFalse, question: "Vrai ou faux : le slogan Viva VERDI, écrit sur les murs italiens, cache l'acronyme de Vittorio Emanuele Re D'Italia.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Derrière le nom du compositeur se cache un message politique en faveur du futur roi d'Italie."),
        QuizQuestion(id: "course_134_l_opera_de_verdi_q4", question: "Quel mouvement politique italien Verdi soutient-il, allant jusqu'à devenir député en 1861 ?", options: ["Le Risorgimento", "Le fascisme", "Le carbonarisme", "Le socialisme"], correctIndex: 0, explanation: "Verdi devient une figure du Risorgimento, le mouvement d'unification nationale porté par Cavour."),
        QuizQuestion(id: "course_134_l_opera_de_verdi_q5", question: "Sur quel roman français est basée La Traviata ?", options: ["La Dame aux camélias d'Alexandre Dumas fils", "Notre-Dame de Paris de Victor Hugo", "Les Misérables de Victor Hugo", "Madame Bovary de Gustave Flaubert"], correctIndex: 0, explanation: "La Traviata adapte La Dame aux camélias, ce qui choque par son héroïne contemporaine et tuberculeuse."),
        QuizQuestion(id: "course_134_l_opera_de_verdi_q6", type: .trueFalse, question: "Vrai ou faux : Aida est composée pour Le Caire, à l'occasion du percement du Canal de Suez.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Aida est commandée en 1871 pour Le Caire et le Canal de Suez, mêlant spectacle et drame."),
        QuizQuestion(id: "course_134_l_opera_de_verdi_q7", type: .numericSlider, question: "En quelle année Verdi meurt-il, suivi par plus de 300 000 personnes à Milan ?", explanation: "Verdi meurt en 1901 ; la foule entonne spontanément Nabucco lors de ses funérailles.", correctValue: 1901, sliderMin: 1850, sliderMax: 1950, tolerance: 3, unit: ""),
        QuizQuestion(id: "course_134_l_opera_de_verdi_q8", type: .chronological, question: "Remets ces opéras de Verdi dans l'ordre chronologique de leur création.", explanation: "De Nabucco en 1842 à Falstaff en 1893, Verdi traverse plus de cinquante ans de création lyrique.", items: ["Nabucco triomphe et Va, pensiero devient un hymne", "La trilogie populaire s'achève avec La Traviata", "Aida est créée pour Le Caire", "Falstaff, dernier opéra, est créé"]),
        QuizQuestion(id: "course_134_l_opera_de_verdi_q9", question: "Quel compositeur allemand incarne, face à Verdi, l'autre grande voie de l'opéra du XIXe siècle ?", options: ["Richard Wagner", "Johannes Brahms", "Franz Liszt", "Robert Schumann"], correctIndex: 0, explanation: "Face à Wagner et son œuvre totale mythologique, Verdi reste fidèle à la clarté mélodique italienne.")
    ]
        ),
        Course(
            id: "course_135_mozart_enfant_prodige_et_vie_tragique",
            title: "Qui était Mozart, au-delà de l'enfant prodige ?",
            description: "Wolfgang Amadeus Mozart (1756-1791) est peut-être le génie musical le plus extraordinaire de l'histoire humaine. Il composa sa première symphonie à 8 ans, so...",
            subject: .art,
            subcategory: "Musique",
            lessons: [
                LessonPage(id: "course_135_mozart_enfant_prodige_et_vie_tragique_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_135_mozart_enfant_prodige_et_vie_tragique_p1", title: "L'enfance prodige et la formation itinérante", content: ""),
                LessonPage(id: "course_135_mozart_enfant_prodige_et_vie_tragique_p2", title: "L'émancipation viennoise et l'invention de l'indépendance", content: ""),
                LessonPage(id: "course_135_mozart_enfant_prodige_et_vie_tragique_p3", title: "Le crépuscule et le mystère du Requiem", content: ""),
                LessonPage(id: "course_135_mozart_enfant_prodige_et_vie_tragique_p4", title: "Héritage et postérité d'un mythe", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_135_mozart_enfant_prodige_et_vie_tragique_q1", question: "Dans quelle ville Mozart naît-il en 1756 ?", options: ["Salzbourg", "Vienne", "Prague", "Paris"], correctIndex: 0, explanation: "Wolfgang Amadeus Mozart naît le 27 janvier 1756 à Salzbourg."),
        QuizQuestion(id: "course_135_mozart_enfant_prodige_et_vie_tragique_q2", question: "Qui organise, dès les six ans de Mozart, des tournées à travers les cours d'Europe ?", options: ["Son père Leopold", "L'archevêque Colloredo", "L'empereur Joseph II", "Joseph Haydn"], correctIndex: 0, explanation: "Leopold, violoniste et pédagogue ambitieux, organise ces tournées qui forgent l'oreille de son fils."),
        QuizQuestion(id: "course_135_mozart_enfant_prodige_et_vie_tragique_q3", question: "Quel exploit Mozart réalise-t-il en Italie en 1770 avec le Miserere de Gregorio Allegri ?", options: ["Le retranscrire de mémoire après une seule audition", "Le traduire en allemand", "Le diriger devant le pape", "Le réorchestrer pour piano seul"], correctIndex: 0, explanation: "Après une seule écoute à la Chapelle Sixtine, Mozart retranscrit de mémoire cette partition pourtant protégée."),
        QuizQuestion(id: "course_135_mozart_enfant_prodige_et_vie_tragique_q4", type: .trueFalse, question: "Vrai ou faux : en 1781, Mozart quitte le service de l'archevêque Colloredo pour devenir compositeur indépendant à Vienne.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Mozart devient l'un des premiers compositeurs free-lance de l'histoire en s'installant à Vienne en 1781."),
        QuizQuestion(id: "course_135_mozart_enfant_prodige_et_vie_tragique_q5", question: "Quel opéra de 1786 marque l'explosion du génie dramatique de Mozart à Vienne ?", options: ["Les Noces de Figaro", "Don Giovanni", "La Flûte enchantée", "Cosi fan tutte"], correctIndex: 0, explanation: "Les Noces de Figaro, créé en 1786, donne à l'opéra une psychologie moderne inédite."),
        QuizQuestion(id: "course_135_mozart_enfant_prodige_et_vie_tragique_q6", type: .numericSlider, question: "En quelle année Mozart meurt-il, à seulement 35 ans ?", explanation: "Mozart meurt le 5 décembre 1791, laissant son Requiem inachevé.", correctValue: 1791, sliderMin: 1750, sliderMax: 1820, tolerance: 2, unit: ""),
        QuizQuestion(id: "course_135_mozart_enfant_prodige_et_vie_tragique_q7", question: "Quelle œuvre inachevée Mozart compose-t-il juste avant sa mort, sur une commande secrète ?", options: ["Le Requiem", "La Flûte enchantée", "La Symphonie n°41", "Le Concerto pour clarinette"], correctIndex: 0, explanation: "Un émissaire mystérieux commande à Mozart un Requiem, qu'il ne peut achever avant sa mort."),
        QuizQuestion(id: "course_135_mozart_enfant_prodige_et_vie_tragique_q8", type: .trueFalse, question: "Vrai ou faux : c'est le compositeur Antonio Salieri qui termine le Requiem de Mozart après sa mort.", options: ["Vrai", "Faux"], correctIndex: 1, explanation: "C'est son élève Franz Xaver Süssmayr qui termine le Requiem, pour que la veuve Constance touche le solde de la commande."),
        QuizQuestion(id: "course_135_mozart_enfant_prodige_et_vie_tragique_q9", type: .chronological, question: "Remets ces étapes de la vie de Mozart dans l'ordre chronologique.", explanation: "De la tournée européenne à la mort en 1791, en passant par Rome et la rupture viennoise, la vie de Mozart s'accélère jusqu'à sa fin précoce.", items: ["Mozart part en tournée à travers l'Europe sous la tutelle de son père", "Il retranscrit de mémoire le Miserere d'Allegri en Italie", "Il rompt avec l'archevêque Colloredo et s'installe à Vienne", "Il achève La Flûte enchantée et meurt peu après"])
    ]
        ),
        Course(
            id: "course_136_beethoven_genie_et_surdite",
            title: "Comment Beethoven a-t-il pu composer en devenant sourd ?",
            description: "Ludwig van Beethoven (1770-1827) est peut-être le compositeur le plus célèbre de l'histoire occidentale. Sa trajectoire est l'une des plus extraordinaires de...",
            subject: .art,
            subcategory: "Musique",
            lessons: [
                LessonPage(id: "course_136_beethoven_genie_et_surdite_intro", title: "Introduction", content: ""),
                LessonPage(id: "course_136_beethoven_genie_et_surdite_p1", title: "L'enfance à Bonn et l'ascension viennoise", content: ""),
                LessonPage(id: "course_136_beethoven_genie_et_surdite_p2", title: "Le drame de la surdité et le sursaut héroïque", content: ""),
                LessonPage(id: "course_136_beethoven_genie_et_surdite_p3", title: "La Neuvième Symphonie : l'apothéose du silence", content: ""),
                LessonPage(id: "course_136_beethoven_genie_et_surdite_p4", title: "Héritage et révolution du langage musical", content: ""),
            ],
            quiz: [
        QuizQuestion(id: "course_136_beethoven_genie_et_surdite_q1", question: "Dans quelle ville Beethoven naît-il en 1770 ?", options: ["Bonn", "Vienne", "Salzbourg", "Leipzig"], correctIndex: 0, explanation: "Ludwig van Beethoven naît à Bonn en 1770, sous la tutelle d'un père brutal."),
        QuizQuestion(id: "course_136_beethoven_genie_et_surdite_q2", question: "Avec quel compositeur célèbre Beethoven étudie-t-il brièvement à son arrivée à Vienne en 1792 ?", options: ["Joseph Haydn", "Mozart", "Bach", "Schubert"], correctIndex: 0, explanation: "Beethoven étudie brièvement avec Joseph Haydn à son arrivée dans la capitale musicale."),
        QuizQuestion(id: "course_136_beethoven_genie_et_surdite_q3", type: .trueFalse, question: "Vrai ou faux : dans le Testament de Heiligenstadt rédigé en 1802, Beethoven confie des pensées suicidaires avant de choisir de vivre pour composer.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Cette lettre à ses frères, jamais envoyée, marque le basculement vers la période héroïque de sa création."),
        QuizQuestion(id: "course_136_beethoven_genie_et_surdite_q4", question: "À qui la Symphonie Héroïque est-elle d'abord dédiée, avant que Beethoven ne retire la dédicace ?", options: ["Napoléon Bonaparte", "L'empereur Joseph II", "Le prince Lichnowsky", "Le tsar Alexandre Ier"], correctIndex: 0, explanation: "Beethoven retire la dédicace lorsque Napoléon se fait proclamer empereur."),
        QuizQuestion(id: "course_136_beethoven_genie_et_surdite_q5", question: "Quel poème de Friedrich von Schiller inspire le finale choral de la Neuvième Symphonie ?", options: ["L'Ode à la joie", "Les Brigands", "Guillaume Tell", "Marie Stuart"], correctIndex: 0, explanation: "Le finale de la Neuvième transforme l'Ode à la joie de Schiller en message de fraternité universelle."),
        QuizQuestion(id: "course_136_beethoven_genie_et_surdite_q6", type: .numericSlider, question: "En quelle année Beethoven achève-t-il sa Neuvième Symphonie ?", explanation: "Beethoven achève la Neuvième Symphonie en 1824, alors qu'il est presque totalement sourd.", correctValue: 1824, sliderMin: 1780, sliderMax: 1830, tolerance: 3, unit: ""),
        QuizQuestion(id: "course_136_beethoven_genie_et_surdite_q7", question: "Qui fait se retourner Beethoven, devenu sourd, pour qu'il voie la foule debout à la création de la Neuvième ?", options: ["La contralto Caroline Unger", "Le pianiste Franz Liszt", "Son frère", "Joseph Haydn"], correctIndex: 0, explanation: "Incapable d'entendre les ovations, Beethoven est retourné par la contralto Caroline Unger pour voir la foule debout."),
        QuizQuestion(id: "course_136_beethoven_genie_et_surdite_q8", type: .trueFalse, question: "Vrai ou faux : Beethoven a fait scier les pieds de ses pianos pour mieux sentir les vibrations par le plancher.", options: ["Vrai", "Faux"], correctIndex: 0, explanation: "Pour compenser sa surdité, Beethoven fait scier les pieds de ses pianos afin qu'ils reposent directement sur le plancher."),
        QuizQuestion(id: "course_136_beethoven_genie_et_surdite_q9", type: .chronological, question: "Remets ces étapes de la vie de Beethoven dans l'ordre chronologique.", explanation: "De l'arrivée à Vienne en 1792 à la Neuvième Symphonie de 1824, Beethoven transforme son épreuve de la surdité en création monumentale.", items: ["Beethoven s'installe à Vienne et étudie avec Haydn", "Il rédige le Testament de Heiligenstadt", "Il compose la Symphonie Héroïque", "Il achève la Neuvième Symphonie et l'Ode à la joie"])
    ]
        ),
    ]
}
